;; packet-aeron.c
;;
;; Wireshark - Network traffic analyzer
;; By Gerald Combs <gerald@wireshark.org>
;; Copyright 1998 Gerald Combs
;;
;; SPDX-License-Identifier: GPL-2.0-or-later
;;

;; jerboa-ethereal/dissectors/aeron.ss
;; Auto-generated from wireshark/epan/dissectors/packet-aeron.c

(import (jerboa prelude))

;; ── Protocol Helpers ─────────────────────────────────────────────────
(def (read-u8 buf offset)
  (if (>= offset (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u8-ref buf offset))))

(def (read-u16be buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness big)))))

(def (read-u24be buf offset)
  (if (> (+ offset 3) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (+ (* (bytevector-u8-ref buf offset) 65536)
             (* (bytevector-u8-ref buf (+ offset 1)) 256)
             (bytevector-u8-ref buf (+ offset 2))))))

(def (read-u32be buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness big)))))

(def (read-u16le buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness little)))))

(def (read-u32le buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness little)))))

(def (read-u64be buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness big)))))

(def (read-u64le buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness little)))))

(def (slice buf offset len)
  (if (> (+ offset len) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (let ((result (make-bytevector len)))
            (bytevector-copy! buf offset result 0 len)
            result))))

(def (extract-bits val mask shift)
  (bitwise-arithmetic-shift-right (bitwise-and val mask) shift))

(def (fmt-ipv4 addr)
  (let ((b0 (bitwise-arithmetic-shift-right addr 24))
        (b1 (bitwise-and (bitwise-arithmetic-shift-right addr 16) 255))
        (b2 (bitwise-and (bitwise-arithmetic-shift-right addr 8) 255))
        (b3 (bitwise-and addr 255)))
    (str b0 "." b1 "." b2 "." b3)))

(def (fmt-mac bytes)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bytes))
    ":"))

(def (fmt-hex val)
  (str "0x" (number->string val 16)))

(def (fmt-oct val)
  (str "0" (number->string val 8)))

(def (fmt-port port)
  (number->string port))

(def (fmt-bytes bv)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bv))
    " "))

(def (fmt-ipv6-address bytes)
  (let loop ((i 0) (parts '()))
    (if (>= i 16)
        (string-join (reverse parts) ":")
        (loop (+ i 2)
              (cons (let ((w (+ (* (bytevector-u8-ref bytes i) 256)
                                (bytevector-u8-ref bytes (+ i 1)))))
                      (number->string w 16))
                    parts)))))

;; ── Dissector ──────────────────────────────────────────────────────
(def (dissect-aeron buffer)
  "Aeron Protocol"
  (try
    (let* (
           (channel-id (unwrap (read-u64be buffer 0)))
           (data-next-offset-first-frame (unwrap (read-u32be buffer 0)))
           (data-next-offset-term (unwrap (read-u32be buffer 0)))
           (data-next-offset (unwrap (read-u32be buffer 0)))
           (stream-analysis-outstanding-bytes (unwrap (read-u32be buffer 0)))
           (stream-analysis-completed-term-offset (unwrap (read-u32be buffer 0)))
           (stream-analysis-completed-term-id (unwrap (read-u32be buffer 0)))
           (stream-analysis-high-term-offset (unwrap (read-u32be buffer 0)))
           (stream-analysis-high-term-id (unwrap (read-u32be buffer 0)))
           (sequence-analysis-nak-rx-frame (unwrap (read-u32be buffer 0)))
           (sequence-analysis-nak-unrecovered (unwrap (read-u32be buffer 0)))
           (sequence-analysis-keepalive (unwrap (read-u8 buffer 0)))
           (sequence-analysis-retransmission-rx-frame (unwrap (read-u32be buffer 0)))
           (sequence-analysis-retransmission (unwrap (read-u8 buffer 0)))
           (sequence-analysis-term-next-frame (unwrap (read-u32be buffer 0)))
           (sequence-analysis-term-prev-frame (unwrap (read-u32be buffer 0)))
           (sequence-analysis-stream-next-frame (unwrap (read-u32be buffer 0)))
           (sequence-analysis-stream-prev-frame (unwrap (read-u32be buffer 0)))
           (sequence-analysis-channel-next-frame (unwrap (read-u32be buffer 0)))
           (sequence-analysis-channel-prev-frame (unwrap (read-u32be buffer 0)))
           (sequence-analysis-term-offset-frame (unwrap (read-u32be buffer 0)))
           (pad-frame-length (unwrap (read-u32be buffer 0)))
           (pad-version (unwrap (read-u8 buffer 0)))
           (pad-flags (unwrap (read-u8 buffer 0)))
           (pad-term-offset (unwrap (read-u32be buffer 0)))
           (pad-session-id (unwrap (read-u32be buffer 0)))
           (pad-stream-id (unwrap (read-u32be buffer 0)))
           (pad-term-id (unwrap (read-u32be buffer 0)))
           (data-frame-length (unwrap (read-u32be buffer 0)))
           (data-version (unwrap (read-u8 buffer 0)))
           (data-flags (unwrap (read-u8 buffer 0)))
           (data-term-offset (unwrap (read-u32be buffer 0)))
           (data-session-id (unwrap (read-u32be buffer 0)))
           (data-stream-id (unwrap (read-u32be buffer 0)))
           (data-term-id (unwrap (read-u32be buffer 0)))
           (data-reserved-value (unwrap (read-u64be buffer 0)))
           (nak-frame-length (unwrap (read-u32be buffer 0)))
           (nak-version (unwrap (read-u8 buffer 0)))
           (nak-flags (unwrap (read-u8 buffer 0)))
           (nak-session-id (unwrap (read-u32be buffer 0)))
           (nak-stream-id (unwrap (read-u32be buffer 0)))
           (nak-term-id (unwrap (read-u32be buffer 0)))
           (nak-term-offset (unwrap (read-u32be buffer 0)))
           (nak-length (unwrap (read-u32be buffer 0)))
           (sm-frame-length (unwrap (read-u32be buffer 0)))
           (sm-version (unwrap (read-u8 buffer 0)))
           (sm-flags (unwrap (read-u8 buffer 0)))
           (sm-session-id (unwrap (read-u32be buffer 0)))
           (sm-stream-id (unwrap (read-u32be buffer 0)))
           (sm-consumption-term-id (unwrap (read-u32be buffer 0)))
           (sm-consumption-term-offset (unwrap (read-u32be buffer 0)))
           (sm-receiver-window (unwrap (read-u32be buffer 0)))
           (sm-receiver-id (unwrap (read-u64be buffer 0)))
           (sm-feedback (unwrap (slice buffer 0 1)))
           (err-frame-length (unwrap (read-u32be buffer 0)))
           (err-version (unwrap (read-u8 buffer 0)))
           (err-code (unwrap (read-u8 buffer 0)))
           (err-off-frame-length (unwrap (read-u32be buffer 0)))
           (err-off-hdr (unwrap (slice buffer 0 1)))
           (err-string (unwrap (slice buffer 0 1)))
           (heartbeat-frame-length (unwrap (read-u32be buffer 0)))
           (heartbeat-version (unwrap (read-u8 buffer 0)))
           (heartbeat-flags (unwrap (read-u8 buffer 0)))
           (heartbeat-term-offset (unwrap (read-u32be buffer 0)))
           (heartbeat-session-id (unwrap (read-u32be buffer 0)))
           (heartbeat-stream-id (unwrap (read-u32be buffer 0)))
           (heartbeat-term-id (unwrap (read-u32be buffer 0)))
           (rtt-frame-length (unwrap (read-u32be buffer 0)))
           (rtt-version (unwrap (read-u8 buffer 0)))
           (rtt-flags (unwrap (read-u8 buffer 0)))
           (rtt-flags-r (extract-bits rtt-flags 0x0 0))
           (rtt-session-id (unwrap (read-u32be buffer 0)))
           (rtt-stream-id (unwrap (read-u32be buffer 0)))
           (rtt-echo-timestamp (unwrap (read-u64be buffer 0)))
           (rtt-reception-delta (unwrap (read-u64be buffer 0)))
           (rtt-receiver-id (unwrap (read-u64be buffer 0)))
           (setup-frame-length (unwrap (read-u32be buffer 0)))
           (setup-version (unwrap (read-u8 buffer 0)))
           (setup-flags (unwrap (read-u8 buffer 0)))
           (setup-term-offset (unwrap (read-u32be buffer 0)))
           (setup-session-id (unwrap (read-u32be buffer 0)))
           (setup-stream-id (unwrap (read-u32be buffer 0)))
           (setup-initial-term-id (unwrap (read-u32be buffer 0)))
           (setup-active-term-id (unwrap (read-u32be buffer 0)))
           (setup-term-length (unwrap (read-u32be buffer 0)))
           (setup-mtu (unwrap (read-u32be buffer 0)))
           (setup-ttl (unwrap (read-u32be buffer 0)))
           )

      (ok (list
        (cons 'channel-id (list (cons 'raw channel-id) (cons 'formatted (number->string channel-id))))
        (cons 'data-next-offset-first-frame (list (cons 'raw data-next-offset-first-frame) (cons 'formatted (number->string data-next-offset-first-frame))))
        (cons 'data-next-offset-term (list (cons 'raw data-next-offset-term) (cons 'formatted (number->string data-next-offset-term))))
        (cons 'data-next-offset (list (cons 'raw data-next-offset) (cons 'formatted (number->string data-next-offset))))
        (cons 'stream-analysis-outstanding-bytes (list (cons 'raw stream-analysis-outstanding-bytes) (cons 'formatted (number->string stream-analysis-outstanding-bytes))))
        (cons 'stream-analysis-completed-term-offset (list (cons 'raw stream-analysis-completed-term-offset) (cons 'formatted (number->string stream-analysis-completed-term-offset))))
        (cons 'stream-analysis-completed-term-id (list (cons 'raw stream-analysis-completed-term-id) (cons 'formatted (number->string stream-analysis-completed-term-id))))
        (cons 'stream-analysis-high-term-offset (list (cons 'raw stream-analysis-high-term-offset) (cons 'formatted (number->string stream-analysis-high-term-offset))))
        (cons 'stream-analysis-high-term-id (list (cons 'raw stream-analysis-high-term-id) (cons 'formatted (number->string stream-analysis-high-term-id))))
        (cons 'sequence-analysis-nak-rx-frame (list (cons 'raw sequence-analysis-nak-rx-frame) (cons 'formatted (number->string sequence-analysis-nak-rx-frame))))
        (cons 'sequence-analysis-nak-unrecovered (list (cons 'raw sequence-analysis-nak-unrecovered) (cons 'formatted (number->string sequence-analysis-nak-unrecovered))))
        (cons 'sequence-analysis-keepalive (list (cons 'raw sequence-analysis-keepalive) (cons 'formatted (number->string sequence-analysis-keepalive))))
        (cons 'sequence-analysis-retransmission-rx-frame (list (cons 'raw sequence-analysis-retransmission-rx-frame) (cons 'formatted (number->string sequence-analysis-retransmission-rx-frame))))
        (cons 'sequence-analysis-retransmission (list (cons 'raw sequence-analysis-retransmission) (cons 'formatted (number->string sequence-analysis-retransmission))))
        (cons 'sequence-analysis-term-next-frame (list (cons 'raw sequence-analysis-term-next-frame) (cons 'formatted (number->string sequence-analysis-term-next-frame))))
        (cons 'sequence-analysis-term-prev-frame (list (cons 'raw sequence-analysis-term-prev-frame) (cons 'formatted (number->string sequence-analysis-term-prev-frame))))
        (cons 'sequence-analysis-stream-next-frame (list (cons 'raw sequence-analysis-stream-next-frame) (cons 'formatted (number->string sequence-analysis-stream-next-frame))))
        (cons 'sequence-analysis-stream-prev-frame (list (cons 'raw sequence-analysis-stream-prev-frame) (cons 'formatted (number->string sequence-analysis-stream-prev-frame))))
        (cons 'sequence-analysis-channel-next-frame (list (cons 'raw sequence-analysis-channel-next-frame) (cons 'formatted (number->string sequence-analysis-channel-next-frame))))
        (cons 'sequence-analysis-channel-prev-frame (list (cons 'raw sequence-analysis-channel-prev-frame) (cons 'formatted (number->string sequence-analysis-channel-prev-frame))))
        (cons 'sequence-analysis-term-offset-frame (list (cons 'raw sequence-analysis-term-offset-frame) (cons 'formatted (number->string sequence-analysis-term-offset-frame))))
        (cons 'pad-frame-length (list (cons 'raw pad-frame-length) (cons 'formatted (number->string pad-frame-length))))
        (cons 'pad-version (list (cons 'raw pad-version) (cons 'formatted (number->string pad-version))))
        (cons 'pad-flags (list (cons 'raw pad-flags) (cons 'formatted (fmt-hex pad-flags))))
        (cons 'pad-term-offset (list (cons 'raw pad-term-offset) (cons 'formatted (number->string pad-term-offset))))
        (cons 'pad-session-id (list (cons 'raw pad-session-id) (cons 'formatted (number->string pad-session-id))))
        (cons 'pad-stream-id (list (cons 'raw pad-stream-id) (cons 'formatted (number->string pad-stream-id))))
        (cons 'pad-term-id (list (cons 'raw pad-term-id) (cons 'formatted (number->string pad-term-id))))
        (cons 'data-frame-length (list (cons 'raw data-frame-length) (cons 'formatted (number->string data-frame-length))))
        (cons 'data-version (list (cons 'raw data-version) (cons 'formatted (number->string data-version))))
        (cons 'data-flags (list (cons 'raw data-flags) (cons 'formatted (fmt-hex data-flags))))
        (cons 'data-term-offset (list (cons 'raw data-term-offset) (cons 'formatted (number->string data-term-offset))))
        (cons 'data-session-id (list (cons 'raw data-session-id) (cons 'formatted (number->string data-session-id))))
        (cons 'data-stream-id (list (cons 'raw data-stream-id) (cons 'formatted (number->string data-stream-id))))
        (cons 'data-term-id (list (cons 'raw data-term-id) (cons 'formatted (number->string data-term-id))))
        (cons 'data-reserved-value (list (cons 'raw data-reserved-value) (cons 'formatted (number->string data-reserved-value))))
        (cons 'nak-frame-length (list (cons 'raw nak-frame-length) (cons 'formatted (number->string nak-frame-length))))
        (cons 'nak-version (list (cons 'raw nak-version) (cons 'formatted (number->string nak-version))))
        (cons 'nak-flags (list (cons 'raw nak-flags) (cons 'formatted (fmt-hex nak-flags))))
        (cons 'nak-session-id (list (cons 'raw nak-session-id) (cons 'formatted (number->string nak-session-id))))
        (cons 'nak-stream-id (list (cons 'raw nak-stream-id) (cons 'formatted (number->string nak-stream-id))))
        (cons 'nak-term-id (list (cons 'raw nak-term-id) (cons 'formatted (number->string nak-term-id))))
        (cons 'nak-term-offset (list (cons 'raw nak-term-offset) (cons 'formatted (number->string nak-term-offset))))
        (cons 'nak-length (list (cons 'raw nak-length) (cons 'formatted (number->string nak-length))))
        (cons 'sm-frame-length (list (cons 'raw sm-frame-length) (cons 'formatted (number->string sm-frame-length))))
        (cons 'sm-version (list (cons 'raw sm-version) (cons 'formatted (number->string sm-version))))
        (cons 'sm-flags (list (cons 'raw sm-flags) (cons 'formatted (fmt-hex sm-flags))))
        (cons 'sm-session-id (list (cons 'raw sm-session-id) (cons 'formatted (number->string sm-session-id))))
        (cons 'sm-stream-id (list (cons 'raw sm-stream-id) (cons 'formatted (number->string sm-stream-id))))
        (cons 'sm-consumption-term-id (list (cons 'raw sm-consumption-term-id) (cons 'formatted (number->string sm-consumption-term-id))))
        (cons 'sm-consumption-term-offset (list (cons 'raw sm-consumption-term-offset) (cons 'formatted (number->string sm-consumption-term-offset))))
        (cons 'sm-receiver-window (list (cons 'raw sm-receiver-window) (cons 'formatted (number->string sm-receiver-window))))
        (cons 'sm-receiver-id (list (cons 'raw sm-receiver-id) (cons 'formatted (number->string sm-receiver-id))))
        (cons 'sm-feedback (list (cons 'raw sm-feedback) (cons 'formatted (fmt-bytes sm-feedback))))
        (cons 'err-frame-length (list (cons 'raw err-frame-length) (cons 'formatted (number->string err-frame-length))))
        (cons 'err-version (list (cons 'raw err-version) (cons 'formatted (number->string err-version))))
        (cons 'err-code (list (cons 'raw err-code) (cons 'formatted (fmt-hex err-code))))
        (cons 'err-off-frame-length (list (cons 'raw err-off-frame-length) (cons 'formatted (number->string err-off-frame-length))))
        (cons 'err-off-hdr (list (cons 'raw err-off-hdr) (cons 'formatted (fmt-bytes err-off-hdr))))
        (cons 'err-string (list (cons 'raw err-string) (cons 'formatted (utf8->string err-string))))
        (cons 'heartbeat-frame-length (list (cons 'raw heartbeat-frame-length) (cons 'formatted (number->string heartbeat-frame-length))))
        (cons 'heartbeat-version (list (cons 'raw heartbeat-version) (cons 'formatted (number->string heartbeat-version))))
        (cons 'heartbeat-flags (list (cons 'raw heartbeat-flags) (cons 'formatted (fmt-hex heartbeat-flags))))
        (cons 'heartbeat-term-offset (list (cons 'raw heartbeat-term-offset) (cons 'formatted (number->string heartbeat-term-offset))))
        (cons 'heartbeat-session-id (list (cons 'raw heartbeat-session-id) (cons 'formatted (number->string heartbeat-session-id))))
        (cons 'heartbeat-stream-id (list (cons 'raw heartbeat-stream-id) (cons 'formatted (number->string heartbeat-stream-id))))
        (cons 'heartbeat-term-id (list (cons 'raw heartbeat-term-id) (cons 'formatted (number->string heartbeat-term-id))))
        (cons 'rtt-frame-length (list (cons 'raw rtt-frame-length) (cons 'formatted (number->string rtt-frame-length))))
        (cons 'rtt-version (list (cons 'raw rtt-version) (cons 'formatted (number->string rtt-version))))
        (cons 'rtt-flags (list (cons 'raw rtt-flags) (cons 'formatted (fmt-hex rtt-flags))))
        (cons 'rtt-flags-r (list (cons 'raw rtt-flags-r) (cons 'formatted (if (= rtt-flags-r 0) "Not set" "Set"))))
        (cons 'rtt-session-id (list (cons 'raw rtt-session-id) (cons 'formatted (number->string rtt-session-id))))
        (cons 'rtt-stream-id (list (cons 'raw rtt-stream-id) (cons 'formatted (number->string rtt-stream-id))))
        (cons 'rtt-echo-timestamp (list (cons 'raw rtt-echo-timestamp) (cons 'formatted (number->string rtt-echo-timestamp))))
        (cons 'rtt-reception-delta (list (cons 'raw rtt-reception-delta) (cons 'formatted (number->string rtt-reception-delta))))
        (cons 'rtt-receiver-id (list (cons 'raw rtt-receiver-id) (cons 'formatted (number->string rtt-receiver-id))))
        (cons 'setup-frame-length (list (cons 'raw setup-frame-length) (cons 'formatted (number->string setup-frame-length))))
        (cons 'setup-version (list (cons 'raw setup-version) (cons 'formatted (number->string setup-version))))
        (cons 'setup-flags (list (cons 'raw setup-flags) (cons 'formatted (fmt-hex setup-flags))))
        (cons 'setup-term-offset (list (cons 'raw setup-term-offset) (cons 'formatted (number->string setup-term-offset))))
        (cons 'setup-session-id (list (cons 'raw setup-session-id) (cons 'formatted (number->string setup-session-id))))
        (cons 'setup-stream-id (list (cons 'raw setup-stream-id) (cons 'formatted (number->string setup-stream-id))))
        (cons 'setup-initial-term-id (list (cons 'raw setup-initial-term-id) (cons 'formatted (number->string setup-initial-term-id))))
        (cons 'setup-active-term-id (list (cons 'raw setup-active-term-id) (cons 'formatted (number->string setup-active-term-id))))
        (cons 'setup-term-length (list (cons 'raw setup-term-length) (cons 'formatted (number->string setup-term-length))))
        (cons 'setup-mtu (list (cons 'raw setup-mtu) (cons 'formatted (number->string setup-mtu))))
        (cons 'setup-ttl (list (cons 'raw setup-ttl) (cons 'formatted (number->string setup-ttl))))
        )))

    (catch (e)
      (err (str "AERON parse error: " e)))))

;; dissect-aeron: parse AERON from bytevector
;; Returns (ok fields-alist) or (err message)