;; packet-atm.c
;; Routines for ATM packet disassembly
;;
;; Wireshark - Network traffic analyzer
;; By Gerald Combs <gerald@wireshark.org>
;; Copyright 1998 Gerald Combs
;;
;; SPDX-License-Identifier: GPL-2.0-or-later
;;

;; jerboa-ethereal/dissectors/atm.ss
;; Auto-generated from wireshark/epan/dissectors/packet-atm.c

(import (jerboa prelude))

;; ── Protocol Helpers ─────────────────────────────────────────────────
(def (read-u8 buf offset)
  (if (>= offset (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u8-ref buf offset))))

(def (read-u16be buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness big)))))

(def (read-u24be buf offset)
  (if (> (+ offset 3) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (+ (* (bytevector-u8-ref buf offset) 65536)
             (* (bytevector-u8-ref buf (+ offset 1)) 256)
             (bytevector-u8-ref buf (+ offset 2))))))

(def (read-u32be buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness big)))))

(def (read-u16le buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness little)))))

(def (read-u32le buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness little)))))

(def (read-u64be buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness big)))))

(def (read-u64le buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness little)))))

(def (slice buf offset len)
  (if (> (+ offset len) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (let ((result (make-bytevector len)))
            (bytevector-copy! buf offset result 0 len)
            result))))

(def (extract-bits val mask shift)
  (bitwise-arithmetic-shift-right (bitwise-and val mask) shift))

(def (fmt-ipv4 addr)
  (let ((b0 (bitwise-arithmetic-shift-right addr 24))
        (b1 (bitwise-and (bitwise-arithmetic-shift-right addr 16) 255))
        (b2 (bitwise-and (bitwise-arithmetic-shift-right addr 8) 255))
        (b3 (bitwise-and addr 255)))
    (str b0 "." b1 "." b2 "." b3)))

(def (fmt-mac bytes)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bytes))
    ":"))

(def (fmt-hex val)
  (str "0x" (number->string val 16)))

(def (fmt-oct val)
  (str "0" (number->string val 8)))

(def (fmt-port port)
  (number->string port))

(def (fmt-bytes bv)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bv))
    " "))

(def (fmt-ipv6-address bytes)
  (let loop ((i 0) (parts '()))
    (if (>= i 16)
        (string-join (reverse parts) ":")
        (loop (+ i 2)
              (cons (let ((w (+ (* (bytevector-u8-ref bytes i) 256)
                                (bytevector-u8-ref bytes (+ i 1)))))
                      (number->string w 16))
                    parts)))))

;; ── Dissector ──────────────────────────────────────────────────────
(def (dissect-atm buffer)
  "Asynchronous Transfer Mode"
  (try
    (let* (
           (gfc (unwrap (read-u8 buffer 0)))
           (cid (unwrap (read-u8 buffer 0)))
           (padding (unwrap (slice buffer 0 2)))
           (aal5-crc (unwrap (read-u32be buffer 0)))
           (aal5-len (unwrap (read-u16be buffer 0)))
           (aal5-cpi (unwrap (read-u8 buffer 0)))
           (aal5-uu (unwrap (read-u8 buffer 0)))
           (cells (unwrap (read-u16be buffer 0)))
           (vci (unwrap (read-u16be buffer 0)))
           (vpi (unwrap (read-u16be buffer 0)))
           (le-client-client (unwrap (read-u16be buffer 0)))
           (le-control-marker (unwrap (read-u16be buffer 0)))
           (lan-destination-mac (unwrap (slice buffer 2 6)))
           (le-control-protocol (unwrap (read-u8 buffer 2)))
           (cell-loss-priority (unwrap (read-u8 buffer 3)))
           (payload-type (unwrap (read-u8 buffer 3)))
           (le-control-version (unwrap (read-u8 buffer 3)))
           (header-error-check (unwrap (read-u8 buffer 4)))
           (lan-destination-route-desc (unwrap (read-u16be buffer 6)))
           (lan-destination-lan-id (unwrap (read-u16be buffer 6)))
           (lan-destination-bridge-num (unwrap (read-u16be buffer 6)))
           (le-control-tlv-length (unwrap (read-u8 buffer 6)))
           (le-control-transaction-id (unwrap (read-u32be buffer 8)))
           (le-control-requester-lecid (unwrap (read-u16be buffer 12)))
           (le-control-flags (unwrap (read-u16be buffer 14)))
           (le-control-flag-v2-capable (unwrap (read-u8 buffer 16)))
           (le-control-flag-selective-multicast (unwrap (read-u8 buffer 16)))
           (le-control-flag-v2-required (unwrap (read-u8 buffer 16)))
           (le-control-flag-proxy (unwrap (read-u8 buffer 16)))
           (le-control-flag-exclude-explorer-frames (unwrap (read-u8 buffer 16)))
           (le-control-flag-address (unwrap (read-u8 buffer 20)))
           (le-control-topology-change (unwrap (read-u8 buffer 22)))
           (reserved (unwrap (slice buffer 24 92)))
           (aa1-csi (unwrap (read-u8 buffer 28)))
           (aa1-seq-count (unwrap (read-u8 buffer 28)))
           (aa1-crc (unwrap (read-u8 buffer 28)))
           (aa1-parity (unwrap (read-u8 buffer 28)))
           (aa1-payload (unwrap (slice buffer 28 47)))
           (aal3-4-seq-num (unwrap (read-u16be buffer 28)))
           (aal3-4-multiplex-id (unwrap (read-u16be buffer 28)))
           (aal3-4-information (unwrap (slice buffer 30 44)))
           (le-configure-join-frame-num-tlvs (unwrap (read-u8 buffer 49)))
           (le-configure-join-frame-elan-name-size (unwrap (read-u8 buffer 50)))
           (le-configure-join-frame-elan-name (unwrap (slice buffer 71 1)))
           (aal3-4-crc (unwrap (read-u16be buffer 74)))
           (aal-oamcell-type-ft (unwrap (read-u8 buffer 74)))
           (aal-oamcell-func-spec (unwrap (slice buffer 75 45)))
           (aal-oamcell-crc (unwrap (read-u16be buffer 120)))
           (le-registration-frame-num-tlvs (unwrap (read-u8 buffer 141)))
           (le-arp-frame-num-tlvs (unwrap (read-u8 buffer 233)))
           (le-verify-frame-num-tlvs (unwrap (read-u8 buffer 325)))
           (source-atm (unwrap (slice buffer 395 20)))
           (target-atm (unwrap (slice buffer 419 20)))
           )

      (ok (list
        (cons 'gfc (list (cons 'raw gfc) (cons 'formatted (number->string gfc))))
        (cons 'cid (list (cons 'raw cid) (cons 'formatted (number->string cid))))
        (cons 'padding (list (cons 'raw padding) (cons 'formatted (fmt-bytes padding))))
        (cons 'aal5-crc (list (cons 'raw aal5-crc) (cons 'formatted (fmt-hex aal5-crc))))
        (cons 'aal5-len (list (cons 'raw aal5-len) (cons 'formatted (number->string aal5-len))))
        (cons 'aal5-cpi (list (cons 'raw aal5-cpi) (cons 'formatted (fmt-hex aal5-cpi))))
        (cons 'aal5-uu (list (cons 'raw aal5-uu) (cons 'formatted (fmt-hex aal5-uu))))
        (cons 'cells (list (cons 'raw cells) (cons 'formatted (number->string cells))))
        (cons 'vci (list (cons 'raw vci) (cons 'formatted (number->string vci))))
        (cons 'vpi (list (cons 'raw vpi) (cons 'formatted (number->string vpi))))
        (cons 'le-client-client (list (cons 'raw le-client-client) (cons 'formatted (fmt-hex le-client-client))))
        (cons 'le-control-marker (list (cons 'raw le-control-marker) (cons 'formatted (fmt-hex le-control-marker))))
        (cons 'lan-destination-mac (list (cons 'raw lan-destination-mac) (cons 'formatted (fmt-mac lan-destination-mac))))
        (cons 'le-control-protocol (list (cons 'raw le-control-protocol) (cons 'formatted (fmt-hex le-control-protocol))))
        (cons 'cell-loss-priority (list (cons 'raw cell-loss-priority) (cons 'formatted (if (= cell-loss-priority 0) "High priority" "Low priority"))))
        (cons 'payload-type (list (cons 'raw payload-type) (cons 'formatted (number->string payload-type))))
        (cons 'le-control-version (list (cons 'raw le-control-version) (cons 'formatted (fmt-hex le-control-version))))
        (cons 'header-error-check (list (cons 'raw header-error-check) (cons 'formatted (fmt-hex header-error-check))))
        (cons 'lan-destination-route-desc (list (cons 'raw lan-destination-route-desc) (cons 'formatted (fmt-hex lan-destination-route-desc))))
        (cons 'lan-destination-lan-id (list (cons 'raw lan-destination-lan-id) (cons 'formatted (number->string lan-destination-lan-id))))
        (cons 'lan-destination-bridge-num (list (cons 'raw lan-destination-bridge-num) (cons 'formatted (number->string lan-destination-bridge-num))))
        (cons 'le-control-tlv-length (list (cons 'raw le-control-tlv-length) (cons 'formatted (number->string le-control-tlv-length))))
        (cons 'le-control-transaction-id (list (cons 'raw le-control-transaction-id) (cons 'formatted (fmt-hex le-control-transaction-id))))
        (cons 'le-control-requester-lecid (list (cons 'raw le-control-requester-lecid) (cons 'formatted (fmt-hex le-control-requester-lecid))))
        (cons 'le-control-flags (list (cons 'raw le-control-flags) (cons 'formatted (fmt-hex le-control-flags))))
        (cons 'le-control-flag-v2-capable (list (cons 'raw le-control-flag-v2-capable) (cons 'formatted (if (= le-control-flag-v2-capable 0) "False" "True"))))
        (cons 'le-control-flag-selective-multicast (list (cons 'raw le-control-flag-selective-multicast) (cons 'formatted (if (= le-control-flag-selective-multicast 0) "False" "True"))))
        (cons 'le-control-flag-v2-required (list (cons 'raw le-control-flag-v2-required) (cons 'formatted (if (= le-control-flag-v2-required 0) "False" "True"))))
        (cons 'le-control-flag-proxy (list (cons 'raw le-control-flag-proxy) (cons 'formatted (if (= le-control-flag-proxy 0) "False" "True"))))
        (cons 'le-control-flag-exclude-explorer-frames (list (cons 'raw le-control-flag-exclude-explorer-frames) (cons 'formatted (if (= le-control-flag-exclude-explorer-frames 0) "False" "True"))))
        (cons 'le-control-flag-address (list (cons 'raw le-control-flag-address) (cons 'formatted (if (= le-control-flag-address 0) "False" "True"))))
        (cons 'le-control-topology-change (list (cons 'raw le-control-topology-change) (cons 'formatted (if (= le-control-topology-change 0) "Local" "Remote"))))
        (cons 'reserved (list (cons 'raw reserved) (cons 'formatted (fmt-bytes reserved))))
        (cons 'aa1-csi (list (cons 'raw aa1-csi) (cons 'formatted (number->string aa1-csi))))
        (cons 'aa1-seq-count (list (cons 'raw aa1-seq-count) (cons 'formatted (number->string aa1-seq-count))))
        (cons 'aa1-crc (list (cons 'raw aa1-crc) (cons 'formatted (number->string aa1-crc))))
        (cons 'aa1-parity (list (cons 'raw aa1-parity) (cons 'formatted (number->string aa1-parity))))
        (cons 'aa1-payload (list (cons 'raw aa1-payload) (cons 'formatted (fmt-bytes aa1-payload))))
        (cons 'aal3-4-seq-num (list (cons 'raw aal3-4-seq-num) (cons 'formatted (number->string aal3-4-seq-num))))
        (cons 'aal3-4-multiplex-id (list (cons 'raw aal3-4-multiplex-id) (cons 'formatted (number->string aal3-4-multiplex-id))))
        (cons 'aal3-4-information (list (cons 'raw aal3-4-information) (cons 'formatted (fmt-bytes aal3-4-information))))
        (cons 'le-configure-join-frame-num-tlvs (list (cons 'raw le-configure-join-frame-num-tlvs) (cons 'formatted (number->string le-configure-join-frame-num-tlvs))))
        (cons 'le-configure-join-frame-elan-name-size (list (cons 'raw le-configure-join-frame-elan-name-size) (cons 'formatted (number->string le-configure-join-frame-elan-name-size))))
        (cons 'le-configure-join-frame-elan-name (list (cons 'raw le-configure-join-frame-elan-name) (cons 'formatted (fmt-bytes le-configure-join-frame-elan-name))))
        (cons 'aal3-4-crc (list (cons 'raw aal3-4-crc) (cons 'formatted (number->string aal3-4-crc))))
        (cons 'aal-oamcell-type-ft (list (cons 'raw aal-oamcell-type-ft) (cons 'formatted (number->string aal-oamcell-type-ft))))
        (cons 'aal-oamcell-func-spec (list (cons 'raw aal-oamcell-func-spec) (cons 'formatted (fmt-bytes aal-oamcell-func-spec))))
        (cons 'aal-oamcell-crc (list (cons 'raw aal-oamcell-crc) (cons 'formatted (fmt-hex aal-oamcell-crc))))
        (cons 'le-registration-frame-num-tlvs (list (cons 'raw le-registration-frame-num-tlvs) (cons 'formatted (number->string le-registration-frame-num-tlvs))))
        (cons 'le-arp-frame-num-tlvs (list (cons 'raw le-arp-frame-num-tlvs) (cons 'formatted (number->string le-arp-frame-num-tlvs))))
        (cons 'le-verify-frame-num-tlvs (list (cons 'raw le-verify-frame-num-tlvs) (cons 'formatted (number->string le-verify-frame-num-tlvs))))
        (cons 'source-atm (list (cons 'raw source-atm) (cons 'formatted (fmt-bytes source-atm))))
        (cons 'target-atm (list (cons 'raw target-atm) (cons 'formatted (fmt-bytes target-atm))))
        )))

    (catch (e)
      (err (str "ATM parse error: " e)))))

;; dissect-atm: parse ATM from bytevector
;; Returns (ok fields-alist) or (err message)