;; packet-bpv6.c
;; References:
;; RFC 5050: https://tools.ietf.org/html/rfc5050
;;
;; Copyright 2006-2007 The MITRE Corporation.
;; All Rights Reserved.
;; Approved for Public Release; Distribution Unlimited.
;; Tracking Number 07-0090.
;;
;; The US Government will not be charged any license fee and/or royalties
;; related to this software. Neither name of The MITRE Corporation; nor the
;; names of its contributors may be used to endorse or promote products
;; derived from this software without specific prior written permission.
;;
;; Wireshark - Network traffic analyzer
;; By Gerald Combs <gerald@wireshark.org>
;; Copyright 1998 Gerald Combs
;;
;; SPDX-License-Identifier: GPL-2.0-or-later
;;
;; Specification reference:
;; RFC 5050
;; https://tools.ietf.org/html/rfc5050
;;

;; jerboa-ethereal/dissectors/bpv6.ss
;; Auto-generated from wireshark/epan/dissectors/packet-bpv6.c
;; RFC 5050

(import (jerboa prelude))

;; ── Protocol Helpers ─────────────────────────────────────────────────
(def (read-u8 buf offset)
  (if (>= offset (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u8-ref buf offset))))

(def (read-u16be buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness big)))))

(def (read-u24be buf offset)
  (if (> (+ offset 3) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (+ (* (bytevector-u8-ref buf offset) 65536)
             (* (bytevector-u8-ref buf (+ offset 1)) 256)
             (bytevector-u8-ref buf (+ offset 2))))))

(def (read-u32be buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness big)))))

(def (read-u16le buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness little)))))

(def (read-u32le buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness little)))))

(def (read-u64be buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness big)))))

(def (read-u64le buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness little)))))

(def (slice buf offset len)
  (if (> (+ offset len) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (let ((result (make-bytevector len)))
            (bytevector-copy! buf offset result 0 len)
            result))))

(def (extract-bits val mask shift)
  (bitwise-arithmetic-shift-right (bitwise-and val mask) shift))

(def (fmt-ipv4 addr)
  (let ((b0 (bitwise-arithmetic-shift-right addr 24))
        (b1 (bitwise-and (bitwise-arithmetic-shift-right addr 16) 255))
        (b2 (bitwise-and (bitwise-arithmetic-shift-right addr 8) 255))
        (b3 (bitwise-and addr 255)))
    (str b0 "." b1 "." b2 "." b3)))

(def (fmt-mac bytes)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bytes))
    ":"))

(def (fmt-hex val)
  (str "0x" (number->string val 16)))

(def (fmt-oct val)
  (str "0" (number->string val 8)))

(def (fmt-port port)
  (number->string port))

(def (fmt-bytes bv)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bv))
    " "))

(def (fmt-ipv6-address bytes)
  (let loop ((i 0) (parts '()))
    (if (>= i 16)
        (string-join (reverse parts) ":")
        (loop (+ i 2)
              (cons (let ((w (+ (* (bytevector-u8-ref bytes i) 256)
                                (bytevector-u8-ref bytes (+ i 1)))))
                      (number->string w 16))
                    parts)))))

;; ── Dissector ──────────────────────────────────────────────────────
(def (dissect-bpv6 buffer)
  "Bundle Protocol"
  (try
    (let* (
           (custodian-scheme (unwrap (slice buffer 0 1)))
           (report-scheme (unwrap (slice buffer 0 1)))
           (source-scheme (unwrap (slice buffer 0 1)))
           (dest-scheme (unwrap (slice buffer 0 1)))
           (pdu-version (unwrap (read-u8 buffer 0)))
           (procflags (unwrap (read-u8 buffer 1)))
           (procflags-fragment (unwrap (read-u8 buffer 1)))
           (procflags-admin (unwrap (read-u8 buffer 1)))
           (procflags-dont-fragment (unwrap (read-u8 buffer 1)))
           (procflags-cust-xfer-req (unwrap (read-u8 buffer 1)))
           (procflags-dest-singleton (unwrap (read-u8 buffer 1)))
           (cosflags (unwrap (read-u8 buffer 1)))
           (srrflags (unwrap (read-u8 buffer 1)))
           (srrflags-report-receipt (unwrap (read-u8 buffer 1)))
           (srrflags-report-cust-accept (unwrap (read-u8 buffer 1)))
           (srrflags-report-forward (unwrap (read-u8 buffer 1)))
           (srrflags-report-delivery (unwrap (read-u8 buffer 1)))
           (srrflags-report-deletion (unwrap (read-u8 buffer 1)))
           (srrflags-report-ack (unwrap (read-u8 buffer 1)))
           (primary-header-len (unwrap (read-u32be buffer 1)))
           (dest-scheme-offset-u16 (unwrap (read-u16be buffer 1)))
           (procflags-general (unwrap (read-u8 buffer 1)))
           (procflags-cos (unwrap (read-u8 buffer 1)))
           (procflags-status (unwrap (read-u8 buffer 1)))
           (dest-scheme-offset-i32 (unwrap (read-u32be buffer 1)))
           (dest-ssp-offset-i32 (unwrap (read-u32be buffer 1)))
           (source-scheme-offset-i32 (unwrap (read-u32be buffer 1)))
           (source-ssp-offset-i32 (unwrap (read-u32be buffer 1)))
           (report-scheme-offset-i32 (unwrap (read-u32be buffer 1)))
           (report-ssp-offset-i32 (unwrap (read-u32be buffer 1)))
           (cust-scheme-offset-i32 (unwrap (read-u32be buffer 1)))
           (cust-ssp-offset-i32 (unwrap (read-u32be buffer 1)))
           (primary-timestamp-seq-num64 (unwrap (read-u64be buffer 1)))
           (primary-timestamp-seq-num32 (unwrap (read-u32be buffer 1)))
           (primary-dictionary-len (unwrap (read-u32be buffer 1)))
           (payload-header-type (unwrap (read-u8 buffer 1)))
           (payload-flags (unwrap (read-u8 buffer 1)))
           (payload-flags-replicate-hdr (extract-bits payload-flags 0x0 0))
           (payload-flags-xmit-report (extract-bits payload-flags 0x0 0))
           (payload-flags-discard-on-fail (extract-bits payload-flags 0x0 0))
           (payload-flags-last-header (extract-bits payload-flags 0x0 0))
           (control-flags (unwrap (read-u8 buffer 1)))
           (control-replicate (unwrap (read-u8 buffer 1)))
           (control-transmit-status (unwrap (read-u8 buffer 1)))
           (control-delete-bundle (unwrap (read-u8 buffer 1)))
           (control-last-block (unwrap (read-u8 buffer 1)))
           (control-discard-block (unwrap (read-u8 buffer 1)))
           (control-not-processed (unwrap (read-u8 buffer 1)))
           (control-eid-reference (unwrap (read-u8 buffer 1)))
           (payload-length (unwrap (read-u32be buffer 1)))
           (payload-data (unwrap (slice buffer 1 1)))
           (admin-record-fragment (unwrap (read-u8 buffer 1)))
           (admin-statflags (unwrap (read-u8 buffer 1)))
           (admin-rcvd (unwrap (read-u8 buffer 1)))
           (admin-accepted (unwrap (read-u8 buffer 1)))
           (admin-forwarded (unwrap (read-u8 buffer 1)))
           (admin-delivered (unwrap (read-u8 buffer 1)))
           (admin-deleted (unwrap (read-u8 buffer 1)))
           (admin-acked (unwrap (read-u8 buffer 1)))
           (admin-timestamp-seq-num64 (unwrap (read-u64be buffer 1)))
           (admin-timestamp-seq-num32 (unwrap (read-u32be buffer 1)))
           (admin-endpoint-length (unwrap (read-u32be buffer 1)))
           (admin-endpoint-id (unwrap (slice buffer 1 1)))
           (custody-trf-succ-flg (unwrap (read-u8 buffer 1)))
           (custody-id-range-start (unwrap (read-u32be buffer 1)))
           (custody-id-range-end (unwrap (read-u32be buffer 1)))
           (control-flags-sdnv (unwrap (read-u32be buffer 1)))
           (control-block-length (unwrap (read-u32be buffer 1)))
           (age-extension-block-code (unwrap (read-u32be buffer 1)))
           (block-previous-hop-scheme (unwrap (slice buffer 1 4)))
           (block-previous-hop-eid (unwrap (slice buffer 1 1)))
           (target-block-type (unwrap (read-u32be buffer 1)))
           (target-block-occurrence (unwrap (read-u32be buffer 1)))
           (ciphersuite-flags (unwrap (read-u8 buffer 1)))
           (ciphersuite-params (unwrap (read-u8 buffer 1)))
           (ciphersuite-params-length (unwrap (read-u8 buffer 1)))
           (ciphersuite-params-item-length (unwrap (read-u8 buffer 1)))
           (ciphersuite-param-data (unwrap (slice buffer 1 1)))
           (ciphersuite-range-offset (unwrap (read-u8 buffer 1)))
           (ciphersuite-range-length (unwrap (read-u8 buffer 1)))
           (ciphersuite-result-length (unwrap (read-u8 buffer 1)))
           (ciphersuite-result-item-length (unwrap (read-u8 buffer 1)))
           (ciphersuite-result-data (unwrap (slice buffer 1 1)))
           (control-block-cteb-custody-id (unwrap (read-u32be buffer 1)))
           (control-block-cteb-creator-custodian-eid (unwrap (slice buffer 1 1)))
           (flags (unwrap (read-u8 buffer 1)))
           (flags-critical (extract-bits flags 0x0 0))
           (flags-streaming (extract-bits flags 0x0 0))
           (flags-flowlabel (extract-bits flags 0x0 0))
           (flags-reliable (extract-bits flags 0x0 0))
           (ordinal (unwrap (read-u8 buffer 2)))
           (dest-ssp-offset-u16 (unwrap (read-u16be buffer 3)))
           (flow-label (unwrap (read-u32be buffer 3)))
           (unprocessed-block-data (unwrap (slice buffer 3 1)))
           (source-scheme-offset-u16 (unwrap (read-u16be buffer 5)))
           (source-ssp-offset-u16 (unwrap (read-u16be buffer 7)))
           (report-scheme-offset-u16 (unwrap (read-u16be buffer 9)))
           (report-ssp-offset-u16 (unwrap (read-u16be buffer 11)))
           (cust-scheme-offset-u16 (unwrap (read-u16be buffer 13)))
           (cust-ssp-offset-u16 (unwrap (read-u16be buffer 15)))
           (creation-timestamp (unwrap (read-u64be buffer 17)))
           (lifetime (unwrap (read-u32be buffer 25)))
           )

      (ok (list
        (cons 'custodian-scheme (list (cons 'raw custodian-scheme) (cons 'formatted (utf8->string custodian-scheme))))
        (cons 'report-scheme (list (cons 'raw report-scheme) (cons 'formatted (utf8->string report-scheme))))
        (cons 'source-scheme (list (cons 'raw source-scheme) (cons 'formatted (utf8->string source-scheme))))
        (cons 'dest-scheme (list (cons 'raw dest-scheme) (cons 'formatted (utf8->string dest-scheme))))
        (cons 'pdu-version (list (cons 'raw pdu-version) (cons 'formatted (number->string pdu-version))))
        (cons 'procflags (list (cons 'raw procflags) (cons 'formatted (fmt-hex procflags))))
        (cons 'procflags-fragment (list (cons 'raw procflags-fragment) (cons 'formatted (number->string procflags-fragment))))
        (cons 'procflags-admin (list (cons 'raw procflags-admin) (cons 'formatted (number->string procflags-admin))))
        (cons 'procflags-dont-fragment (list (cons 'raw procflags-dont-fragment) (cons 'formatted (number->string procflags-dont-fragment))))
        (cons 'procflags-cust-xfer-req (list (cons 'raw procflags-cust-xfer-req) (cons 'formatted (number->string procflags-cust-xfer-req))))
        (cons 'procflags-dest-singleton (list (cons 'raw procflags-dest-singleton) (cons 'formatted (number->string procflags-dest-singleton))))
        (cons 'cosflags (list (cons 'raw cosflags) (cons 'formatted (fmt-hex cosflags))))
        (cons 'srrflags (list (cons 'raw srrflags) (cons 'formatted (fmt-hex srrflags))))
        (cons 'srrflags-report-receipt (list (cons 'raw srrflags-report-receipt) (cons 'formatted (number->string srrflags-report-receipt))))
        (cons 'srrflags-report-cust-accept (list (cons 'raw srrflags-report-cust-accept) (cons 'formatted (number->string srrflags-report-cust-accept))))
        (cons 'srrflags-report-forward (list (cons 'raw srrflags-report-forward) (cons 'formatted (number->string srrflags-report-forward))))
        (cons 'srrflags-report-delivery (list (cons 'raw srrflags-report-delivery) (cons 'formatted (number->string srrflags-report-delivery))))
        (cons 'srrflags-report-deletion (list (cons 'raw srrflags-report-deletion) (cons 'formatted (number->string srrflags-report-deletion))))
        (cons 'srrflags-report-ack (list (cons 'raw srrflags-report-ack) (cons 'formatted (number->string srrflags-report-ack))))
        (cons 'primary-header-len (list (cons 'raw primary-header-len) (cons 'formatted (number->string primary-header-len))))
        (cons 'dest-scheme-offset-u16 (list (cons 'raw dest-scheme-offset-u16) (cons 'formatted (number->string dest-scheme-offset-u16))))
        (cons 'procflags-general (list (cons 'raw procflags-general) (cons 'formatted (fmt-hex procflags-general))))
        (cons 'procflags-cos (list (cons 'raw procflags-cos) (cons 'formatted (fmt-hex procflags-cos))))
        (cons 'procflags-status (list (cons 'raw procflags-status) (cons 'formatted (fmt-hex procflags-status))))
        (cons 'dest-scheme-offset-i32 (list (cons 'raw dest-scheme-offset-i32) (cons 'formatted (number->string dest-scheme-offset-i32))))
        (cons 'dest-ssp-offset-i32 (list (cons 'raw dest-ssp-offset-i32) (cons 'formatted (number->string dest-ssp-offset-i32))))
        (cons 'source-scheme-offset-i32 (list (cons 'raw source-scheme-offset-i32) (cons 'formatted (number->string source-scheme-offset-i32))))
        (cons 'source-ssp-offset-i32 (list (cons 'raw source-ssp-offset-i32) (cons 'formatted (number->string source-ssp-offset-i32))))
        (cons 'report-scheme-offset-i32 (list (cons 'raw report-scheme-offset-i32) (cons 'formatted (number->string report-scheme-offset-i32))))
        (cons 'report-ssp-offset-i32 (list (cons 'raw report-ssp-offset-i32) (cons 'formatted (number->string report-ssp-offset-i32))))
        (cons 'cust-scheme-offset-i32 (list (cons 'raw cust-scheme-offset-i32) (cons 'formatted (number->string cust-scheme-offset-i32))))
        (cons 'cust-ssp-offset-i32 (list (cons 'raw cust-ssp-offset-i32) (cons 'formatted (number->string cust-ssp-offset-i32))))
        (cons 'primary-timestamp-seq-num64 (list (cons 'raw primary-timestamp-seq-num64) (cons 'formatted (number->string primary-timestamp-seq-num64))))
        (cons 'primary-timestamp-seq-num32 (list (cons 'raw primary-timestamp-seq-num32) (cons 'formatted (number->string primary-timestamp-seq-num32))))
        (cons 'primary-dictionary-len (list (cons 'raw primary-dictionary-len) (cons 'formatted (number->string primary-dictionary-len))))
        (cons 'payload-header-type (list (cons 'raw payload-header-type) (cons 'formatted (number->string payload-header-type))))
        (cons 'payload-flags (list (cons 'raw payload-flags) (cons 'formatted (fmt-hex payload-flags))))
        (cons 'payload-flags-replicate-hdr (list (cons 'raw payload-flags-replicate-hdr) (cons 'formatted (if (= payload-flags-replicate-hdr 0) "Not set" "Set"))))
        (cons 'payload-flags-xmit-report (list (cons 'raw payload-flags-xmit-report) (cons 'formatted (if (= payload-flags-xmit-report 0) "Not set" "Set"))))
        (cons 'payload-flags-discard-on-fail (list (cons 'raw payload-flags-discard-on-fail) (cons 'formatted (if (= payload-flags-discard-on-fail 0) "Not set" "Set"))))
        (cons 'payload-flags-last-header (list (cons 'raw payload-flags-last-header) (cons 'formatted (if (= payload-flags-last-header 0) "Not set" "Set"))))
        (cons 'control-flags (list (cons 'raw control-flags) (cons 'formatted (fmt-hex control-flags))))
        (cons 'control-replicate (list (cons 'raw control-replicate) (cons 'formatted (number->string control-replicate))))
        (cons 'control-transmit-status (list (cons 'raw control-transmit-status) (cons 'formatted (number->string control-transmit-status))))
        (cons 'control-delete-bundle (list (cons 'raw control-delete-bundle) (cons 'formatted (number->string control-delete-bundle))))
        (cons 'control-last-block (list (cons 'raw control-last-block) (cons 'formatted (number->string control-last-block))))
        (cons 'control-discard-block (list (cons 'raw control-discard-block) (cons 'formatted (number->string control-discard-block))))
        (cons 'control-not-processed (list (cons 'raw control-not-processed) (cons 'formatted (number->string control-not-processed))))
        (cons 'control-eid-reference (list (cons 'raw control-eid-reference) (cons 'formatted (number->string control-eid-reference))))
        (cons 'payload-length (list (cons 'raw payload-length) (cons 'formatted (number->string payload-length))))
        (cons 'payload-data (list (cons 'raw payload-data) (cons 'formatted (utf8->string payload-data))))
        (cons 'admin-record-fragment (list (cons 'raw admin-record-fragment) (cons 'formatted (if (= admin-record-fragment 0) "False" "True"))))
        (cons 'admin-statflags (list (cons 'raw admin-statflags) (cons 'formatted (fmt-hex admin-statflags))))
        (cons 'admin-rcvd (list (cons 'raw admin-rcvd) (cons 'formatted (number->string admin-rcvd))))
        (cons 'admin-accepted (list (cons 'raw admin-accepted) (cons 'formatted (number->string admin-accepted))))
        (cons 'admin-forwarded (list (cons 'raw admin-forwarded) (cons 'formatted (number->string admin-forwarded))))
        (cons 'admin-delivered (list (cons 'raw admin-delivered) (cons 'formatted (number->string admin-delivered))))
        (cons 'admin-deleted (list (cons 'raw admin-deleted) (cons 'formatted (number->string admin-deleted))))
        (cons 'admin-acked (list (cons 'raw admin-acked) (cons 'formatted (number->string admin-acked))))
        (cons 'admin-timestamp-seq-num64 (list (cons 'raw admin-timestamp-seq-num64) (cons 'formatted (number->string admin-timestamp-seq-num64))))
        (cons 'admin-timestamp-seq-num32 (list (cons 'raw admin-timestamp-seq-num32) (cons 'formatted (number->string admin-timestamp-seq-num32))))
        (cons 'admin-endpoint-length (list (cons 'raw admin-endpoint-length) (cons 'formatted (number->string admin-endpoint-length))))
        (cons 'admin-endpoint-id (list (cons 'raw admin-endpoint-id) (cons 'formatted (utf8->string admin-endpoint-id))))
        (cons 'custody-trf-succ-flg (list (cons 'raw custody-trf-succ-flg) (cons 'formatted (number->string custody-trf-succ-flg))))
        (cons 'custody-id-range-start (list (cons 'raw custody-id-range-start) (cons 'formatted (number->string custody-id-range-start))))
        (cons 'custody-id-range-end (list (cons 'raw custody-id-range-end) (cons 'formatted (number->string custody-id-range-end))))
        (cons 'control-flags-sdnv (list (cons 'raw control-flags-sdnv) (cons 'formatted (fmt-hex control-flags-sdnv))))
        (cons 'control-block-length (list (cons 'raw control-block-length) (cons 'formatted (number->string control-block-length))))
        (cons 'age-extension-block-code (list (cons 'raw age-extension-block-code) (cons 'formatted (number->string age-extension-block-code))))
        (cons 'block-previous-hop-scheme (list (cons 'raw block-previous-hop-scheme) (cons 'formatted (utf8->string block-previous-hop-scheme))))
        (cons 'block-previous-hop-eid (list (cons 'raw block-previous-hop-eid) (cons 'formatted (utf8->string block-previous-hop-eid))))
        (cons 'target-block-type (list (cons 'raw target-block-type) (cons 'formatted (number->string target-block-type))))
        (cons 'target-block-occurrence (list (cons 'raw target-block-occurrence) (cons 'formatted (number->string target-block-occurrence))))
        (cons 'ciphersuite-flags (list (cons 'raw ciphersuite-flags) (cons 'formatted (fmt-hex ciphersuite-flags))))
        (cons 'ciphersuite-params (list (cons 'raw ciphersuite-params) (cons 'formatted (number->string ciphersuite-params))))
        (cons 'ciphersuite-params-length (list (cons 'raw ciphersuite-params-length) (cons 'formatted (number->string ciphersuite-params-length))))
        (cons 'ciphersuite-params-item-length (list (cons 'raw ciphersuite-params-item-length) (cons 'formatted (number->string ciphersuite-params-item-length))))
        (cons 'ciphersuite-param-data (list (cons 'raw ciphersuite-param-data) (cons 'formatted (fmt-bytes ciphersuite-param-data))))
        (cons 'ciphersuite-range-offset (list (cons 'raw ciphersuite-range-offset) (cons 'formatted (number->string ciphersuite-range-offset))))
        (cons 'ciphersuite-range-length (list (cons 'raw ciphersuite-range-length) (cons 'formatted (number->string ciphersuite-range-length))))
        (cons 'ciphersuite-result-length (list (cons 'raw ciphersuite-result-length) (cons 'formatted (number->string ciphersuite-result-length))))
        (cons 'ciphersuite-result-item-length (list (cons 'raw ciphersuite-result-item-length) (cons 'formatted (number->string ciphersuite-result-item-length))))
        (cons 'ciphersuite-result-data (list (cons 'raw ciphersuite-result-data) (cons 'formatted (fmt-bytes ciphersuite-result-data))))
        (cons 'control-block-cteb-custody-id (list (cons 'raw control-block-cteb-custody-id) (cons 'formatted (number->string control-block-cteb-custody-id))))
        (cons 'control-block-cteb-creator-custodian-eid (list (cons 'raw control-block-cteb-creator-custodian-eid) (cons 'formatted (utf8->string control-block-cteb-creator-custodian-eid))))
        (cons 'flags (list (cons 'raw flags) (cons 'formatted (fmt-hex flags))))
        (cons 'flags-critical (list (cons 'raw flags-critical) (cons 'formatted (if (= flags-critical 0) "Not set" "Set"))))
        (cons 'flags-streaming (list (cons 'raw flags-streaming) (cons 'formatted (if (= flags-streaming 0) "Not set" "Set"))))
        (cons 'flags-flowlabel (list (cons 'raw flags-flowlabel) (cons 'formatted (if (= flags-flowlabel 0) "Not set" "Set"))))
        (cons 'flags-reliable (list (cons 'raw flags-reliable) (cons 'formatted (if (= flags-reliable 0) "Not set" "Set"))))
        (cons 'ordinal (list (cons 'raw ordinal) (cons 'formatted (number->string ordinal))))
        (cons 'dest-ssp-offset-u16 (list (cons 'raw dest-ssp-offset-u16) (cons 'formatted (number->string dest-ssp-offset-u16))))
        (cons 'flow-label (list (cons 'raw flow-label) (cons 'formatted (number->string flow-label))))
        (cons 'unprocessed-block-data (list (cons 'raw unprocessed-block-data) (cons 'formatted (utf8->string unprocessed-block-data))))
        (cons 'source-scheme-offset-u16 (list (cons 'raw source-scheme-offset-u16) (cons 'formatted (number->string source-scheme-offset-u16))))
        (cons 'source-ssp-offset-u16 (list (cons 'raw source-ssp-offset-u16) (cons 'formatted (number->string source-ssp-offset-u16))))
        (cons 'report-scheme-offset-u16 (list (cons 'raw report-scheme-offset-u16) (cons 'formatted (number->string report-scheme-offset-u16))))
        (cons 'report-ssp-offset-u16 (list (cons 'raw report-ssp-offset-u16) (cons 'formatted (number->string report-ssp-offset-u16))))
        (cons 'cust-scheme-offset-u16 (list (cons 'raw cust-scheme-offset-u16) (cons 'formatted (number->string cust-scheme-offset-u16))))
        (cons 'cust-ssp-offset-u16 (list (cons 'raw cust-ssp-offset-u16) (cons 'formatted (number->string cust-ssp-offset-u16))))
        (cons 'creation-timestamp (list (cons 'raw creation-timestamp) (cons 'formatted (fmt-hex creation-timestamp))))
        (cons 'lifetime (list (cons 'raw lifetime) (cons 'formatted (number->string lifetime))))
        )))

    (catch (e)
      (err (str "BPV6 parse error: " e)))))

;; dissect-bpv6: parse BPV6 from bytevector
;; Returns (ok fields-alist) or (err message)