;; packet-cfm.c
;; Routines for CFM EOAM dissection
;; Copyright 2007, Keith Mercer <keith.mercer@alcatel-lucent.com>
;; Copyright 2011, Peter Nahas <pnahas@mrv.com>
;; Copyright 2012, Wim Leflere <wim.leflere-ext@oneaccess-net.com>
;; Copyright 2013, Andreas Urke <arurke@gmail.com>
;;
;; Wireshark - Network traffic analyzer
;; By Gerald Combs <gerald@wireshark.org>
;; Copyright 1998 Gerald Combs
;;
;; SPDX-License-Identifier: GPL-2.0-or-later
;;

;; jerboa-ethereal/dissectors/cfm.ss
;; Auto-generated from wireshark/epan/dissectors/packet-cfm.c

(import (jerboa prelude))

;; ── Protocol Helpers ─────────────────────────────────────────────────
(def (read-u8 buf offset)
  (if (>= offset (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u8-ref buf offset))))

(def (read-u16be buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness big)))))

(def (read-u24be buf offset)
  (if (> (+ offset 3) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (+ (* (bytevector-u8-ref buf offset) 65536)
             (* (bytevector-u8-ref buf (+ offset 1)) 256)
             (bytevector-u8-ref buf (+ offset 2))))))

(def (read-u32be buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness big)))))

(def (read-u16le buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness little)))))

(def (read-u32le buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness little)))))

(def (read-u64be buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness big)))))

(def (read-u64le buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness little)))))

(def (slice buf offset len)
  (if (> (+ offset len) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (let ((result (make-bytevector len)))
            (bytevector-copy! buf offset result 0 len)
            result))))

(def (extract-bits val mask shift)
  (bitwise-arithmetic-shift-right (bitwise-and val mask) shift))

(def (fmt-ipv4 addr)
  (let ((b0 (bitwise-arithmetic-shift-right addr 24))
        (b1 (bitwise-and (bitwise-arithmetic-shift-right addr 16) 255))
        (b2 (bitwise-and (bitwise-arithmetic-shift-right addr 8) 255))
        (b3 (bitwise-and addr 255)))
    (str b0 "." b1 "." b2 "." b3)))

(def (fmt-mac bytes)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bytes))
    ":"))

(def (fmt-hex val)
  (str "0x" (number->string val 16)))

(def (fmt-oct val)
  (str "0" (number->string val 8)))

(def (fmt-port port)
  (number->string port))

(def (fmt-bytes bv)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bv))
    " "))

(def (fmt-ipv6-address bytes)
  (let loop ((i 0) (parts '()))
    (if (>= i 16)
        (string-join (reverse parts) ":")
        (loop (+ i 2)
              (cons (let ((w (+ (* (bytevector-u8-ref bytes i) 256)
                                (bytevector-u8-ref bytes (+ i 1)))))
                      (number->string w 16))
                    parts)))))

;; ── Dissector ──────────────────────────────────────────────────────
(def (dissect-cfm buffer)
  "CFM EOAM IEEE 802.1Q/ITU-T Y.1731 Protocol"
  (try
    (let* (
           (mep-id (unwrap (read-u16be buffer 0)))
           (md-level (unwrap (read-u8 buffer 0)))
           (version (unwrap (read-u8 buffer 0)))
           (ccm-flags-RDI (unwrap (read-u8 buffer 54)))
           (ccm-flags-Traffic (unwrap (read-u8 buffer 54)))
           (ccm-flags-Reserved (unwrap (read-u8 buffer 54)))
           (ccm-seq-number (unwrap (read-u32be buffer 56)))
           (ccm-itu-TxFCf (unwrap (read-u32be buffer 60)))
           (ccm-itu-RxFCb (unwrap (read-u32be buffer 64)))
           (ccm-itu-TxFCb (unwrap (read-u32be buffer 68)))
           (ccm-itu-reserved (unwrap (slice buffer 72 4)))
           (lbm-lbr-transaction-id (unwrap (read-u32be buffer 84)))
           (ltm-flags-UseFDBonly (unwrap (read-u8 buffer 88)))
           (ltm-flags-Reserved (unwrap (read-u8 buffer 88)))
           (ltm-orig-addr (unwrap (slice buffer 95 6)))
           (ltm-targ-addr (unwrap (slice buffer 101 6)))
           (ltr-flags-UseFDBonly (unwrap (read-u8 buffer 107)))
           (ltr-flags-FwdYes (unwrap (read-u8 buffer 107)))
           (ltr-flags-TerminalMEP (unwrap (read-u8 buffer 107)))
           (ltr-flags-Reserved (unwrap (read-u8 buffer 107)))
           (ltm-ltr-transaction-id (unwrap (read-u32be buffer 109)))
           (ltm-ltr-ttl (unwrap (read-u8 buffer 113)))
           (rfm-transaction-id (unwrap (read-u32be buffer 117)))
           (sfm-transaction-id (unwrap (read-u32be buffer 123)))
           (bnm-flags-Reserved (unwrap (read-u8 buffer 127)))
           (bnm-nominal-bw (unwrap (read-u32be buffer 130)))
           (bnm-current-bw (unwrap (read-u32be buffer 134)))
           (bnm-port-id (unwrap (read-u32be buffer 138)))
           (gnm-unknown-flags (unwrap (read-u8 buffer 142)))
           (ais-flags-Reserved (unwrap (read-u8 buffer 145)))
           (lck-flags-Reserved (unwrap (read-u8 buffer 147)))
           (tst-sequence-num (unwrap (read-u32be buffer 151)))
           (aps-protection-type-A (unwrap (read-u8 buffer 157)))
           (aps-protection-type-B (unwrap (read-u8 buffer 157)))
           (aps-protection-type-D (unwrap (read-u8 buffer 157)))
           (aps-protection-type-R (unwrap (read-u8 buffer 157)))
           (raps-subcode-reserved (unwrap (read-u8 buffer 163)))
           (raps-status (unwrap (read-u8 buffer 164)))
           (raps-status-rb (unwrap (read-u8 buffer 164)))
           (raps-status-dnf (unwrap (read-u8 buffer 164)))
           (raps-status-bpr (unwrap (read-u8 buffer 164)))
           (raps-status-reserved-v2 (unwrap (read-u8 buffer 164)))
           (raps-status-reserved-v1 (unwrap (read-u8 buffer 164)))
           (raps-node-id (unwrap (slice buffer 165 6)))
           (raps-reserved (unwrap (slice buffer 171 24)))
           (mcc-oui (unwrap (read-u24be buffer 197)))
           (mcc-subopcode (unwrap (read-u8 buffer 200)))
           (lmm-lmr-flags-Reserved (unwrap (read-u8 buffer 215)))
           (lmm-lmr-flags-Type (unwrap (read-u8 buffer 215)))
           (lmm-lmr-TxFCf (unwrap (read-u32be buffer 217)))
           (lmm-lmr-RxFCf (unwrap (read-u32be buffer 221)))
           (lmm-lmr-TxFCb (unwrap (read-u32be buffer 225)))
           (odm-dmm-dmr-flags-Reserved (unwrap (read-u8 buffer 281)))
           (odm-dmm-dmr-flags-Type (unwrap (read-u8 buffer 281)))
           (exm-oui (unwrap (read-u24be buffer 317)))
           (exm-subopcode (unwrap (read-u8 buffer 320)))
           (exr-oui (unwrap (read-u24be buffer 323)))
           (exr-subopcode (unwrap (read-u8 buffer 326)))
           (vsm-oui (unwrap (read-u24be buffer 329)))
           (vsm-subopcode (unwrap (read-u8 buffer 332)))
           (vsr-oui (unwrap (read-u24be buffer 335)))
           (vsr-subopcode (unwrap (read-u8 buffer 338)))
           (csf-flags-Reserved (unwrap (read-u8 buffer 339)))
           (osl-src-mep (unwrap (read-u16be buffer 343)))
           (osl-testid (unwrap (slice buffer 347 4)))
           (osl-txfcf (unwrap (read-u32be buffer 351)))
           (osl-reserved (unwrap (slice buffer 355 4)))
           (slm-reserved (unwrap (slice buffer 373 4)))
           (flags-Reserved (unwrap (read-u8 buffer 377)))
           (slm-slr-src-mep (unwrap (read-u16be buffer 379)))
           (slr-rsp-mep (unwrap (read-u16be buffer 381)))
           (slm-slr-testid (unwrap (slice buffer 383 4)))
           (slm-slr-txfcf (unwrap (read-u32be buffer 387)))
           (slr-txfcb (unwrap (read-u32be buffer 391)))
           (flags (unwrap (read-u8 buffer 395)))
           (unknown-flags (unwrap (read-u8 buffer 395)))
           (first-tlv-offset (unwrap (read-u8 buffer 396)))
           (unknown-data (unwrap (slice buffer 397 1)))
           )

      (ok (list
        (cons 'mep-id (list (cons 'raw mep-id) (cons 'formatted (number->string mep-id))))
        (cons 'md-level (list (cons 'raw md-level) (cons 'formatted (number->string md-level))))
        (cons 'version (list (cons 'raw version) (cons 'formatted (number->string version))))
        (cons 'ccm-flags-RDI (list (cons 'raw ccm-flags-RDI) (cons 'formatted (number->string ccm-flags-RDI))))
        (cons 'ccm-flags-Traffic (list (cons 'raw ccm-flags-Traffic) (cons 'formatted (number->string ccm-flags-Traffic))))
        (cons 'ccm-flags-Reserved (list (cons 'raw ccm-flags-Reserved) (cons 'formatted (number->string ccm-flags-Reserved))))
        (cons 'ccm-seq-number (list (cons 'raw ccm-seq-number) (cons 'formatted (number->string ccm-seq-number))))
        (cons 'ccm-itu-TxFCf (list (cons 'raw ccm-itu-TxFCf) (cons 'formatted (number->string ccm-itu-TxFCf))))
        (cons 'ccm-itu-RxFCb (list (cons 'raw ccm-itu-RxFCb) (cons 'formatted (number->string ccm-itu-RxFCb))))
        (cons 'ccm-itu-TxFCb (list (cons 'raw ccm-itu-TxFCb) (cons 'formatted (number->string ccm-itu-TxFCb))))
        (cons 'ccm-itu-reserved (list (cons 'raw ccm-itu-reserved) (cons 'formatted (fmt-bytes ccm-itu-reserved))))
        (cons 'lbm-lbr-transaction-id (list (cons 'raw lbm-lbr-transaction-id) (cons 'formatted (number->string lbm-lbr-transaction-id))))
        (cons 'ltm-flags-UseFDBonly (list (cons 'raw ltm-flags-UseFDBonly) (cons 'formatted (number->string ltm-flags-UseFDBonly))))
        (cons 'ltm-flags-Reserved (list (cons 'raw ltm-flags-Reserved) (cons 'formatted (number->string ltm-flags-Reserved))))
        (cons 'ltm-orig-addr (list (cons 'raw ltm-orig-addr) (cons 'formatted (fmt-mac ltm-orig-addr))))
        (cons 'ltm-targ-addr (list (cons 'raw ltm-targ-addr) (cons 'formatted (fmt-mac ltm-targ-addr))))
        (cons 'ltr-flags-UseFDBonly (list (cons 'raw ltr-flags-UseFDBonly) (cons 'formatted (number->string ltr-flags-UseFDBonly))))
        (cons 'ltr-flags-FwdYes (list (cons 'raw ltr-flags-FwdYes) (cons 'formatted (number->string ltr-flags-FwdYes))))
        (cons 'ltr-flags-TerminalMEP (list (cons 'raw ltr-flags-TerminalMEP) (cons 'formatted (number->string ltr-flags-TerminalMEP))))
        (cons 'ltr-flags-Reserved (list (cons 'raw ltr-flags-Reserved) (cons 'formatted (number->string ltr-flags-Reserved))))
        (cons 'ltm-ltr-transaction-id (list (cons 'raw ltm-ltr-transaction-id) (cons 'formatted (number->string ltm-ltr-transaction-id))))
        (cons 'ltm-ltr-ttl (list (cons 'raw ltm-ltr-ttl) (cons 'formatted (number->string ltm-ltr-ttl))))
        (cons 'rfm-transaction-id (list (cons 'raw rfm-transaction-id) (cons 'formatted (number->string rfm-transaction-id))))
        (cons 'sfm-transaction-id (list (cons 'raw sfm-transaction-id) (cons 'formatted (number->string sfm-transaction-id))))
        (cons 'bnm-flags-Reserved (list (cons 'raw bnm-flags-Reserved) (cons 'formatted (number->string bnm-flags-Reserved))))
        (cons 'bnm-nominal-bw (list (cons 'raw bnm-nominal-bw) (cons 'formatted (number->string bnm-nominal-bw))))
        (cons 'bnm-current-bw (list (cons 'raw bnm-current-bw) (cons 'formatted (number->string bnm-current-bw))))
        (cons 'bnm-port-id (list (cons 'raw bnm-port-id) (cons 'formatted (number->string bnm-port-id))))
        (cons 'gnm-unknown-flags (list (cons 'raw gnm-unknown-flags) (cons 'formatted (fmt-hex gnm-unknown-flags))))
        (cons 'ais-flags-Reserved (list (cons 'raw ais-flags-Reserved) (cons 'formatted (number->string ais-flags-Reserved))))
        (cons 'lck-flags-Reserved (list (cons 'raw lck-flags-Reserved) (cons 'formatted (number->string lck-flags-Reserved))))
        (cons 'tst-sequence-num (list (cons 'raw tst-sequence-num) (cons 'formatted (number->string tst-sequence-num))))
        (cons 'aps-protection-type-A (list (cons 'raw aps-protection-type-A) (cons 'formatted (if (= aps-protection-type-A 0) "No APS channel" "APS channel"))))
        (cons 'aps-protection-type-B (list (cons 'raw aps-protection-type-B) (cons 'formatted (if (= aps-protection-type-B 0) "1+1 (permanent bridge)" "1:1 (no permanent bridge)"))))
        (cons 'aps-protection-type-D (list (cons 'raw aps-protection-type-D) (cons 'formatted (if (= aps-protection-type-D 0) "Unidirectional switching" "Bidirectional switching"))))
        (cons 'aps-protection-type-R (list (cons 'raw aps-protection-type-R) (cons 'formatted (if (= aps-protection-type-R 0) "Non-revertive operation" "Revertive operation"))))
        (cons 'raps-subcode-reserved (list (cons 'raw raps-subcode-reserved) (cons 'formatted (fmt-hex raps-subcode-reserved))))
        (cons 'raps-status (list (cons 'raw raps-status) (cons 'formatted (fmt-hex raps-status))))
        (cons 'raps-status-rb (list (cons 'raw raps-status-rb) (cons 'formatted (if (= raps-status-rb 0) "Not Blocked" "Blocked"))))
        (cons 'raps-status-dnf (list (cons 'raw raps-status-dnf) (cons 'formatted (if (= raps-status-dnf 0) "May Flush DB" "Do Not Flush DB"))))
        (cons 'raps-status-bpr (list (cons 'raw raps-status-bpr) (cons 'formatted (if (= raps-status-bpr 0) "Ring link 0" "Ring link 1"))))
        (cons 'raps-status-reserved-v2 (list (cons 'raw raps-status-reserved-v2) (cons 'formatted (fmt-hex raps-status-reserved-v2))))
        (cons 'raps-status-reserved-v1 (list (cons 'raw raps-status-reserved-v1) (cons 'formatted (fmt-hex raps-status-reserved-v1))))
        (cons 'raps-node-id (list (cons 'raw raps-node-id) (cons 'formatted (fmt-mac raps-node-id))))
        (cons 'raps-reserved (list (cons 'raw raps-reserved) (cons 'formatted (fmt-bytes raps-reserved))))
        (cons 'mcc-oui (list (cons 'raw mcc-oui) (cons 'formatted (number->string mcc-oui))))
        (cons 'mcc-subopcode (list (cons 'raw mcc-subopcode) (cons 'formatted (number->string mcc-subopcode))))
        (cons 'lmm-lmr-flags-Reserved (list (cons 'raw lmm-lmr-flags-Reserved) (cons 'formatted (fmt-hex lmm-lmr-flags-Reserved))))
        (cons 'lmm-lmr-flags-Type (list (cons 'raw lmm-lmr-flags-Type) (cons 'formatted (if (= lmm-lmr-flags-Type 0) "On-demand" "Proactive"))))
        (cons 'lmm-lmr-TxFCf (list (cons 'raw lmm-lmr-TxFCf) (cons 'formatted (number->string lmm-lmr-TxFCf))))
        (cons 'lmm-lmr-RxFCf (list (cons 'raw lmm-lmr-RxFCf) (cons 'formatted (number->string lmm-lmr-RxFCf))))
        (cons 'lmm-lmr-TxFCb (list (cons 'raw lmm-lmr-TxFCb) (cons 'formatted (number->string lmm-lmr-TxFCb))))
        (cons 'odm-dmm-dmr-flags-Reserved (list (cons 'raw odm-dmm-dmr-flags-Reserved) (cons 'formatted (fmt-hex odm-dmm-dmr-flags-Reserved))))
        (cons 'odm-dmm-dmr-flags-Type (list (cons 'raw odm-dmm-dmr-flags-Type) (cons 'formatted (if (= odm-dmm-dmr-flags-Type 0) "On-demand" "Proactive"))))
        (cons 'exm-oui (list (cons 'raw exm-oui) (cons 'formatted (number->string exm-oui))))
        (cons 'exm-subopcode (list (cons 'raw exm-subopcode) (cons 'formatted (number->string exm-subopcode))))
        (cons 'exr-oui (list (cons 'raw exr-oui) (cons 'formatted (number->string exr-oui))))
        (cons 'exr-subopcode (list (cons 'raw exr-subopcode) (cons 'formatted (number->string exr-subopcode))))
        (cons 'vsm-oui (list (cons 'raw vsm-oui) (cons 'formatted (number->string vsm-oui))))
        (cons 'vsm-subopcode (list (cons 'raw vsm-subopcode) (cons 'formatted (number->string vsm-subopcode))))
        (cons 'vsr-oui (list (cons 'raw vsr-oui) (cons 'formatted (number->string vsr-oui))))
        (cons 'vsr-subopcode (list (cons 'raw vsr-subopcode) (cons 'formatted (number->string vsr-subopcode))))
        (cons 'csf-flags-Reserved (list (cons 'raw csf-flags-Reserved) (cons 'formatted (fmt-hex csf-flags-Reserved))))
        (cons 'osl-src-mep (list (cons 'raw osl-src-mep) (cons 'formatted (number->string osl-src-mep))))
        (cons 'osl-testid (list (cons 'raw osl-testid) (cons 'formatted (fmt-bytes osl-testid))))
        (cons 'osl-txfcf (list (cons 'raw osl-txfcf) (cons 'formatted (number->string osl-txfcf))))
        (cons 'osl-reserved (list (cons 'raw osl-reserved) (cons 'formatted (fmt-bytes osl-reserved))))
        (cons 'slm-reserved (list (cons 'raw slm-reserved) (cons 'formatted (fmt-bytes slm-reserved))))
        (cons 'flags-Reserved (list (cons 'raw flags-Reserved) (cons 'formatted (fmt-hex flags-Reserved))))
        (cons 'slm-slr-src-mep (list (cons 'raw slm-slr-src-mep) (cons 'formatted (number->string slm-slr-src-mep))))
        (cons 'slr-rsp-mep (list (cons 'raw slr-rsp-mep) (cons 'formatted (number->string slr-rsp-mep))))
        (cons 'slm-slr-testid (list (cons 'raw slm-slr-testid) (cons 'formatted (fmt-bytes slm-slr-testid))))
        (cons 'slm-slr-txfcf (list (cons 'raw slm-slr-txfcf) (cons 'formatted (number->string slm-slr-txfcf))))
        (cons 'slr-txfcb (list (cons 'raw slr-txfcb) (cons 'formatted (number->string slr-txfcb))))
        (cons 'flags (list (cons 'raw flags) (cons 'formatted (fmt-hex flags))))
        (cons 'unknown-flags (list (cons 'raw unknown-flags) (cons 'formatted (fmt-hex unknown-flags))))
        (cons 'first-tlv-offset (list (cons 'raw first-tlv-offset) (cons 'formatted (number->string first-tlv-offset))))
        (cons 'unknown-data (list (cons 'raw unknown-data) (cons 'formatted (fmt-bytes unknown-data))))
        )))

    (catch (e)
      (err (str "CFM parse error: " e)))))

;; dissect-cfm: parse CFM from bytevector
;; Returns (ok fields-alist) or (err message)