;; packet-citp.c
;; Routines for CITP packet disassembly
;;
;; Copyright (c) 2025 by Matt Morris <mattm.dev.1[AT]gmail.com>
;;
;; Wireshark - Network traffic analyzer
;; By Gerald Combs <gerald@wireshark.org>
;; Copyright 1999 Gerald Combs
;;
;; Specification:
;; https://bitbucket.org/lars_wernlund/citp/src/master/
;; https://www.capture.se/Portals/0/Downloads/CITP%20CAEX%20Specification%20F.pdf?ver=2020-07-03-093027-283
;; http://www.techref.info/web/prod/cap/data/citp.pdf
;;
;;
;; SPDX-License-Identifier: GPL-2.0-or-later
;;

;; jerboa-ethereal/dissectors/citp.ss
;; Auto-generated from wireshark/epan/dissectors/packet-citp.c

(import (jerboa prelude))

;; ── Protocol Helpers ─────────────────────────────────────────────────
(def (read-u8 buf offset)
  (if (>= offset (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u8-ref buf offset))))

(def (read-u16be buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness big)))))

(def (read-u24be buf offset)
  (if (> (+ offset 3) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (+ (* (bytevector-u8-ref buf offset) 65536)
             (* (bytevector-u8-ref buf (+ offset 1)) 256)
             (bytevector-u8-ref buf (+ offset 2))))))

(def (read-u32be buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness big)))))

(def (read-u16le buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness little)))))

(def (read-u32le buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness little)))))

(def (read-u64be buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness big)))))

(def (read-u64le buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness little)))))

(def (slice buf offset len)
  (if (> (+ offset len) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (let ((result (make-bytevector len)))
            (bytevector-copy! buf offset result 0 len)
            result))))

(def (extract-bits val mask shift)
  (bitwise-arithmetic-shift-right (bitwise-and val mask) shift))

(def (fmt-ipv4 addr)
  (let ((b0 (bitwise-arithmetic-shift-right addr 24))
        (b1 (bitwise-and (bitwise-arithmetic-shift-right addr 16) 255))
        (b2 (bitwise-and (bitwise-arithmetic-shift-right addr 8) 255))
        (b3 (bitwise-and addr 255)))
    (str b0 "." b1 "." b2 "." b3)))

(def (fmt-mac bytes)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bytes))
    ":"))

(def (fmt-hex val)
  (str "0x" (number->string val 16)))

(def (fmt-oct val)
  (str "0" (number->string val 8)))

(def (fmt-port port)
  (number->string port))

(def (fmt-bytes bv)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bv))
    " "))

(def (fmt-ipv6-address bytes)
  (let loop ((i 0) (parts '()))
    (if (>= i 16)
        (string-join (reverse parts) ":")
        (loop (+ i 2)
              (cons (let ((w (+ (* (bytevector-u8-ref bytes i) 256)
                                (bytevector-u8-ref bytes (+ i 1)))))
                      (number->string w 16))
                    parts)))))

;; ── Dissector ──────────────────────────────────────────────────────
(def (dissect-citp buffer)
  "Controller Interface Transport Protocol"
  (try
    (let* (
           (msex-version-major (unwrap (read-u8 buffer 0)))
           (cookie (unwrap (slice buffer 0 4)))
           (msex-version-minor (unwrap (read-u8 buffer 1)))
           (pinf-listening-port (unwrap (read-u16be buffer 4)))
           (sdmx-capability-count (unwrap (read-u16be buffer 4)))
           (fptc-content-hint (unwrap (read-u32le buffer 4)))
           (fptc-content-hint-in-sequence (extract-bits fptc-content-hint 0x1 0))
           (fptc-content-hint-end-sequence (extract-bits fptc-content-hint 0x2 1))
           (fsel-complete (unwrap (read-u8 buffer 4)))
           (version-major (unwrap (read-u8 buffer 4)))
           (version-minor (unwrap (read-u8 buffer 5)))
           (pinf-type (unwrap (slice buffer 6 1)))
           (pinf-name (unwrap (slice buffer 6 1)))
           (pinf-state (unwrap (slice buffer 6 1)))
           (fsel-fixture-count (unwrap (read-u16be buffer 6)))
           (finf-fixture-identifier (unwrap (read-u16be buffer 6)))
           (message-index (unwrap (read-u16be buffer 6)))
           (sdmx-universe-name (unwrap (slice buffer 7 1)))
           (sdmx-blind (unwrap (read-u8 buffer 7)))
           (caex-view-format (unwrap (read-u8 buffer 7)))
           (fptc-fixture-identifier (unwrap (read-u16be buffer 8)))
           (finf-frame-filter-count (unwrap (read-u8 buffer 8)))
           (caex-view-data-size (unwrap (read-u32be buffer 8)))
           (message-size (unwrap (read-u32be buffer 8)))
           (sdmx-first-channel (unwrap (read-u16be buffer 9)))
           (finf-frame-gobo-count (unwrap (read-u8 buffer 9)))
           (fptc-universe (unwrap (read-u8 buffer 10)))
           (finf-filter-name (unwrap (slice buffer 10 1)))
           (finf-gobo-name (unwrap (slice buffer 10 1)))
           (caex-view-width (unwrap (read-u16be buffer 10)))
           (msex-library-update-flags (unwrap (read-u8 buffer 11)))
           (msex-library-update-flags-elements-updated (extract-bits msex-library-update-flags 0x1 0))
           (msex-library-update-flags-elements-added-removed (extract-bits msex-library-update-flags 0x2 1))
           (msex-library-update-flags-subs-updated (extract-bits msex-library-update-flags 0x4 2))
           (msex-library-update-flags-subs-added-removed (extract-bits msex-library-update-flags 0x8 3))
           (msex-library-update-flags-all-elements (extract-bits msex-library-update-flags 0x10 4))
           (msex-library-update-flags-all-subs (extract-bits msex-library-update-flags 0x20 5))
           (fptc-channel (unwrap (read-u16be buffer 12)))
           (caex-view-height (unwrap (read-u16be buffer 12)))
           (caex-view-data (unwrap (slice buffer 12 1)))
           (msex-source-id (unwrap (read-u16be buffer 12)))
           (message-part-count (unwrap (read-u16be buffer 12)))
           (sdmx-encrypted-channel-data (unwrap (slice buffer 13 1)))
           (sdmx-encryption-identifier (unwrap (slice buffer 13 1)))
           (sdmx-channel-levels (unwrap (slice buffer 13 1)))
           (sdmx-channel-count (unwrap (read-u16be buffer 13)))
           (fptc-channel-count (unwrap (read-u16be buffer 14)))
           (caex-view-position-x (unwrap (read-u32be buffer 14)))
           (caex-show-name (unwrap (slice buffer 14 1)))
           (msex-stream-format (unwrap (slice buffer 14 4)))
           (message-part-index (unwrap (read-u16be buffer 14)))
           (caex-laser-source-key (unwrap (read-u32be buffer 15)))
           (sdmx-channel (unwrap (read-u16be buffer 16)))
           (fptc-fixture-make (unwrap (slice buffer 16 1)))
           (fptc-fixture-name (unwrap (slice buffer 16 1)))
           (sdmx-channel-level (unwrap (read-u8 buffer 18)))
           (caex-view-position-y (unwrap (read-u32be buffer 18)))
           (msex-stream-width (unwrap (read-u16be buffer 18)))
           (sdmx-universe-index (unwrap (read-u8 buffer 19)))
           (caex-laser-feed-count (unwrap (read-u8 buffer 19)))
           (sdmx-connection-string (unwrap (slice buffer 20 1)))
           (caex-laser-feed-name (unwrap (slice buffer 20 1)))
           (caex-laser-feed-index (unwrap (read-u8 buffer 20)))
           (msex-stream-height (unwrap (read-u16be buffer 20)))
           (caex-laser-frame-rate (unwrap (read-u8 buffer 21)))
           (caex-view-position-z (unwrap (read-u32be buffer 22)))
           (msex-stream-fps (unwrap (read-u8 buffer 22)))
           (msex-stream-timeout (unwrap (read-u8 buffer 23)))
           (msex-library-id-level (unwrap (read-u8 buffer 25)))
           (caex-view-focus-x (unwrap (read-u32be buffer 26)))
           (msex-library-id-level-1 (unwrap (read-u8 buffer 26)))
           (msex-library-id-level-2 (unwrap (read-u8 buffer 27)))
           (msex-library-id-level-3 (unwrap (read-u8 buffer 28)))
           (caex-view-focus-y (unwrap (read-u32be buffer 30)))
           (msex-supported-version-count (unwrap (read-u8 buffer 30)))
           (caex-view-focus-z (unwrap (read-u32be buffer 34)))
           (msex-uuid (unwrap (slice buffer 34 1)))
           (msex-product-name (unwrap (slice buffer 34 1)))
           (msex-product-version-major (unwrap (read-u8 buffer 34)))
           (msex-product-version-minor (unwrap (read-u8 buffer 35)))
           (msex-product-version-bugfix (unwrap (read-u8 buffer 36)))
           (msex-supported-library-types (unwrap (read-u16le buffer 37)))
           (msex-supported-library-types-media (extract-bits msex-supported-library-types 0x1 0))
           (msex-supported-library-types-effects (extract-bits msex-supported-library-types 0x2 1))
           (msex-supported-library-types-cues (extract-bits msex-supported-library-types 0x4 2))
           (msex-supported-library-types-crossfades (extract-bits msex-supported-library-types 0x8 3))
           (msex-supported-library-types-masks (extract-bits msex-supported-library-types 0x10 4))
           (msex-supported-library-types-blend-presets (extract-bits msex-supported-library-types 0x20 5))
           (msex-supported-library-types-effect-presets (extract-bits msex-supported-library-types 0x40 6))
           (msex-supported-library-types-image-presets (extract-bits msex-supported-library-types 0x80 7))
           (msex-supported-library-types-3d-meshes (extract-bits msex-supported-library-types 0x100 8))
           (caex-cue-option-count (unwrap (read-u8 buffer 38)))
           (caex-cue-option-name (unwrap (slice buffer 39 1)))
           (caex-cue-option-choices (unwrap (slice buffer 39 1)))
           (caex-cue-option-help (unwrap (slice buffer 39 1)))
           (caex-cue-option-value (unwrap (slice buffer 39 1)))
           (msex-thumbnail-format-count (unwrap (read-u8 buffer 39)))
           (caex-show-fixture-count (unwrap (read-u16be buffer 40)))
           (msex-stream-format-count (unwrap (read-u8 buffer 44)))
           (msex-layer-dmx-source (unwrap (slice buffer 50 1)))
           (msex-layer-count (unwrap (read-u8 buffer 50)))
           (msex-layers (unwrap (read-u8 buffer 51)))
           (msex-layer-number (unwrap (read-u8 buffer 51)))
           (msex-layer-physical-output (unwrap (read-u8 buffer 52)))
           (msex-element-position (unwrap (read-u32be buffer 55)))
           (msex-layer-status-flags (unwrap (read-u32le buffer 64)))
           (msex-layer-status-flags-playing (extract-bits msex-layer-status-flags 0x1 0))
           (msex-layer-status-flags-reverse (extract-bits msex-layer-status-flags 0x2 1))
           (msex-layer-status-flags-looping (extract-bits msex-layer-status-flags 0x4 2))
           (msex-layer-status-flags-bouncing (extract-bits msex-layer-status-flags 0x8 3))
           (msex-layer-status-flags-random (extract-bits msex-layer-status-flags 0x10 4))
           (msex-layer-status-flags-paused (extract-bits msex-layer-status-flags 0x20 5))
           (caex-show-fixture-locked (unwrap (read-u8 buffer 66)))
           (caex-show-fixture-clearable (unwrap (read-u8 buffer 67)))
           (caex-show-fixture-console-identifier (unwrap (read-u32be buffer 68)))
           (msex-library-number (unwrap (read-u8 buffer 69)))
           (msex-library-serial-number (unwrap (read-u32be buffer 70)))
           (caex-show-fixture-manufacturer-name (unwrap (slice buffer 72 1)))
           (caex-show-fixture-model-name (unwrap (slice buffer 72 1)))
           (caex-show-fixture-mode-name (unwrap (slice buffer 72 1)))
           (caex-show-fixture-channel-count (unwrap (read-u16be buffer 72)))
           (caex-show-fixture-is-dimmer (unwrap (read-u8 buffer 74)))
           (msex-library-dmx-min (unwrap (read-u8 buffer 74)))
           (caex-show-fixture-identifier-count (unwrap (read-u8 buffer 75)))
           (msex-library-dmx-max (unwrap (read-u8 buffer 75)))
           (msex-library-name (unwrap (slice buffer 76 1)))
           (caex-show-fixture-identifier-data-size (unwrap (read-u16be buffer 77)))
           (caex-show-fixture-identifier-data (unwrap (slice buffer 79 1)))
           (caex-show-fixture-identifier-rdm-manufacturer-id (unwrap (read-u16be buffer 79)))
           (caex-show-fixture-identifier-rdm-device-model-id (unwrap (read-u16be buffer 79)))
           (caex-show-fixture-identifier-rdm-personality-id (unwrap (read-u64be buffer 79)))
           (caex-show-fixture-identifier-altabase-fixture-id (unwrap (slice buffer 79 16)))
           (caex-show-fixture-identifier-altabase-mode-id (unwrap (slice buffer 79 16)))
           (caex-show-fixture-identifier-capture-instance-id (unwrap (slice buffer 79 16)))
           (caex-show-fixture-changed-fields (unwrap (read-u8 buffer 79)))
           (caex-show-fixture-changed-fields-patch (extract-bits caex-show-fixture-changed-fields 0x1 0))
           (caex-show-fixture-changed-fields-unit (extract-bits caex-show-fixture-changed-fields 0x2 1))
           (caex-show-fixture-changed-fields-channel (extract-bits caex-show-fixture-changed-fields 0x4 2))
           (caex-show-fixture-changed-fields-circuit (extract-bits caex-show-fixture-changed-fields 0x8 3))
           (caex-show-fixture-changed-fields-note (extract-bits caex-show-fixture-changed-fields 0x10 4))
           (caex-show-fixture-changed-fields-position (extract-bits caex-show-fixture-changed-fields 0x20 5))
           (msex-element-serial-number (unwrap (read-u32be buffer 79)))
           (caex-show-fixture-patched (unwrap (read-u8 buffer 80)))
           (caex-show-fixture-universe (unwrap (read-u8 buffer 81)))
           (caex-show-fixture-universe-channel (unwrap (read-u16be buffer 82)))
           (msex-element-dmx-min (unwrap (read-u8 buffer 83)))
           (caex-show-fixture-unit (unwrap (slice buffer 84 1)))
           (caex-show-fixture-channel (unwrap (read-u16be buffer 84)))
           (msex-element-dmx-max (unwrap (read-u8 buffer 84)))
           (msex-element-name (unwrap (slice buffer 85 1)))
           (caex-show-fixture-circuit (unwrap (slice buffer 86 1)))
           (caex-show-fixture-note (unwrap (slice buffer 86 1)))
           (caex-show-fixture-position-x (unwrap (read-u32be buffer 86)))
           (caex-show-fixture-position-y (unwrap (read-u32be buffer 90)))
           (msex-element-width (unwrap (read-u16be buffer 93)))
           (caex-show-fixture-position-z (unwrap (read-u32be buffer 94)))
           (msex-element-height (unwrap (read-u16be buffer 95)))
           (msex-element-length (unwrap (read-u32be buffer 97)))
           (caex-show-fixture-angles-x (unwrap (read-u32be buffer 98)))
           (msex-element-fps (unwrap (read-u8 buffer 101)))
           (caex-show-fixture-angles-y (unwrap (read-u32be buffer 102)))
           (msex-element-parameter-count (unwrap (read-u8 buffer 102)))
           (msex-element-parameter-name (unwrap (slice buffer 103 1)))
           (caex-show-fixture-angles-z (unwrap (read-u32be buffer 106)))
           (msex-thumbnail-flags (unwrap (read-u8 buffer 111)))
           (msex-thumbnail-flags-preserve-aspect (extract-bits msex-thumbnail-flags 0x1 0))
           (caex-laser-frame-sequence-number (unwrap (read-u32be buffer 115)))
           (msex-element-number (unwrap (read-u8 buffer 115)))
           (msex-thumbnail-format (unwrap (slice buffer 116 4)))
           (caex-laser-point-count (unwrap (read-u16be buffer 119)))
           (msex-thumbnail-width (unwrap (read-u16be buffer 120)))
           (caex-laser-point-x-low (unwrap (read-u8 buffer 121)))
           (caex-laser-point-y-low (unwrap (read-u8 buffer 122)))
           (msex-thumbnail-height (unwrap (read-u16be buffer 122)))
           (caex-laser-point-xy-high (unwrap (read-u8 buffer 123)))
           (caex-laser-point-x (unwrap (read-u16be buffer 124)))
           (caex-laser-point-y (unwrap (read-u16be buffer 124)))
           (caex-laser-point-colour (unwrap (read-u16le buffer 124)))
           (caex-laser-point-colour-r (extract-bits caex-laser-point-colour 0x0 0))
           (caex-laser-point-colour-g (extract-bits caex-laser-point-colour 0x0 0))
           (caex-laser-point-colour-b (extract-bits caex-laser-point-colour 0x0 0))
           (msex-thumbnail-buffer-size (unwrap (read-u16be buffer 124)))
           (msex-thumbnail-buffer (unwrap (slice buffer 126 1)))
           (msex-source-count (unwrap (read-u16be buffer 126)))
           (msex-source-name (unwrap (slice buffer 130 1)))
           (msex-source-physical-output (unwrap (read-u8 buffer 130)))
           (msex-source-layer-number (unwrap (read-u8 buffer 131)))
           (msex-source-flags (unwrap (read-u16le buffer 132)))
           (msex-source-flags-without-effects (extract-bits msex-source-flags 0x1 0))
           (msex-source-width (unwrap (read-u16be buffer 134)))
           (msex-source-height (unwrap (read-u16be buffer 136)))
           (msex-source-server-uuid (unwrap (slice buffer 138 36)))
           (msex-frame-buffer-size (unwrap (read-u16be buffer 184)))
           (msex-frame-buffer (unwrap (slice buffer 186 1)))
           )

      (ok (list
        (cons 'msex-version-major (list (cons 'raw msex-version-major) (cons 'formatted (number->string msex-version-major))))
        (cons 'cookie (list (cons 'raw cookie) (cons 'formatted (utf8->string cookie))))
        (cons 'msex-version-minor (list (cons 'raw msex-version-minor) (cons 'formatted (number->string msex-version-minor))))
        (cons 'pinf-listening-port (list (cons 'raw pinf-listening-port) (cons 'formatted (number->string pinf-listening-port))))
        (cons 'sdmx-capability-count (list (cons 'raw sdmx-capability-count) (cons 'formatted (number->string sdmx-capability-count))))
        (cons 'fptc-content-hint (list (cons 'raw fptc-content-hint) (cons 'formatted (fmt-hex fptc-content-hint))))
        (cons 'fptc-content-hint-in-sequence (list (cons 'raw fptc-content-hint-in-sequence) (cons 'formatted (if (= fptc-content-hint-in-sequence 0) "Not set" "Set"))))
        (cons 'fptc-content-hint-end-sequence (list (cons 'raw fptc-content-hint-end-sequence) (cons 'formatted (if (= fptc-content-hint-end-sequence 0) "Not set" "Set"))))
        (cons 'fsel-complete (list (cons 'raw fsel-complete) (cons 'formatted (number->string fsel-complete))))
        (cons 'version-major (list (cons 'raw version-major) (cons 'formatted (number->string version-major))))
        (cons 'version-minor (list (cons 'raw version-minor) (cons 'formatted (number->string version-minor))))
        (cons 'pinf-type (list (cons 'raw pinf-type) (cons 'formatted (utf8->string pinf-type))))
        (cons 'pinf-name (list (cons 'raw pinf-name) (cons 'formatted (utf8->string pinf-name))))
        (cons 'pinf-state (list (cons 'raw pinf-state) (cons 'formatted (utf8->string pinf-state))))
        (cons 'fsel-fixture-count (list (cons 'raw fsel-fixture-count) (cons 'formatted (number->string fsel-fixture-count))))
        (cons 'finf-fixture-identifier (list (cons 'raw finf-fixture-identifier) (cons 'formatted (number->string finf-fixture-identifier))))
        (cons 'message-index (list (cons 'raw message-index) (cons 'formatted (number->string message-index))))
        (cons 'sdmx-universe-name (list (cons 'raw sdmx-universe-name) (cons 'formatted (utf8->string sdmx-universe-name))))
        (cons 'sdmx-blind (list (cons 'raw sdmx-blind) (cons 'formatted (if (= sdmx-blind 0) "False" "True"))))
        (cons 'caex-view-format (list (cons 'raw caex-view-format) (cons 'formatted (fmt-hex caex-view-format))))
        (cons 'fptc-fixture-identifier (list (cons 'raw fptc-fixture-identifier) (cons 'formatted (number->string fptc-fixture-identifier))))
        (cons 'finf-frame-filter-count (list (cons 'raw finf-frame-filter-count) (cons 'formatted (number->string finf-frame-filter-count))))
        (cons 'caex-view-data-size (list (cons 'raw caex-view-data-size) (cons 'formatted (number->string caex-view-data-size))))
        (cons 'message-size (list (cons 'raw message-size) (cons 'formatted (number->string message-size))))
        (cons 'sdmx-first-channel (list (cons 'raw sdmx-first-channel) (cons 'formatted (number->string sdmx-first-channel))))
        (cons 'finf-frame-gobo-count (list (cons 'raw finf-frame-gobo-count) (cons 'formatted (number->string finf-frame-gobo-count))))
        (cons 'fptc-universe (list (cons 'raw fptc-universe) (cons 'formatted (number->string fptc-universe))))
        (cons 'finf-filter-name (list (cons 'raw finf-filter-name) (cons 'formatted (utf8->string finf-filter-name))))
        (cons 'finf-gobo-name (list (cons 'raw finf-gobo-name) (cons 'formatted (utf8->string finf-gobo-name))))
        (cons 'caex-view-width (list (cons 'raw caex-view-width) (cons 'formatted (number->string caex-view-width))))
        (cons 'msex-library-update-flags (list (cons 'raw msex-library-update-flags) (cons 'formatted (fmt-hex msex-library-update-flags))))
        (cons 'msex-library-update-flags-elements-updated (list (cons 'raw msex-library-update-flags-elements-updated) (cons 'formatted (if (= msex-library-update-flags-elements-updated 0) "Not set" "Set"))))
        (cons 'msex-library-update-flags-elements-added-removed (list (cons 'raw msex-library-update-flags-elements-added-removed) (cons 'formatted (if (= msex-library-update-flags-elements-added-removed 0) "Not set" "Set"))))
        (cons 'msex-library-update-flags-subs-updated (list (cons 'raw msex-library-update-flags-subs-updated) (cons 'formatted (if (= msex-library-update-flags-subs-updated 0) "Not set" "Set"))))
        (cons 'msex-library-update-flags-subs-added-removed (list (cons 'raw msex-library-update-flags-subs-added-removed) (cons 'formatted (if (= msex-library-update-flags-subs-added-removed 0) "Not set" "Set"))))
        (cons 'msex-library-update-flags-all-elements (list (cons 'raw msex-library-update-flags-all-elements) (cons 'formatted (if (= msex-library-update-flags-all-elements 0) "Not set" "Set"))))
        (cons 'msex-library-update-flags-all-subs (list (cons 'raw msex-library-update-flags-all-subs) (cons 'formatted (if (= msex-library-update-flags-all-subs 0) "Not set" "Set"))))
        (cons 'fptc-channel (list (cons 'raw fptc-channel) (cons 'formatted (number->string fptc-channel))))
        (cons 'caex-view-height (list (cons 'raw caex-view-height) (cons 'formatted (number->string caex-view-height))))
        (cons 'caex-view-data (list (cons 'raw caex-view-data) (cons 'formatted (fmt-bytes caex-view-data))))
        (cons 'msex-source-id (list (cons 'raw msex-source-id) (cons 'formatted (number->string msex-source-id))))
        (cons 'message-part-count (list (cons 'raw message-part-count) (cons 'formatted (number->string message-part-count))))
        (cons 'sdmx-encrypted-channel-data (list (cons 'raw sdmx-encrypted-channel-data) (cons 'formatted (fmt-bytes sdmx-encrypted-channel-data))))
        (cons 'sdmx-encryption-identifier (list (cons 'raw sdmx-encryption-identifier) (cons 'formatted (utf8->string sdmx-encryption-identifier))))
        (cons 'sdmx-channel-levels (list (cons 'raw sdmx-channel-levels) (cons 'formatted (fmt-bytes sdmx-channel-levels))))
        (cons 'sdmx-channel-count (list (cons 'raw sdmx-channel-count) (cons 'formatted (number->string sdmx-channel-count))))
        (cons 'fptc-channel-count (list (cons 'raw fptc-channel-count) (cons 'formatted (number->string fptc-channel-count))))
        (cons 'caex-view-position-x (list (cons 'raw caex-view-position-x) (cons 'formatted (number->string caex-view-position-x))))
        (cons 'caex-show-name (list (cons 'raw caex-show-name) (cons 'formatted (utf8->string caex-show-name))))
        (cons 'msex-stream-format (list (cons 'raw msex-stream-format) (cons 'formatted (utf8->string msex-stream-format))))
        (cons 'message-part-index (list (cons 'raw message-part-index) (cons 'formatted (number->string message-part-index))))
        (cons 'caex-laser-source-key (list (cons 'raw caex-laser-source-key) (cons 'formatted (fmt-hex caex-laser-source-key))))
        (cons 'sdmx-channel (list (cons 'raw sdmx-channel) (cons 'formatted (number->string sdmx-channel))))
        (cons 'fptc-fixture-make (list (cons 'raw fptc-fixture-make) (cons 'formatted (utf8->string fptc-fixture-make))))
        (cons 'fptc-fixture-name (list (cons 'raw fptc-fixture-name) (cons 'formatted (utf8->string fptc-fixture-name))))
        (cons 'sdmx-channel-level (list (cons 'raw sdmx-channel-level) (cons 'formatted (number->string sdmx-channel-level))))
        (cons 'caex-view-position-y (list (cons 'raw caex-view-position-y) (cons 'formatted (number->string caex-view-position-y))))
        (cons 'msex-stream-width (list (cons 'raw msex-stream-width) (cons 'formatted (number->string msex-stream-width))))
        (cons 'sdmx-universe-index (list (cons 'raw sdmx-universe-index) (cons 'formatted (number->string sdmx-universe-index))))
        (cons 'caex-laser-feed-count (list (cons 'raw caex-laser-feed-count) (cons 'formatted (number->string caex-laser-feed-count))))
        (cons 'sdmx-connection-string (list (cons 'raw sdmx-connection-string) (cons 'formatted (utf8->string sdmx-connection-string))))
        (cons 'caex-laser-feed-name (list (cons 'raw caex-laser-feed-name) (cons 'formatted (utf8->string caex-laser-feed-name))))
        (cons 'caex-laser-feed-index (list (cons 'raw caex-laser-feed-index) (cons 'formatted (number->string caex-laser-feed-index))))
        (cons 'msex-stream-height (list (cons 'raw msex-stream-height) (cons 'formatted (number->string msex-stream-height))))
        (cons 'caex-laser-frame-rate (list (cons 'raw caex-laser-frame-rate) (cons 'formatted (number->string caex-laser-frame-rate))))
        (cons 'caex-view-position-z (list (cons 'raw caex-view-position-z) (cons 'formatted (number->string caex-view-position-z))))
        (cons 'msex-stream-fps (list (cons 'raw msex-stream-fps) (cons 'formatted (number->string msex-stream-fps))))
        (cons 'msex-stream-timeout (list (cons 'raw msex-stream-timeout) (cons 'formatted (number->string msex-stream-timeout))))
        (cons 'msex-library-id-level (list (cons 'raw msex-library-id-level) (cons 'formatted (number->string msex-library-id-level))))
        (cons 'caex-view-focus-x (list (cons 'raw caex-view-focus-x) (cons 'formatted (number->string caex-view-focus-x))))
        (cons 'msex-library-id-level-1 (list (cons 'raw msex-library-id-level-1) (cons 'formatted (number->string msex-library-id-level-1))))
        (cons 'msex-library-id-level-2 (list (cons 'raw msex-library-id-level-2) (cons 'formatted (number->string msex-library-id-level-2))))
        (cons 'msex-library-id-level-3 (list (cons 'raw msex-library-id-level-3) (cons 'formatted (number->string msex-library-id-level-3))))
        (cons 'caex-view-focus-y (list (cons 'raw caex-view-focus-y) (cons 'formatted (number->string caex-view-focus-y))))
        (cons 'msex-supported-version-count (list (cons 'raw msex-supported-version-count) (cons 'formatted (number->string msex-supported-version-count))))
        (cons 'caex-view-focus-z (list (cons 'raw caex-view-focus-z) (cons 'formatted (number->string caex-view-focus-z))))
        (cons 'msex-uuid (list (cons 'raw msex-uuid) (cons 'formatted (utf8->string msex-uuid))))
        (cons 'msex-product-name (list (cons 'raw msex-product-name) (cons 'formatted (utf8->string msex-product-name))))
        (cons 'msex-product-version-major (list (cons 'raw msex-product-version-major) (cons 'formatted (number->string msex-product-version-major))))
        (cons 'msex-product-version-minor (list (cons 'raw msex-product-version-minor) (cons 'formatted (number->string msex-product-version-minor))))
        (cons 'msex-product-version-bugfix (list (cons 'raw msex-product-version-bugfix) (cons 'formatted (number->string msex-product-version-bugfix))))
        (cons 'msex-supported-library-types (list (cons 'raw msex-supported-library-types) (cons 'formatted (fmt-hex msex-supported-library-types))))
        (cons 'msex-supported-library-types-media (list (cons 'raw msex-supported-library-types-media) (cons 'formatted (if (= msex-supported-library-types-media 0) "Not set" "Set"))))
        (cons 'msex-supported-library-types-effects (list (cons 'raw msex-supported-library-types-effects) (cons 'formatted (if (= msex-supported-library-types-effects 0) "Not set" "Set"))))
        (cons 'msex-supported-library-types-cues (list (cons 'raw msex-supported-library-types-cues) (cons 'formatted (if (= msex-supported-library-types-cues 0) "Not set" "Set"))))
        (cons 'msex-supported-library-types-crossfades (list (cons 'raw msex-supported-library-types-crossfades) (cons 'formatted (if (= msex-supported-library-types-crossfades 0) "Not set" "Set"))))
        (cons 'msex-supported-library-types-masks (list (cons 'raw msex-supported-library-types-masks) (cons 'formatted (if (= msex-supported-library-types-masks 0) "Not set" "Set"))))
        (cons 'msex-supported-library-types-blend-presets (list (cons 'raw msex-supported-library-types-blend-presets) (cons 'formatted (if (= msex-supported-library-types-blend-presets 0) "Not set" "Set"))))
        (cons 'msex-supported-library-types-effect-presets (list (cons 'raw msex-supported-library-types-effect-presets) (cons 'formatted (if (= msex-supported-library-types-effect-presets 0) "Not set" "Set"))))
        (cons 'msex-supported-library-types-image-presets (list (cons 'raw msex-supported-library-types-image-presets) (cons 'formatted (if (= msex-supported-library-types-image-presets 0) "Not set" "Set"))))
        (cons 'msex-supported-library-types-3d-meshes (list (cons 'raw msex-supported-library-types-3d-meshes) (cons 'formatted (if (= msex-supported-library-types-3d-meshes 0) "Not set" "Set"))))
        (cons 'caex-cue-option-count (list (cons 'raw caex-cue-option-count) (cons 'formatted (number->string caex-cue-option-count))))
        (cons 'caex-cue-option-name (list (cons 'raw caex-cue-option-name) (cons 'formatted (utf8->string caex-cue-option-name))))
        (cons 'caex-cue-option-choices (list (cons 'raw caex-cue-option-choices) (cons 'formatted (utf8->string caex-cue-option-choices))))
        (cons 'caex-cue-option-help (list (cons 'raw caex-cue-option-help) (cons 'formatted (utf8->string caex-cue-option-help))))
        (cons 'caex-cue-option-value (list (cons 'raw caex-cue-option-value) (cons 'formatted (utf8->string caex-cue-option-value))))
        (cons 'msex-thumbnail-format-count (list (cons 'raw msex-thumbnail-format-count) (cons 'formatted (number->string msex-thumbnail-format-count))))
        (cons 'caex-show-fixture-count (list (cons 'raw caex-show-fixture-count) (cons 'formatted (number->string caex-show-fixture-count))))
        (cons 'msex-stream-format-count (list (cons 'raw msex-stream-format-count) (cons 'formatted (number->string msex-stream-format-count))))
        (cons 'msex-layer-dmx-source (list (cons 'raw msex-layer-dmx-source) (cons 'formatted (utf8->string msex-layer-dmx-source))))
        (cons 'msex-layer-count (list (cons 'raw msex-layer-count) (cons 'formatted (number->string msex-layer-count))))
        (cons 'msex-layers (list (cons 'raw msex-layers) (cons 'formatted (number->string msex-layers))))
        (cons 'msex-layer-number (list (cons 'raw msex-layer-number) (cons 'formatted (number->string msex-layer-number))))
        (cons 'msex-layer-physical-output (list (cons 'raw msex-layer-physical-output) (cons 'formatted (number->string msex-layer-physical-output))))
        (cons 'msex-element-position (list (cons 'raw msex-element-position) (cons 'formatted (number->string msex-element-position))))
        (cons 'msex-layer-status-flags (list (cons 'raw msex-layer-status-flags) (cons 'formatted (fmt-hex msex-layer-status-flags))))
        (cons 'msex-layer-status-flags-playing (list (cons 'raw msex-layer-status-flags-playing) (cons 'formatted (if (= msex-layer-status-flags-playing 0) "Not set" "Set"))))
        (cons 'msex-layer-status-flags-reverse (list (cons 'raw msex-layer-status-flags-reverse) (cons 'formatted (if (= msex-layer-status-flags-reverse 0) "Not set" "Set"))))
        (cons 'msex-layer-status-flags-looping (list (cons 'raw msex-layer-status-flags-looping) (cons 'formatted (if (= msex-layer-status-flags-looping 0) "Not set" "Set"))))
        (cons 'msex-layer-status-flags-bouncing (list (cons 'raw msex-layer-status-flags-bouncing) (cons 'formatted (if (= msex-layer-status-flags-bouncing 0) "Not set" "Set"))))
        (cons 'msex-layer-status-flags-random (list (cons 'raw msex-layer-status-flags-random) (cons 'formatted (if (= msex-layer-status-flags-random 0) "Not set" "Set"))))
        (cons 'msex-layer-status-flags-paused (list (cons 'raw msex-layer-status-flags-paused) (cons 'formatted (if (= msex-layer-status-flags-paused 0) "Not set" "Set"))))
        (cons 'caex-show-fixture-locked (list (cons 'raw caex-show-fixture-locked) (cons 'formatted (number->string caex-show-fixture-locked))))
        (cons 'caex-show-fixture-clearable (list (cons 'raw caex-show-fixture-clearable) (cons 'formatted (number->string caex-show-fixture-clearable))))
        (cons 'caex-show-fixture-console-identifier (list (cons 'raw caex-show-fixture-console-identifier) (cons 'formatted (fmt-hex caex-show-fixture-console-identifier))))
        (cons 'msex-library-number (list (cons 'raw msex-library-number) (cons 'formatted (number->string msex-library-number))))
        (cons 'msex-library-serial-number (list (cons 'raw msex-library-serial-number) (cons 'formatted (number->string msex-library-serial-number))))
        (cons 'caex-show-fixture-manufacturer-name (list (cons 'raw caex-show-fixture-manufacturer-name) (cons 'formatted (utf8->string caex-show-fixture-manufacturer-name))))
        (cons 'caex-show-fixture-model-name (list (cons 'raw caex-show-fixture-model-name) (cons 'formatted (utf8->string caex-show-fixture-model-name))))
        (cons 'caex-show-fixture-mode-name (list (cons 'raw caex-show-fixture-mode-name) (cons 'formatted (utf8->string caex-show-fixture-mode-name))))
        (cons 'caex-show-fixture-channel-count (list (cons 'raw caex-show-fixture-channel-count) (cons 'formatted (number->string caex-show-fixture-channel-count))))
        (cons 'caex-show-fixture-is-dimmer (list (cons 'raw caex-show-fixture-is-dimmer) (cons 'formatted (number->string caex-show-fixture-is-dimmer))))
        (cons 'msex-library-dmx-min (list (cons 'raw msex-library-dmx-min) (cons 'formatted (number->string msex-library-dmx-min))))
        (cons 'caex-show-fixture-identifier-count (list (cons 'raw caex-show-fixture-identifier-count) (cons 'formatted (number->string caex-show-fixture-identifier-count))))
        (cons 'msex-library-dmx-max (list (cons 'raw msex-library-dmx-max) (cons 'formatted (number->string msex-library-dmx-max))))
        (cons 'msex-library-name (list (cons 'raw msex-library-name) (cons 'formatted (utf8->string msex-library-name))))
        (cons 'caex-show-fixture-identifier-data-size (list (cons 'raw caex-show-fixture-identifier-data-size) (cons 'formatted (number->string caex-show-fixture-identifier-data-size))))
        (cons 'caex-show-fixture-identifier-data (list (cons 'raw caex-show-fixture-identifier-data) (cons 'formatted (fmt-bytes caex-show-fixture-identifier-data))))
        (cons 'caex-show-fixture-identifier-rdm-manufacturer-id (list (cons 'raw caex-show-fixture-identifier-rdm-manufacturer-id) (cons 'formatted (fmt-hex caex-show-fixture-identifier-rdm-manufacturer-id))))
        (cons 'caex-show-fixture-identifier-rdm-device-model-id (list (cons 'raw caex-show-fixture-identifier-rdm-device-model-id) (cons 'formatted (fmt-hex caex-show-fixture-identifier-rdm-device-model-id))))
        (cons 'caex-show-fixture-identifier-rdm-personality-id (list (cons 'raw caex-show-fixture-identifier-rdm-personality-id) (cons 'formatted (fmt-hex caex-show-fixture-identifier-rdm-personality-id))))
        (cons 'caex-show-fixture-identifier-altabase-fixture-id (list (cons 'raw caex-show-fixture-identifier-altabase-fixture-id) (cons 'formatted (fmt-bytes caex-show-fixture-identifier-altabase-fixture-id))))
        (cons 'caex-show-fixture-identifier-altabase-mode-id (list (cons 'raw caex-show-fixture-identifier-altabase-mode-id) (cons 'formatted (fmt-bytes caex-show-fixture-identifier-altabase-mode-id))))
        (cons 'caex-show-fixture-identifier-capture-instance-id (list (cons 'raw caex-show-fixture-identifier-capture-instance-id) (cons 'formatted (fmt-bytes caex-show-fixture-identifier-capture-instance-id))))
        (cons 'caex-show-fixture-changed-fields (list (cons 'raw caex-show-fixture-changed-fields) (cons 'formatted (fmt-hex caex-show-fixture-changed-fields))))
        (cons 'caex-show-fixture-changed-fields-patch (list (cons 'raw caex-show-fixture-changed-fields-patch) (cons 'formatted (if (= caex-show-fixture-changed-fields-patch 0) "Not set" "Set"))))
        (cons 'caex-show-fixture-changed-fields-unit (list (cons 'raw caex-show-fixture-changed-fields-unit) (cons 'formatted (if (= caex-show-fixture-changed-fields-unit 0) "Not set" "Set"))))
        (cons 'caex-show-fixture-changed-fields-channel (list (cons 'raw caex-show-fixture-changed-fields-channel) (cons 'formatted (if (= caex-show-fixture-changed-fields-channel 0) "Not set" "Set"))))
        (cons 'caex-show-fixture-changed-fields-circuit (list (cons 'raw caex-show-fixture-changed-fields-circuit) (cons 'formatted (if (= caex-show-fixture-changed-fields-circuit 0) "Not set" "Set"))))
        (cons 'caex-show-fixture-changed-fields-note (list (cons 'raw caex-show-fixture-changed-fields-note) (cons 'formatted (if (= caex-show-fixture-changed-fields-note 0) "Not set" "Set"))))
        (cons 'caex-show-fixture-changed-fields-position (list (cons 'raw caex-show-fixture-changed-fields-position) (cons 'formatted (if (= caex-show-fixture-changed-fields-position 0) "Not set" "Set"))))
        (cons 'msex-element-serial-number (list (cons 'raw msex-element-serial-number) (cons 'formatted (number->string msex-element-serial-number))))
        (cons 'caex-show-fixture-patched (list (cons 'raw caex-show-fixture-patched) (cons 'formatted (number->string caex-show-fixture-patched))))
        (cons 'caex-show-fixture-universe (list (cons 'raw caex-show-fixture-universe) (cons 'formatted (number->string caex-show-fixture-universe))))
        (cons 'caex-show-fixture-universe-channel (list (cons 'raw caex-show-fixture-universe-channel) (cons 'formatted (number->string caex-show-fixture-universe-channel))))
        (cons 'msex-element-dmx-min (list (cons 'raw msex-element-dmx-min) (cons 'formatted (number->string msex-element-dmx-min))))
        (cons 'caex-show-fixture-unit (list (cons 'raw caex-show-fixture-unit) (cons 'formatted (utf8->string caex-show-fixture-unit))))
        (cons 'caex-show-fixture-channel (list (cons 'raw caex-show-fixture-channel) (cons 'formatted (number->string caex-show-fixture-channel))))
        (cons 'msex-element-dmx-max (list (cons 'raw msex-element-dmx-max) (cons 'formatted (number->string msex-element-dmx-max))))
        (cons 'msex-element-name (list (cons 'raw msex-element-name) (cons 'formatted (utf8->string msex-element-name))))
        (cons 'caex-show-fixture-circuit (list (cons 'raw caex-show-fixture-circuit) (cons 'formatted (utf8->string caex-show-fixture-circuit))))
        (cons 'caex-show-fixture-note (list (cons 'raw caex-show-fixture-note) (cons 'formatted (utf8->string caex-show-fixture-note))))
        (cons 'caex-show-fixture-position-x (list (cons 'raw caex-show-fixture-position-x) (cons 'formatted (number->string caex-show-fixture-position-x))))
        (cons 'caex-show-fixture-position-y (list (cons 'raw caex-show-fixture-position-y) (cons 'formatted (number->string caex-show-fixture-position-y))))
        (cons 'msex-element-width (list (cons 'raw msex-element-width) (cons 'formatted (number->string msex-element-width))))
        (cons 'caex-show-fixture-position-z (list (cons 'raw caex-show-fixture-position-z) (cons 'formatted (number->string caex-show-fixture-position-z))))
        (cons 'msex-element-height (list (cons 'raw msex-element-height) (cons 'formatted (number->string msex-element-height))))
        (cons 'msex-element-length (list (cons 'raw msex-element-length) (cons 'formatted (number->string msex-element-length))))
        (cons 'caex-show-fixture-angles-x (list (cons 'raw caex-show-fixture-angles-x) (cons 'formatted (number->string caex-show-fixture-angles-x))))
        (cons 'msex-element-fps (list (cons 'raw msex-element-fps) (cons 'formatted (number->string msex-element-fps))))
        (cons 'caex-show-fixture-angles-y (list (cons 'raw caex-show-fixture-angles-y) (cons 'formatted (number->string caex-show-fixture-angles-y))))
        (cons 'msex-element-parameter-count (list (cons 'raw msex-element-parameter-count) (cons 'formatted (number->string msex-element-parameter-count))))
        (cons 'msex-element-parameter-name (list (cons 'raw msex-element-parameter-name) (cons 'formatted (utf8->string msex-element-parameter-name))))
        (cons 'caex-show-fixture-angles-z (list (cons 'raw caex-show-fixture-angles-z) (cons 'formatted (number->string caex-show-fixture-angles-z))))
        (cons 'msex-thumbnail-flags (list (cons 'raw msex-thumbnail-flags) (cons 'formatted (fmt-hex msex-thumbnail-flags))))
        (cons 'msex-thumbnail-flags-preserve-aspect (list (cons 'raw msex-thumbnail-flags-preserve-aspect) (cons 'formatted (if (= msex-thumbnail-flags-preserve-aspect 0) "Not set" "Set"))))
        (cons 'caex-laser-frame-sequence-number (list (cons 'raw caex-laser-frame-sequence-number) (cons 'formatted (number->string caex-laser-frame-sequence-number))))
        (cons 'msex-element-number (list (cons 'raw msex-element-number) (cons 'formatted (number->string msex-element-number))))
        (cons 'msex-thumbnail-format (list (cons 'raw msex-thumbnail-format) (cons 'formatted (utf8->string msex-thumbnail-format))))
        (cons 'caex-laser-point-count (list (cons 'raw caex-laser-point-count) (cons 'formatted (number->string caex-laser-point-count))))
        (cons 'msex-thumbnail-width (list (cons 'raw msex-thumbnail-width) (cons 'formatted (number->string msex-thumbnail-width))))
        (cons 'caex-laser-point-x-low (list (cons 'raw caex-laser-point-x-low) (cons 'formatted (fmt-hex caex-laser-point-x-low))))
        (cons 'caex-laser-point-y-low (list (cons 'raw caex-laser-point-y-low) (cons 'formatted (fmt-hex caex-laser-point-y-low))))
        (cons 'msex-thumbnail-height (list (cons 'raw msex-thumbnail-height) (cons 'formatted (number->string msex-thumbnail-height))))
        (cons 'caex-laser-point-xy-high (list (cons 'raw caex-laser-point-xy-high) (cons 'formatted (fmt-hex caex-laser-point-xy-high))))
        (cons 'caex-laser-point-x (list (cons 'raw caex-laser-point-x) (cons 'formatted (number->string caex-laser-point-x))))
        (cons 'caex-laser-point-y (list (cons 'raw caex-laser-point-y) (cons 'formatted (number->string caex-laser-point-y))))
        (cons 'caex-laser-point-colour (list (cons 'raw caex-laser-point-colour) (cons 'formatted (fmt-hex caex-laser-point-colour))))
        (cons 'caex-laser-point-colour-r (list (cons 'raw caex-laser-point-colour-r) (cons 'formatted (if (= caex-laser-point-colour-r 0) "Not set" "Set"))))
        (cons 'caex-laser-point-colour-g (list (cons 'raw caex-laser-point-colour-g) (cons 'formatted (if (= caex-laser-point-colour-g 0) "Not set" "Set"))))
        (cons 'caex-laser-point-colour-b (list (cons 'raw caex-laser-point-colour-b) (cons 'formatted (if (= caex-laser-point-colour-b 0) "Not set" "Set"))))
        (cons 'msex-thumbnail-buffer-size (list (cons 'raw msex-thumbnail-buffer-size) (cons 'formatted (number->string msex-thumbnail-buffer-size))))
        (cons 'msex-thumbnail-buffer (list (cons 'raw msex-thumbnail-buffer) (cons 'formatted (fmt-bytes msex-thumbnail-buffer))))
        (cons 'msex-source-count (list (cons 'raw msex-source-count) (cons 'formatted (number->string msex-source-count))))
        (cons 'msex-source-name (list (cons 'raw msex-source-name) (cons 'formatted (utf8->string msex-source-name))))
        (cons 'msex-source-physical-output (list (cons 'raw msex-source-physical-output) (cons 'formatted (number->string msex-source-physical-output))))
        (cons 'msex-source-layer-number (list (cons 'raw msex-source-layer-number) (cons 'formatted (number->string msex-source-layer-number))))
        (cons 'msex-source-flags (list (cons 'raw msex-source-flags) (cons 'formatted (fmt-hex msex-source-flags))))
        (cons 'msex-source-flags-without-effects (list (cons 'raw msex-source-flags-without-effects) (cons 'formatted (if (= msex-source-flags-without-effects 0) "Not set" "Set"))))
        (cons 'msex-source-width (list (cons 'raw msex-source-width) (cons 'formatted (number->string msex-source-width))))
        (cons 'msex-source-height (list (cons 'raw msex-source-height) (cons 'formatted (number->string msex-source-height))))
        (cons 'msex-source-server-uuid (list (cons 'raw msex-source-server-uuid) (cons 'formatted (utf8->string msex-source-server-uuid))))
        (cons 'msex-frame-buffer-size (list (cons 'raw msex-frame-buffer-size) (cons 'formatted (number->string msex-frame-buffer-size))))
        (cons 'msex-frame-buffer (list (cons 'raw msex-frame-buffer) (cons 'formatted (fmt-bytes msex-frame-buffer))))
        )))

    (catch (e)
      (err (str "CITP parse error: " e)))))

;; dissect-citp: parse CITP from bytevector
;; Returns (ok fields-alist) or (err message)