;; packet-edonkey.c
;; Routines for edonkey dissection
;; Copyright 2003, Xuan Zhang <xz@aemail4u.com>
;; Copyright 2007, Stefano Picerno <stefano.picerno@gmail.com>
;; Copyright 2008, Stefan Monhof <stefan.monhof@stud.uni-due.de>
;;
;; eDonkey dissector based on protocol descriptions from mldonkey:
;; ftp://ftp.chatnfiles.com/gnu-mirror/savannah/files/mldonkey/docs/Edonkey-Overnet/edonkey-protocol.txt
;; ftp://ftp.chatnfiles.com/gnu-mirror/savannah/files/mldonkey/docs/Edonkey-Overnet/overnet-protocol.txt
;;
;; Kademlia dissector based on source code inspection of aMule 2.1.3 and eMule 0.48a
;; Modified and added on the basis of information and names from the eMule 0.50 source code
;; found at http://www.emule-project.net
;;
;; Wireshark - Network traffic analyzer
;; By Gerald Combs <gerald@wireshark.org>
;; Copyright 1998 Gerald Combs
;;
;; SPDX-License-Identifier: GPL-2.0-or-later
;;

;; jerboa-ethereal/dissectors/edonkey.ss
;; Auto-generated from wireshark/epan/dissectors/packet-edonkey.c

(import (jerboa prelude))

;; ── Protocol Helpers ─────────────────────────────────────────────────
(def (read-u8 buf offset)
  (if (>= offset (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u8-ref buf offset))))

(def (read-u16be buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness big)))))

(def (read-u24be buf offset)
  (if (> (+ offset 3) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (+ (* (bytevector-u8-ref buf offset) 65536)
             (* (bytevector-u8-ref buf (+ offset 1)) 256)
             (bytevector-u8-ref buf (+ offset 2))))))

(def (read-u32be buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness big)))))

(def (read-u16le buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness little)))))

(def (read-u32le buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness little)))))

(def (read-u64be buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness big)))))

(def (read-u64le buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness little)))))

(def (slice buf offset len)
  (if (> (+ offset len) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (let ((result (make-bytevector len)))
            (bytevector-copy! buf offset result 0 len)
            result))))

(def (extract-bits val mask shift)
  (bitwise-arithmetic-shift-right (bitwise-and val mask) shift))

(def (fmt-ipv4 addr)
  (let ((b0 (bitwise-arithmetic-shift-right addr 24))
        (b1 (bitwise-and (bitwise-arithmetic-shift-right addr 16) 255))
        (b2 (bitwise-and (bitwise-arithmetic-shift-right addr 8) 255))
        (b3 (bitwise-and addr 255)))
    (str b0 "." b1 "." b2 "." b3)))

(def (fmt-mac bytes)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bytes))
    ":"))

(def (fmt-hex val)
  (str "0x" (number->string val 16)))

(def (fmt-oct val)
  (str "0" (number->string val 8)))

(def (fmt-port port)
  (number->string port))

(def (fmt-bytes bv)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bv))
    " "))

(def (fmt-ipv6-address bytes)
  (let loop ((i 0) (parts '()))
    (if (>= i 16)
        (string-join (reverse parts) ":")
        (loop (+ i 2)
              (cons (let ((w (+ (* (bytevector-u8-ref bytes i) 256)
                                (bytevector-u8-ref bytes (+ i 1)))))
                      (number->string w 16))
                    parts)))))

;; ── Dissector ──────────────────────────────────────────────────────
(def (dissect-edonkey buffer)
  "eDonkey Protocol"
  (try
    (let* (
           (search-condition-argument-uint64 (unwrap (read-u64be buffer 0)))
           (search-condition-argument-uint32 (unwrap (read-u32be buffer 0)))
           (search-condition (unwrap (read-u8 buffer 0)))
           (metatag-type (unwrap (read-u8 buffer 0)))
           (metatag-namesize (unwrap (read-u16be buffer 0)))
           (udp-port (unwrap (read-u16be buffer 0)))
           (tcp-port (unwrap (read-u16be buffer 0)))
           (ip (unwrap (read-u32be buffer 0)))
           (tag-name-length (unwrap (read-u16be buffer 0)))
           (string-length (unwrap (read-u16be buffer 0)))
           (tag-name (unwrap (read-u8 buffer 0)))
           (kademlia-string (unwrap (slice buffer 0 1)))
           (file-hash (unwrap (slice buffer 0 16)))
           (public-key-length (unwrap (read-u8 buffer 0)))
           (public-key (unwrap (slice buffer 0 1)))
           (signature-length (unwrap (read-u8 buffer 0)))
           (signature (unwrap (slice buffer 0 1)))
           (hash (unwrap (slice buffer 0 16)))
           (tag-hash (unwrap (slice buffer 0 16)))
           (tag-bsob (unwrap (slice buffer 0 1)))
           (string (unwrap (slice buffer 0 1)))
           (tag-string (unwrap (slice buffer 0 1)))
           (directory (unwrap (slice buffer 0 1)))
           (part-count (unwrap (read-u16be buffer 0)))
           (file-status (unwrap (slice buffer 0 1)))
           (server-hash (unwrap (slice buffer 0 16)))
           (client-hash (unwrap (slice buffer 0 16)))
           (obfuscation-settings (unwrap (read-u8 buffer 0)))
           (message-length (unwrap (read-u32be buffer 0)))
           (message-type (unwrap (read-u8 buffer 0)))
           (unparsed-data-length (unwrap (read-u32be buffer 0)))
           (client-id (unwrap (read-u32be buffer 7)))
           (start-offset (unwrap (read-u32be buffer 7)))
           (start-offset-64 (unwrap (read-u64be buffer 7)))
           (end-offset (unwrap (read-u32be buffer 7)))
           (end-offset-64 (unwrap (read-u64be buffer 7)))
           (aich-hash-id (unwrap (read-u16be buffer 7)))
           (aich-hash (unwrap (slice buffer 7 20)))
           (emule-file-length (unwrap (read-u64be buffer 7)))
           (aich-root-hash (unwrap (slice buffer 18 20)))
           (multipacket-opcode (unwrap (read-u8 buffer 39)))
           (overnet-peer-type (unwrap (read-u8 buffer 39)))
           (peertype (unwrap (read-u8 buffer 39)))
           (search-limit (unwrap (read-u32be buffer 41)))
           (user-hash-length (unwrap (read-u8 buffer 41)))
           (more-search-file-results (unwrap (read-u8 buffer 42)))
           (file-size (unwrap (read-u32be buffer 42)))
           (large-file-size (unwrap (read-u64be buffer 46)))
           (tcp-flags (unwrap (read-u32be buffer 46)))
           (aux-port (unwrap (read-u32be buffer 50)))
           (server-reported-ip (unwrap (read-u32be buffer 54)))
           (emule-version (unwrap (read-u16be buffer 62)))
           (emule-rndchallenge (unwrap (read-u32be buffer 62)))
           (emule-sig-ip-used (unwrap (read-u8 buffer 62)))
           (packed-length (unwrap (read-u32be buffer 66)))
           (compressed-message-data (unwrap (slice buffer 70 1)))
           (aich-partnum (unwrap (read-u16be buffer 70)))
           (challenge (unwrap (read-u32be buffer 82)))
           (number-of-users (unwrap (read-u32be buffer 86)))
           (number-of-files (unwrap (read-u32be buffer 86)))
           (max-number-of-users (unwrap (read-u32be buffer 94)))
           (soft-limit-files (unwrap (read-u32be buffer 98)))
           (hard-limit-files (unwrap (read-u32be buffer 102)))
           (udp-flags (unwrap (read-u32be buffer 106)))
           (number-of-lowid-users (unwrap (read-u32be buffer 110)))
           (udp-obfuscation-port (unwrap (read-u16be buffer 114)))
           (tcp-obfuscation-port (unwrap (read-u32be buffer 116)))
           (server-udp-key (unwrap (read-u32be buffer 118)))
           (search-range-min (unwrap (read-u16be buffer 122)))
           (search-range-max (unwrap (read-u16be buffer 122)))
           (port (unwrap (read-u16be buffer 122)))
           (message-data (unwrap (slice buffer 122 1)))
           (source-count (unwrap (read-u16be buffer 122)))
           (emule-queue-ranking (unwrap (read-u16be buffer 124)))
           (tag-uint8 (unwrap (read-u8 buffer 127)))
           (tag-uint16 (unwrap (read-u16be buffer 128)))
           (tag-uint64 (unwrap (read-u64be buffer 130)))
           (tag-ipv4 (unwrap (read-u32be buffer 138)))
           (tag-uint32 (unwrap (read-u32be buffer 138)))
           (tag-float (unwrap (read-u32be buffer 142)))
           (kademlia-uload (unwrap (read-u8 buffer 146)))
           (hf-kademlia (unwrap (read-u8 buffer 146)))
           (kademlia-filesize (unwrap (read-u64be buffer 148)))
           (kademlia-start-position (unwrap (read-u16be buffer 156)))
           (request-type (unwrap (read-u8 buffer 158)))
           (distance (unwrap (slice buffer 159 1)))
           (kademlia-restrictive (unwrap (read-u8 buffer 159)))
           (broken-compressed-data (unwrap (slice buffer 160 1)))
           (list-size (unwrap (read-u32be buffer 161)))
           )

      (ok (list
        (cons 'search-condition-argument-uint64 (list (cons 'raw search-condition-argument-uint64) (cons 'formatted (number->string search-condition-argument-uint64))))
        (cons 'search-condition-argument-uint32 (list (cons 'raw search-condition-argument-uint32) (cons 'formatted (number->string search-condition-argument-uint32))))
        (cons 'search-condition (list (cons 'raw search-condition) (cons 'formatted (fmt-hex search-condition))))
        (cons 'metatag-type (list (cons 'raw metatag-type) (cons 'formatted (fmt-hex metatag-type))))
        (cons 'metatag-namesize (list (cons 'raw metatag-namesize) (cons 'formatted (number->string metatag-namesize))))
        (cons 'udp-port (list (cons 'raw udp-port) (cons 'formatted (fmt-port udp-port))))
        (cons 'tcp-port (list (cons 'raw tcp-port) (cons 'formatted (fmt-port tcp-port))))
        (cons 'ip (list (cons 'raw ip) (cons 'formatted (fmt-ipv4 ip))))
        (cons 'tag-name-length (list (cons 'raw tag-name-length) (cons 'formatted (number->string tag-name-length))))
        (cons 'string-length (list (cons 'raw string-length) (cons 'formatted (number->string string-length))))
        (cons 'tag-name (list (cons 'raw tag-name) (cons 'formatted (fmt-hex tag-name))))
        (cons 'kademlia-string (list (cons 'raw kademlia-string) (cons 'formatted (utf8->string kademlia-string))))
        (cons 'file-hash (list (cons 'raw file-hash) (cons 'formatted (fmt-bytes file-hash))))
        (cons 'public-key-length (list (cons 'raw public-key-length) (cons 'formatted (number->string public-key-length))))
        (cons 'public-key (list (cons 'raw public-key) (cons 'formatted (fmt-bytes public-key))))
        (cons 'signature-length (list (cons 'raw signature-length) (cons 'formatted (number->string signature-length))))
        (cons 'signature (list (cons 'raw signature) (cons 'formatted (fmt-bytes signature))))
        (cons 'hash (list (cons 'raw hash) (cons 'formatted (utf8->string hash))))
        (cons 'tag-hash (list (cons 'raw tag-hash) (cons 'formatted (utf8->string tag-hash))))
        (cons 'tag-bsob (list (cons 'raw tag-bsob) (cons 'formatted (fmt-bytes tag-bsob))))
        (cons 'string (list (cons 'raw string) (cons 'formatted (utf8->string string))))
        (cons 'tag-string (list (cons 'raw tag-string) (cons 'formatted (utf8->string tag-string))))
        (cons 'directory (list (cons 'raw directory) (cons 'formatted (utf8->string directory))))
        (cons 'part-count (list (cons 'raw part-count) (cons 'formatted (number->string part-count))))
        (cons 'file-status (list (cons 'raw file-status) (cons 'formatted (fmt-bytes file-status))))
        (cons 'server-hash (list (cons 'raw server-hash) (cons 'formatted (fmt-bytes server-hash))))
        (cons 'client-hash (list (cons 'raw client-hash) (cons 'formatted (fmt-bytes client-hash))))
        (cons 'obfuscation-settings (list (cons 'raw obfuscation-settings) (cons 'formatted (number->string obfuscation-settings))))
        (cons 'message-length (list (cons 'raw message-length) (cons 'formatted (number->string message-length))))
        (cons 'message-type (list (cons 'raw message-type) (cons 'formatted (fmt-hex message-type))))
        (cons 'unparsed-data-length (list (cons 'raw unparsed-data-length) (cons 'formatted (number->string unparsed-data-length))))
        (cons 'client-id (list (cons 'raw client-id) (cons 'formatted (fmt-ipv4 client-id))))
        (cons 'start-offset (list (cons 'raw start-offset) (cons 'formatted (number->string start-offset))))
        (cons 'start-offset-64 (list (cons 'raw start-offset-64) (cons 'formatted (number->string start-offset-64))))
        (cons 'end-offset (list (cons 'raw end-offset) (cons 'formatted (number->string end-offset))))
        (cons 'end-offset-64 (list (cons 'raw end-offset-64) (cons 'formatted (number->string end-offset-64))))
        (cons 'aich-hash-id (list (cons 'raw aich-hash-id) (cons 'formatted (fmt-hex aich-hash-id))))
        (cons 'aich-hash (list (cons 'raw aich-hash) (cons 'formatted (fmt-bytes aich-hash))))
        (cons 'emule-file-length (list (cons 'raw emule-file-length) (cons 'formatted (number->string emule-file-length))))
        (cons 'aich-root-hash (list (cons 'raw aich-root-hash) (cons 'formatted (fmt-bytes aich-root-hash))))
        (cons 'multipacket-opcode (list (cons 'raw multipacket-opcode) (cons 'formatted (fmt-hex multipacket-opcode))))
        (cons 'overnet-peer-type (list (cons 'raw overnet-peer-type) (cons 'formatted (number->string overnet-peer-type))))
        (cons 'peertype (list (cons 'raw peertype) (cons 'formatted (number->string peertype))))
        (cons 'search-limit (list (cons 'raw search-limit) (cons 'formatted (number->string search-limit))))
        (cons 'user-hash-length (list (cons 'raw user-hash-length) (cons 'formatted (number->string user-hash-length))))
        (cons 'more-search-file-results (list (cons 'raw more-search-file-results) (cons 'formatted (number->string more-search-file-results))))
        (cons 'file-size (list (cons 'raw file-size) (cons 'formatted (number->string file-size))))
        (cons 'large-file-size (list (cons 'raw large-file-size) (cons 'formatted (number->string large-file-size))))
        (cons 'tcp-flags (list (cons 'raw tcp-flags) (cons 'formatted (fmt-hex tcp-flags))))
        (cons 'aux-port (list (cons 'raw aux-port) (cons 'formatted (number->string aux-port))))
        (cons 'server-reported-ip (list (cons 'raw server-reported-ip) (cons 'formatted (fmt-ipv4 server-reported-ip))))
        (cons 'emule-version (list (cons 'raw emule-version) (cons 'formatted (number->string emule-version))))
        (cons 'emule-rndchallenge (list (cons 'raw emule-rndchallenge) (cons 'formatted (number->string emule-rndchallenge))))
        (cons 'emule-sig-ip-used (list (cons 'raw emule-sig-ip-used) (cons 'formatted (number->string emule-sig-ip-used))))
        (cons 'packed-length (list (cons 'raw packed-length) (cons 'formatted (number->string packed-length))))
        (cons 'compressed-message-data (list (cons 'raw compressed-message-data) (cons 'formatted (fmt-bytes compressed-message-data))))
        (cons 'aich-partnum (list (cons 'raw aich-partnum) (cons 'formatted (number->string aich-partnum))))
        (cons 'challenge (list (cons 'raw challenge) (cons 'formatted (fmt-hex challenge))))
        (cons 'number-of-users (list (cons 'raw number-of-users) (cons 'formatted (number->string number-of-users))))
        (cons 'number-of-files (list (cons 'raw number-of-files) (cons 'formatted (number->string number-of-files))))
        (cons 'max-number-of-users (list (cons 'raw max-number-of-users) (cons 'formatted (number->string max-number-of-users))))
        (cons 'soft-limit-files (list (cons 'raw soft-limit-files) (cons 'formatted (number->string soft-limit-files))))
        (cons 'hard-limit-files (list (cons 'raw hard-limit-files) (cons 'formatted (number->string hard-limit-files))))
        (cons 'udp-flags (list (cons 'raw udp-flags) (cons 'formatted (fmt-hex udp-flags))))
        (cons 'number-of-lowid-users (list (cons 'raw number-of-lowid-users) (cons 'formatted (number->string number-of-lowid-users))))
        (cons 'udp-obfuscation-port (list (cons 'raw udp-obfuscation-port) (cons 'formatted (fmt-port udp-obfuscation-port))))
        (cons 'tcp-obfuscation-port (list (cons 'raw tcp-obfuscation-port) (cons 'formatted (number->string tcp-obfuscation-port))))
        (cons 'server-udp-key (list (cons 'raw server-udp-key) (cons 'formatted (fmt-hex server-udp-key))))
        (cons 'search-range-min (list (cons 'raw search-range-min) (cons 'formatted (number->string search-range-min))))
        (cons 'search-range-max (list (cons 'raw search-range-max) (cons 'formatted (number->string search-range-max))))
        (cons 'port (list (cons 'raw port) (cons 'formatted (number->string port))))
        (cons 'message-data (list (cons 'raw message-data) (cons 'formatted (fmt-bytes message-data))))
        (cons 'source-count (list (cons 'raw source-count) (cons 'formatted (number->string source-count))))
        (cons 'emule-queue-ranking (list (cons 'raw emule-queue-ranking) (cons 'formatted (number->string emule-queue-ranking))))
        (cons 'tag-uint8 (list (cons 'raw tag-uint8) (cons 'formatted (number->string tag-uint8))))
        (cons 'tag-uint16 (list (cons 'raw tag-uint16) (cons 'formatted (number->string tag-uint16))))
        (cons 'tag-uint64 (list (cons 'raw tag-uint64) (cons 'formatted (number->string tag-uint64))))
        (cons 'tag-ipv4 (list (cons 'raw tag-ipv4) (cons 'formatted (fmt-ipv4 tag-ipv4))))
        (cons 'tag-uint32 (list (cons 'raw tag-uint32) (cons 'formatted (number->string tag-uint32))))
        (cons 'tag-float (list (cons 'raw tag-float) (cons 'formatted (number->string tag-float))))
        (cons 'kademlia-uload (list (cons 'raw kademlia-uload) (cons 'formatted (number->string kademlia-uload))))
        (cons 'hf-kademlia (list (cons 'raw hf-kademlia) (cons 'formatted (fmt-hex hf-kademlia))))
        (cons 'kademlia-filesize (list (cons 'raw kademlia-filesize) (cons 'formatted (number->string kademlia-filesize))))
        (cons 'kademlia-start-position (list (cons 'raw kademlia-start-position) (cons 'formatted (number->string kademlia-start-position))))
        (cons 'request-type (list (cons 'raw request-type) (cons 'formatted (fmt-hex request-type))))
        (cons 'distance (list (cons 'raw distance) (cons 'formatted (utf8->string distance))))
        (cons 'kademlia-restrictive (list (cons 'raw kademlia-restrictive) (cons 'formatted (fmt-hex kademlia-restrictive))))
        (cons 'broken-compressed-data (list (cons 'raw broken-compressed-data) (cons 'formatted (fmt-bytes broken-compressed-data))))
        (cons 'list-size (list (cons 'raw list-size) (cons 'formatted (number->string list-size))))
        )))

    (catch (e)
      (err (str "EDONKEY parse error: " e)))))

;; dissect-edonkey: parse EDONKEY from bytevector
;; Returns (ok fields-alist) or (err message)