;; packet-extreme.c
;; Routines for the disassembly of Extreme Networks specific
;; protocols (EDP/ESRP/EAPS(including ESL)/ELSM)
;;
;; Copyright 2005 Joerg Mayer (see AUTHORS file)
;;
;; Wireshark - Network traffic analyzer
;; By Gerald Combs <gerald@wireshark.org>
;; Copyright 1998 Gerald Combs
;;
;; SPDX-License-Identifier: GPL-2.0-or-later
;;

;; jerboa-ethereal/dissectors/extreme.ss
;; Auto-generated from wireshark/epan/dissectors/packet-extreme.c
;; RFC 3619

(import (jerboa prelude))

;; ── Protocol Helpers ─────────────────────────────────────────────────
(def (read-u8 buf offset)
  (if (>= offset (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u8-ref buf offset))))

(def (read-u16be buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness big)))))

(def (read-u24be buf offset)
  (if (> (+ offset 3) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (+ (* (bytevector-u8-ref buf offset) 65536)
             (* (bytevector-u8-ref buf (+ offset 1)) 256)
             (bytevector-u8-ref buf (+ offset 2))))))

(def (read-u32be buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness big)))))

(def (read-u16le buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness little)))))

(def (read-u32le buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness little)))))

(def (read-u64be buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness big)))))

(def (read-u64le buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness little)))))

(def (slice buf offset len)
  (if (> (+ offset len) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (let ((result (make-bytevector len)))
            (bytevector-copy! buf offset result 0 len)
            result))))

(def (extract-bits val mask shift)
  (bitwise-arithmetic-shift-right (bitwise-and val mask) shift))

(def (fmt-ipv4 addr)
  (let ((b0 (bitwise-arithmetic-shift-right addr 24))
        (b1 (bitwise-and (bitwise-arithmetic-shift-right addr 16) 255))
        (b2 (bitwise-and (bitwise-arithmetic-shift-right addr 8) 255))
        (b3 (bitwise-and addr 255)))
    (str b0 "." b1 "." b2 "." b3)))

(def (fmt-mac bytes)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bytes))
    ":"))

(def (fmt-hex val)
  (str "0x" (number->string val 16)))

(def (fmt-oct val)
  (str "0" (number->string val 8)))

(def (fmt-port port)
  (number->string port))

(def (fmt-bytes bv)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bv))
    " "))

(def (fmt-ipv6-address bytes)
  (let loop ((i 0) (parts '()))
    (if (>= i 16)
        (string-join (reverse parts) ":")
        (loop (+ i 2)
              (cons (let ((w (+ (* (bytevector-u8-ref bytes i) 256)
                                (bytevector-u8-ref bytes (+ i 1)))))
                      (number->string w 16))
                    parts)))))

;; ── Dissector ──────────────────────────────────────────────────────
(def (dissect-extreme buffer)
  "Extreme Discovery Protocol"
  (try
    (let* (
           (tlv-marker (unwrap (read-u8 buffer 0)))
           (version (unwrap (read-u8 buffer 0)))
           (reserved (unwrap (read-u8 buffer 1)))
           (tlv-length (unwrap (read-u16be buffer 2)))
           (length (unwrap (read-u16be buffer 2)))
           (display (unwrap (slice buffer 4 1)))
           (seqno (unwrap (read-u16be buffer 6)))
           (display-string (unwrap (slice buffer 8 1)))
           (null (unwrap (slice buffer 8 1)))
           (midmac (unwrap (slice buffer 10 6)))
           (info (unwrap (slice buffer 12 1)))
           (info-slot (unwrap (read-u16be buffer 16)))
           (info-port (unwrap (read-u16be buffer 18)))
           (info-vchassid (unwrap (read-u16be buffer 20)))
           (info-reserved (unwrap (slice buffer 22 6)))
           (info-version (unwrap (read-u32be buffer 28)))
           (info-version-major1 (unwrap (read-u8 buffer 28)))
           (info-version-major2 (unwrap (read-u8 buffer 29)))
           (info-version-sustaining (unwrap (read-u8 buffer 30)))
           (info-version-internal (unwrap (read-u8 buffer 31)))
           (info-vchassconn (unwrap (slice buffer 32 16)))
           (vlan (unwrap (slice buffer 48 1)))
           (vlan-flags (unwrap (read-u8 buffer 52)))
           (vlan-flags-ip (unwrap (read-u8 buffer 52)))
           (vlan-flags-reserved (unwrap (read-u8 buffer 52)))
           (vlan-flags-unknown (unwrap (read-u8 buffer 52)))
           (vlan-reserved1 (unwrap (slice buffer 53 1)))
           (vlan-id (unwrap (read-u16be buffer 54)))
           (vlan-reserved2 (unwrap (slice buffer 56 4)))
           (vlan-ip (unwrap (read-u32be buffer 60)))
           (vlan-name (unwrap (slice buffer 64 1)))
           (esrp (unwrap (slice buffer 64 1)))
           (esrp-group (unwrap (read-u8 buffer 69)))
           (esrp-prio (unwrap (read-u16be buffer 70)))
           (esrp-ports (unwrap (read-u16be buffer 74)))
           (esrp-virtip (unwrap (read-u32be buffer 76)))
           (esrp-sysmac (unwrap (slice buffer 80 6)))
           (esrp-hello (unwrap (read-u16be buffer 86)))
           (esrp-reserved (unwrap (slice buffer 88 2)))
           (eaps (unwrap (slice buffer 90 1)))
           (eaps-ver (unwrap (read-u8 buffer 94)))
           (eaps-ctrlvlanid (unwrap (read-u16be buffer 96)))
           (eaps-reserved0 (unwrap (slice buffer 98 4)))
           (eaps-sysmac (unwrap (slice buffer 102 6)))
           (eaps-hello (unwrap (read-u16be buffer 108)))
           (eaps-fail (unwrap (read-u16be buffer 110)))
           (eaps-reserved1 (unwrap (slice buffer 113 1)))
           (eaps-helloseq (unwrap (read-u16be buffer 114)))
           (eaps-reserved2 (unwrap (slice buffer 116 38)))
           (esl (unwrap (slice buffer 154 1)))
           (esl-ver (unwrap (read-u8 buffer 158)))
           (esl-ctrlvlanid (unwrap (read-u16be buffer 160)))
           (esl-reserved0 (unwrap (slice buffer 162 4)))
           (esl-sysmac (unwrap (slice buffer 166 6)))
           (esl-reserved1 (unwrap (slice buffer 172 4)))
           (esl-linkid1 (unwrap (read-u16be buffer 178)))
           (esl-failed1 (unwrap (read-u16be buffer 180)))
           (esl-failed2 (unwrap (read-u16be buffer 182)))
           (esl-reserved4 (unwrap (slice buffer 184 2)))
           (esl-linkid2 (unwrap (read-u16be buffer 186)))
           (esl-reserved5 (unwrap (slice buffer 188 2)))
           (esl-numlinks (unwrap (read-u16be buffer 190)))
           (esl-linklist (unwrap (read-u16be buffer 192)))
           (esl-rest (unwrap (slice buffer 194 1)))
           (elsm (unwrap (slice buffer 194 1)))
           (elsm-magic (unwrap (slice buffer 200 2)))
           (elrp (unwrap (slice buffer 202 1)))
           (elrp-unknown (unwrap (slice buffer 206 1)))
           (link (unwrap (slice buffer 206 1)))
           (link-flags (unwrap (read-u8 buffer 210)))
           (link-flags-autoneg (unwrap (read-u8 buffer 210)))
           (link-flags-flowcontrol (unwrap (read-u8 buffer 210)))
           (link-flags-unknown (unwrap (read-u8 buffer 210)))
           (link-zero (unwrap (read-u8 buffer 210)))
           (link-unknown (unwrap (slice buffer 210 1)))
           (unknown (unwrap (slice buffer 210 1)))
           (unknown-data (unwrap (slice buffer 214 1)))
           )

      (ok (list
        (cons 'tlv-marker (list (cons 'raw tlv-marker) (cons 'formatted (fmt-hex tlv-marker))))
        (cons 'version (list (cons 'raw version) (cons 'formatted (number->string version))))
        (cons 'reserved (list (cons 'raw reserved) (cons 'formatted (number->string reserved))))
        (cons 'tlv-length (list (cons 'raw tlv-length) (cons 'formatted (number->string tlv-length))))
        (cons 'length (list (cons 'raw length) (cons 'formatted (number->string length))))
        (cons 'display (list (cons 'raw display) (cons 'formatted (fmt-bytes display))))
        (cons 'seqno (list (cons 'raw seqno) (cons 'formatted (number->string seqno))))
        (cons 'display-string (list (cons 'raw display-string) (cons 'formatted (utf8->string display-string))))
        (cons 'null (list (cons 'raw null) (cons 'formatted (fmt-bytes null))))
        (cons 'midmac (list (cons 'raw midmac) (cons 'formatted (fmt-mac midmac))))
        (cons 'info (list (cons 'raw info) (cons 'formatted (fmt-bytes info))))
        (cons 'info-slot (list (cons 'raw info-slot) (cons 'formatted (number->string info-slot))))
        (cons 'info-port (list (cons 'raw info-port) (cons 'formatted (number->string info-port))))
        (cons 'info-vchassid (list (cons 'raw info-vchassid) (cons 'formatted (number->string info-vchassid))))
        (cons 'info-reserved (list (cons 'raw info-reserved) (cons 'formatted (fmt-bytes info-reserved))))
        (cons 'info-version (list (cons 'raw info-version) (cons 'formatted (fmt-hex info-version))))
        (cons 'info-version-major1 (list (cons 'raw info-version-major1) (cons 'formatted (number->string info-version-major1))))
        (cons 'info-version-major2 (list (cons 'raw info-version-major2) (cons 'formatted (number->string info-version-major2))))
        (cons 'info-version-sustaining (list (cons 'raw info-version-sustaining) (cons 'formatted (number->string info-version-sustaining))))
        (cons 'info-version-internal (list (cons 'raw info-version-internal) (cons 'formatted (number->string info-version-internal))))
        (cons 'info-vchassconn (list (cons 'raw info-vchassconn) (cons 'formatted (fmt-bytes info-vchassconn))))
        (cons 'vlan (list (cons 'raw vlan) (cons 'formatted (fmt-bytes vlan))))
        (cons 'vlan-flags (list (cons 'raw vlan-flags) (cons 'formatted (fmt-hex vlan-flags))))
        (cons 'vlan-flags-ip (list (cons 'raw vlan-flags-ip) (cons 'formatted (if (= vlan-flags-ip 0) "False" "True"))))
        (cons 'vlan-flags-reserved (list (cons 'raw vlan-flags-reserved) (cons 'formatted (fmt-hex vlan-flags-reserved))))
        (cons 'vlan-flags-unknown (list (cons 'raw vlan-flags-unknown) (cons 'formatted (if (= vlan-flags-unknown 0) "False" "True"))))
        (cons 'vlan-reserved1 (list (cons 'raw vlan-reserved1) (cons 'formatted (fmt-bytes vlan-reserved1))))
        (cons 'vlan-id (list (cons 'raw vlan-id) (cons 'formatted (number->string vlan-id))))
        (cons 'vlan-reserved2 (list (cons 'raw vlan-reserved2) (cons 'formatted (fmt-bytes vlan-reserved2))))
        (cons 'vlan-ip (list (cons 'raw vlan-ip) (cons 'formatted (fmt-ipv4 vlan-ip))))
        (cons 'vlan-name (list (cons 'raw vlan-name) (cons 'formatted (utf8->string vlan-name))))
        (cons 'esrp (list (cons 'raw esrp) (cons 'formatted (fmt-bytes esrp))))
        (cons 'esrp-group (list (cons 'raw esrp-group) (cons 'formatted (number->string esrp-group))))
        (cons 'esrp-prio (list (cons 'raw esrp-prio) (cons 'formatted (number->string esrp-prio))))
        (cons 'esrp-ports (list (cons 'raw esrp-ports) (cons 'formatted (number->string esrp-ports))))
        (cons 'esrp-virtip (list (cons 'raw esrp-virtip) (cons 'formatted (fmt-ipv4 esrp-virtip))))
        (cons 'esrp-sysmac (list (cons 'raw esrp-sysmac) (cons 'formatted (fmt-mac esrp-sysmac))))
        (cons 'esrp-hello (list (cons 'raw esrp-hello) (cons 'formatted (number->string esrp-hello))))
        (cons 'esrp-reserved (list (cons 'raw esrp-reserved) (cons 'formatted (fmt-bytes esrp-reserved))))
        (cons 'eaps (list (cons 'raw eaps) (cons 'formatted (fmt-bytes eaps))))
        (cons 'eaps-ver (list (cons 'raw eaps-ver) (cons 'formatted (number->string eaps-ver))))
        (cons 'eaps-ctrlvlanid (list (cons 'raw eaps-ctrlvlanid) (cons 'formatted (number->string eaps-ctrlvlanid))))
        (cons 'eaps-reserved0 (list (cons 'raw eaps-reserved0) (cons 'formatted (fmt-bytes eaps-reserved0))))
        (cons 'eaps-sysmac (list (cons 'raw eaps-sysmac) (cons 'formatted (fmt-mac eaps-sysmac))))
        (cons 'eaps-hello (list (cons 'raw eaps-hello) (cons 'formatted (number->string eaps-hello))))
        (cons 'eaps-fail (list (cons 'raw eaps-fail) (cons 'formatted (number->string eaps-fail))))
        (cons 'eaps-reserved1 (list (cons 'raw eaps-reserved1) (cons 'formatted (fmt-bytes eaps-reserved1))))
        (cons 'eaps-helloseq (list (cons 'raw eaps-helloseq) (cons 'formatted (number->string eaps-helloseq))))
        (cons 'eaps-reserved2 (list (cons 'raw eaps-reserved2) (cons 'formatted (fmt-bytes eaps-reserved2))))
        (cons 'esl (list (cons 'raw esl) (cons 'formatted (fmt-bytes esl))))
        (cons 'esl-ver (list (cons 'raw esl-ver) (cons 'formatted (number->string esl-ver))))
        (cons 'esl-ctrlvlanid (list (cons 'raw esl-ctrlvlanid) (cons 'formatted (number->string esl-ctrlvlanid))))
        (cons 'esl-reserved0 (list (cons 'raw esl-reserved0) (cons 'formatted (fmt-bytes esl-reserved0))))
        (cons 'esl-sysmac (list (cons 'raw esl-sysmac) (cons 'formatted (fmt-mac esl-sysmac))))
        (cons 'esl-reserved1 (list (cons 'raw esl-reserved1) (cons 'formatted (fmt-bytes esl-reserved1))))
        (cons 'esl-linkid1 (list (cons 'raw esl-linkid1) (cons 'formatted (number->string esl-linkid1))))
        (cons 'esl-failed1 (list (cons 'raw esl-failed1) (cons 'formatted (number->string esl-failed1))))
        (cons 'esl-failed2 (list (cons 'raw esl-failed2) (cons 'formatted (number->string esl-failed2))))
        (cons 'esl-reserved4 (list (cons 'raw esl-reserved4) (cons 'formatted (fmt-bytes esl-reserved4))))
        (cons 'esl-linkid2 (list (cons 'raw esl-linkid2) (cons 'formatted (number->string esl-linkid2))))
        (cons 'esl-reserved5 (list (cons 'raw esl-reserved5) (cons 'formatted (fmt-bytes esl-reserved5))))
        (cons 'esl-numlinks (list (cons 'raw esl-numlinks) (cons 'formatted (number->string esl-numlinks))))
        (cons 'esl-linklist (list (cons 'raw esl-linklist) (cons 'formatted (number->string esl-linklist))))
        (cons 'esl-rest (list (cons 'raw esl-rest) (cons 'formatted (fmt-bytes esl-rest))))
        (cons 'elsm (list (cons 'raw elsm) (cons 'formatted (fmt-bytes elsm))))
        (cons 'elsm-magic (list (cons 'raw elsm-magic) (cons 'formatted (fmt-bytes elsm-magic))))
        (cons 'elrp (list (cons 'raw elrp) (cons 'formatted (fmt-bytes elrp))))
        (cons 'elrp-unknown (list (cons 'raw elrp-unknown) (cons 'formatted (fmt-bytes elrp-unknown))))
        (cons 'link (list (cons 'raw link) (cons 'formatted (fmt-bytes link))))
        (cons 'link-flags (list (cons 'raw link-flags) (cons 'formatted (fmt-hex link-flags))))
        (cons 'link-flags-autoneg (list (cons 'raw link-flags-autoneg) (cons 'formatted (if (= link-flags-autoneg 0) "False" "True"))))
        (cons 'link-flags-flowcontrol (list (cons 'raw link-flags-flowcontrol) (cons 'formatted (if (= link-flags-flowcontrol 0) "False" "True"))))
        (cons 'link-flags-unknown (list (cons 'raw link-flags-unknown) (cons 'formatted (fmt-hex link-flags-unknown))))
        (cons 'link-zero (list (cons 'raw link-zero) (cons 'formatted (number->string link-zero))))
        (cons 'link-unknown (list (cons 'raw link-unknown) (cons 'formatted (fmt-bytes link-unknown))))
        (cons 'unknown (list (cons 'raw unknown) (cons 'formatted (fmt-bytes unknown))))
        (cons 'unknown-data (list (cons 'raw unknown-data) (cons 'formatted (fmt-bytes unknown-data))))
        )))

    (catch (e)
      (err (str "EXTREME parse error: " e)))))

;; dissect-extreme: parse EXTREME from bytevector
;; Returns (ok fields-alist) or (err message)