;; packet-fcswils.c
;; Routines for FC Inter-switch link services
;; Copyright 2001, Dinesh G Dutt <ddutt@cisco.com>
;;
;; Wireshark - Network traffic analyzer
;; By Gerald Combs <gerald@wireshark.org>
;; Copyright 1998 Gerald Combs
;;
;; SPDX-License-Identifier: GPL-2.0-or-later
;;

;; jerboa-ethereal/dissectors/fcswils.ss
;; Auto-generated from wireshark/epan/dissectors/packet-fcswils.c

(import (jerboa prelude))

;; ── Protocol Helpers ─────────────────────────────────────────────────
(def (read-u8 buf offset)
  (if (>= offset (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u8-ref buf offset))))

(def (read-u16be buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness big)))))

(def (read-u24be buf offset)
  (if (> (+ offset 3) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (+ (* (bytevector-u8-ref buf offset) 65536)
             (* (bytevector-u8-ref buf (+ offset 1)) 256)
             (bytevector-u8-ref buf (+ offset 2))))))

(def (read-u32be buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness big)))))

(def (read-u16le buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness little)))))

(def (read-u32le buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness little)))))

(def (read-u64be buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness big)))))

(def (read-u64le buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness little)))))

(def (slice buf offset len)
  (if (> (+ offset len) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (let ((result (make-bytevector len)))
            (bytevector-copy! buf offset result 0 len)
            result))))

(def (extract-bits val mask shift)
  (bitwise-arithmetic-shift-right (bitwise-and val mask) shift))

(def (fmt-ipv4 addr)
  (let ((b0 (bitwise-arithmetic-shift-right addr 24))
        (b1 (bitwise-and (bitwise-arithmetic-shift-right addr 16) 255))
        (b2 (bitwise-and (bitwise-arithmetic-shift-right addr 8) 255))
        (b3 (bitwise-and addr 255)))
    (str b0 "." b1 "." b2 "." b3)))

(def (fmt-mac bytes)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bytes))
    ":"))

(def (fmt-hex val)
  (str "0x" (number->string val 16)))

(def (fmt-oct val)
  (str "0" (number->string val 8)))

(def (fmt-port port)
  (number->string port))

(def (fmt-bytes bv)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bv))
    " "))

(def (fmt-ipv6-address bytes)
  (let loop ((i 0) (parts '()))
    (if (>= i 16)
        (string-join (reverse parts) ":")
        (loop (+ i 2)
              (cons (let ((w (+ (* (bytevector-u8-ref bytes i) 256)
                                (bytevector-u8-ref bytes (+ i 1)))))
                      (number->string w 16))
                    parts)))))

;; ── Dissector ──────────────────────────────────────────────────────
(def (dissect-fcswils buffer)
  "Fibre Channel SW_ILS"
  (try
    (let* (
           (ess-vendorname (unwrap (slice buffer 0 1)))
           (ess-modelname (unwrap (slice buffer 0 1)))
           (ess-relcode (unwrap (slice buffer 0 1)))
           (ess-vendorspecific (unwrap (slice buffer 0 1)))
           (ess-dns-zlacc (unwrap (read-u8 buffer 0)))
           (ess-dns-obj3h (unwrap (read-u8 buffer 0)))
           (ess-dns-obj2h (unwrap (read-u8 buffer 0)))
           (ess-dns-obj1h (unwrap (read-u8 buffer 0)))
           (ess-dns-obj0h (unwrap (read-u8 buffer 0)))
           (ess-dns-vendor (unwrap (read-u32be buffer 0)))
           (ess-fctlr-rscn (unwrap (read-u8 buffer 0)))
           (ess-fctlr-vendor (unwrap (read-u32be buffer 0)))
           (ess-fcs-basic (unwrap (read-u8 buffer 0)))
           (ess-fcs-platform (unwrap (read-u8 buffer 0)))
           (ess-fcs-topology (unwrap (read-u8 buffer 0)))
           (ess-fcs-enhanced (unwrap (read-u8 buffer 0)))
           (ess-fzs-enh-supp (unwrap (read-u8 buffer 0)))
           (ess-fzs-enh-ena (unwrap (read-u8 buffer 0)))
           (ess-fzs-mr (unwrap (read-u8 buffer 0)))
           (ess-fzs-defzone (unwrap (read-u8 buffer 0)))
           (ess-fzs-zsdb-supp (unwrap (read-u8 buffer 0)))
           (ess-fzs-zsdb-ena (unwrap (read-u8 buffer 0)))
           (ess-fzs-adc-supp (unwrap (read-u8 buffer 0)))
           (ess-fzs-hardzone (unwrap (read-u8 buffer 0)))
           (ess-cap-subtype (unwrap (read-u8 buffer 0)))
           (ess-cap-numentries (unwrap (read-u8 buffer 0)))
           (rdi-payload-len (unwrap (read-u16be buffer 0)))
           (hlo-options (unwrap (slice buffer 0 4)))
           (hlo-hloint (unwrap (read-u32be buffer 0)))
           (hlo-deadint (unwrap (read-u32be buffer 0)))
           (hlo-rcv-domid (unwrap (read-u8 buffer 0)))
           (hlo-orig-pidx (unwrap (read-u24be buffer 0)))
           (lsupdate-num-of-lsrs (unwrap (read-u32be buffer 0)))
           (lsack-num-of-lsr-headers (unwrap (read-u32be buffer 0)))
           (rscn-num-entries (unwrap (read-u32be buffer 0)))
           (zone-active-zoneset-length (unwrap (read-u16be buffer 0)))
           (zone-activezonenm (unwrap (slice buffer 0 1)))
           (domain-id-list-length (unwrap (read-u16be buffer 0)))
           (zone-vendor-unique (unwrap (read-u8 buffer 0)))
           (sfc-zoneset-length (unwrap (read-u16be buffer 0)))
           (sfc-zonenm (unwrap (slice buffer 0 1)))
           (esc-payload-length (unwrap (read-u16be buffer 0)))
           (rjtvendor (unwrap (read-u8 buffer 0)))
           (ess-rev (unwrap (read-u32be buffer 0)))
           (ess-len (unwrap (read-u32be buffer 0)))
           (mrra-rev (unwrap (read-u32be buffer 0)))
           (mrra-size (unwrap (read-u32be buffer 0)))
           (mrra-vendorid (unwrap (slice buffer 0 8)))
           (mrra-vendorinfo (unwrap (slice buffer 0 8)))
           (mrra-reply (unwrap (read-u32be buffer 0)))
           (mrra-reply-size (unwrap (read-u32be buffer 0)))
           (mrra-waittime (unwrap (read-u32be buffer 0)))
           (efp-record-len (unwrap (read-u8 buffer 1)))
           (efp-payload-len (unwrap (read-u16be buffer 2)))
           (aca-domainid (unwrap (read-u8 buffer 4)))
           (efp-pswitch-pri (unwrap (read-u8 buffer 7)))
           (elp-flags (unwrap (slice buffer 8 2)))
           (zone-full-zone-set-length (unwrap (read-u32be buffer 8)))
           (ess-cap-len (unwrap (read-u8 buffer 12)))
           (ess-cap-t10 (unwrap (slice buffer 12 8)))
           (requested-domain-id (unwrap (read-u8 buffer 12)))
           (granted-domain-id (unwrap (read-u8 buffer 12)))
           (zone-num-zoning-objects (unwrap (read-u32be buffer 12)))
           (efp-dom-id (unwrap (read-u8 buffer 16)))
           (efp-mcast-grpno (unwrap (read-u8 buffer 16)))
           (fspfh-rev (unwrap (read-u8 buffer 16)))
           (fspfh-ar-num (unwrap (read-u8 buffer 16)))
           (fspfh-auth-type (unwrap (read-u8 buffer 16)))
           (fspfh-dom-id (unwrap (read-u8 buffer 16)))
           (fspfh-auth (unwrap (slice buffer 16 8)))
           (lsrh-options (unwrap (read-u32be buffer 16)))
           (lsrh-lsid (unwrap (read-u8 buffer 16)))
           (lsrh-adv-domid (unwrap (read-u8 buffer 16)))
           (lsrh-ls-incid (unwrap (read-u32be buffer 16)))
           (lsrh-lsr-length (unwrap (read-u16be buffer 16)))
           (ldrec-out-pidx (unwrap (read-u24be buffer 16)))
           (ldrec-nbr-pidx (unwrap (read-u24be buffer 16)))
           (ldrec-link-cost (unwrap (read-u16be buffer 16)))
           (lsrec-number-of-links (unwrap (read-u16be buffer 16)))
           (rscn-portstate (unwrap (read-u8 buffer 16)))
           (ess-cap-vendorobj (unwrap (slice buffer 24 8)))
           (esc-swvendorid (unwrap (slice buffer 24 8)))
           (esc-pdesc-vendorid (unwrap (slice buffer 24 8)))
           (elp-clsf-svcp (unwrap (slice buffer 35 6)))
           (zone-mbrflags (unwrap (read-u8 buffer 36)))
           (zone-mbr-identifier-length (unwrap (read-u8 buffer 36)))
           (zone-mbrid-uint (unwrap (read-u32be buffer 36)))
           (zone-mbrid (unwrap (slice buffer 36 1)))
           (zone-mbrid-lun (unwrap (slice buffer 36 8)))
           (zone-protocol (unwrap (read-u8 buffer 36)))
           (zone-objname (unwrap (slice buffer 36 1)))
           (elp-clsf-rcvsz (unwrap (read-u16be buffer 41)))
           (elp-clsf-conseq (unwrap (read-u16be buffer 43)))
           (elp-clsf-e2e (unwrap (read-u16be buffer 45)))
           (elp-clsf-openseq (unwrap (read-u16be buffer 47)))
           (elp-cls1-svcp (unwrap (slice buffer 51 2)))
           (elp-cls1-rcvsz (unwrap (read-u16be buffer 53)))
           (elp-cls2-svcp (unwrap (slice buffer 55 2)))
           (elp-cls2-rcvsz (unwrap (read-u16be buffer 57)))
           (elp-cls3-svcp (unwrap (slice buffer 59 2)))
           (elp-cls3-rcvsz (unwrap (read-u16be buffer 61)))
           (elp-isl-fc-mode (unwrap (slice buffer 83 2)))
           (elp-fcplen (unwrap (read-u16be buffer 85)))
           (elp-b2bcredit (unwrap (read-u32be buffer 87)))
           (elp-compat1 (unwrap (read-u32be buffer 91)))
           (elp-compat2 (unwrap (read-u32be buffer 95)))
           (elp-compat3 (unwrap (read-u32be buffer 99)))
           (elp-compat4 (unwrap (read-u32be buffer 103)))
           (ess-numobj (unwrap (read-u16be buffer 268)))
           (interconnect-list-len (unwrap (read-u8 buffer 270)))
           )

      (ok (list
        (cons 'ess-vendorname (list (cons 'raw ess-vendorname) (cons 'formatted (utf8->string ess-vendorname))))
        (cons 'ess-modelname (list (cons 'raw ess-modelname) (cons 'formatted (utf8->string ess-modelname))))
        (cons 'ess-relcode (list (cons 'raw ess-relcode) (cons 'formatted (utf8->string ess-relcode))))
        (cons 'ess-vendorspecific (list (cons 'raw ess-vendorspecific) (cons 'formatted (utf8->string ess-vendorspecific))))
        (cons 'ess-dns-zlacc (list (cons 'raw ess-dns-zlacc) (cons 'formatted (number->string ess-dns-zlacc))))
        (cons 'ess-dns-obj3h (list (cons 'raw ess-dns-obj3h) (cons 'formatted (number->string ess-dns-obj3h))))
        (cons 'ess-dns-obj2h (list (cons 'raw ess-dns-obj2h) (cons 'formatted (number->string ess-dns-obj2h))))
        (cons 'ess-dns-obj1h (list (cons 'raw ess-dns-obj1h) (cons 'formatted (number->string ess-dns-obj1h))))
        (cons 'ess-dns-obj0h (list (cons 'raw ess-dns-obj0h) (cons 'formatted (number->string ess-dns-obj0h))))
        (cons 'ess-dns-vendor (list (cons 'raw ess-dns-vendor) (cons 'formatted (fmt-hex ess-dns-vendor))))
        (cons 'ess-fctlr-rscn (list (cons 'raw ess-fctlr-rscn) (cons 'formatted (number->string ess-fctlr-rscn))))
        (cons 'ess-fctlr-vendor (list (cons 'raw ess-fctlr-vendor) (cons 'formatted (fmt-hex ess-fctlr-vendor))))
        (cons 'ess-fcs-basic (list (cons 'raw ess-fcs-basic) (cons 'formatted (number->string ess-fcs-basic))))
        (cons 'ess-fcs-platform (list (cons 'raw ess-fcs-platform) (cons 'formatted (number->string ess-fcs-platform))))
        (cons 'ess-fcs-topology (list (cons 'raw ess-fcs-topology) (cons 'formatted (number->string ess-fcs-topology))))
        (cons 'ess-fcs-enhanced (list (cons 'raw ess-fcs-enhanced) (cons 'formatted (number->string ess-fcs-enhanced))))
        (cons 'ess-fzs-enh-supp (list (cons 'raw ess-fzs-enh-supp) (cons 'formatted (number->string ess-fzs-enh-supp))))
        (cons 'ess-fzs-enh-ena (list (cons 'raw ess-fzs-enh-ena) (cons 'formatted (number->string ess-fzs-enh-ena))))
        (cons 'ess-fzs-mr (list (cons 'raw ess-fzs-mr) (cons 'formatted (number->string ess-fzs-mr))))
        (cons 'ess-fzs-defzone (list (cons 'raw ess-fzs-defzone) (cons 'formatted (number->string ess-fzs-defzone))))
        (cons 'ess-fzs-zsdb-supp (list (cons 'raw ess-fzs-zsdb-supp) (cons 'formatted (number->string ess-fzs-zsdb-supp))))
        (cons 'ess-fzs-zsdb-ena (list (cons 'raw ess-fzs-zsdb-ena) (cons 'formatted (number->string ess-fzs-zsdb-ena))))
        (cons 'ess-fzs-adc-supp (list (cons 'raw ess-fzs-adc-supp) (cons 'formatted (number->string ess-fzs-adc-supp))))
        (cons 'ess-fzs-hardzone (list (cons 'raw ess-fzs-hardzone) (cons 'formatted (number->string ess-fzs-hardzone))))
        (cons 'ess-cap-subtype (list (cons 'raw ess-cap-subtype) (cons 'formatted (number->string ess-cap-subtype))))
        (cons 'ess-cap-numentries (list (cons 'raw ess-cap-numentries) (cons 'formatted (number->string ess-cap-numentries))))
        (cons 'rdi-payload-len (list (cons 'raw rdi-payload-len) (cons 'formatted (number->string rdi-payload-len))))
        (cons 'hlo-options (list (cons 'raw hlo-options) (cons 'formatted (fmt-bytes hlo-options))))
        (cons 'hlo-hloint (list (cons 'raw hlo-hloint) (cons 'formatted (number->string hlo-hloint))))
        (cons 'hlo-deadint (list (cons 'raw hlo-deadint) (cons 'formatted (number->string hlo-deadint))))
        (cons 'hlo-rcv-domid (list (cons 'raw hlo-rcv-domid) (cons 'formatted (number->string hlo-rcv-domid))))
        (cons 'hlo-orig-pidx (list (cons 'raw hlo-orig-pidx) (cons 'formatted (fmt-hex hlo-orig-pidx))))
        (cons 'lsupdate-num-of-lsrs (list (cons 'raw lsupdate-num-of-lsrs) (cons 'formatted (number->string lsupdate-num-of-lsrs))))
        (cons 'lsack-num-of-lsr-headers (list (cons 'raw lsack-num-of-lsr-headers) (cons 'formatted (number->string lsack-num-of-lsr-headers))))
        (cons 'rscn-num-entries (list (cons 'raw rscn-num-entries) (cons 'formatted (number->string rscn-num-entries))))
        (cons 'zone-active-zoneset-length (list (cons 'raw zone-active-zoneset-length) (cons 'formatted (number->string zone-active-zoneset-length))))
        (cons 'zone-activezonenm (list (cons 'raw zone-activezonenm) (cons 'formatted (utf8->string zone-activezonenm))))
        (cons 'domain-id-list-length (list (cons 'raw domain-id-list-length) (cons 'formatted (number->string domain-id-list-length))))
        (cons 'zone-vendor-unique (list (cons 'raw zone-vendor-unique) (cons 'formatted (fmt-hex zone-vendor-unique))))
        (cons 'sfc-zoneset-length (list (cons 'raw sfc-zoneset-length) (cons 'formatted (number->string sfc-zoneset-length))))
        (cons 'sfc-zonenm (list (cons 'raw sfc-zonenm) (cons 'formatted (utf8->string sfc-zonenm))))
        (cons 'esc-payload-length (list (cons 'raw esc-payload-length) (cons 'formatted (number->string esc-payload-length))))
        (cons 'rjtvendor (list (cons 'raw rjtvendor) (cons 'formatted (fmt-hex rjtvendor))))
        (cons 'ess-rev (list (cons 'raw ess-rev) (cons 'formatted (number->string ess-rev))))
        (cons 'ess-len (list (cons 'raw ess-len) (cons 'formatted (number->string ess-len))))
        (cons 'mrra-rev (list (cons 'raw mrra-rev) (cons 'formatted (number->string mrra-rev))))
        (cons 'mrra-size (list (cons 'raw mrra-size) (cons 'formatted (number->string mrra-size))))
        (cons 'mrra-vendorid (list (cons 'raw mrra-vendorid) (cons 'formatted (utf8->string mrra-vendorid))))
        (cons 'mrra-vendorinfo (list (cons 'raw mrra-vendorinfo) (cons 'formatted (fmt-bytes mrra-vendorinfo))))
        (cons 'mrra-reply (list (cons 'raw mrra-reply) (cons 'formatted (number->string mrra-reply))))
        (cons 'mrra-reply-size (list (cons 'raw mrra-reply-size) (cons 'formatted (number->string mrra-reply-size))))
        (cons 'mrra-waittime (list (cons 'raw mrra-waittime) (cons 'formatted (number->string mrra-waittime))))
        (cons 'efp-record-len (list (cons 'raw efp-record-len) (cons 'formatted (number->string efp-record-len))))
        (cons 'efp-payload-len (list (cons 'raw efp-payload-len) (cons 'formatted (number->string efp-payload-len))))
        (cons 'aca-domainid (list (cons 'raw aca-domainid) (cons 'formatted (fmt-hex aca-domainid))))
        (cons 'efp-pswitch-pri (list (cons 'raw efp-pswitch-pri) (cons 'formatted (number->string efp-pswitch-pri))))
        (cons 'elp-flags (list (cons 'raw elp-flags) (cons 'formatted (fmt-bytes elp-flags))))
        (cons 'zone-full-zone-set-length (list (cons 'raw zone-full-zone-set-length) (cons 'formatted (number->string zone-full-zone-set-length))))
        (cons 'ess-cap-len (list (cons 'raw ess-cap-len) (cons 'formatted (number->string ess-cap-len))))
        (cons 'ess-cap-t10 (list (cons 'raw ess-cap-t10) (cons 'formatted (utf8->string ess-cap-t10))))
        (cons 'requested-domain-id (list (cons 'raw requested-domain-id) (cons 'formatted (number->string requested-domain-id))))
        (cons 'granted-domain-id (list (cons 'raw granted-domain-id) (cons 'formatted (number->string granted-domain-id))))
        (cons 'zone-num-zoning-objects (list (cons 'raw zone-num-zoning-objects) (cons 'formatted (number->string zone-num-zoning-objects))))
        (cons 'efp-dom-id (list (cons 'raw efp-dom-id) (cons 'formatted (fmt-hex efp-dom-id))))
        (cons 'efp-mcast-grpno (list (cons 'raw efp-mcast-grpno) (cons 'formatted (fmt-hex efp-mcast-grpno))))
        (cons 'fspfh-rev (list (cons 'raw fspfh-rev) (cons 'formatted (fmt-hex fspfh-rev))))
        (cons 'fspfh-ar-num (list (cons 'raw fspfh-ar-num) (cons 'formatted (fmt-hex fspfh-ar-num))))
        (cons 'fspfh-auth-type (list (cons 'raw fspfh-auth-type) (cons 'formatted (fmt-hex fspfh-auth-type))))
        (cons 'fspfh-dom-id (list (cons 'raw fspfh-dom-id) (cons 'formatted (number->string fspfh-dom-id))))
        (cons 'fspfh-auth (list (cons 'raw fspfh-auth) (cons 'formatted (fmt-bytes fspfh-auth))))
        (cons 'lsrh-options (list (cons 'raw lsrh-options) (cons 'formatted (fmt-hex lsrh-options))))
        (cons 'lsrh-lsid (list (cons 'raw lsrh-lsid) (cons 'formatted (number->string lsrh-lsid))))
        (cons 'lsrh-adv-domid (list (cons 'raw lsrh-adv-domid) (cons 'formatted (number->string lsrh-adv-domid))))
        (cons 'lsrh-ls-incid (list (cons 'raw lsrh-ls-incid) (cons 'formatted (number->string lsrh-ls-incid))))
        (cons 'lsrh-lsr-length (list (cons 'raw lsrh-lsr-length) (cons 'formatted (number->string lsrh-lsr-length))))
        (cons 'ldrec-out-pidx (list (cons 'raw ldrec-out-pidx) (cons 'formatted (fmt-hex ldrec-out-pidx))))
        (cons 'ldrec-nbr-pidx (list (cons 'raw ldrec-nbr-pidx) (cons 'formatted (fmt-hex ldrec-nbr-pidx))))
        (cons 'ldrec-link-cost (list (cons 'raw ldrec-link-cost) (cons 'formatted (number->string ldrec-link-cost))))
        (cons 'lsrec-number-of-links (list (cons 'raw lsrec-number-of-links) (cons 'formatted (number->string lsrec-number-of-links))))
        (cons 'rscn-portstate (list (cons 'raw rscn-portstate) (cons 'formatted (fmt-hex rscn-portstate))))
        (cons 'ess-cap-vendorobj (list (cons 'raw ess-cap-vendorobj) (cons 'formatted (fmt-bytes ess-cap-vendorobj))))
        (cons 'esc-swvendorid (list (cons 'raw esc-swvendorid) (cons 'formatted (utf8->string esc-swvendorid))))
        (cons 'esc-pdesc-vendorid (list (cons 'raw esc-pdesc-vendorid) (cons 'formatted (utf8->string esc-pdesc-vendorid))))
        (cons 'elp-clsf-svcp (list (cons 'raw elp-clsf-svcp) (cons 'formatted (fmt-bytes elp-clsf-svcp))))
        (cons 'zone-mbrflags (list (cons 'raw zone-mbrflags) (cons 'formatted (fmt-hex zone-mbrflags))))
        (cons 'zone-mbr-identifier-length (list (cons 'raw zone-mbr-identifier-length) (cons 'formatted (number->string zone-mbr-identifier-length))))
        (cons 'zone-mbrid-uint (list (cons 'raw zone-mbrid-uint) (cons 'formatted (fmt-hex zone-mbrid-uint))))
        (cons 'zone-mbrid (list (cons 'raw zone-mbrid) (cons 'formatted (utf8->string zone-mbrid))))
        (cons 'zone-mbrid-lun (list (cons 'raw zone-mbrid-lun) (cons 'formatted (fmt-bytes zone-mbrid-lun))))
        (cons 'zone-protocol (list (cons 'raw zone-protocol) (cons 'formatted (fmt-hex zone-protocol))))
        (cons 'zone-objname (list (cons 'raw zone-objname) (cons 'formatted (utf8->string zone-objname))))
        (cons 'elp-clsf-rcvsz (list (cons 'raw elp-clsf-rcvsz) (cons 'formatted (number->string elp-clsf-rcvsz))))
        (cons 'elp-clsf-conseq (list (cons 'raw elp-clsf-conseq) (cons 'formatted (number->string elp-clsf-conseq))))
        (cons 'elp-clsf-e2e (list (cons 'raw elp-clsf-e2e) (cons 'formatted (number->string elp-clsf-e2e))))
        (cons 'elp-clsf-openseq (list (cons 'raw elp-clsf-openseq) (cons 'formatted (number->string elp-clsf-openseq))))
        (cons 'elp-cls1-svcp (list (cons 'raw elp-cls1-svcp) (cons 'formatted (fmt-bytes elp-cls1-svcp))))
        (cons 'elp-cls1-rcvsz (list (cons 'raw elp-cls1-rcvsz) (cons 'formatted (number->string elp-cls1-rcvsz))))
        (cons 'elp-cls2-svcp (list (cons 'raw elp-cls2-svcp) (cons 'formatted (fmt-bytes elp-cls2-svcp))))
        (cons 'elp-cls2-rcvsz (list (cons 'raw elp-cls2-rcvsz) (cons 'formatted (number->string elp-cls2-rcvsz))))
        (cons 'elp-cls3-svcp (list (cons 'raw elp-cls3-svcp) (cons 'formatted (fmt-bytes elp-cls3-svcp))))
        (cons 'elp-cls3-rcvsz (list (cons 'raw elp-cls3-rcvsz) (cons 'formatted (number->string elp-cls3-rcvsz))))
        (cons 'elp-isl-fc-mode (list (cons 'raw elp-isl-fc-mode) (cons 'formatted (utf8->string elp-isl-fc-mode))))
        (cons 'elp-fcplen (list (cons 'raw elp-fcplen) (cons 'formatted (number->string elp-fcplen))))
        (cons 'elp-b2bcredit (list (cons 'raw elp-b2bcredit) (cons 'formatted (number->string elp-b2bcredit))))
        (cons 'elp-compat1 (list (cons 'raw elp-compat1) (cons 'formatted (number->string elp-compat1))))
        (cons 'elp-compat2 (list (cons 'raw elp-compat2) (cons 'formatted (number->string elp-compat2))))
        (cons 'elp-compat3 (list (cons 'raw elp-compat3) (cons 'formatted (number->string elp-compat3))))
        (cons 'elp-compat4 (list (cons 'raw elp-compat4) (cons 'formatted (number->string elp-compat4))))
        (cons 'ess-numobj (list (cons 'raw ess-numobj) (cons 'formatted (number->string ess-numobj))))
        (cons 'interconnect-list-len (list (cons 'raw interconnect-list-len) (cons 'formatted (number->string interconnect-list-len))))
        )))

    (catch (e)
      (err (str "FCSWILS parse error: " e)))))

;; dissect-fcswils: parse FCSWILS from bytevector
;; Returns (ok fields-alist) or (err message)