;; packet-ipv6.c
;; Routines for IPv6 packet disassembly
;;
;; Wireshark - Network traffic analyzer
;; By Gerald Combs <gerald@wireshark.org>
;; Copyright 1998 Gerald Combs
;;
;; SHIM6 support added by Matthijs Mekking <matthijs@NLnetLabs.nl>
;;
;; MobileIPv6 support added by Tomislav Borosa <tomislav.borosa@siemens.hr>
;;
;; Added support for new IPv6 Hop by Hop PMTU Option  <bob.hinden@gmail.com>
;;
;; SPDX-License-Identifier: GPL-2.0-or-later
;;

;; jerboa-ethereal/dissectors/ipv6.ss
;; Auto-generated from wireshark/epan/dissectors/packet-ipv6.c

(import (jerboa prelude))

;; ── Protocol Helpers ─────────────────────────────────────────────────
(def (read-u8 buf offset)
  (if (>= offset (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u8-ref buf offset))))

(def (read-u16be buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness big)))))

(def (read-u24be buf offset)
  (if (> (+ offset 3) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (+ (* (bytevector-u8-ref buf offset) 65536)
             (* (bytevector-u8-ref buf (+ offset 1)) 256)
             (bytevector-u8-ref buf (+ offset 2))))))

(def (read-u32be buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness big)))))

(def (read-u16le buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness little)))))

(def (read-u32le buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness little)))))

(def (read-u64be buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness big)))))

(def (read-u64le buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness little)))))

(def (slice buf offset len)
  (if (> (+ offset len) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (let ((result (make-bytevector len)))
            (bytevector-copy! buf offset result 0 len)
            result))))

(def (extract-bits val mask shift)
  (bitwise-arithmetic-shift-right (bitwise-and val mask) shift))

(def (fmt-ipv4 addr)
  (let ((b0 (bitwise-arithmetic-shift-right addr 24))
        (b1 (bitwise-and (bitwise-arithmetic-shift-right addr 16) 255))
        (b2 (bitwise-and (bitwise-arithmetic-shift-right addr 8) 255))
        (b3 (bitwise-and addr 255)))
    (str b0 "." b1 "." b2 "." b3)))

(def (fmt-mac bytes)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bytes))
    ":"))

(def (fmt-hex val)
  (str "0x" (number->string val 16)))

(def (fmt-oct val)
  (str "0" (number->string val 8)))

(def (fmt-port port)
  (number->string port))

(def (fmt-bytes bv)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bv))
    " "))

(def (fmt-ipv6-address bytes)
  (let loop ((i 0) (parts '()))
    (if (>= i 16)
        (string-join (reverse parts) ":")
        (loop (+ i 2)
              (cons (let ((w (+ (* (bytevector-u8-ref bytes i) 256)
                                (bytevector-u8-ref bytes (+ i 1)))))
                      (number->string w 16))
                    parts)))))

;; ── Dissector ──────────────────────────────────────────────────────
(def (dissect-ipv6 buffer)
  "Internet Protocol Version 6"
  (try
    (let* (
           (stream (unwrap (read-u32be buffer 0)))
           (routing-src-reserved (unwrap (slice buffer 0 4)))
           (routing-mipv6-reserved (unwrap (slice buffer 0 4)))
           (routing-rpl-cmprI (unwrap (read-u32be buffer 0)))
           (routing-rpl-cmprE (unwrap (read-u32be buffer 0)))
           (routing-rpl-pad (unwrap (read-u32be buffer 0)))
           (routing-rpl-reserved (unwrap (read-u32be buffer 0)))
           (routing-rpl-addr-count (unwrap (read-u32be buffer 0)))
           (routing-srh-last-entry (unwrap (read-u8 buffer 0)))
           (routing-crh16-segment-id (unwrap (read-u16be buffer 0)))
           (routing-crh32-segment-id (unwrap (read-u32be buffer 0)))
           (version (unwrap (read-u8 buffer 0)))
           (tclass (unwrap (read-u32be buffer 0)))
           (plen (unwrap (read-u16be buffer 0)))
           (hlim (unwrap (read-u8 buffer 0)))
           (routing-srh-flags (unwrap (read-u8 buffer 1)))
           (routing-len (unwrap (read-u8 buffer 1)))
           (fraghdr-reserved-octet (unwrap (read-u8 buffer 1)))
           (routing-srh-tag (unwrap (slice buffer 2 2)))
           (fraghdr-offset (unwrap (read-u16be buffer 2)))
           (fraghdr-reserved-bits (unwrap (read-u16be buffer 2)))
           (fraghdr-more (unwrap (read-u8 buffer 2)))
           (routing-segleft (unwrap (read-u8 buffer 3)))
           (routing-rpl-addr (unwrap (slice buffer 4 1)))
           (routing-unknown-data (unwrap (slice buffer 4 1)))
           (fraghdr-ident (unwrap (read-u32be buffer 4)))
           (opt-jumbo (unwrap (read-u32be buffer 8)))
           (opt-rpl-flag (unwrap (read-u8 buffer 12)))
           (opt-rpl-flag-o (extract-bits opt-rpl-flag 0x80 7))
           (opt-rpl-flag-r (extract-bits opt-rpl-flag 0x40 6))
           (opt-rpl-flag-f (extract-bits opt-rpl-flag 0x20 5))
           (opt-rpl-flag-rsv (extract-bits opt-rpl-flag 0x1F 0))
           (opt-rpl-instance-id (unwrap (read-u8 buffer 13)))
           (opt-rpl-senderrank (unwrap (read-u16be buffer 14)))
           (opt-tel (unwrap (read-u8 buffer 16)))
           (opt-pmtu-min (unwrap (read-u16be buffer 17)))
           (opt-pmtu-rtn (unwrap (read-u16be buffer 19)))
           (opt-pmtu-rtn-flag (unwrap (read-u8 buffer 20)))
           (opt-apn-flags (unwrap (read-u8 buffer 21)))
           (opt-apn-param-type (unwrap (read-u16be buffer 21)))
           (opt-apn-id-part1 (unwrap (read-u32be buffer 25)))
           (opt-apn-id-part2 (unwrap (read-u32be buffer 33)))
           (opt-apn-id-part3 (unwrap (read-u32be buffer 41)))
           (opt-apn-id-part4 (unwrap (read-u32be buffer 45)))
           (opt-qs-ttl (unwrap (read-u8 buffer 52)))
           (opt-qs-ttl-diff (unwrap (read-u8 buffer 52)))
           (opt-qs-unused (unwrap (read-u8 buffer 58)))
           (opt-qs-nonce (unwrap (read-u32be buffer 59)))
           (opt-qs-reserved (unwrap (read-u32be buffer 59)))
           (opt-ioam-trace-node-id (unwrap (read-u24be buffer 63)))
           (opt-ioam-trace-node-iif (unwrap (read-u16be buffer 67)))
           (opt-ioam-trace-node-eif (unwrap (read-u16be buffer 67)))
           (opt-ioam-trace-node-tss (unwrap (read-u32be buffer 71)))
           (opt-ioam-trace-node-tsf (unwrap (read-u32be buffer 75)))
           (opt-ioam-trace-node-trdelay (unwrap (read-u32be buffer 79)))
           (opt-ioam-trace-node-nsdata (unwrap (read-u32be buffer 83)))
           (opt-ioam-trace-node-qdepth (unwrap (read-u32be buffer 87)))
           (opt-ioam-trace-node-csum (unwrap (read-u32be buffer 91)))
           (opt-ioam-trace-node-hlim (unwrap (read-u8 buffer 95)))
           (opt-ioam-trace-node-id-wide (unwrap (slice buffer 95 7)))
           (opt-ioam-trace-node-iif-wide (unwrap (read-u32be buffer 103)))
           (opt-ioam-trace-node-eif-wide (unwrap (read-u32be buffer 103)))
           (opt-ioam-trace-node-nsdata-wide (unwrap (read-u64be buffer 111)))
           (opt-ioam-trace-node-bufoccup (unwrap (read-u32be buffer 119)))
           (opt-ioam-trace-node-undefined (unwrap (read-u32be buffer 159)))
           (opt-ioam-trace-ns (unwrap (read-u16be buffer 163)))
           (opt-ioam-trace-flags (unwrap (read-u16be buffer 165)))
           (opt-ioam-trace-flag-o (extract-bits opt-ioam-trace-flags 0x400 10))
           (opt-ioam-trace-flag-l (extract-bits opt-ioam-trace-flags 0x200 9))
           (opt-ioam-trace-flag-a (extract-bits opt-ioam-trace-flags 0x100 8))
           (opt-ioam-trace-flag-rsv (extract-bits opt-ioam-trace-flags 0x80 7))
           (opt-ioam-trace-free-space (unwrap (slice buffer 171 1)))
           (opt-ioam-trace-node-oss-len (unwrap (read-u8 buffer 171)))
           (opt-ioam-trace-node-oss-scid (unwrap (read-u24be buffer 171)))
           (opt-ioam-trace-node-oss-data (unwrap (slice buffer 175 1)))
           (opt-ioam-dex-ns (unwrap (read-u16be buffer 175)))
           (opt-ioam-dex-flags (unwrap (read-u8 buffer 177)))
           (opt-ioam-dex-extflags (unwrap (read-u8 buffer 177)))
           (opt-ioam-dex-extflag-flag-rsv (extract-bits opt-ioam-dex-extflags 0x3F 0))
           (opt-ioam-dex-extflag-flag-seqnum (extract-bits opt-ioam-dex-extflags 0x40 6))
           (opt-ioam-dex-extflag-flag-flowid (extract-bits opt-ioam-dex-extflags 0x80 7))
           (opt-ioam-trace-type (unwrap (read-u24be buffer 177)))
           (opt-ioam-trace-type-bit0 (extract-bits opt-ioam-trace-type 0x800000 23))
           (opt-ioam-trace-type-bit1 (extract-bits opt-ioam-trace-type 0x400000 22))
           (opt-ioam-trace-type-bit2 (extract-bits opt-ioam-trace-type 0x200000 21))
           (opt-ioam-trace-type-bit3 (extract-bits opt-ioam-trace-type 0x100000 20))
           (opt-ioam-trace-type-bit4 (extract-bits opt-ioam-trace-type 0x80000 19))
           (opt-ioam-trace-type-bit5 (extract-bits opt-ioam-trace-type 0x40000 18))
           (opt-ioam-trace-type-bit6 (extract-bits opt-ioam-trace-type 0x20000 17))
           (opt-ioam-trace-type-bit7 (extract-bits opt-ioam-trace-type 0x10000 16))
           (opt-ioam-trace-type-bit8 (extract-bits opt-ioam-trace-type 0x8000 15))
           (opt-ioam-trace-type-bit9 (extract-bits opt-ioam-trace-type 0x4000 14))
           (opt-ioam-trace-type-bit10 (extract-bits opt-ioam-trace-type 0x2000 13))
           (opt-ioam-trace-type-bit11 (extract-bits opt-ioam-trace-type 0x1000 12))
           (opt-ioam-trace-type-undef (extract-bits opt-ioam-trace-type 0xFFC 2))
           (opt-ioam-trace-type-bit22 (extract-bits opt-ioam-trace-type 0x2 1))
           (opt-ioam-trace-type-rsv (extract-bits opt-ioam-trace-type 0x1 0))
           (opt-ioam-trace-rsv (unwrap (read-u8 buffer 177)))
           (opt-ioam-dex-extflag-flowid (unwrap (read-u32be buffer 181)))
           (opt-ioam-dex-extflag-seqnum (unwrap (read-u32be buffer 185)))
           (opt-ioam-rsv (unwrap (read-u8 buffer 189)))
           (opt-tpf-information (unwrap (read-u32be buffer 191)))
           (opt-calipso-doi (unwrap (read-u32be buffer 195)))
           (opt-calipso-cmpt-length (unwrap (read-u8 buffer 199)))
           (opt-calipso-sens-level (unwrap (read-u8 buffer 200)))
           (opt-calipso-cmpt-bitmap (unwrap (slice buffer 203 1)))
           (opt-smf-dpd-hash-bit (unwrap (read-u8 buffer 203)))
           (opt-smf-dpd-hav (unwrap (slice buffer 203 1)))
           (opt-smf-dpd-tid-len (unwrap (read-u8 buffer 203)))
           (opt-smf-dpd-tagger-id (unwrap (slice buffer 204 1)))
           (opt-smf-dpd-ident (unwrap (slice buffer 204 1)))
           (opt-pdm-scale-dtlr (unwrap (read-u8 buffer 204)))
           (opt-pdm-scale-dtls (unwrap (read-u8 buffer 205)))
           (opt-pdm-psn-this-pkt (unwrap (read-u16be buffer 206)))
           (opt-pdm-psn-last-recv (unwrap (read-u16be buffer 208)))
           (opt-pdm-delta-last-recv (unwrap (read-u16be buffer 210)))
           (opt-pdm-delta-last-sent (unwrap (read-u16be buffer 212)))
           (opt-mipv6-home-address (unwrap (slice buffer 214 16)))
           (opt-ilnp-nonce (unwrap (slice buffer 214 1)))
           (opt-lio-len (unwrap (read-u8 buffer 214)))
           (opt-lio-id (unwrap (slice buffer 215 1)))
           (opt-mpl-flag (unwrap (read-u8 buffer 215)))
           (opt-mpl-flag-m (extract-bits opt-mpl-flag 0x20 5))
           (opt-mpl-flag-v (extract-bits opt-mpl-flag 0x10 4))
           (opt-mpl-flag-rsv (extract-bits opt-mpl-flag 0xF 0))
           (opt-mpl-sequence (unwrap (read-u8 buffer 216)))
           (opt-mpl-seed-id (unwrap (slice buffer 217 1)))
           (opt-dff-flags (unwrap (read-u8 buffer 217)))
           (opt-dff-flag-ver (extract-bits opt-dff-flags 0xC0 6))
           (opt-dff-flag-dup (extract-bits opt-dff-flags 0x20 5))
           (opt-dff-flag-ret (extract-bits opt-dff-flags 0x10 4))
           (opt-dff-flag-rsv (extract-bits opt-dff-flags 0xF 0))
           (opt-dff-seqnum (unwrap (read-u16be buffer 218)))
           (opt-unknown (unwrap (slice buffer 220 1)))
           (opt-type-change (unwrap (read-u8 buffer 223)))
           (opt-type-rest (unwrap (read-u8 buffer 223)))
           (opt-length (unwrap (read-u8 buffer 224)))
           (opt-experimental (unwrap (slice buffer 225 1)))
           (opt-unknown-data (unwrap (slice buffer 225 1)))
           (addr-space (unwrap (slice buffer 229 1)))
           (multicast-flags (unwrap (read-u16be buffer 229)))
           (multicast-flags-reserved (extract-bits multicast-flags 0x80 7))
           (multicast-flags-embed-rp (extract-bits multicast-flags 0x40 6))
           (multicast-flags-network-prefix (extract-bits multicast-flags 0x20 5))
           (multicast-flags-transient (extract-bits multicast-flags 0x10 4))
           (addr-special-purpose (unwrap (slice buffer 229 1)))
           (addr-special-purpose-source (unwrap (read-u8 buffer 229)))
           (addr-special-purpose-destination (unwrap (read-u8 buffer 229)))
           (addr-special-purpose-forwardable (unwrap (read-u8 buffer 229)))
           (addr-special-purpose-global (unwrap (read-u8 buffer 229)))
           (addr-special-purpose-reserved (unwrap (read-u8 buffer 229)))
           (addr (unwrap (slice buffer 229 16)))
           (host (unwrap (slice buffer 229 1)))
           (embed-ipv4-prefix (unwrap (slice buffer 229 1)))
           (embed-ipv4-u (unwrap (slice buffer 229 1)))
           )

      (ok (list
        (cons 'stream (list (cons 'raw stream) (cons 'formatted (number->string stream))))
        (cons 'routing-src-reserved (list (cons 'raw routing-src-reserved) (cons 'formatted (fmt-bytes routing-src-reserved))))
        (cons 'routing-mipv6-reserved (list (cons 'raw routing-mipv6-reserved) (cons 'formatted (fmt-bytes routing-mipv6-reserved))))
        (cons 'routing-rpl-cmprI (list (cons 'raw routing-rpl-cmprI) (cons 'formatted (number->string routing-rpl-cmprI))))
        (cons 'routing-rpl-cmprE (list (cons 'raw routing-rpl-cmprE) (cons 'formatted (number->string routing-rpl-cmprE))))
        (cons 'routing-rpl-pad (list (cons 'raw routing-rpl-pad) (cons 'formatted (number->string routing-rpl-pad))))
        (cons 'routing-rpl-reserved (list (cons 'raw routing-rpl-reserved) (cons 'formatted (number->string routing-rpl-reserved))))
        (cons 'routing-rpl-addr-count (list (cons 'raw routing-rpl-addr-count) (cons 'formatted (number->string routing-rpl-addr-count))))
        (cons 'routing-srh-last-entry (list (cons 'raw routing-srh-last-entry) (cons 'formatted (number->string routing-srh-last-entry))))
        (cons 'routing-crh16-segment-id (list (cons 'raw routing-crh16-segment-id) (cons 'formatted (number->string routing-crh16-segment-id))))
        (cons 'routing-crh32-segment-id (list (cons 'raw routing-crh32-segment-id) (cons 'formatted (number->string routing-crh32-segment-id))))
        (cons 'version (list (cons 'raw version) (cons 'formatted (number->string version))))
        (cons 'tclass (list (cons 'raw tclass) (cons 'formatted (fmt-hex tclass))))
        (cons 'plen (list (cons 'raw plen) (cons 'formatted (number->string plen))))
        (cons 'hlim (list (cons 'raw hlim) (cons 'formatted (number->string hlim))))
        (cons 'routing-srh-flags (list (cons 'raw routing-srh-flags) (cons 'formatted (fmt-hex routing-srh-flags))))
        (cons 'routing-len (list (cons 'raw routing-len) (cons 'formatted (number->string routing-len))))
        (cons 'fraghdr-reserved-octet (list (cons 'raw fraghdr-reserved-octet) (cons 'formatted (fmt-hex fraghdr-reserved-octet))))
        (cons 'routing-srh-tag (list (cons 'raw routing-srh-tag) (cons 'formatted (fmt-bytes routing-srh-tag))))
        (cons 'fraghdr-offset (list (cons 'raw fraghdr-offset) (cons 'formatted (number->string fraghdr-offset))))
        (cons 'fraghdr-reserved-bits (list (cons 'raw fraghdr-reserved-bits) (cons 'formatted (number->string fraghdr-reserved-bits))))
        (cons 'fraghdr-more (list (cons 'raw fraghdr-more) (cons 'formatted (if (= fraghdr-more 0) "False" "True"))))
        (cons 'routing-segleft (list (cons 'raw routing-segleft) (cons 'formatted (number->string routing-segleft))))
        (cons 'routing-rpl-addr (list (cons 'raw routing-rpl-addr) (cons 'formatted (fmt-bytes routing-rpl-addr))))
        (cons 'routing-unknown-data (list (cons 'raw routing-unknown-data) (cons 'formatted (fmt-bytes routing-unknown-data))))
        (cons 'fraghdr-ident (list (cons 'raw fraghdr-ident) (cons 'formatted (fmt-hex fraghdr-ident))))
        (cons 'opt-jumbo (list (cons 'raw opt-jumbo) (cons 'formatted (number->string opt-jumbo))))
        (cons 'opt-rpl-flag (list (cons 'raw opt-rpl-flag) (cons 'formatted (fmt-hex opt-rpl-flag))))
        (cons 'opt-rpl-flag-o (list (cons 'raw opt-rpl-flag-o) (cons 'formatted (if (= opt-rpl-flag-o 0) "Not set" "Set"))))
        (cons 'opt-rpl-flag-r (list (cons 'raw opt-rpl-flag-r) (cons 'formatted (if (= opt-rpl-flag-r 0) "Not set" "Set"))))
        (cons 'opt-rpl-flag-f (list (cons 'raw opt-rpl-flag-f) (cons 'formatted (if (= opt-rpl-flag-f 0) "Not set" "Set"))))
        (cons 'opt-rpl-flag-rsv (list (cons 'raw opt-rpl-flag-rsv) (cons 'formatted (if (= opt-rpl-flag-rsv 0) "Not set" "Set"))))
        (cons 'opt-rpl-instance-id (list (cons 'raw opt-rpl-instance-id) (cons 'formatted (fmt-hex opt-rpl-instance-id))))
        (cons 'opt-rpl-senderrank (list (cons 'raw opt-rpl-senderrank) (cons 'formatted (fmt-hex opt-rpl-senderrank))))
        (cons 'opt-tel (list (cons 'raw opt-tel) (cons 'formatted (number->string opt-tel))))
        (cons 'opt-pmtu-min (list (cons 'raw opt-pmtu-min) (cons 'formatted (number->string opt-pmtu-min))))
        (cons 'opt-pmtu-rtn (list (cons 'raw opt-pmtu-rtn) (cons 'formatted (number->string opt-pmtu-rtn))))
        (cons 'opt-pmtu-rtn-flag (list (cons 'raw opt-pmtu-rtn-flag) (cons 'formatted (number->string opt-pmtu-rtn-flag))))
        (cons 'opt-apn-flags (list (cons 'raw opt-apn-flags) (cons 'formatted (fmt-hex opt-apn-flags))))
        (cons 'opt-apn-param-type (list (cons 'raw opt-apn-param-type) (cons 'formatted (fmt-hex opt-apn-param-type))))
        (cons 'opt-apn-id-part1 (list (cons 'raw opt-apn-id-part1) (cons 'formatted (fmt-hex opt-apn-id-part1))))
        (cons 'opt-apn-id-part2 (list (cons 'raw opt-apn-id-part2) (cons 'formatted (fmt-hex opt-apn-id-part2))))
        (cons 'opt-apn-id-part3 (list (cons 'raw opt-apn-id-part3) (cons 'formatted (fmt-hex opt-apn-id-part3))))
        (cons 'opt-apn-id-part4 (list (cons 'raw opt-apn-id-part4) (cons 'formatted (fmt-hex opt-apn-id-part4))))
        (cons 'opt-qs-ttl (list (cons 'raw opt-qs-ttl) (cons 'formatted (number->string opt-qs-ttl))))
        (cons 'opt-qs-ttl-diff (list (cons 'raw opt-qs-ttl-diff) (cons 'formatted (number->string opt-qs-ttl-diff))))
        (cons 'opt-qs-unused (list (cons 'raw opt-qs-unused) (cons 'formatted (number->string opt-qs-unused))))
        (cons 'opt-qs-nonce (list (cons 'raw opt-qs-nonce) (cons 'formatted (fmt-hex opt-qs-nonce))))
        (cons 'opt-qs-reserved (list (cons 'raw opt-qs-reserved) (cons 'formatted (fmt-hex opt-qs-reserved))))
        (cons 'opt-ioam-trace-node-id (list (cons 'raw opt-ioam-trace-node-id) (cons 'formatted (fmt-hex opt-ioam-trace-node-id))))
        (cons 'opt-ioam-trace-node-iif (list (cons 'raw opt-ioam-trace-node-iif) (cons 'formatted (fmt-hex opt-ioam-trace-node-iif))))
        (cons 'opt-ioam-trace-node-eif (list (cons 'raw opt-ioam-trace-node-eif) (cons 'formatted (fmt-hex opt-ioam-trace-node-eif))))
        (cons 'opt-ioam-trace-node-tss (list (cons 'raw opt-ioam-trace-node-tss) (cons 'formatted (fmt-hex opt-ioam-trace-node-tss))))
        (cons 'opt-ioam-trace-node-tsf (list (cons 'raw opt-ioam-trace-node-tsf) (cons 'formatted (fmt-hex opt-ioam-trace-node-tsf))))
        (cons 'opt-ioam-trace-node-trdelay (list (cons 'raw opt-ioam-trace-node-trdelay) (cons 'formatted (fmt-hex opt-ioam-trace-node-trdelay))))
        (cons 'opt-ioam-trace-node-nsdata (list (cons 'raw opt-ioam-trace-node-nsdata) (cons 'formatted (fmt-hex opt-ioam-trace-node-nsdata))))
        (cons 'opt-ioam-trace-node-qdepth (list (cons 'raw opt-ioam-trace-node-qdepth) (cons 'formatted (fmt-hex opt-ioam-trace-node-qdepth))))
        (cons 'opt-ioam-trace-node-csum (list (cons 'raw opt-ioam-trace-node-csum) (cons 'formatted (fmt-hex opt-ioam-trace-node-csum))))
        (cons 'opt-ioam-trace-node-hlim (list (cons 'raw opt-ioam-trace-node-hlim) (cons 'formatted (number->string opt-ioam-trace-node-hlim))))
        (cons 'opt-ioam-trace-node-id-wide (list (cons 'raw opt-ioam-trace-node-id-wide) (cons 'formatted (fmt-hex opt-ioam-trace-node-id-wide))))
        (cons 'opt-ioam-trace-node-iif-wide (list (cons 'raw opt-ioam-trace-node-iif-wide) (cons 'formatted (fmt-hex opt-ioam-trace-node-iif-wide))))
        (cons 'opt-ioam-trace-node-eif-wide (list (cons 'raw opt-ioam-trace-node-eif-wide) (cons 'formatted (fmt-hex opt-ioam-trace-node-eif-wide))))
        (cons 'opt-ioam-trace-node-nsdata-wide (list (cons 'raw opt-ioam-trace-node-nsdata-wide) (cons 'formatted (fmt-hex opt-ioam-trace-node-nsdata-wide))))
        (cons 'opt-ioam-trace-node-bufoccup (list (cons 'raw opt-ioam-trace-node-bufoccup) (cons 'formatted (fmt-hex opt-ioam-trace-node-bufoccup))))
        (cons 'opt-ioam-trace-node-undefined (list (cons 'raw opt-ioam-trace-node-undefined) (cons 'formatted (fmt-hex opt-ioam-trace-node-undefined))))
        (cons 'opt-ioam-trace-ns (list (cons 'raw opt-ioam-trace-ns) (cons 'formatted (number->string opt-ioam-trace-ns))))
        (cons 'opt-ioam-trace-flags (list (cons 'raw opt-ioam-trace-flags) (cons 'formatted (fmt-hex opt-ioam-trace-flags))))
        (cons 'opt-ioam-trace-flag-o (list (cons 'raw opt-ioam-trace-flag-o) (cons 'formatted (if (= opt-ioam-trace-flag-o 0) "Not set" "Set"))))
        (cons 'opt-ioam-trace-flag-l (list (cons 'raw opt-ioam-trace-flag-l) (cons 'formatted (if (= opt-ioam-trace-flag-l 0) "Not set" "Set"))))
        (cons 'opt-ioam-trace-flag-a (list (cons 'raw opt-ioam-trace-flag-a) (cons 'formatted (if (= opt-ioam-trace-flag-a 0) "Not set" "Set"))))
        (cons 'opt-ioam-trace-flag-rsv (list (cons 'raw opt-ioam-trace-flag-rsv) (cons 'formatted (if (= opt-ioam-trace-flag-rsv 0) "Not set" "Set"))))
        (cons 'opt-ioam-trace-free-space (list (cons 'raw opt-ioam-trace-free-space) (cons 'formatted (fmt-bytes opt-ioam-trace-free-space))))
        (cons 'opt-ioam-trace-node-oss-len (list (cons 'raw opt-ioam-trace-node-oss-len) (cons 'formatted (number->string opt-ioam-trace-node-oss-len))))
        (cons 'opt-ioam-trace-node-oss-scid (list (cons 'raw opt-ioam-trace-node-oss-scid) (cons 'formatted (fmt-hex opt-ioam-trace-node-oss-scid))))
        (cons 'opt-ioam-trace-node-oss-data (list (cons 'raw opt-ioam-trace-node-oss-data) (cons 'formatted (fmt-bytes opt-ioam-trace-node-oss-data))))
        (cons 'opt-ioam-dex-ns (list (cons 'raw opt-ioam-dex-ns) (cons 'formatted (number->string opt-ioam-dex-ns))))
        (cons 'opt-ioam-dex-flags (list (cons 'raw opt-ioam-dex-flags) (cons 'formatted (number->string opt-ioam-dex-flags))))
        (cons 'opt-ioam-dex-extflags (list (cons 'raw opt-ioam-dex-extflags) (cons 'formatted (fmt-hex opt-ioam-dex-extflags))))
        (cons 'opt-ioam-dex-extflag-flag-rsv (list (cons 'raw opt-ioam-dex-extflag-flag-rsv) (cons 'formatted (if (= opt-ioam-dex-extflag-flag-rsv 0) "Not set" "Set"))))
        (cons 'opt-ioam-dex-extflag-flag-seqnum (list (cons 'raw opt-ioam-dex-extflag-flag-seqnum) (cons 'formatted (if (= opt-ioam-dex-extflag-flag-seqnum 0) "Not set" "Set"))))
        (cons 'opt-ioam-dex-extflag-flag-flowid (list (cons 'raw opt-ioam-dex-extflag-flag-flowid) (cons 'formatted (if (= opt-ioam-dex-extflag-flag-flowid 0) "Not set" "Set"))))
        (cons 'opt-ioam-trace-type (list (cons 'raw opt-ioam-trace-type) (cons 'formatted (fmt-hex opt-ioam-trace-type))))
        (cons 'opt-ioam-trace-type-bit0 (list (cons 'raw opt-ioam-trace-type-bit0) (cons 'formatted (if (= opt-ioam-trace-type-bit0 0) "Not set" "Set"))))
        (cons 'opt-ioam-trace-type-bit1 (list (cons 'raw opt-ioam-trace-type-bit1) (cons 'formatted (if (= opt-ioam-trace-type-bit1 0) "Not set" "Set"))))
        (cons 'opt-ioam-trace-type-bit2 (list (cons 'raw opt-ioam-trace-type-bit2) (cons 'formatted (if (= opt-ioam-trace-type-bit2 0) "Not set" "Set"))))
        (cons 'opt-ioam-trace-type-bit3 (list (cons 'raw opt-ioam-trace-type-bit3) (cons 'formatted (if (= opt-ioam-trace-type-bit3 0) "Not set" "Set"))))
        (cons 'opt-ioam-trace-type-bit4 (list (cons 'raw opt-ioam-trace-type-bit4) (cons 'formatted (if (= opt-ioam-trace-type-bit4 0) "Not set" "Set"))))
        (cons 'opt-ioam-trace-type-bit5 (list (cons 'raw opt-ioam-trace-type-bit5) (cons 'formatted (if (= opt-ioam-trace-type-bit5 0) "Not set" "Set"))))
        (cons 'opt-ioam-trace-type-bit6 (list (cons 'raw opt-ioam-trace-type-bit6) (cons 'formatted (if (= opt-ioam-trace-type-bit6 0) "Not set" "Set"))))
        (cons 'opt-ioam-trace-type-bit7 (list (cons 'raw opt-ioam-trace-type-bit7) (cons 'formatted (if (= opt-ioam-trace-type-bit7 0) "Not set" "Set"))))
        (cons 'opt-ioam-trace-type-bit8 (list (cons 'raw opt-ioam-trace-type-bit8) (cons 'formatted (if (= opt-ioam-trace-type-bit8 0) "Not set" "Set"))))
        (cons 'opt-ioam-trace-type-bit9 (list (cons 'raw opt-ioam-trace-type-bit9) (cons 'formatted (if (= opt-ioam-trace-type-bit9 0) "Not set" "Set"))))
        (cons 'opt-ioam-trace-type-bit10 (list (cons 'raw opt-ioam-trace-type-bit10) (cons 'formatted (if (= opt-ioam-trace-type-bit10 0) "Not set" "Set"))))
        (cons 'opt-ioam-trace-type-bit11 (list (cons 'raw opt-ioam-trace-type-bit11) (cons 'formatted (if (= opt-ioam-trace-type-bit11 0) "Not set" "Set"))))
        (cons 'opt-ioam-trace-type-undef (list (cons 'raw opt-ioam-trace-type-undef) (cons 'formatted (if (= opt-ioam-trace-type-undef 0) "Not set" "Set"))))
        (cons 'opt-ioam-trace-type-bit22 (list (cons 'raw opt-ioam-trace-type-bit22) (cons 'formatted (if (= opt-ioam-trace-type-bit22 0) "Not set" "Set"))))
        (cons 'opt-ioam-trace-type-rsv (list (cons 'raw opt-ioam-trace-type-rsv) (cons 'formatted (if (= opt-ioam-trace-type-rsv 0) "Not set" "Set"))))
        (cons 'opt-ioam-trace-rsv (list (cons 'raw opt-ioam-trace-rsv) (cons 'formatted (number->string opt-ioam-trace-rsv))))
        (cons 'opt-ioam-dex-extflag-flowid (list (cons 'raw opt-ioam-dex-extflag-flowid) (cons 'formatted (number->string opt-ioam-dex-extflag-flowid))))
        (cons 'opt-ioam-dex-extflag-seqnum (list (cons 'raw opt-ioam-dex-extflag-seqnum) (cons 'formatted (number->string opt-ioam-dex-extflag-seqnum))))
        (cons 'opt-ioam-rsv (list (cons 'raw opt-ioam-rsv) (cons 'formatted (number->string opt-ioam-rsv))))
        (cons 'opt-tpf-information (list (cons 'raw opt-tpf-information) (cons 'formatted (fmt-hex opt-tpf-information))))
        (cons 'opt-calipso-doi (list (cons 'raw opt-calipso-doi) (cons 'formatted (number->string opt-calipso-doi))))
        (cons 'opt-calipso-cmpt-length (list (cons 'raw opt-calipso-cmpt-length) (cons 'formatted (number->string opt-calipso-cmpt-length))))
        (cons 'opt-calipso-sens-level (list (cons 'raw opt-calipso-sens-level) (cons 'formatted (number->string opt-calipso-sens-level))))
        (cons 'opt-calipso-cmpt-bitmap (list (cons 'raw opt-calipso-cmpt-bitmap) (cons 'formatted (fmt-bytes opt-calipso-cmpt-bitmap))))
        (cons 'opt-smf-dpd-hash-bit (list (cons 'raw opt-smf-dpd-hash-bit) (cons 'formatted (number->string opt-smf-dpd-hash-bit))))
        (cons 'opt-smf-dpd-hav (list (cons 'raw opt-smf-dpd-hav) (cons 'formatted (fmt-bytes opt-smf-dpd-hav))))
        (cons 'opt-smf-dpd-tid-len (list (cons 'raw opt-smf-dpd-tid-len) (cons 'formatted (number->string opt-smf-dpd-tid-len))))
        (cons 'opt-smf-dpd-tagger-id (list (cons 'raw opt-smf-dpd-tagger-id) (cons 'formatted (fmt-bytes opt-smf-dpd-tagger-id))))
        (cons 'opt-smf-dpd-ident (list (cons 'raw opt-smf-dpd-ident) (cons 'formatted (fmt-bytes opt-smf-dpd-ident))))
        (cons 'opt-pdm-scale-dtlr (list (cons 'raw opt-pdm-scale-dtlr) (cons 'formatted (number->string opt-pdm-scale-dtlr))))
        (cons 'opt-pdm-scale-dtls (list (cons 'raw opt-pdm-scale-dtls) (cons 'formatted (number->string opt-pdm-scale-dtls))))
        (cons 'opt-pdm-psn-this-pkt (list (cons 'raw opt-pdm-psn-this-pkt) (cons 'formatted (number->string opt-pdm-psn-this-pkt))))
        (cons 'opt-pdm-psn-last-recv (list (cons 'raw opt-pdm-psn-last-recv) (cons 'formatted (number->string opt-pdm-psn-last-recv))))
        (cons 'opt-pdm-delta-last-recv (list (cons 'raw opt-pdm-delta-last-recv) (cons 'formatted (number->string opt-pdm-delta-last-recv))))
        (cons 'opt-pdm-delta-last-sent (list (cons 'raw opt-pdm-delta-last-sent) (cons 'formatted (number->string opt-pdm-delta-last-sent))))
        (cons 'opt-mipv6-home-address (list (cons 'raw opt-mipv6-home-address) (cons 'formatted (fmt-ipv6-address opt-mipv6-home-address))))
        (cons 'opt-ilnp-nonce (list (cons 'raw opt-ilnp-nonce) (cons 'formatted (fmt-bytes opt-ilnp-nonce))))
        (cons 'opt-lio-len (list (cons 'raw opt-lio-len) (cons 'formatted (number->string opt-lio-len))))
        (cons 'opt-lio-id (list (cons 'raw opt-lio-id) (cons 'formatted (utf8->string opt-lio-id))))
        (cons 'opt-mpl-flag (list (cons 'raw opt-mpl-flag) (cons 'formatted (fmt-hex opt-mpl-flag))))
        (cons 'opt-mpl-flag-m (list (cons 'raw opt-mpl-flag-m) (cons 'formatted (if (= opt-mpl-flag-m 0) "Not set" "Set"))))
        (cons 'opt-mpl-flag-v (list (cons 'raw opt-mpl-flag-v) (cons 'formatted (if (= opt-mpl-flag-v 0) "Not set" "Set"))))
        (cons 'opt-mpl-flag-rsv (list (cons 'raw opt-mpl-flag-rsv) (cons 'formatted (if (= opt-mpl-flag-rsv 0) "Not set" "Set"))))
        (cons 'opt-mpl-sequence (list (cons 'raw opt-mpl-sequence) (cons 'formatted (fmt-hex opt-mpl-sequence))))
        (cons 'opt-mpl-seed-id (list (cons 'raw opt-mpl-seed-id) (cons 'formatted (fmt-bytes opt-mpl-seed-id))))
        (cons 'opt-dff-flags (list (cons 'raw opt-dff-flags) (cons 'formatted (fmt-hex opt-dff-flags))))
        (cons 'opt-dff-flag-ver (list (cons 'raw opt-dff-flag-ver) (cons 'formatted (if (= opt-dff-flag-ver 0) "Not set" "Set"))))
        (cons 'opt-dff-flag-dup (list (cons 'raw opt-dff-flag-dup) (cons 'formatted (if (= opt-dff-flag-dup 0) "Not set" "Set"))))
        (cons 'opt-dff-flag-ret (list (cons 'raw opt-dff-flag-ret) (cons 'formatted (if (= opt-dff-flag-ret 0) "Not set" "Set"))))
        (cons 'opt-dff-flag-rsv (list (cons 'raw opt-dff-flag-rsv) (cons 'formatted (if (= opt-dff-flag-rsv 0) "Not set" "Set"))))
        (cons 'opt-dff-seqnum (list (cons 'raw opt-dff-seqnum) (cons 'formatted (number->string opt-dff-seqnum))))
        (cons 'opt-unknown (list (cons 'raw opt-unknown) (cons 'formatted (fmt-bytes opt-unknown))))
        (cons 'opt-type-change (list (cons 'raw opt-type-change) (cons 'formatted (if (= opt-type-change 0) "False" "True"))))
        (cons 'opt-type-rest (list (cons 'raw opt-type-rest) (cons 'formatted (fmt-hex opt-type-rest))))
        (cons 'opt-length (list (cons 'raw opt-length) (cons 'formatted (number->string opt-length))))
        (cons 'opt-experimental (list (cons 'raw opt-experimental) (cons 'formatted (fmt-bytes opt-experimental))))
        (cons 'opt-unknown-data (list (cons 'raw opt-unknown-data) (cons 'formatted (fmt-bytes opt-unknown-data))))
        (cons 'addr-space (list (cons 'raw addr-space) (cons 'formatted (utf8->string addr-space))))
        (cons 'multicast-flags (list (cons 'raw multicast-flags) (cons 'formatted (fmt-hex multicast-flags))))
        (cons 'multicast-flags-reserved (list (cons 'raw multicast-flags-reserved) (cons 'formatted (if (= multicast-flags-reserved 0) "Not set" "Set"))))
        (cons 'multicast-flags-embed-rp (list (cons 'raw multicast-flags-embed-rp) (cons 'formatted (if (= multicast-flags-embed-rp 0) "Not set" "Set"))))
        (cons 'multicast-flags-network-prefix (list (cons 'raw multicast-flags-network-prefix) (cons 'formatted (if (= multicast-flags-network-prefix 0) "Not set" "Set"))))
        (cons 'multicast-flags-transient (list (cons 'raw multicast-flags-transient) (cons 'formatted (if (= multicast-flags-transient 0) "Not set" "Set"))))
        (cons 'addr-special-purpose (list (cons 'raw addr-special-purpose) (cons 'formatted (utf8->string addr-special-purpose))))
        (cons 'addr-special-purpose-source (list (cons 'raw addr-special-purpose-source) (cons 'formatted (number->string addr-special-purpose-source))))
        (cons 'addr-special-purpose-destination (list (cons 'raw addr-special-purpose-destination) (cons 'formatted (number->string addr-special-purpose-destination))))
        (cons 'addr-special-purpose-forwardable (list (cons 'raw addr-special-purpose-forwardable) (cons 'formatted (number->string addr-special-purpose-forwardable))))
        (cons 'addr-special-purpose-global (list (cons 'raw addr-special-purpose-global) (cons 'formatted (number->string addr-special-purpose-global))))
        (cons 'addr-special-purpose-reserved (list (cons 'raw addr-special-purpose-reserved) (cons 'formatted (number->string addr-special-purpose-reserved))))
        (cons 'addr (list (cons 'raw addr) (cons 'formatted (fmt-ipv6-address addr))))
        (cons 'host (list (cons 'raw host) (cons 'formatted (utf8->string host))))
        (cons 'embed-ipv4-prefix (list (cons 'raw embed-ipv4-prefix) (cons 'formatted (fmt-bytes embed-ipv4-prefix))))
        (cons 'embed-ipv4-u (list (cons 'raw embed-ipv4-u) (cons 'formatted (fmt-bytes embed-ipv4-u))))
        )))

    (catch (e)
      (err (str "IPV6 parse error: " e)))))

;; dissect-ipv6: parse IPV6 from bytevector
;; Returns (ok fields-alist) or (err message)