;; packet-lltd.c
;; Routines for LLTD dissection
;; Copyright 2012, Michael Mann
;;
;; Wireshark - Network traffic analyzer
;; By Gerald Combs <gerald@wireshark.org>
;; Copyright 1998 Gerald Combs
;;
;; SPDX-License-Identifier: GPL-2.0-or-later
;;

;; jerboa-ethereal/dissectors/lltd.ss
;; Auto-generated from wireshark/epan/dissectors/packet-lltd.c

(import (jerboa prelude))

;; ── Protocol Helpers ─────────────────────────────────────────────────
(def (read-u8 buf offset)
  (if (>= offset (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u8-ref buf offset))))

(def (read-u16be buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness big)))))

(def (read-u24be buf offset)
  (if (> (+ offset 3) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (+ (* (bytevector-u8-ref buf offset) 65536)
             (* (bytevector-u8-ref buf (+ offset 1)) 256)
             (bytevector-u8-ref buf (+ offset 2))))))

(def (read-u32be buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness big)))))

(def (read-u16le buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness little)))))

(def (read-u32le buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness little)))))

(def (read-u64be buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness big)))))

(def (read-u64le buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness little)))))

(def (slice buf offset len)
  (if (> (+ offset len) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (let ((result (make-bytevector len)))
            (bytevector-copy! buf offset result 0 len)
            result))))

(def (extract-bits val mask shift)
  (bitwise-arithmetic-shift-right (bitwise-and val mask) shift))

(def (fmt-ipv4 addr)
  (let ((b0 (bitwise-arithmetic-shift-right addr 24))
        (b1 (bitwise-and (bitwise-arithmetic-shift-right addr 16) 255))
        (b2 (bitwise-and (bitwise-arithmetic-shift-right addr 8) 255))
        (b3 (bitwise-and addr 255)))
    (str b0 "." b1 "." b2 "." b3)))

(def (fmt-mac bytes)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bytes))
    ":"))

(def (fmt-hex val)
  (str "0x" (number->string val 16)))

(def (fmt-oct val)
  (str "0" (number->string val 8)))

(def (fmt-port port)
  (number->string port))

(def (fmt-bytes bv)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bv))
    " "))

(def (fmt-ipv6-address bytes)
  (let loop ((i 0) (parts '()))
    (if (>= i 16)
        (string-join (reverse parts) ":")
        (loop (+ i 2)
              (cons (let ((w (+ (* (bytevector-u8-ref bytes i) 256)
                                (bytevector-u8-ref bytes (+ i 1)))))
                      (number->string w 16))
                    parts)))))

;; ── Dissector ──────────────────────────────────────────────────────
(def (dissect-lltd buffer)
  "Link Layer Topology Discovery"
  (try
    (let* (
           (version (unwrap (read-u8 buffer 0)))
           (tlv-length (unwrap (read-u8 buffer 0)))
           (host-id (unwrap (slice buffer 0 6)))
           (char-p (unwrap (read-u8 buffer 0)))
           (char-x (unwrap (read-u8 buffer 0)))
           (char-f (unwrap (read-u8 buffer 0)))
           (char-m (unwrap (read-u8 buffer 0)))
           (char-l (unwrap (read-u8 buffer 0)))
           (char-reserved (unwrap (read-u32be buffer 0)))
           (physical-medium (unwrap (read-u32be buffer 0)))
           (bssid (unwrap (slice buffer 0 6)))
           (ssid (unwrap (slice buffer 0 1)))
           (ipv4-address (unwrap (read-u32be buffer 0)))
           (ipv6-address (unwrap (slice buffer 0 16)))
           (max-operation-rate (unwrap (read-u16be buffer 0)))
           (performance-count-freq (unwrap (read-u64be buffer 0)))
           (link-speed (unwrap (read-u32be buffer 0)))
           (rssi (unwrap (read-u32be buffer 0)))
           (device-uuid (unwrap (slice buffer 0 22)))
           (qos-char-e (unwrap (read-u8 buffer 0)))
           (qos-char-q (unwrap (read-u8 buffer 0)))
           (qos-char-p (unwrap (read-u8 buffer 0)))
           (qos-char-reserved (unwrap (read-u32be buffer 0)))
           (sees-list-working-set (unwrap (read-u16be buffer 0)))
           (discovery-real-dest-addr (unwrap (slice buffer 0 6)))
           (discovery-real-src-addr (unwrap (slice buffer 0 6)))
           (discovery-xid (unwrap (read-u16be buffer 0)))
           (discovery-seq-num (unwrap (read-u16be buffer 0)))
           (discover-gen-num (unwrap (read-u16be buffer 0)))
           (discover-num-stations (unwrap (read-u16be buffer 0)))
           (reserved (unwrap (read-u8 buffer 2)))
           (hello-gen-num (unwrap (read-u16be buffer 6)))
           (hello-current-address (unwrap (slice buffer 6 6)))
           (hello-apparent-address (unwrap (slice buffer 6 6)))
           (emit-num-descs (unwrap (read-u16be buffer 6)))
           (queryresp-more-descs (unwrap (read-u8 buffer 20)))
           (queryresp-memory-descs (unwrap (read-u8 buffer 20)))
           (queryresp-num-descs (unwrap (read-u16be buffer 20)))
           (flat-crc-bytes (unwrap (read-u32be buffer 40)))
           (flat-crc-packets (unwrap (read-u8 buffer 40)))
           (query-large-tlv-offset (unwrap (read-u24be buffer 40)))
           (querylargeresp-more-descs (unwrap (read-u8 buffer 40)))
           (querylargeresp-memory-descs (unwrap (read-u8 buffer 40)))
           (querylargeresp-num-descs (unwrap (read-u16be buffer 40)))
           (querylargeresp-data (unwrap (slice buffer 40 1)))
           (qos-real-dest-addr (unwrap (slice buffer 40 6)))
           (qos-real-src-addr (unwrap (slice buffer 40 6)))
           (qos-seq-num (unwrap (read-u16be buffer 40)))
           (qos-ready-sink-link-speed (unwrap (read-u32be buffer 40)))
           (qos-ready-perf-count-freq (unwrap (read-u64be buffer 40)))
           (qos-probe-controller-transmit-timestamp (unwrap (read-u64be buffer 40)))
           (qos-probe-sink-receive-timestamp (unwrap (read-u64be buffer 40)))
           (qos-probe-sink-transmit-timestamp (unwrap (read-u64be buffer 40)))
           (qos-probe-packet-id (unwrap (read-u8 buffer 40)))
           (qos-probe-t (unwrap (read-u8 buffer 40)))
           (qos-probe-8021p-value (unwrap (read-u8 buffer 40)))
           (qos-probe-payload (unwrap (slice buffer 40 5)))
           (qos-query-resp-r (unwrap (read-u8 buffer 40)))
           (qos-query-resp-e (unwrap (read-u8 buffer 40)))
           (qos-query-resp-num-events (unwrap (read-u16be buffer 40)))
           (qos-count-snapshot-history (unwrap (read-u8 buffer 58)))
           (qos-counter-result-subsec-span (unwrap (read-u8 buffer 58)))
           (qos-counter-result-byte-scale (unwrap (read-u8 buffer 58)))
           (qos-counter-result-packet-scale (unwrap (read-u8 buffer 58)))
           (qos-counter-result-history-size (unwrap (read-u8 buffer 58)))
           )

      (ok (list
        (cons 'version (list (cons 'raw version) (cons 'formatted (number->string version))))
        (cons 'tlv-length (list (cons 'raw tlv-length) (cons 'formatted (number->string tlv-length))))
        (cons 'host-id (list (cons 'raw host-id) (cons 'formatted (fmt-mac host-id))))
        (cons 'char-p (list (cons 'raw char-p) (cons 'formatted (number->string char-p))))
        (cons 'char-x (list (cons 'raw char-x) (cons 'formatted (number->string char-x))))
        (cons 'char-f (list (cons 'raw char-f) (cons 'formatted (if (= char-f 0) "Half Duplex" "Full Duplex"))))
        (cons 'char-m (list (cons 'raw char-m) (cons 'formatted (if (= char-m 0) "False" "True"))))
        (cons 'char-l (list (cons 'raw char-l) (cons 'formatted (number->string char-l))))
        (cons 'char-reserved (list (cons 'raw char-reserved) (cons 'formatted (fmt-hex char-reserved))))
        (cons 'physical-medium (list (cons 'raw physical-medium) (cons 'formatted (number->string physical-medium))))
        (cons 'bssid (list (cons 'raw bssid) (cons 'formatted (fmt-mac bssid))))
        (cons 'ssid (list (cons 'raw ssid) (cons 'formatted (utf8->string ssid))))
        (cons 'ipv4-address (list (cons 'raw ipv4-address) (cons 'formatted (fmt-ipv4 ipv4-address))))
        (cons 'ipv6-address (list (cons 'raw ipv6-address) (cons 'formatted (fmt-ipv6-address ipv6-address))))
        (cons 'max-operation-rate (list (cons 'raw max-operation-rate) (cons 'formatted (number->string max-operation-rate))))
        (cons 'performance-count-freq (list (cons 'raw performance-count-freq) (cons 'formatted (number->string performance-count-freq))))
        (cons 'link-speed (list (cons 'raw link-speed) (cons 'formatted (number->string link-speed))))
        (cons 'rssi (list (cons 'raw rssi) (cons 'formatted (number->string rssi))))
        (cons 'device-uuid (list (cons 'raw device-uuid) (cons 'formatted (fmt-bytes device-uuid))))
        (cons 'qos-char-e (list (cons 'raw qos-char-e) (cons 'formatted (number->string qos-char-e))))
        (cons 'qos-char-q (list (cons 'raw qos-char-q) (cons 'formatted (if (= qos-char-q 0) "False" "True"))))
        (cons 'qos-char-p (list (cons 'raw qos-char-p) (cons 'formatted (if (= qos-char-p 0) "False" "True"))))
        (cons 'qos-char-reserved (list (cons 'raw qos-char-reserved) (cons 'formatted (fmt-hex qos-char-reserved))))
        (cons 'sees-list-working-set (list (cons 'raw sees-list-working-set) (cons 'formatted (number->string sees-list-working-set))))
        (cons 'discovery-real-dest-addr (list (cons 'raw discovery-real-dest-addr) (cons 'formatted (fmt-mac discovery-real-dest-addr))))
        (cons 'discovery-real-src-addr (list (cons 'raw discovery-real-src-addr) (cons 'formatted (fmt-mac discovery-real-src-addr))))
        (cons 'discovery-xid (list (cons 'raw discovery-xid) (cons 'formatted (fmt-hex discovery-xid))))
        (cons 'discovery-seq-num (list (cons 'raw discovery-seq-num) (cons 'formatted (fmt-hex discovery-seq-num))))
        (cons 'discover-gen-num (list (cons 'raw discover-gen-num) (cons 'formatted (fmt-hex discover-gen-num))))
        (cons 'discover-num-stations (list (cons 'raw discover-num-stations) (cons 'formatted (number->string discover-num-stations))))
        (cons 'reserved (list (cons 'raw reserved) (cons 'formatted (fmt-hex reserved))))
        (cons 'hello-gen-num (list (cons 'raw hello-gen-num) (cons 'formatted (fmt-hex hello-gen-num))))
        (cons 'hello-current-address (list (cons 'raw hello-current-address) (cons 'formatted (fmt-mac hello-current-address))))
        (cons 'hello-apparent-address (list (cons 'raw hello-apparent-address) (cons 'formatted (fmt-mac hello-apparent-address))))
        (cons 'emit-num-descs (list (cons 'raw emit-num-descs) (cons 'formatted (number->string emit-num-descs))))
        (cons 'queryresp-more-descs (list (cons 'raw queryresp-more-descs) (cons 'formatted (number->string queryresp-more-descs))))
        (cons 'queryresp-memory-descs (list (cons 'raw queryresp-memory-descs) (cons 'formatted (number->string queryresp-memory-descs))))
        (cons 'queryresp-num-descs (list (cons 'raw queryresp-num-descs) (cons 'formatted (number->string queryresp-num-descs))))
        (cons 'flat-crc-bytes (list (cons 'raw flat-crc-bytes) (cons 'formatted (number->string flat-crc-bytes))))
        (cons 'flat-crc-packets (list (cons 'raw flat-crc-packets) (cons 'formatted (number->string flat-crc-packets))))
        (cons 'query-large-tlv-offset (list (cons 'raw query-large-tlv-offset) (cons 'formatted (number->string query-large-tlv-offset))))
        (cons 'querylargeresp-more-descs (list (cons 'raw querylargeresp-more-descs) (cons 'formatted (number->string querylargeresp-more-descs))))
        (cons 'querylargeresp-memory-descs (list (cons 'raw querylargeresp-memory-descs) (cons 'formatted (number->string querylargeresp-memory-descs))))
        (cons 'querylargeresp-num-descs (list (cons 'raw querylargeresp-num-descs) (cons 'formatted (number->string querylargeresp-num-descs))))
        (cons 'querylargeresp-data (list (cons 'raw querylargeresp-data) (cons 'formatted (fmt-bytes querylargeresp-data))))
        (cons 'qos-real-dest-addr (list (cons 'raw qos-real-dest-addr) (cons 'formatted (fmt-mac qos-real-dest-addr))))
        (cons 'qos-real-src-addr (list (cons 'raw qos-real-src-addr) (cons 'formatted (fmt-mac qos-real-src-addr))))
        (cons 'qos-seq-num (list (cons 'raw qos-seq-num) (cons 'formatted (fmt-hex qos-seq-num))))
        (cons 'qos-ready-sink-link-speed (list (cons 'raw qos-ready-sink-link-speed) (cons 'formatted (number->string qos-ready-sink-link-speed))))
        (cons 'qos-ready-perf-count-freq (list (cons 'raw qos-ready-perf-count-freq) (cons 'formatted (number->string qos-ready-perf-count-freq))))
        (cons 'qos-probe-controller-transmit-timestamp (list (cons 'raw qos-probe-controller-transmit-timestamp) (cons 'formatted (number->string qos-probe-controller-transmit-timestamp))))
        (cons 'qos-probe-sink-receive-timestamp (list (cons 'raw qos-probe-sink-receive-timestamp) (cons 'formatted (number->string qos-probe-sink-receive-timestamp))))
        (cons 'qos-probe-sink-transmit-timestamp (list (cons 'raw qos-probe-sink-transmit-timestamp) (cons 'formatted (number->string qos-probe-sink-transmit-timestamp))))
        (cons 'qos-probe-packet-id (list (cons 'raw qos-probe-packet-id) (cons 'formatted (fmt-hex qos-probe-packet-id))))
        (cons 'qos-probe-t (list (cons 'raw qos-probe-t) (cons 'formatted (if (= qos-probe-t 0) "False" "True"))))
        (cons 'qos-probe-8021p-value (list (cons 'raw qos-probe-8021p-value) (cons 'formatted (number->string qos-probe-8021p-value))))
        (cons 'qos-probe-payload (list (cons 'raw qos-probe-payload) (cons 'formatted (fmt-bytes qos-probe-payload))))
        (cons 'qos-query-resp-r (list (cons 'raw qos-query-resp-r) (cons 'formatted (number->string qos-query-resp-r))))
        (cons 'qos-query-resp-e (list (cons 'raw qos-query-resp-e) (cons 'formatted (number->string qos-query-resp-e))))
        (cons 'qos-query-resp-num-events (list (cons 'raw qos-query-resp-num-events) (cons 'formatted (number->string qos-query-resp-num-events))))
        (cons 'qos-count-snapshot-history (list (cons 'raw qos-count-snapshot-history) (cons 'formatted (number->string qos-count-snapshot-history))))
        (cons 'qos-counter-result-subsec-span (list (cons 'raw qos-counter-result-subsec-span) (cons 'formatted (number->string qos-counter-result-subsec-span))))
        (cons 'qos-counter-result-byte-scale (list (cons 'raw qos-counter-result-byte-scale) (cons 'formatted (number->string qos-counter-result-byte-scale))))
        (cons 'qos-counter-result-packet-scale (list (cons 'raw qos-counter-result-packet-scale) (cons 'formatted (number->string qos-counter-result-packet-scale))))
        (cons 'qos-counter-result-history-size (list (cons 'raw qos-counter-result-history-size) (cons 'formatted (number->string qos-counter-result-history-size))))
        )))

    (catch (e)
      (err (str "LLTD parse error: " e)))))

;; dissect-lltd: parse LLTD from bytevector
;; Returns (ok fields-alist) or (err message)