;; packet-mpeg-descriptor.c
;; Routines for MPEG2 (ISO/ISO 13818-1 and co) descriptors
;; Copyright 2012, Guy Martin <gmsoft@tuxicoman.be>
;;
;; Wireshark - Network traffic analyzer
;; By Gerald Combs <gerald@wireshark.org>
;; Copyright 1998 Gerald Combs
;;
;; SPDX-License-Identifier: GPL-2.0-or-later
;;

;; jerboa-ethereal/dissectors/mpeg-descriptor.ss
;; Auto-generated from wireshark/epan/dissectors/packet-mpeg_descriptor.c

(import (jerboa prelude))

;; ── Protocol Helpers ─────────────────────────────────────────────────
(def (read-u8 buf offset)
  (if (>= offset (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u8-ref buf offset))))

(def (read-u16be buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness big)))))

(def (read-u24be buf offset)
  (if (> (+ offset 3) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (+ (* (bytevector-u8-ref buf offset) 65536)
             (* (bytevector-u8-ref buf (+ offset 1)) 256)
             (bytevector-u8-ref buf (+ offset 2))))))

(def (read-u32be buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness big)))))

(def (read-u16le buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness little)))))

(def (read-u32le buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness little)))))

(def (read-u64be buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness big)))))

(def (read-u64le buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness little)))))

(def (slice buf offset len)
  (if (> (+ offset len) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (let ((result (make-bytevector len)))
            (bytevector-copy! buf offset result 0 len)
            result))))

(def (extract-bits val mask shift)
  (bitwise-arithmetic-shift-right (bitwise-and val mask) shift))

(def (fmt-ipv4 addr)
  (let ((b0 (bitwise-arithmetic-shift-right addr 24))
        (b1 (bitwise-and (bitwise-arithmetic-shift-right addr 16) 255))
        (b2 (bitwise-and (bitwise-arithmetic-shift-right addr 8) 255))
        (b3 (bitwise-and addr 255)))
    (str b0 "." b1 "." b2 "." b3)))

(def (fmt-mac bytes)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bytes))
    ":"))

(def (fmt-hex val)
  (str "0x" (number->string val 16)))

(def (fmt-oct val)
  (str "0" (number->string val 8)))

(def (fmt-port port)
  (number->string port))

(def (fmt-bytes bv)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bv))
    " "))

(def (fmt-ipv6-address bytes)
  (let loop ((i 0) (parts '()))
    (if (>= i 16)
        (string-join (reverse parts) ":")
        (loop (+ i 2)
              (cons (let ((w (+ (* (bytevector-u8-ref bytes i) 256)
                                (bytevector-u8-ref bytes (+ i 1)))))
                      (number->string w 16))
                    parts)))))

;; ── Dissector ──────────────────────────────────────────────────────
(def (dissect-mpeg-descriptor buffer)
  "MPEG2 Descriptors"
  (try
    (let* (
           (descr-video-stream-frame-rate-code (unwrap (read-u8 buffer 0)))
           (descr-video-stream-mpeg1-only-flag (unwrap (read-u8 buffer 0)))
           (descr-video-stream-constrained-parameter-flag (unwrap (read-u8 buffer 0)))
           (descr-video-stream-still-picture-flag (unwrap (read-u8 buffer 0)))
           (descr-video-stream-profile-and-level-indication (unwrap (read-u8 buffer 1)))
           (descr-video-stream-chroma-format (unwrap (read-u8 buffer 2)))
           (descr-video-stream-frame-rate-extension-flag (unwrap (read-u8 buffer 2)))
           (descr-video-stream-reserved (unwrap (read-u8 buffer 2)))
           (descr-audio-stream-layer (unwrap (read-u8 buffer 2)))
           (descr-audio-stream-reserved (unwrap (read-u8 buffer 2)))
           (descr-reg-add-id-inf (unwrap (read-u8 buffer 6)))
           (descr-ca-system-id (unwrap (read-u16be buffer 6)))
           (descr-ca-reserved (unwrap (read-u16be buffer 8)))
           (descr-ca-pid (unwrap (read-u16be buffer 8)))
           (descr-ca-private (unwrap (slice buffer 10 1)))
           (descr-iso639-lang (unwrap (slice buffer 10 1)))
           (descr-system-clock-external-clock-reference-indicator (unwrap (read-u8 buffer 10)))
           (descr-system-clock-reserved1 (unwrap (read-u8 buffer 10)))
           (descr-system-clock-accuracy-integer (unwrap (read-u8 buffer 10)))
           (descr-system-clock-accuracy-exponent (unwrap (read-u8 buffer 11)))
           (descr-system-clock-reserved2 (unwrap (read-u8 buffer 11)))
           (descr-max-bitrate-reserved (unwrap (read-u24be buffer 11)))
           (descr-max-bitrate (unwrap (read-u24be buffer 11)))
           (descr-smoothing-buffer-reserved1 (unwrap (read-u24be buffer 11)))
           (descr-smoothing-buffer-leak-rate (unwrap (read-u24be buffer 11)))
           (descr-smoothing-buffer-reserved2 (unwrap (read-u24be buffer 14)))
           (descr-smoothing-buffer-size (unwrap (read-u24be buffer 14)))
           (descr-std-reserved (unwrap (read-u8 buffer 14)))
           (descr-std-leak-valid (unwrap (read-u8 buffer 14)))
           (descr-carousel-identifier-id (unwrap (read-u32be buffer 14)))
           (descr-carousel-identifier-module-version (unwrap (read-u8 buffer 19)))
           (descr-carousel-identifier-module-id (unwrap (read-u16be buffer 20)))
           (descr-carousel-identifier-block-size (unwrap (read-u16be buffer 22)))
           (descr-carousel-identifier-module-size (unwrap (read-u32be buffer 24)))
           (descr-carousel-identifier-compression-method (unwrap (read-u8 buffer 28)))
           (descr-carousel-identifier-original-size (unwrap (read-u32be buffer 29)))
           (descr-carousel-identifier-timeout (unwrap (read-u8 buffer 33)))
           (descr-carousel-identifier-object-key-len (unwrap (read-u8 buffer 34)))
           (descr-carousel-identifier-object-key-data (unwrap (slice buffer 35 1)))
           (descr-carousel-identifier-private (unwrap (slice buffer 35 1)))
           (descr-association-tag (unwrap (read-u16be buffer 35)))
           (descr-association-tag-use (unwrap (read-u16be buffer 37)))
           (descr-association-tag-selector-len (unwrap (read-u8 buffer 39)))
           (descr-association-tag-transaction-id (unwrap (read-u32be buffer 39)))
           (descr-association-tag-timeout (unwrap (read-u32be buffer 43)))
           (descr-association-tag-selector-bytes (unwrap (slice buffer 47 1)))
           (descr-association-tag-private-bytes (unwrap (slice buffer 47 1)))
           (descr-avc-vid-profile-idc (unwrap (read-u8 buffer 47)))
           (descr-avc-vid-constraint-set0-flag (unwrap (read-u8 buffer 48)))
           (descr-avc-vid-constraint-set1-flag (unwrap (read-u8 buffer 48)))
           (descr-avc-vid-constraint-set2-flag (unwrap (read-u8 buffer 48)))
           (descr-avc-vid-compatible-flags (unwrap (read-u8 buffer 48)))
           (descr-avc-vid-level-idc (unwrap (read-u8 buffer 49)))
           (descr-avc-vid-still-present (unwrap (read-u8 buffer 50)))
           (descr-avc-vid-24h-picture-flag (unwrap (read-u8 buffer 50)))
           (descr-avc-vid-reserved (unwrap (read-u8 buffer 50)))
           (descr-network-name-descriptor (unwrap (slice buffer 50 1)))
           (descr-iso-extension-data (unwrap (slice buffer 51 1)))
           (descr-service-list-id (unwrap (read-u16be buffer 51)))
           (descr-stuffing (unwrap (slice buffer 54 1)))
           (descr-satellite-delivery-zero (unwrap (read-u8 buffer 60)))
           (descr-satellite-delivery-symbol-rate (unwrap (read-u64be buffer 61)))
           (descr-cable-delivery-frequency (unwrap (read-u64be buffer 64)))
           (descr-cable-delivery-reserved (unwrap (read-u16be buffer 68)))
           (descr-cable-delivery-symbol-rate (unwrap (read-u64be buffer 71)))
           (descr-vbi-data-descr-len (unwrap (read-u8 buffer 75)))
           (descr-vbi-data-reserved1 (unwrap (read-u8 buffer 76)))
           (descr-vbi-data-line-offset (unwrap (read-u8 buffer 76)))
           (descr-vbi-data-reserved2 (unwrap (slice buffer 77 1)))
           (descr-bouquet-name (unwrap (slice buffer 77 1)))
           (descr-service-provider-name-length (unwrap (read-u8 buffer 78)))
           (descr-service-provider (unwrap (slice buffer 79 1)))
           (descr-service-name-length (unwrap (read-u8 buffer 79)))
           (descr-service-name (unwrap (slice buffer 80 1)))
           (descr-country-availability-reserved-future-use (unwrap (read-u8 buffer 80)))
           (descr-country-availability-country-code (unwrap (slice buffer 81 3)))
           (descr-linkage-transport-stream-id (unwrap (read-u16be buffer 84)))
           (descr-linkage-original-network-id (unwrap (read-u16be buffer 86)))
           (descr-linkage-service-id (unwrap (read-u16be buffer 88)))
           (descr-linkage-hand-over-type (unwrap (read-u8 buffer 91)))
           (descr-linkage-reserved1 (unwrap (read-u8 buffer 91)))
           (descr-linkage-network-id (unwrap (read-u16be buffer 92)))
           (descr-linkage-initial-service-id (unwrap (read-u16be buffer 94)))
           (descr-linkage-target-event-id (unwrap (read-u16be buffer 96)))
           (descr-linkage-reserved2 (unwrap (read-u8 buffer 98)))
           (descr-linkage-interactive-network-id (unwrap (read-u16be buffer 98)))
           (descr-linkage-population-id-loop-count (unwrap (read-u8 buffer 100)))
           (descr-linkage-population-id (unwrap (read-u32be buffer 101)))
           (descr-linkage-population-id-base (unwrap (read-u16be buffer 101)))
           (descr-linkage-population-id-mask (unwrap (read-u16be buffer 103)))
           (descr-linkage-private-data-byte (unwrap (slice buffer 105 1)))
           (descr-nvod-reference-tsid (unwrap (read-u16be buffer 105)))
           (descr-nvod-reference-onid (unwrap (read-u16be buffer 107)))
           (descr-nvod-reference-sid (unwrap (read-u16be buffer 109)))
           (descr-time-shifted-service-id (unwrap (read-u16be buffer 111)))
           (descr-short-event-lang-code (unwrap (slice buffer 111 3)))
           (descr-short-event-name-length (unwrap (read-u8 buffer 114)))
           (descr-short-event-name (unwrap (slice buffer 115 1)))
           (descr-short-event-text-length (unwrap (read-u8 buffer 115)))
           (descr-short-event-text (unwrap (slice buffer 116 1)))
           (descr-extended-event-descriptor-number (unwrap (read-u8 buffer 116)))
           (descr-extended-event-last-descriptor-number (unwrap (read-u8 buffer 116)))
           (descr-extended-event-lang-code (unwrap (slice buffer 117 3)))
           (descr-extended-event-length-of-items (unwrap (read-u8 buffer 120)))
           (descr-extended-event-item-description-length (unwrap (read-u8 buffer 121)))
           (descr-extended-event-item-description-char (unwrap (slice buffer 122 1)))
           (descr-extended-event-item-length (unwrap (read-u8 buffer 122)))
           (descr-extended-event-item-char (unwrap (slice buffer 123 1)))
           (descr-extended-event-text-length (unwrap (read-u8 buffer 123)))
           (descr-extended-event-text (unwrap (slice buffer 124 1)))
           (descr-time-shifted-event-reference-service-id (unwrap (read-u16be buffer 124)))
           (descr-time-shifted-event-reference-event-id (unwrap (read-u16be buffer 126)))
           (descr-component-high-stream-content-ext (unwrap (read-u16be buffer 126)))
           (descr-component-high-stream-content (unwrap (read-u16be buffer 126)))
           (descr-component-nga-bits-b7-reserved (unwrap (read-u16be buffer 126)))
           (descr-component-nga-bits-b6-headphones (unwrap (read-u16be buffer 126)))
           (descr-component-nga-bits-b5-interactivity (unwrap (read-u16be buffer 126)))
           (descr-component-nga-bits-b4-dialogue-enhancement (unwrap (read-u16be buffer 126)))
           (descr-component-nga-bits-b3-spoken-subtitles (unwrap (read-u16be buffer 126)))
           (descr-component-nga-bits-b2-audio-description (unwrap (read-u16be buffer 126)))
           (descr-component-high-component-type (unwrap (read-u16be buffer 126)))
           (descr-component-stream-content-ext (unwrap (read-u8 buffer 128)))
           (descr-component-type (unwrap (read-u8 buffer 129)))
           (descr-component-tag (unwrap (read-u8 buffer 130)))
           (descr-component-lang-code (unwrap (slice buffer 131 3)))
           (descr-component-text (unwrap (slice buffer 134 1)))
           (descr-mosaic-mosaic-entry-point (unwrap (read-u8 buffer 154)))
           (descr-mosaic-reserved-future-use1 (unwrap (read-u8 buffer 154)))
           (descr-mosaic-logical-cell-id (unwrap (read-u16be buffer 155)))
           (descr-mosaic-reserved-future-use2 (unwrap (read-u16be buffer 155)))
           (descr-mosaic-elementary-cell-field-length (unwrap (read-u8 buffer 157)))
           (descr-mosaic-reserved-future-use3 (unwrap (read-u8 buffer 158)))
           (descr-mosaic-elementary-cell-id (unwrap (read-u8 buffer 158)))
           (descr-mosaic-bouquet-id (unwrap (read-u16be buffer 160)))
           (descr-mosaic-original-network-id (unwrap (read-u16be buffer 162)))
           (descr-mosaic-transport-stream-id (unwrap (read-u16be buffer 164)))
           (descr-mosaic-service-id (unwrap (read-u16be buffer 166)))
           (descr-mosaic-event-id (unwrap (read-u16be buffer 168)))
           (descr-stream-identifier-component-tag (unwrap (read-u8 buffer 170)))
           (descr-ca-identifier-system-id (unwrap (read-u16be buffer 170)))
           (descr-content-nibble-level-2 (unwrap (read-u8 buffer 172)))
           (descr-content-user-byte (unwrap (read-u8 buffer 173)))
           (descr-parental-rating-country-code (unwrap (slice buffer 174 3)))
           (descr-teletext-lang-code (unwrap (slice buffer 177 3)))
           (descr-teletext-magazine-number (unwrap (read-u8 buffer 180)))
           (descr-teletext-page-number (unwrap (read-u8 buffer 181)))
           (descr-telephone-reserved-future-use1 (unwrap (read-u8 buffer 182)))
           (descr-telephone-reserved-future-use2 (unwrap (read-u8 buffer 183)))
           (descr-telephone-country-prefix-length (unwrap (read-u8 buffer 183)))
           (descr-telephone-international-area-code-length (unwrap (read-u8 buffer 183)))
           (descr-telephone-operator-code-length (unwrap (read-u8 buffer 183)))
           (descr-telephone-reserved-future-use3 (unwrap (read-u8 buffer 184)))
           (descr-telephone-national-area-code-length (unwrap (read-u8 buffer 184)))
           (descr-telephone-core-number-length (unwrap (read-u8 buffer 184)))
           (descr-telephone-number (unwrap (slice buffer 185 1)))
           (descr-telephone-country-prefix (unwrap (slice buffer 185 1)))
           (descr-telephone-international-area-code (unwrap (slice buffer 185 1)))
           (descr-telephone-operator-code (unwrap (slice buffer 185 1)))
           (descr-telephone-national-area-code (unwrap (slice buffer 185 1)))
           (descr-telephone-core-number (unwrap (slice buffer 185 1)))
           (descr-local-time-offset-country-code (unwrap (slice buffer 185 3)))
           (descr-local-time-offset-region-id (unwrap (read-u8 buffer 188)))
           (descr-local-time-offset-reserved (unwrap (read-u8 buffer 188)))
           (descr-subtitling-lang-code (unwrap (slice buffer 198 3)))
           (descr-subtitling-composition-page-id (unwrap (read-u16be buffer 202)))
           (descr-subtitling-ancillary-page-id (unwrap (read-u16be buffer 204)))
           (descr-terrestrial-delivery-centre-frequency (unwrap (read-u64be buffer 206)))
           (descr-terrestrial-delivery-reserved1 (unwrap (read-u8 buffer 210)))
           (descr-terrestrial-delivery-reserved2 (unwrap (read-u32be buffer 213)))
           (descr-multilng-srv-name-desc-iso639-language-code (unwrap (slice buffer 226 3)))
           (descr-multilng-srv-name-desc-service-provider-name-length (unwrap (read-u8 buffer 229)))
           (descr-multilng-srv-name-desc-service-provider-name (unwrap (slice buffer 230 1)))
           (descr-multilng-srv-name-desc-service-name-length (unwrap (read-u8 buffer 230)))
           (descr-multilng-srv-name-desc-service-name (unwrap (slice buffer 231 1)))
           (descr-multilng-component-desc-tag (unwrap (read-u8 buffer 231)))
           (descr-multilng-component-desc-iso639-language-code (unwrap (slice buffer 232 3)))
           (descr-multilng-component-desc-text-length (unwrap (read-u8 buffer 235)))
           (descr-multilng-component-desc-text (unwrap (slice buffer 236 1)))
           (descr-short-smoothing-buffer-dvb-reserved (unwrap (slice buffer 237 1)))
           (descr-partial-transport-stream-reserved-future-use1 (unwrap (read-u24be buffer 237)))
           (descr-partial-transport-stream-reserved-future-use2 (unwrap (read-u24be buffer 240)))
           (descr-partial-transport-stream-reserved-future-use3 (unwrap (read-u16be buffer 243)))
           (descr-data-bcast-component-tag (unwrap (read-u8 buffer 245)))
           (descr-data-bcast-selector-len (unwrap (read-u8 buffer 246)))
           (descr-data-bcast-selector-bytes (unwrap (slice buffer 247 1)))
           (descr-data-bcast-lang-code (unwrap (slice buffer 247 3)))
           (descr-data-bcast-text-len (unwrap (read-u8 buffer 250)))
           (descr-data-bcast-text (unwrap (slice buffer 251 1)))
           (descr-data-bcast-id-id-selector-bytes (unwrap (slice buffer 253 1)))
           (descr-pdc-reserved (unwrap (read-u24be buffer 253)))
           (descr-pdc-pil (unwrap (read-u24be buffer 253)))
           (descr-pdc-day (unwrap (read-u24be buffer 253)))
           (descr-pdc-month (unwrap (read-u24be buffer 253)))
           (descr-pdc-hour (unwrap (read-u24be buffer 253)))
           (descr-pdc-minute (unwrap (read-u24be buffer 253)))
           (descr-ac3-reserved (unwrap (read-u8 buffer 253)))
           (descr-ac3-component-type-reserved-flag (unwrap (read-u8 buffer 254)))
           (descr-ac3-bsid (unwrap (read-u8 buffer 255)))
           (descr-ac3-mainid (unwrap (read-u8 buffer 256)))
           (descr-ac3-asvc (unwrap (read-u8 buffer 257)))
           (descr-app-sig-app-type (unwrap (read-u16be buffer 258)))
           (descr-app-sig-ait-ver (unwrap (read-u8 buffer 260)))
           (descr-service-identifier (unwrap (slice buffer 261 1)))
           (descr-service-availability-reserved (unwrap (read-u8 buffer 261)))
           (descr-service-availability-cell-id (unwrap (read-u16be buffer 262)))
           (descr-default-authority-name (unwrap (slice buffer 264 1)))
           (descr-tva-id (unwrap (read-u16be buffer 264)))
           (descr-tva-reserved (unwrap (read-u8 buffer 266)))
           (descr-content-identifier-crid-length (unwrap (read-u8 buffer 268)))
           (descr-content-identifier-crid-bytes (unwrap (slice buffer 269 1)))
           (descr-content-identifier-cird-ref (unwrap (read-u16be buffer 269)))
           (descr-xait-onid (unwrap (read-u16be buffer 269)))
           (descr-xait-sid (unwrap (read-u16be buffer 271)))
           (descr-xait-version-number (unwrap (read-u8 buffer 273)))
           (descr-fta-user-defined (unwrap (read-u8 buffer 273)))
           (descr-fta-reserved-future-use (unwrap (read-u8 buffer 273)))
           (descr-fta-do-not-scramble (unwrap (read-u8 buffer 273)))
           (descr-fta-do-not-apply-revocation (unwrap (read-u8 buffer 273)))
           (descr-etsi-extension-supp-audio-lang-code-present (unwrap (read-u8 buffer 274)))
           (descr-etsi-extension-supp-audio-lang-code (unwrap (slice buffer 275 3)))
           (descr-etsi-extension-data (unwrap (slice buffer 278 1)))
           (descr-ac3-sysa-bsid (unwrap (read-u8 buffer 278)))
           (descr-ac3-sysa-bsmod (unwrap (read-u8 buffer 280)))
           (descr-ac3-sysa-full-svc (unwrap (read-u8 buffer 280)))
           (descr-ac3-sysa-langcode (unwrap (read-u8 buffer 281)))
           (descr-ac3-sysa-langcode2 (unwrap (read-u8 buffer 282)))
           (descr-ac3-sysa-mainid (unwrap (read-u8 buffer 283)))
           (descr-ac3-sysa-reserved (unwrap (read-u8 buffer 283)))
           (descr-ac3-sysa-asvcflags (unwrap (read-u8 buffer 283)))
           (descr-ac3-sysa-textlen (unwrap (read-u8 buffer 284)))
           (descr-ac3-sysa-textcode (unwrap (read-u8 buffer 284)))
           (descr-ac3-sysa-lang1 (unwrap (read-u8 buffer 285)))
           (descr-ac3-sysa-lang2 (unwrap (read-u8 buffer 285)))
           (descr-ac3-sysa-lang1-bytes (unwrap (slice buffer 286 3)))
           (descr-ac3-sysa-lang2-bytes (unwrap (slice buffer 289 3)))
           (descr-ac3-additional-info (unwrap (slice buffer 292 1)))
           (descr-nordig-lcd-v1-service-list-id (unwrap (read-u16be buffer 292)))
           (descr-nordig-lcd-v1-service-list-visible-service-flag (unwrap (read-u16be buffer 294)))
           (descr-nordig-lcd-v1-service-list-reserved (unwrap (read-u16be buffer 294)))
           (descr-nordig-lcd-v1-service-list-logical-channel-number (unwrap (read-u16be buffer 294)))
           (descr-nordig-lcd-v2-channel-list-id (unwrap (read-u8 buffer 298)))
           (descr-nordig-lcd-v2-channel-list-name-length (unwrap (read-u8 buffer 299)))
           (descr-nordig-lcd-v2-channel-list-name (unwrap (slice buffer 300 1)))
           (descr-nordig-lcd-v2-country-code (unwrap (slice buffer 300 3)))
           (descr-nordig-lcd-v2-descriptor-length (unwrap (read-u8 buffer 303)))
           (descr-nordig-lcd-v2-service-id (unwrap (read-u16be buffer 304)))
           (descr-nordig-lcd-v2-visible-service-flag (unwrap (read-u16be buffer 306)))
           (descr-nordig-lcd-v2-reserved (unwrap (read-u16be buffer 306)))
           (descr-nordig-lcd-v2-logical-channel-number (unwrap (read-u16be buffer 306)))
           (descr-logon-initialize-group-id (unwrap (read-u8 buffer 308)))
           (descr-logon-initialize-logon-id (unwrap (read-u16be buffer 309)))
           (descr-logon-initialize-continuous-carrier-reserved (unwrap (read-u8 buffer 311)))
           (descr-logon-initialize-continuous-carrier (unwrap (read-u8 buffer 311)))
           (descr-logon-initialize-security-handshake-required (unwrap (read-u8 buffer 311)))
           (descr-logon-initialize-prefix-flag (unwrap (read-u8 buffer 311)))
           (descr-logon-initialize-data-unit-labelling-flag (unwrap (read-u8 buffer 311)))
           (descr-logon-initialize-mini-slot-flag (unwrap (read-u8 buffer 311)))
           (descr-logon-initialize-contention-based-mini-slot-flag (unwrap (read-u8 buffer 311)))
           (descr-logon-initialize-capacity-type-flag-reserved (unwrap (read-u8 buffer 312)))
           (descr-logon-initialize-capacity-type-flag (unwrap (read-u8 buffer 312)))
           (descr-logon-initialize-traffic-burst-type (unwrap (read-u8 buffer 312)))
           (descr-logon-initialize-connectivity (unwrap (read-u16be buffer 312)))
           (descr-logon-initialize-return-signalling-vpi-reserved (unwrap (read-u8 buffer 312)))
           (descr-logon-initialize-return-signalling-vpi (unwrap (read-u8 buffer 312)))
           (descr-logon-initialize-return-signalling-vci (unwrap (read-u16be buffer 313)))
           (descr-logon-initialize-forward-signalling-vpi-reserved (unwrap (read-u8 buffer 315)))
           (descr-logon-initialize-forward-signalling-vpi (unwrap (read-u8 buffer 315)))
           (descr-logon-initialize-forward-signalling-vci (unwrap (read-u16be buffer 316)))
           (descr-logon-initialize-return-vpi-reserved (unwrap (read-u8 buffer 318)))
           (descr-logon-initialize-return-vpi (unwrap (read-u8 buffer 318)))
           (descr-logon-initialize-return-vci (unwrap (read-u16be buffer 319)))
           (descr-logon-initialize-return-trf-pid (unwrap (read-u16be buffer 321)))
           (descr-logon-initialize-return-ctrl-mngm-pid-reserved (unwrap (read-u16be buffer 323)))
           (descr-logon-initialize-return-ctrl-mngm-pid (unwrap (read-u16be buffer 323)))
           (descr-logon-initialize-cra-level (unwrap (read-u24be buffer 325)))
           (descr-logon-initialize-vbdc-max-reserved (unwrap (read-u16be buffer 328)))
           (descr-logon-initialize-vbdc-max (unwrap (read-u16be buffer 328)))
           (descr-logon-initialize-rbdc-max (unwrap (read-u24be buffer 330)))
           (descr-logon-initialize-rbdc-timeout (unwrap (read-u16be buffer 333)))
           (descr-rcs-content-table-id (unwrap (read-u8 buffer 335)))
           (descr-ciplus-cl-cb-min (unwrap (read-u8 buffer 338)))
           (descr-ciplus-cl-cb-max (unwrap (read-u8 buffer 339)))
           (descr-ciplus-cl-lang (unwrap (slice buffer 340 3)))
           (descr-ciplus-cl-label (unwrap (slice buffer 343 1)))
           (descr-ciplus-svc-id (unwrap (read-u16be buffer 343)))
           (descr-ciplus-svc-visible (unwrap (read-u16be buffer 346)))
           (descr-ciplus-svc-selectable (unwrap (read-u16be buffer 346)))
           (descr-ciplus-svc-lcn (unwrap (read-u16be buffer 346)))
           (descr-ciplus-prot-free-ci-mode (unwrap (read-u8 buffer 350)))
           (descr-ciplus-prot-match-brand-flag (unwrap (read-u8 buffer 350)))
           (descr-ciplus-prot-num-entries (unwrap (read-u8 buffer 350)))
           (descr-ciplus-prot-brand-id (unwrap (read-u16be buffer 350)))
           (descr-etsi-private-data (unwrap (slice buffer 352 1)))
           (descriptor-length (unwrap (read-u8 buffer 353)))
           (descriptor-data (unwrap (slice buffer 354 1)))
           )

      (ok (list
        (cons 'descr-video-stream-frame-rate-code (list (cons 'raw descr-video-stream-frame-rate-code) (cons 'formatted (fmt-hex descr-video-stream-frame-rate-code))))
        (cons 'descr-video-stream-mpeg1-only-flag (list (cons 'raw descr-video-stream-mpeg1-only-flag) (cons 'formatted (number->string descr-video-stream-mpeg1-only-flag))))
        (cons 'descr-video-stream-constrained-parameter-flag (list (cons 'raw descr-video-stream-constrained-parameter-flag) (cons 'formatted (number->string descr-video-stream-constrained-parameter-flag))))
        (cons 'descr-video-stream-still-picture-flag (list (cons 'raw descr-video-stream-still-picture-flag) (cons 'formatted (number->string descr-video-stream-still-picture-flag))))
        (cons 'descr-video-stream-profile-and-level-indication (list (cons 'raw descr-video-stream-profile-and-level-indication) (cons 'formatted (number->string descr-video-stream-profile-and-level-indication))))
        (cons 'descr-video-stream-chroma-format (list (cons 'raw descr-video-stream-chroma-format) (cons 'formatted (fmt-hex descr-video-stream-chroma-format))))
        (cons 'descr-video-stream-frame-rate-extension-flag (list (cons 'raw descr-video-stream-frame-rate-extension-flag) (cons 'formatted (number->string descr-video-stream-frame-rate-extension-flag))))
        (cons 'descr-video-stream-reserved (list (cons 'raw descr-video-stream-reserved) (cons 'formatted (fmt-hex descr-video-stream-reserved))))
        (cons 'descr-audio-stream-layer (list (cons 'raw descr-audio-stream-layer) (cons 'formatted (number->string descr-audio-stream-layer))))
        (cons 'descr-audio-stream-reserved (list (cons 'raw descr-audio-stream-reserved) (cons 'formatted (fmt-hex descr-audio-stream-reserved))))
        (cons 'descr-reg-add-id-inf (list (cons 'raw descr-reg-add-id-inf) (cons 'formatted (fmt-hex descr-reg-add-id-inf))))
        (cons 'descr-ca-system-id (list (cons 'raw descr-ca-system-id) (cons 'formatted (fmt-hex descr-ca-system-id))))
        (cons 'descr-ca-reserved (list (cons 'raw descr-ca-reserved) (cons 'formatted (fmt-hex descr-ca-reserved))))
        (cons 'descr-ca-pid (list (cons 'raw descr-ca-pid) (cons 'formatted (fmt-hex descr-ca-pid))))
        (cons 'descr-ca-private (list (cons 'raw descr-ca-private) (cons 'formatted (fmt-bytes descr-ca-private))))
        (cons 'descr-iso639-lang (list (cons 'raw descr-iso639-lang) (cons 'formatted (utf8->string descr-iso639-lang))))
        (cons 'descr-system-clock-external-clock-reference-indicator (list (cons 'raw descr-system-clock-external-clock-reference-indicator) (cons 'formatted (number->string descr-system-clock-external-clock-reference-indicator))))
        (cons 'descr-system-clock-reserved1 (list (cons 'raw descr-system-clock-reserved1) (cons 'formatted (fmt-hex descr-system-clock-reserved1))))
        (cons 'descr-system-clock-accuracy-integer (list (cons 'raw descr-system-clock-accuracy-integer) (cons 'formatted (number->string descr-system-clock-accuracy-integer))))
        (cons 'descr-system-clock-accuracy-exponent (list (cons 'raw descr-system-clock-accuracy-exponent) (cons 'formatted (number->string descr-system-clock-accuracy-exponent))))
        (cons 'descr-system-clock-reserved2 (list (cons 'raw descr-system-clock-reserved2) (cons 'formatted (fmt-hex descr-system-clock-reserved2))))
        (cons 'descr-max-bitrate-reserved (list (cons 'raw descr-max-bitrate-reserved) (cons 'formatted (fmt-hex descr-max-bitrate-reserved))))
        (cons 'descr-max-bitrate (list (cons 'raw descr-max-bitrate) (cons 'formatted (number->string descr-max-bitrate))))
        (cons 'descr-smoothing-buffer-reserved1 (list (cons 'raw descr-smoothing-buffer-reserved1) (cons 'formatted (fmt-hex descr-smoothing-buffer-reserved1))))
        (cons 'descr-smoothing-buffer-leak-rate (list (cons 'raw descr-smoothing-buffer-leak-rate) (cons 'formatted (number->string descr-smoothing-buffer-leak-rate))))
        (cons 'descr-smoothing-buffer-reserved2 (list (cons 'raw descr-smoothing-buffer-reserved2) (cons 'formatted (fmt-hex descr-smoothing-buffer-reserved2))))
        (cons 'descr-smoothing-buffer-size (list (cons 'raw descr-smoothing-buffer-size) (cons 'formatted (number->string descr-smoothing-buffer-size))))
        (cons 'descr-std-reserved (list (cons 'raw descr-std-reserved) (cons 'formatted (fmt-hex descr-std-reserved))))
        (cons 'descr-std-leak-valid (list (cons 'raw descr-std-leak-valid) (cons 'formatted (number->string descr-std-leak-valid))))
        (cons 'descr-carousel-identifier-id (list (cons 'raw descr-carousel-identifier-id) (cons 'formatted (fmt-hex descr-carousel-identifier-id))))
        (cons 'descr-carousel-identifier-module-version (list (cons 'raw descr-carousel-identifier-module-version) (cons 'formatted (fmt-hex descr-carousel-identifier-module-version))))
        (cons 'descr-carousel-identifier-module-id (list (cons 'raw descr-carousel-identifier-module-id) (cons 'formatted (fmt-hex descr-carousel-identifier-module-id))))
        (cons 'descr-carousel-identifier-block-size (list (cons 'raw descr-carousel-identifier-block-size) (cons 'formatted (number->string descr-carousel-identifier-block-size))))
        (cons 'descr-carousel-identifier-module-size (list (cons 'raw descr-carousel-identifier-module-size) (cons 'formatted (number->string descr-carousel-identifier-module-size))))
        (cons 'descr-carousel-identifier-compression-method (list (cons 'raw descr-carousel-identifier-compression-method) (cons 'formatted (fmt-hex descr-carousel-identifier-compression-method))))
        (cons 'descr-carousel-identifier-original-size (list (cons 'raw descr-carousel-identifier-original-size) (cons 'formatted (number->string descr-carousel-identifier-original-size))))
        (cons 'descr-carousel-identifier-timeout (list (cons 'raw descr-carousel-identifier-timeout) (cons 'formatted (number->string descr-carousel-identifier-timeout))))
        (cons 'descr-carousel-identifier-object-key-len (list (cons 'raw descr-carousel-identifier-object-key-len) (cons 'formatted (number->string descr-carousel-identifier-object-key-len))))
        (cons 'descr-carousel-identifier-object-key-data (list (cons 'raw descr-carousel-identifier-object-key-data) (cons 'formatted (fmt-bytes descr-carousel-identifier-object-key-data))))
        (cons 'descr-carousel-identifier-private (list (cons 'raw descr-carousel-identifier-private) (cons 'formatted (fmt-bytes descr-carousel-identifier-private))))
        (cons 'descr-association-tag (list (cons 'raw descr-association-tag) (cons 'formatted (fmt-hex descr-association-tag))))
        (cons 'descr-association-tag-use (list (cons 'raw descr-association-tag-use) (cons 'formatted (fmt-hex descr-association-tag-use))))
        (cons 'descr-association-tag-selector-len (list (cons 'raw descr-association-tag-selector-len) (cons 'formatted (number->string descr-association-tag-selector-len))))
        (cons 'descr-association-tag-transaction-id (list (cons 'raw descr-association-tag-transaction-id) (cons 'formatted (fmt-hex descr-association-tag-transaction-id))))
        (cons 'descr-association-tag-timeout (list (cons 'raw descr-association-tag-timeout) (cons 'formatted (fmt-hex descr-association-tag-timeout))))
        (cons 'descr-association-tag-selector-bytes (list (cons 'raw descr-association-tag-selector-bytes) (cons 'formatted (fmt-bytes descr-association-tag-selector-bytes))))
        (cons 'descr-association-tag-private-bytes (list (cons 'raw descr-association-tag-private-bytes) (cons 'formatted (fmt-bytes descr-association-tag-private-bytes))))
        (cons 'descr-avc-vid-profile-idc (list (cons 'raw descr-avc-vid-profile-idc) (cons 'formatted (fmt-hex descr-avc-vid-profile-idc))))
        (cons 'descr-avc-vid-constraint-set0-flag (list (cons 'raw descr-avc-vid-constraint-set0-flag) (cons 'formatted (number->string descr-avc-vid-constraint-set0-flag))))
        (cons 'descr-avc-vid-constraint-set1-flag (list (cons 'raw descr-avc-vid-constraint-set1-flag) (cons 'formatted (number->string descr-avc-vid-constraint-set1-flag))))
        (cons 'descr-avc-vid-constraint-set2-flag (list (cons 'raw descr-avc-vid-constraint-set2-flag) (cons 'formatted (number->string descr-avc-vid-constraint-set2-flag))))
        (cons 'descr-avc-vid-compatible-flags (list (cons 'raw descr-avc-vid-compatible-flags) (cons 'formatted (fmt-hex descr-avc-vid-compatible-flags))))
        (cons 'descr-avc-vid-level-idc (list (cons 'raw descr-avc-vid-level-idc) (cons 'formatted (fmt-hex descr-avc-vid-level-idc))))
        (cons 'descr-avc-vid-still-present (list (cons 'raw descr-avc-vid-still-present) (cons 'formatted (number->string descr-avc-vid-still-present))))
        (cons 'descr-avc-vid-24h-picture-flag (list (cons 'raw descr-avc-vid-24h-picture-flag) (cons 'formatted (number->string descr-avc-vid-24h-picture-flag))))
        (cons 'descr-avc-vid-reserved (list (cons 'raw descr-avc-vid-reserved) (cons 'formatted (fmt-hex descr-avc-vid-reserved))))
        (cons 'descr-network-name-descriptor (list (cons 'raw descr-network-name-descriptor) (cons 'formatted (utf8->string descr-network-name-descriptor))))
        (cons 'descr-iso-extension-data (list (cons 'raw descr-iso-extension-data) (cons 'formatted (fmt-bytes descr-iso-extension-data))))
        (cons 'descr-service-list-id (list (cons 'raw descr-service-list-id) (cons 'formatted (fmt-hex descr-service-list-id))))
        (cons 'descr-stuffing (list (cons 'raw descr-stuffing) (cons 'formatted (fmt-bytes descr-stuffing))))
        (cons 'descr-satellite-delivery-zero (list (cons 'raw descr-satellite-delivery-zero) (cons 'formatted (fmt-hex descr-satellite-delivery-zero))))
        (cons 'descr-satellite-delivery-symbol-rate (list (cons 'raw descr-satellite-delivery-symbol-rate) (cons 'formatted (number->string descr-satellite-delivery-symbol-rate))))
        (cons 'descr-cable-delivery-frequency (list (cons 'raw descr-cable-delivery-frequency) (cons 'formatted (number->string descr-cable-delivery-frequency))))
        (cons 'descr-cable-delivery-reserved (list (cons 'raw descr-cable-delivery-reserved) (cons 'formatted (fmt-hex descr-cable-delivery-reserved))))
        (cons 'descr-cable-delivery-symbol-rate (list (cons 'raw descr-cable-delivery-symbol-rate) (cons 'formatted (number->string descr-cable-delivery-symbol-rate))))
        (cons 'descr-vbi-data-descr-len (list (cons 'raw descr-vbi-data-descr-len) (cons 'formatted (number->string descr-vbi-data-descr-len))))
        (cons 'descr-vbi-data-reserved1 (list (cons 'raw descr-vbi-data-reserved1) (cons 'formatted (fmt-hex descr-vbi-data-reserved1))))
        (cons 'descr-vbi-data-line-offset (list (cons 'raw descr-vbi-data-line-offset) (cons 'formatted (number->string descr-vbi-data-line-offset))))
        (cons 'descr-vbi-data-reserved2 (list (cons 'raw descr-vbi-data-reserved2) (cons 'formatted (fmt-bytes descr-vbi-data-reserved2))))
        (cons 'descr-bouquet-name (list (cons 'raw descr-bouquet-name) (cons 'formatted (utf8->string descr-bouquet-name))))
        (cons 'descr-service-provider-name-length (list (cons 'raw descr-service-provider-name-length) (cons 'formatted (number->string descr-service-provider-name-length))))
        (cons 'descr-service-provider (list (cons 'raw descr-service-provider) (cons 'formatted (utf8->string descr-service-provider))))
        (cons 'descr-service-name-length (list (cons 'raw descr-service-name-length) (cons 'formatted (number->string descr-service-name-length))))
        (cons 'descr-service-name (list (cons 'raw descr-service-name) (cons 'formatted (utf8->string descr-service-name))))
        (cons 'descr-country-availability-reserved-future-use (list (cons 'raw descr-country-availability-reserved-future-use) (cons 'formatted (fmt-hex descr-country-availability-reserved-future-use))))
        (cons 'descr-country-availability-country-code (list (cons 'raw descr-country-availability-country-code) (cons 'formatted (utf8->string descr-country-availability-country-code))))
        (cons 'descr-linkage-transport-stream-id (list (cons 'raw descr-linkage-transport-stream-id) (cons 'formatted (fmt-hex descr-linkage-transport-stream-id))))
        (cons 'descr-linkage-original-network-id (list (cons 'raw descr-linkage-original-network-id) (cons 'formatted (fmt-hex descr-linkage-original-network-id))))
        (cons 'descr-linkage-service-id (list (cons 'raw descr-linkage-service-id) (cons 'formatted (fmt-hex descr-linkage-service-id))))
        (cons 'descr-linkage-hand-over-type (list (cons 'raw descr-linkage-hand-over-type) (cons 'formatted (fmt-hex descr-linkage-hand-over-type))))
        (cons 'descr-linkage-reserved1 (list (cons 'raw descr-linkage-reserved1) (cons 'formatted (fmt-hex descr-linkage-reserved1))))
        (cons 'descr-linkage-network-id (list (cons 'raw descr-linkage-network-id) (cons 'formatted (fmt-hex descr-linkage-network-id))))
        (cons 'descr-linkage-initial-service-id (list (cons 'raw descr-linkage-initial-service-id) (cons 'formatted (fmt-hex descr-linkage-initial-service-id))))
        (cons 'descr-linkage-target-event-id (list (cons 'raw descr-linkage-target-event-id) (cons 'formatted (fmt-hex descr-linkage-target-event-id))))
        (cons 'descr-linkage-reserved2 (list (cons 'raw descr-linkage-reserved2) (cons 'formatted (fmt-hex descr-linkage-reserved2))))
        (cons 'descr-linkage-interactive-network-id (list (cons 'raw descr-linkage-interactive-network-id) (cons 'formatted (fmt-hex descr-linkage-interactive-network-id))))
        (cons 'descr-linkage-population-id-loop-count (list (cons 'raw descr-linkage-population-id-loop-count) (cons 'formatted (number->string descr-linkage-population-id-loop-count))))
        (cons 'descr-linkage-population-id (list (cons 'raw descr-linkage-population-id) (cons 'formatted (fmt-hex descr-linkage-population-id))))
        (cons 'descr-linkage-population-id-base (list (cons 'raw descr-linkage-population-id-base) (cons 'formatted (fmt-hex descr-linkage-population-id-base))))
        (cons 'descr-linkage-population-id-mask (list (cons 'raw descr-linkage-population-id-mask) (cons 'formatted (fmt-hex descr-linkage-population-id-mask))))
        (cons 'descr-linkage-private-data-byte (list (cons 'raw descr-linkage-private-data-byte) (cons 'formatted (fmt-bytes descr-linkage-private-data-byte))))
        (cons 'descr-nvod-reference-tsid (list (cons 'raw descr-nvod-reference-tsid) (cons 'formatted (fmt-hex descr-nvod-reference-tsid))))
        (cons 'descr-nvod-reference-onid (list (cons 'raw descr-nvod-reference-onid) (cons 'formatted (fmt-hex descr-nvod-reference-onid))))
        (cons 'descr-nvod-reference-sid (list (cons 'raw descr-nvod-reference-sid) (cons 'formatted (fmt-hex descr-nvod-reference-sid))))
        (cons 'descr-time-shifted-service-id (list (cons 'raw descr-time-shifted-service-id) (cons 'formatted (fmt-hex descr-time-shifted-service-id))))
        (cons 'descr-short-event-lang-code (list (cons 'raw descr-short-event-lang-code) (cons 'formatted (utf8->string descr-short-event-lang-code))))
        (cons 'descr-short-event-name-length (list (cons 'raw descr-short-event-name-length) (cons 'formatted (number->string descr-short-event-name-length))))
        (cons 'descr-short-event-name (list (cons 'raw descr-short-event-name) (cons 'formatted (utf8->string descr-short-event-name))))
        (cons 'descr-short-event-text-length (list (cons 'raw descr-short-event-text-length) (cons 'formatted (number->string descr-short-event-text-length))))
        (cons 'descr-short-event-text (list (cons 'raw descr-short-event-text) (cons 'formatted (utf8->string descr-short-event-text))))
        (cons 'descr-extended-event-descriptor-number (list (cons 'raw descr-extended-event-descriptor-number) (cons 'formatted (number->string descr-extended-event-descriptor-number))))
        (cons 'descr-extended-event-last-descriptor-number (list (cons 'raw descr-extended-event-last-descriptor-number) (cons 'formatted (number->string descr-extended-event-last-descriptor-number))))
        (cons 'descr-extended-event-lang-code (list (cons 'raw descr-extended-event-lang-code) (cons 'formatted (utf8->string descr-extended-event-lang-code))))
        (cons 'descr-extended-event-length-of-items (list (cons 'raw descr-extended-event-length-of-items) (cons 'formatted (number->string descr-extended-event-length-of-items))))
        (cons 'descr-extended-event-item-description-length (list (cons 'raw descr-extended-event-item-description-length) (cons 'formatted (number->string descr-extended-event-item-description-length))))
        (cons 'descr-extended-event-item-description-char (list (cons 'raw descr-extended-event-item-description-char) (cons 'formatted (utf8->string descr-extended-event-item-description-char))))
        (cons 'descr-extended-event-item-length (list (cons 'raw descr-extended-event-item-length) (cons 'formatted (number->string descr-extended-event-item-length))))
        (cons 'descr-extended-event-item-char (list (cons 'raw descr-extended-event-item-char) (cons 'formatted (utf8->string descr-extended-event-item-char))))
        (cons 'descr-extended-event-text-length (list (cons 'raw descr-extended-event-text-length) (cons 'formatted (number->string descr-extended-event-text-length))))
        (cons 'descr-extended-event-text (list (cons 'raw descr-extended-event-text) (cons 'formatted (utf8->string descr-extended-event-text))))
        (cons 'descr-time-shifted-event-reference-service-id (list (cons 'raw descr-time-shifted-event-reference-service-id) (cons 'formatted (fmt-hex descr-time-shifted-event-reference-service-id))))
        (cons 'descr-time-shifted-event-reference-event-id (list (cons 'raw descr-time-shifted-event-reference-event-id) (cons 'formatted (fmt-hex descr-time-shifted-event-reference-event-id))))
        (cons 'descr-component-high-stream-content-ext (list (cons 'raw descr-component-high-stream-content-ext) (cons 'formatted (fmt-hex descr-component-high-stream-content-ext))))
        (cons 'descr-component-high-stream-content (list (cons 'raw descr-component-high-stream-content) (cons 'formatted (fmt-hex descr-component-high-stream-content))))
        (cons 'descr-component-nga-bits-b7-reserved (list (cons 'raw descr-component-nga-bits-b7-reserved) (cons 'formatted (fmt-hex descr-component-nga-bits-b7-reserved))))
        (cons 'descr-component-nga-bits-b6-headphones (list (cons 'raw descr-component-nga-bits-b6-headphones) (cons 'formatted (fmt-hex descr-component-nga-bits-b6-headphones))))
        (cons 'descr-component-nga-bits-b5-interactivity (list (cons 'raw descr-component-nga-bits-b5-interactivity) (cons 'formatted (fmt-hex descr-component-nga-bits-b5-interactivity))))
        (cons 'descr-component-nga-bits-b4-dialogue-enhancement (list (cons 'raw descr-component-nga-bits-b4-dialogue-enhancement) (cons 'formatted (fmt-hex descr-component-nga-bits-b4-dialogue-enhancement))))
        (cons 'descr-component-nga-bits-b3-spoken-subtitles (list (cons 'raw descr-component-nga-bits-b3-spoken-subtitles) (cons 'formatted (fmt-hex descr-component-nga-bits-b3-spoken-subtitles))))
        (cons 'descr-component-nga-bits-b2-audio-description (list (cons 'raw descr-component-nga-bits-b2-audio-description) (cons 'formatted (fmt-hex descr-component-nga-bits-b2-audio-description))))
        (cons 'descr-component-high-component-type (list (cons 'raw descr-component-high-component-type) (cons 'formatted (fmt-hex descr-component-high-component-type))))
        (cons 'descr-component-stream-content-ext (list (cons 'raw descr-component-stream-content-ext) (cons 'formatted (fmt-hex descr-component-stream-content-ext))))
        (cons 'descr-component-type (list (cons 'raw descr-component-type) (cons 'formatted (fmt-hex descr-component-type))))
        (cons 'descr-component-tag (list (cons 'raw descr-component-tag) (cons 'formatted (fmt-hex descr-component-tag))))
        (cons 'descr-component-lang-code (list (cons 'raw descr-component-lang-code) (cons 'formatted (utf8->string descr-component-lang-code))))
        (cons 'descr-component-text (list (cons 'raw descr-component-text) (cons 'formatted (utf8->string descr-component-text))))
        (cons 'descr-mosaic-mosaic-entry-point (list (cons 'raw descr-mosaic-mosaic-entry-point) (cons 'formatted (fmt-hex descr-mosaic-mosaic-entry-point))))
        (cons 'descr-mosaic-reserved-future-use1 (list (cons 'raw descr-mosaic-reserved-future-use1) (cons 'formatted (fmt-hex descr-mosaic-reserved-future-use1))))
        (cons 'descr-mosaic-logical-cell-id (list (cons 'raw descr-mosaic-logical-cell-id) (cons 'formatted (fmt-hex descr-mosaic-logical-cell-id))))
        (cons 'descr-mosaic-reserved-future-use2 (list (cons 'raw descr-mosaic-reserved-future-use2) (cons 'formatted (fmt-hex descr-mosaic-reserved-future-use2))))
        (cons 'descr-mosaic-elementary-cell-field-length (list (cons 'raw descr-mosaic-elementary-cell-field-length) (cons 'formatted (number->string descr-mosaic-elementary-cell-field-length))))
        (cons 'descr-mosaic-reserved-future-use3 (list (cons 'raw descr-mosaic-reserved-future-use3) (cons 'formatted (fmt-hex descr-mosaic-reserved-future-use3))))
        (cons 'descr-mosaic-elementary-cell-id (list (cons 'raw descr-mosaic-elementary-cell-id) (cons 'formatted (fmt-hex descr-mosaic-elementary-cell-id))))
        (cons 'descr-mosaic-bouquet-id (list (cons 'raw descr-mosaic-bouquet-id) (cons 'formatted (fmt-hex descr-mosaic-bouquet-id))))
        (cons 'descr-mosaic-original-network-id (list (cons 'raw descr-mosaic-original-network-id) (cons 'formatted (fmt-hex descr-mosaic-original-network-id))))
        (cons 'descr-mosaic-transport-stream-id (list (cons 'raw descr-mosaic-transport-stream-id) (cons 'formatted (fmt-hex descr-mosaic-transport-stream-id))))
        (cons 'descr-mosaic-service-id (list (cons 'raw descr-mosaic-service-id) (cons 'formatted (fmt-hex descr-mosaic-service-id))))
        (cons 'descr-mosaic-event-id (list (cons 'raw descr-mosaic-event-id) (cons 'formatted (fmt-hex descr-mosaic-event-id))))
        (cons 'descr-stream-identifier-component-tag (list (cons 'raw descr-stream-identifier-component-tag) (cons 'formatted (fmt-hex descr-stream-identifier-component-tag))))
        (cons 'descr-ca-identifier-system-id (list (cons 'raw descr-ca-identifier-system-id) (cons 'formatted (fmt-hex descr-ca-identifier-system-id))))
        (cons 'descr-content-nibble-level-2 (list (cons 'raw descr-content-nibble-level-2) (cons 'formatted (fmt-hex descr-content-nibble-level-2))))
        (cons 'descr-content-user-byte (list (cons 'raw descr-content-user-byte) (cons 'formatted (fmt-hex descr-content-user-byte))))
        (cons 'descr-parental-rating-country-code (list (cons 'raw descr-parental-rating-country-code) (cons 'formatted (utf8->string descr-parental-rating-country-code))))
        (cons 'descr-teletext-lang-code (list (cons 'raw descr-teletext-lang-code) (cons 'formatted (utf8->string descr-teletext-lang-code))))
        (cons 'descr-teletext-magazine-number (list (cons 'raw descr-teletext-magazine-number) (cons 'formatted (number->string descr-teletext-magazine-number))))
        (cons 'descr-teletext-page-number (list (cons 'raw descr-teletext-page-number) (cons 'formatted (number->string descr-teletext-page-number))))
        (cons 'descr-telephone-reserved-future-use1 (list (cons 'raw descr-telephone-reserved-future-use1) (cons 'formatted (fmt-hex descr-telephone-reserved-future-use1))))
        (cons 'descr-telephone-reserved-future-use2 (list (cons 'raw descr-telephone-reserved-future-use2) (cons 'formatted (fmt-hex descr-telephone-reserved-future-use2))))
        (cons 'descr-telephone-country-prefix-length (list (cons 'raw descr-telephone-country-prefix-length) (cons 'formatted (number->string descr-telephone-country-prefix-length))))
        (cons 'descr-telephone-international-area-code-length (list (cons 'raw descr-telephone-international-area-code-length) (cons 'formatted (number->string descr-telephone-international-area-code-length))))
        (cons 'descr-telephone-operator-code-length (list (cons 'raw descr-telephone-operator-code-length) (cons 'formatted (number->string descr-telephone-operator-code-length))))
        (cons 'descr-telephone-reserved-future-use3 (list (cons 'raw descr-telephone-reserved-future-use3) (cons 'formatted (fmt-hex descr-telephone-reserved-future-use3))))
        (cons 'descr-telephone-national-area-code-length (list (cons 'raw descr-telephone-national-area-code-length) (cons 'formatted (number->string descr-telephone-national-area-code-length))))
        (cons 'descr-telephone-core-number-length (list (cons 'raw descr-telephone-core-number-length) (cons 'formatted (number->string descr-telephone-core-number-length))))
        (cons 'descr-telephone-number (list (cons 'raw descr-telephone-number) (cons 'formatted (utf8->string descr-telephone-number))))
        (cons 'descr-telephone-country-prefix (list (cons 'raw descr-telephone-country-prefix) (cons 'formatted (utf8->string descr-telephone-country-prefix))))
        (cons 'descr-telephone-international-area-code (list (cons 'raw descr-telephone-international-area-code) (cons 'formatted (utf8->string descr-telephone-international-area-code))))
        (cons 'descr-telephone-operator-code (list (cons 'raw descr-telephone-operator-code) (cons 'formatted (utf8->string descr-telephone-operator-code))))
        (cons 'descr-telephone-national-area-code (list (cons 'raw descr-telephone-national-area-code) (cons 'formatted (utf8->string descr-telephone-national-area-code))))
        (cons 'descr-telephone-core-number (list (cons 'raw descr-telephone-core-number) (cons 'formatted (utf8->string descr-telephone-core-number))))
        (cons 'descr-local-time-offset-country-code (list (cons 'raw descr-local-time-offset-country-code) (cons 'formatted (utf8->string descr-local-time-offset-country-code))))
        (cons 'descr-local-time-offset-region-id (list (cons 'raw descr-local-time-offset-region-id) (cons 'formatted (fmt-hex descr-local-time-offset-region-id))))
        (cons 'descr-local-time-offset-reserved (list (cons 'raw descr-local-time-offset-reserved) (cons 'formatted (fmt-hex descr-local-time-offset-reserved))))
        (cons 'descr-subtitling-lang-code (list (cons 'raw descr-subtitling-lang-code) (cons 'formatted (utf8->string descr-subtitling-lang-code))))
        (cons 'descr-subtitling-composition-page-id (list (cons 'raw descr-subtitling-composition-page-id) (cons 'formatted (number->string descr-subtitling-composition-page-id))))
        (cons 'descr-subtitling-ancillary-page-id (list (cons 'raw descr-subtitling-ancillary-page-id) (cons 'formatted (number->string descr-subtitling-ancillary-page-id))))
        (cons 'descr-terrestrial-delivery-centre-frequency (list (cons 'raw descr-terrestrial-delivery-centre-frequency) (cons 'formatted (number->string descr-terrestrial-delivery-centre-frequency))))
        (cons 'descr-terrestrial-delivery-reserved1 (list (cons 'raw descr-terrestrial-delivery-reserved1) (cons 'formatted (fmt-hex descr-terrestrial-delivery-reserved1))))
        (cons 'descr-terrestrial-delivery-reserved2 (list (cons 'raw descr-terrestrial-delivery-reserved2) (cons 'formatted (fmt-hex descr-terrestrial-delivery-reserved2))))
        (cons 'descr-multilng-srv-name-desc-iso639-language-code (list (cons 'raw descr-multilng-srv-name-desc-iso639-language-code) (cons 'formatted (utf8->string descr-multilng-srv-name-desc-iso639-language-code))))
        (cons 'descr-multilng-srv-name-desc-service-provider-name-length (list (cons 'raw descr-multilng-srv-name-desc-service-provider-name-length) (cons 'formatted (number->string descr-multilng-srv-name-desc-service-provider-name-length))))
        (cons 'descr-multilng-srv-name-desc-service-provider-name (list (cons 'raw descr-multilng-srv-name-desc-service-provider-name) (cons 'formatted (utf8->string descr-multilng-srv-name-desc-service-provider-name))))
        (cons 'descr-multilng-srv-name-desc-service-name-length (list (cons 'raw descr-multilng-srv-name-desc-service-name-length) (cons 'formatted (number->string descr-multilng-srv-name-desc-service-name-length))))
        (cons 'descr-multilng-srv-name-desc-service-name (list (cons 'raw descr-multilng-srv-name-desc-service-name) (cons 'formatted (utf8->string descr-multilng-srv-name-desc-service-name))))
        (cons 'descr-multilng-component-desc-tag (list (cons 'raw descr-multilng-component-desc-tag) (cons 'formatted (fmt-hex descr-multilng-component-desc-tag))))
        (cons 'descr-multilng-component-desc-iso639-language-code (list (cons 'raw descr-multilng-component-desc-iso639-language-code) (cons 'formatted (utf8->string descr-multilng-component-desc-iso639-language-code))))
        (cons 'descr-multilng-component-desc-text-length (list (cons 'raw descr-multilng-component-desc-text-length) (cons 'formatted (number->string descr-multilng-component-desc-text-length))))
        (cons 'descr-multilng-component-desc-text (list (cons 'raw descr-multilng-component-desc-text) (cons 'formatted (utf8->string descr-multilng-component-desc-text))))
        (cons 'descr-short-smoothing-buffer-dvb-reserved (list (cons 'raw descr-short-smoothing-buffer-dvb-reserved) (cons 'formatted (fmt-bytes descr-short-smoothing-buffer-dvb-reserved))))
        (cons 'descr-partial-transport-stream-reserved-future-use1 (list (cons 'raw descr-partial-transport-stream-reserved-future-use1) (cons 'formatted (fmt-hex descr-partial-transport-stream-reserved-future-use1))))
        (cons 'descr-partial-transport-stream-reserved-future-use2 (list (cons 'raw descr-partial-transport-stream-reserved-future-use2) (cons 'formatted (fmt-hex descr-partial-transport-stream-reserved-future-use2))))
        (cons 'descr-partial-transport-stream-reserved-future-use3 (list (cons 'raw descr-partial-transport-stream-reserved-future-use3) (cons 'formatted (fmt-hex descr-partial-transport-stream-reserved-future-use3))))
        (cons 'descr-data-bcast-component-tag (list (cons 'raw descr-data-bcast-component-tag) (cons 'formatted (fmt-hex descr-data-bcast-component-tag))))
        (cons 'descr-data-bcast-selector-len (list (cons 'raw descr-data-bcast-selector-len) (cons 'formatted (number->string descr-data-bcast-selector-len))))
        (cons 'descr-data-bcast-selector-bytes (list (cons 'raw descr-data-bcast-selector-bytes) (cons 'formatted (fmt-bytes descr-data-bcast-selector-bytes))))
        (cons 'descr-data-bcast-lang-code (list (cons 'raw descr-data-bcast-lang-code) (cons 'formatted (utf8->string descr-data-bcast-lang-code))))
        (cons 'descr-data-bcast-text-len (list (cons 'raw descr-data-bcast-text-len) (cons 'formatted (number->string descr-data-bcast-text-len))))
        (cons 'descr-data-bcast-text (list (cons 'raw descr-data-bcast-text) (cons 'formatted (utf8->string descr-data-bcast-text))))
        (cons 'descr-data-bcast-id-id-selector-bytes (list (cons 'raw descr-data-bcast-id-id-selector-bytes) (cons 'formatted (fmt-bytes descr-data-bcast-id-id-selector-bytes))))
        (cons 'descr-pdc-reserved (list (cons 'raw descr-pdc-reserved) (cons 'formatted (fmt-hex descr-pdc-reserved))))
        (cons 'descr-pdc-pil (list (cons 'raw descr-pdc-pil) (cons 'formatted (fmt-hex descr-pdc-pil))))
        (cons 'descr-pdc-day (list (cons 'raw descr-pdc-day) (cons 'formatted (number->string descr-pdc-day))))
        (cons 'descr-pdc-month (list (cons 'raw descr-pdc-month) (cons 'formatted (number->string descr-pdc-month))))
        (cons 'descr-pdc-hour (list (cons 'raw descr-pdc-hour) (cons 'formatted (number->string descr-pdc-hour))))
        (cons 'descr-pdc-minute (list (cons 'raw descr-pdc-minute) (cons 'formatted (number->string descr-pdc-minute))))
        (cons 'descr-ac3-reserved (list (cons 'raw descr-ac3-reserved) (cons 'formatted (fmt-hex descr-ac3-reserved))))
        (cons 'descr-ac3-component-type-reserved-flag (list (cons 'raw descr-ac3-component-type-reserved-flag) (cons 'formatted (fmt-hex descr-ac3-component-type-reserved-flag))))
        (cons 'descr-ac3-bsid (list (cons 'raw descr-ac3-bsid) (cons 'formatted (fmt-hex descr-ac3-bsid))))
        (cons 'descr-ac3-mainid (list (cons 'raw descr-ac3-mainid) (cons 'formatted (fmt-hex descr-ac3-mainid))))
        (cons 'descr-ac3-asvc (list (cons 'raw descr-ac3-asvc) (cons 'formatted (fmt-hex descr-ac3-asvc))))
        (cons 'descr-app-sig-app-type (list (cons 'raw descr-app-sig-app-type) (cons 'formatted (fmt-hex descr-app-sig-app-type))))
        (cons 'descr-app-sig-ait-ver (list (cons 'raw descr-app-sig-ait-ver) (cons 'formatted (fmt-hex descr-app-sig-ait-ver))))
        (cons 'descr-service-identifier (list (cons 'raw descr-service-identifier) (cons 'formatted (utf8->string descr-service-identifier))))
        (cons 'descr-service-availability-reserved (list (cons 'raw descr-service-availability-reserved) (cons 'formatted (fmt-hex descr-service-availability-reserved))))
        (cons 'descr-service-availability-cell-id (list (cons 'raw descr-service-availability-cell-id) (cons 'formatted (fmt-hex descr-service-availability-cell-id))))
        (cons 'descr-default-authority-name (list (cons 'raw descr-default-authority-name) (cons 'formatted (utf8->string descr-default-authority-name))))
        (cons 'descr-tva-id (list (cons 'raw descr-tva-id) (cons 'formatted (fmt-hex descr-tva-id))))
        (cons 'descr-tva-reserved (list (cons 'raw descr-tva-reserved) (cons 'formatted (fmt-hex descr-tva-reserved))))
        (cons 'descr-content-identifier-crid-length (list (cons 'raw descr-content-identifier-crid-length) (cons 'formatted (number->string descr-content-identifier-crid-length))))
        (cons 'descr-content-identifier-crid-bytes (list (cons 'raw descr-content-identifier-crid-bytes) (cons 'formatted (fmt-bytes descr-content-identifier-crid-bytes))))
        (cons 'descr-content-identifier-cird-ref (list (cons 'raw descr-content-identifier-cird-ref) (cons 'formatted (fmt-hex descr-content-identifier-cird-ref))))
        (cons 'descr-xait-onid (list (cons 'raw descr-xait-onid) (cons 'formatted (fmt-hex descr-xait-onid))))
        (cons 'descr-xait-sid (list (cons 'raw descr-xait-sid) (cons 'formatted (fmt-hex descr-xait-sid))))
        (cons 'descr-xait-version-number (list (cons 'raw descr-xait-version-number) (cons 'formatted (fmt-hex descr-xait-version-number))))
        (cons 'descr-fta-user-defined (list (cons 'raw descr-fta-user-defined) (cons 'formatted (fmt-hex descr-fta-user-defined))))
        (cons 'descr-fta-reserved-future-use (list (cons 'raw descr-fta-reserved-future-use) (cons 'formatted (fmt-hex descr-fta-reserved-future-use))))
        (cons 'descr-fta-do-not-scramble (list (cons 'raw descr-fta-do-not-scramble) (cons 'formatted (if (= descr-fta-do-not-scramble 0) "Scrambling shall be applied where applicable for content protection" "Scrambling shall not be applied for the purposes of content protection"))))
        (cons 'descr-fta-do-not-apply-revocation (list (cons 'raw descr-fta-do-not-apply-revocation) (cons 'formatted (if (= descr-fta-do-not-apply-revocation 0) "Content revocation process shall be applied" "Content revocation process shall not be applied"))))
        (cons 'descr-etsi-extension-supp-audio-lang-code-present (list (cons 'raw descr-etsi-extension-supp-audio-lang-code-present) (cons 'formatted (fmt-hex descr-etsi-extension-supp-audio-lang-code-present))))
        (cons 'descr-etsi-extension-supp-audio-lang-code (list (cons 'raw descr-etsi-extension-supp-audio-lang-code) (cons 'formatted (utf8->string descr-etsi-extension-supp-audio-lang-code))))
        (cons 'descr-etsi-extension-data (list (cons 'raw descr-etsi-extension-data) (cons 'formatted (fmt-bytes descr-etsi-extension-data))))
        (cons 'descr-ac3-sysa-bsid (list (cons 'raw descr-ac3-sysa-bsid) (cons 'formatted (fmt-hex descr-ac3-sysa-bsid))))
        (cons 'descr-ac3-sysa-bsmod (list (cons 'raw descr-ac3-sysa-bsmod) (cons 'formatted (fmt-hex descr-ac3-sysa-bsmod))))
        (cons 'descr-ac3-sysa-full-svc (list (cons 'raw descr-ac3-sysa-full-svc) (cons 'formatted (fmt-hex descr-ac3-sysa-full-svc))))
        (cons 'descr-ac3-sysa-langcode (list (cons 'raw descr-ac3-sysa-langcode) (cons 'formatted (fmt-hex descr-ac3-sysa-langcode))))
        (cons 'descr-ac3-sysa-langcode2 (list (cons 'raw descr-ac3-sysa-langcode2) (cons 'formatted (fmt-hex descr-ac3-sysa-langcode2))))
        (cons 'descr-ac3-sysa-mainid (list (cons 'raw descr-ac3-sysa-mainid) (cons 'formatted (fmt-hex descr-ac3-sysa-mainid))))
        (cons 'descr-ac3-sysa-reserved (list (cons 'raw descr-ac3-sysa-reserved) (cons 'formatted (fmt-hex descr-ac3-sysa-reserved))))
        (cons 'descr-ac3-sysa-asvcflags (list (cons 'raw descr-ac3-sysa-asvcflags) (cons 'formatted (fmt-hex descr-ac3-sysa-asvcflags))))
        (cons 'descr-ac3-sysa-textlen (list (cons 'raw descr-ac3-sysa-textlen) (cons 'formatted (fmt-hex descr-ac3-sysa-textlen))))
        (cons 'descr-ac3-sysa-textcode (list (cons 'raw descr-ac3-sysa-textcode) (cons 'formatted (fmt-hex descr-ac3-sysa-textcode))))
        (cons 'descr-ac3-sysa-lang1 (list (cons 'raw descr-ac3-sysa-lang1) (cons 'formatted (fmt-hex descr-ac3-sysa-lang1))))
        (cons 'descr-ac3-sysa-lang2 (list (cons 'raw descr-ac3-sysa-lang2) (cons 'formatted (fmt-hex descr-ac3-sysa-lang2))))
        (cons 'descr-ac3-sysa-lang1-bytes (list (cons 'raw descr-ac3-sysa-lang1-bytes) (cons 'formatted (utf8->string descr-ac3-sysa-lang1-bytes))))
        (cons 'descr-ac3-sysa-lang2-bytes (list (cons 'raw descr-ac3-sysa-lang2-bytes) (cons 'formatted (utf8->string descr-ac3-sysa-lang2-bytes))))
        (cons 'descr-ac3-additional-info (list (cons 'raw descr-ac3-additional-info) (cons 'formatted (fmt-bytes descr-ac3-additional-info))))
        (cons 'descr-nordig-lcd-v1-service-list-id (list (cons 'raw descr-nordig-lcd-v1-service-list-id) (cons 'formatted (fmt-hex descr-nordig-lcd-v1-service-list-id))))
        (cons 'descr-nordig-lcd-v1-service-list-visible-service-flag (list (cons 'raw descr-nordig-lcd-v1-service-list-visible-service-flag) (cons 'formatted (fmt-hex descr-nordig-lcd-v1-service-list-visible-service-flag))))
        (cons 'descr-nordig-lcd-v1-service-list-reserved (list (cons 'raw descr-nordig-lcd-v1-service-list-reserved) (cons 'formatted (fmt-hex descr-nordig-lcd-v1-service-list-reserved))))
        (cons 'descr-nordig-lcd-v1-service-list-logical-channel-number (list (cons 'raw descr-nordig-lcd-v1-service-list-logical-channel-number) (cons 'formatted (fmt-hex descr-nordig-lcd-v1-service-list-logical-channel-number))))
        (cons 'descr-nordig-lcd-v2-channel-list-id (list (cons 'raw descr-nordig-lcd-v2-channel-list-id) (cons 'formatted (fmt-hex descr-nordig-lcd-v2-channel-list-id))))
        (cons 'descr-nordig-lcd-v2-channel-list-name-length (list (cons 'raw descr-nordig-lcd-v2-channel-list-name-length) (cons 'formatted (number->string descr-nordig-lcd-v2-channel-list-name-length))))
        (cons 'descr-nordig-lcd-v2-channel-list-name (list (cons 'raw descr-nordig-lcd-v2-channel-list-name) (cons 'formatted (utf8->string descr-nordig-lcd-v2-channel-list-name))))
        (cons 'descr-nordig-lcd-v2-country-code (list (cons 'raw descr-nordig-lcd-v2-country-code) (cons 'formatted (utf8->string descr-nordig-lcd-v2-country-code))))
        (cons 'descr-nordig-lcd-v2-descriptor-length (list (cons 'raw descr-nordig-lcd-v2-descriptor-length) (cons 'formatted (number->string descr-nordig-lcd-v2-descriptor-length))))
        (cons 'descr-nordig-lcd-v2-service-id (list (cons 'raw descr-nordig-lcd-v2-service-id) (cons 'formatted (fmt-hex descr-nordig-lcd-v2-service-id))))
        (cons 'descr-nordig-lcd-v2-visible-service-flag (list (cons 'raw descr-nordig-lcd-v2-visible-service-flag) (cons 'formatted (fmt-hex descr-nordig-lcd-v2-visible-service-flag))))
        (cons 'descr-nordig-lcd-v2-reserved (list (cons 'raw descr-nordig-lcd-v2-reserved) (cons 'formatted (fmt-hex descr-nordig-lcd-v2-reserved))))
        (cons 'descr-nordig-lcd-v2-logical-channel-number (list (cons 'raw descr-nordig-lcd-v2-logical-channel-number) (cons 'formatted (fmt-hex descr-nordig-lcd-v2-logical-channel-number))))
        (cons 'descr-logon-initialize-group-id (list (cons 'raw descr-logon-initialize-group-id) (cons 'formatted (fmt-hex descr-logon-initialize-group-id))))
        (cons 'descr-logon-initialize-logon-id (list (cons 'raw descr-logon-initialize-logon-id) (cons 'formatted (fmt-hex descr-logon-initialize-logon-id))))
        (cons 'descr-logon-initialize-continuous-carrier-reserved (list (cons 'raw descr-logon-initialize-continuous-carrier-reserved) (cons 'formatted (fmt-hex descr-logon-initialize-continuous-carrier-reserved))))
        (cons 'descr-logon-initialize-continuous-carrier (list (cons 'raw descr-logon-initialize-continuous-carrier) (cons 'formatted (number->string descr-logon-initialize-continuous-carrier))))
        (cons 'descr-logon-initialize-security-handshake-required (list (cons 'raw descr-logon-initialize-security-handshake-required) (cons 'formatted (number->string descr-logon-initialize-security-handshake-required))))
        (cons 'descr-logon-initialize-prefix-flag (list (cons 'raw descr-logon-initialize-prefix-flag) (cons 'formatted (number->string descr-logon-initialize-prefix-flag))))
        (cons 'descr-logon-initialize-data-unit-labelling-flag (list (cons 'raw descr-logon-initialize-data-unit-labelling-flag) (cons 'formatted (number->string descr-logon-initialize-data-unit-labelling-flag))))
        (cons 'descr-logon-initialize-mini-slot-flag (list (cons 'raw descr-logon-initialize-mini-slot-flag) (cons 'formatted (number->string descr-logon-initialize-mini-slot-flag))))
        (cons 'descr-logon-initialize-contention-based-mini-slot-flag (list (cons 'raw descr-logon-initialize-contention-based-mini-slot-flag) (cons 'formatted (number->string descr-logon-initialize-contention-based-mini-slot-flag))))
        (cons 'descr-logon-initialize-capacity-type-flag-reserved (list (cons 'raw descr-logon-initialize-capacity-type-flag-reserved) (cons 'formatted (number->string descr-logon-initialize-capacity-type-flag-reserved))))
        (cons 'descr-logon-initialize-capacity-type-flag (list (cons 'raw descr-logon-initialize-capacity-type-flag) (cons 'formatted (number->string descr-logon-initialize-capacity-type-flag))))
        (cons 'descr-logon-initialize-traffic-burst-type (list (cons 'raw descr-logon-initialize-traffic-burst-type) (cons 'formatted (number->string descr-logon-initialize-traffic-burst-type))))
        (cons 'descr-logon-initialize-connectivity (list (cons 'raw descr-logon-initialize-connectivity) (cons 'formatted (fmt-hex descr-logon-initialize-connectivity))))
        (cons 'descr-logon-initialize-return-signalling-vpi-reserved (list (cons 'raw descr-logon-initialize-return-signalling-vpi-reserved) (cons 'formatted (fmt-hex descr-logon-initialize-return-signalling-vpi-reserved))))
        (cons 'descr-logon-initialize-return-signalling-vpi (list (cons 'raw descr-logon-initialize-return-signalling-vpi) (cons 'formatted (fmt-hex descr-logon-initialize-return-signalling-vpi))))
        (cons 'descr-logon-initialize-return-signalling-vci (list (cons 'raw descr-logon-initialize-return-signalling-vci) (cons 'formatted (fmt-hex descr-logon-initialize-return-signalling-vci))))
        (cons 'descr-logon-initialize-forward-signalling-vpi-reserved (list (cons 'raw descr-logon-initialize-forward-signalling-vpi-reserved) (cons 'formatted (fmt-hex descr-logon-initialize-forward-signalling-vpi-reserved))))
        (cons 'descr-logon-initialize-forward-signalling-vpi (list (cons 'raw descr-logon-initialize-forward-signalling-vpi) (cons 'formatted (fmt-hex descr-logon-initialize-forward-signalling-vpi))))
        (cons 'descr-logon-initialize-forward-signalling-vci (list (cons 'raw descr-logon-initialize-forward-signalling-vci) (cons 'formatted (fmt-hex descr-logon-initialize-forward-signalling-vci))))
        (cons 'descr-logon-initialize-return-vpi-reserved (list (cons 'raw descr-logon-initialize-return-vpi-reserved) (cons 'formatted (fmt-hex descr-logon-initialize-return-vpi-reserved))))
        (cons 'descr-logon-initialize-return-vpi (list (cons 'raw descr-logon-initialize-return-vpi) (cons 'formatted (fmt-hex descr-logon-initialize-return-vpi))))
        (cons 'descr-logon-initialize-return-vci (list (cons 'raw descr-logon-initialize-return-vci) (cons 'formatted (fmt-hex descr-logon-initialize-return-vci))))
        (cons 'descr-logon-initialize-return-trf-pid (list (cons 'raw descr-logon-initialize-return-trf-pid) (cons 'formatted (fmt-hex descr-logon-initialize-return-trf-pid))))
        (cons 'descr-logon-initialize-return-ctrl-mngm-pid-reserved (list (cons 'raw descr-logon-initialize-return-ctrl-mngm-pid-reserved) (cons 'formatted (fmt-hex descr-logon-initialize-return-ctrl-mngm-pid-reserved))))
        (cons 'descr-logon-initialize-return-ctrl-mngm-pid (list (cons 'raw descr-logon-initialize-return-ctrl-mngm-pid) (cons 'formatted (fmt-hex descr-logon-initialize-return-ctrl-mngm-pid))))
        (cons 'descr-logon-initialize-cra-level (list (cons 'raw descr-logon-initialize-cra-level) (cons 'formatted (number->string descr-logon-initialize-cra-level))))
        (cons 'descr-logon-initialize-vbdc-max-reserved (list (cons 'raw descr-logon-initialize-vbdc-max-reserved) (cons 'formatted (fmt-hex descr-logon-initialize-vbdc-max-reserved))))
        (cons 'descr-logon-initialize-vbdc-max (list (cons 'raw descr-logon-initialize-vbdc-max) (cons 'formatted (number->string descr-logon-initialize-vbdc-max))))
        (cons 'descr-logon-initialize-rbdc-max (list (cons 'raw descr-logon-initialize-rbdc-max) (cons 'formatted (number->string descr-logon-initialize-rbdc-max))))
        (cons 'descr-logon-initialize-rbdc-timeout (list (cons 'raw descr-logon-initialize-rbdc-timeout) (cons 'formatted (number->string descr-logon-initialize-rbdc-timeout))))
        (cons 'descr-rcs-content-table-id (list (cons 'raw descr-rcs-content-table-id) (cons 'formatted (fmt-hex descr-rcs-content-table-id))))
        (cons 'descr-ciplus-cl-cb-min (list (cons 'raw descr-ciplus-cl-cb-min) (cons 'formatted (fmt-hex descr-ciplus-cl-cb-min))))
        (cons 'descr-ciplus-cl-cb-max (list (cons 'raw descr-ciplus-cl-cb-max) (cons 'formatted (fmt-hex descr-ciplus-cl-cb-max))))
        (cons 'descr-ciplus-cl-lang (list (cons 'raw descr-ciplus-cl-lang) (cons 'formatted (utf8->string descr-ciplus-cl-lang))))
        (cons 'descr-ciplus-cl-label (list (cons 'raw descr-ciplus-cl-label) (cons 'formatted (utf8->string descr-ciplus-cl-label))))
        (cons 'descr-ciplus-svc-id (list (cons 'raw descr-ciplus-svc-id) (cons 'formatted (fmt-hex descr-ciplus-svc-id))))
        (cons 'descr-ciplus-svc-visible (list (cons 'raw descr-ciplus-svc-visible) (cons 'formatted (fmt-hex descr-ciplus-svc-visible))))
        (cons 'descr-ciplus-svc-selectable (list (cons 'raw descr-ciplus-svc-selectable) (cons 'formatted (fmt-hex descr-ciplus-svc-selectable))))
        (cons 'descr-ciplus-svc-lcn (list (cons 'raw descr-ciplus-svc-lcn) (cons 'formatted (number->string descr-ciplus-svc-lcn))))
        (cons 'descr-ciplus-prot-free-ci-mode (list (cons 'raw descr-ciplus-prot-free-ci-mode) (cons 'formatted (if (= descr-ciplus-prot-free-ci-mode 0) "CI+ protection not required" "CI+ protection required"))))
        (cons 'descr-ciplus-prot-match-brand-flag (list (cons 'raw descr-ciplus-prot-match-brand-flag) (cons 'formatted (if (= descr-ciplus-prot-match-brand-flag 0) "False" "True"))))
        (cons 'descr-ciplus-prot-num-entries (list (cons 'raw descr-ciplus-prot-num-entries) (cons 'formatted (number->string descr-ciplus-prot-num-entries))))
        (cons 'descr-ciplus-prot-brand-id (list (cons 'raw descr-ciplus-prot-brand-id) (cons 'formatted (fmt-hex descr-ciplus-prot-brand-id))))
        (cons 'descr-etsi-private-data (list (cons 'raw descr-etsi-private-data) (cons 'formatted (fmt-bytes descr-etsi-private-data))))
        (cons 'descriptor-length (list (cons 'raw descriptor-length) (cons 'formatted (number->string descriptor-length))))
        (cons 'descriptor-data (list (cons 'raw descriptor-data) (cons 'formatted (fmt-bytes descriptor-data))))
        )))

    (catch (e)
      (err (str "MPEG-DESCRIPTOR parse error: " e)))))

;; dissect-mpeg-descriptor: parse MPEG-DESCRIPTOR from bytevector
;; Returns (ok fields-alist) or (err message)