;; TODO: fixup LUN tracking so we can pass the proper LUN across to
;; dissect_scsi_xxx()
;;

;; jerboa-ethereal/dissectors/ndmp.ss
;; Auto-generated from wireshark/epan/dissectors/packet-ndmp.c

(import (jerboa prelude))

;; ── Protocol Helpers ─────────────────────────────────────────────────
(def (read-u8 buf offset)
  (if (>= offset (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u8-ref buf offset))))

(def (read-u16be buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness big)))))

(def (read-u24be buf offset)
  (if (> (+ offset 3) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (+ (* (bytevector-u8-ref buf offset) 65536)
             (* (bytevector-u8-ref buf (+ offset 1)) 256)
             (bytevector-u8-ref buf (+ offset 2))))))

(def (read-u32be buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness big)))))

(def (read-u16le buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness little)))))

(def (read-u32le buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness little)))))

(def (read-u64be buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness big)))))

(def (read-u64le buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness little)))))

(def (slice buf offset len)
  (if (> (+ offset len) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (let ((result (make-bytevector len)))
            (bytevector-copy! buf offset result 0 len)
            result))))

(def (extract-bits val mask shift)
  (bitwise-arithmetic-shift-right (bitwise-and val mask) shift))

(def (fmt-ipv4 addr)
  (let ((b0 (bitwise-arithmetic-shift-right addr 24))
        (b1 (bitwise-and (bitwise-arithmetic-shift-right addr 16) 255))
        (b2 (bitwise-and (bitwise-arithmetic-shift-right addr 8) 255))
        (b3 (bitwise-and addr 255)))
    (str b0 "." b1 "." b2 "." b3)))

(def (fmt-mac bytes)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bytes))
    ":"))

(def (fmt-hex val)
  (str "0x" (number->string val 16)))

(def (fmt-oct val)
  (str "0" (number->string val 8)))

(def (fmt-port port)
  (number->string port))

(def (fmt-bytes bv)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bv))
    " "))

(def (fmt-ipv6-address bytes)
  (let loop ((i 0) (parts '()))
    (if (>= i 16)
        (string-join (reverse parts) ":")
        (loop (+ i 2)
              (cons (let ((w (+ (* (bytevector-u8-ref bytes i) 256)
                                (bytevector-u8-ref bytes (+ i 1)))))
                      (number->string w 16))
                    parts)))))

;; ── Dissector ──────────────────────────────────────────────────────
(def (dissect-ndmp buffer)
  "Network Data Management Protocol"
  (try
    (let* (
           (fraglen (unwrap (read-u32be buffer 0)))
           (lastfrag (unwrap (read-u8 buffer 0)))
           (fragment-data (unwrap (slice buffer 4 1)))
           (auth-challenge (unwrap (slice buffer 20 64)))
           (butype-attr (unwrap (read-u32be buffer 84)))
           (fs-invalid (unwrap (read-u32be buffer 88)))
           (fs-invalid-used-inodes (extract-bits fs-invalid 0x10 4))
           (fs-invalid-total-inodes (extract-bits fs-invalid 0x8 3))
           (fs-invalid-avail-size (extract-bits fs-invalid 0x4 2))
           (fs-invalid-used-size (extract-bits fs-invalid 0x2 1))
           (fs-invalid-total-size (extract-bits fs-invalid 0x1 0))
           (tape-attr (unwrap (read-u32be buffer 92)))
           (tape-attr-unload (extract-bits tape-attr 0x2 1))
           (tape-attr-rewind (extract-bits tape-attr 0x1 0))
           (ext-version (unwrap (read-u32be buffer 96)))
           (ex-class-id (unwrap (read-u32be buffer 100)))
           (ex-class-version (unwrap (read-u32be buffer 108)))
           (scsi-controller (unwrap (read-u32be buffer 124)))
           (scsi-id (unwrap (read-u32be buffer 128)))
           (scsi-lun (unwrap (read-u32be buffer 132)))
           (execute-cdb-flags (unwrap (read-u32be buffer 136)))
           (execute-cdb-flags-data-in (extract-bits execute-cdb-flags 0x1 0))
           (execute-cdb-flags-data-out (extract-bits execute-cdb-flags 0x2 1))
           (execute-cdb-cdb-len (unwrap (read-u32be buffer 140)))
           (execute-cdb-timeout (unwrap (read-u32be buffer 148)))
           (execute-cdb-datain-len (unwrap (read-u32be buffer 152)))
           (execute-cdb-sns-len (unwrap (read-u32be buffer 156)))
           (execute-cdb-dataout-len (unwrap (read-u32be buffer 164)))
           (tape-invalid (unwrap (read-u32be buffer 172)))
           (tape-invalid-partition (extract-bits tape-invalid 0x40 6))
           (tape-invalid-space-remain (extract-bits tape-invalid 0x20 5))
           (tape-invalid-total-space (extract-bits tape-invalid 0x10 4))
           (tape-invalid-block-no (extract-bits tape-invalid 0x8 3))
           (tape-invalid-block-size (extract-bits tape-invalid 0x4 2))
           (tape-invalid-soft-errors (extract-bits tape-invalid 0x2 1))
           (tape-invalid-file-num (extract-bits tape-invalid 0x1 0))
           (tape-flags (unwrap (read-u32be buffer 176)))
           (tape-flags-unload (extract-bits tape-flags 0x40 6))
           (tape-flags-error (extract-bits tape-flags 0x20 5))
           (tape-flags-write-protect (extract-bits tape-flags 0x10 4))
           (tape-flags-no-rewind (extract-bits tape-flags 0x8 3))
           (tape-file-num (unwrap (read-u32be buffer 180)))
           (tape-soft-errors (unwrap (read-u32be buffer 184)))
           (tape-block-size (unwrap (read-u32be buffer 188)))
           (tape-block-no (unwrap (read-u32be buffer 192)))
           (tape-partition (unwrap (read-u32be buffer 196)))
           (resid-count (unwrap (read-u32be buffer 208)))
           (addr-ip (unwrap (read-u32be buffer 224)))
           (addr-tcp (unwrap (read-u32be buffer 228)))
           (addr-fcal-loop-id (unwrap (read-u32be buffer 232)))
           (record-num (unwrap (read-u32be buffer 256)))
           (data-written (unwrap (read-u64be buffer 260)))
           (bytes-left-to-read (unwrap (read-u64be buffer 276)))
           (record-size (unwrap (read-u32be buffer 324)))
           (log-message-id (unwrap (read-u32be buffer 336)))
           (version (unwrap (read-u32be buffer 352)))
           (seek-position (unwrap (read-u64be buffer 360)))
           (auth-digest (unwrap (slice buffer 372 16)))
           (count (unwrap (read-u32be buffer 392)))
           (file-owner (unwrap (read-u32be buffer 424)))
           (file-group (unwrap (read-u32be buffer 428)))
           (file-fattr (unwrap (read-u32be buffer 432)))
           (file-links (unwrap (read-u32be buffer 436)))
           (file-parent (unwrap (read-u64be buffer 464)))
           (file-node (unwrap (read-u64be buffer 492)))
           (file-fh-info (unwrap (read-u64be buffer 500)))
           (window-offset (unwrap (read-u64be buffer 528)))
           (window-length (unwrap (read-u64be buffer 536)))
           (sequence (unwrap (read-u32be buffer 544)))
           (reply-sequence (unwrap (read-u32be buffer 560)))
           )

      (ok (list
        (cons 'fraglen (list (cons 'raw fraglen) (cons 'formatted (number->string fraglen))))
        (cons 'lastfrag (list (cons 'raw lastfrag) (cons 'formatted (if (= lastfrag 0) "False" "True"))))
        (cons 'fragment-data (list (cons 'raw fragment-data) (cons 'formatted (fmt-bytes fragment-data))))
        (cons 'auth-challenge (list (cons 'raw auth-challenge) (cons 'formatted (fmt-bytes auth-challenge))))
        (cons 'butype-attr (list (cons 'raw butype-attr) (cons 'formatted (fmt-hex butype-attr))))
        (cons 'fs-invalid (list (cons 'raw fs-invalid) (cons 'formatted (fmt-hex fs-invalid))))
        (cons 'fs-invalid-used-inodes (list (cons 'raw fs-invalid-used-inodes) (cons 'formatted (if (= fs-invalid-used-inodes 0) "Used inode count is VALID" "Used inode count is INVALID"))))
        (cons 'fs-invalid-total-inodes (list (cons 'raw fs-invalid-total-inodes) (cons 'formatted (if (= fs-invalid-total-inodes 0) "Total inode count is VALID" "Total inode count is INVALID"))))
        (cons 'fs-invalid-avail-size (list (cons 'raw fs-invalid-avail-size) (cons 'formatted (if (= fs-invalid-avail-size 0) "Available size is VALID" "Available size is INVALID"))))
        (cons 'fs-invalid-used-size (list (cons 'raw fs-invalid-used-size) (cons 'formatted (if (= fs-invalid-used-size 0) "Used size is VALID" "Used size is INVALID"))))
        (cons 'fs-invalid-total-size (list (cons 'raw fs-invalid-total-size) (cons 'formatted (if (= fs-invalid-total-size 0) "Total size is VALID" "Total size is INVALID"))))
        (cons 'tape-attr (list (cons 'raw tape-attr) (cons 'formatted (fmt-hex tape-attr))))
        (cons 'tape-attr-unload (list (cons 'raw tape-attr-unload) (cons 'formatted (if (= tape-attr-unload 0) "Device does NOT support unload" "Device supports UNLOAD"))))
        (cons 'tape-attr-rewind (list (cons 'raw tape-attr-rewind) (cons 'formatted (if (= tape-attr-rewind 0) "Device does NOT support rewind" "Device supports REWIND"))))
        (cons 'ext-version (list (cons 'raw ext-version) (cons 'formatted (fmt-hex ext-version))))
        (cons 'ex-class-id (list (cons 'raw ex-class-id) (cons 'formatted (fmt-hex ex-class-id))))
        (cons 'ex-class-version (list (cons 'raw ex-class-version) (cons 'formatted (fmt-hex ex-class-version))))
        (cons 'scsi-controller (list (cons 'raw scsi-controller) (cons 'formatted (number->string scsi-controller))))
        (cons 'scsi-id (list (cons 'raw scsi-id) (cons 'formatted (number->string scsi-id))))
        (cons 'scsi-lun (list (cons 'raw scsi-lun) (cons 'formatted (number->string scsi-lun))))
        (cons 'execute-cdb-flags (list (cons 'raw execute-cdb-flags) (cons 'formatted (fmt-hex execute-cdb-flags))))
        (cons 'execute-cdb-flags-data-in (list (cons 'raw execute-cdb-flags-data-in) (cons 'formatted (if (= execute-cdb-flags-data-in 0) "Not set" "Set"))))
        (cons 'execute-cdb-flags-data-out (list (cons 'raw execute-cdb-flags-data-out) (cons 'formatted (if (= execute-cdb-flags-data-out 0) "Not set" "Set"))))
        (cons 'execute-cdb-cdb-len (list (cons 'raw execute-cdb-cdb-len) (cons 'formatted (number->string execute-cdb-cdb-len))))
        (cons 'execute-cdb-timeout (list (cons 'raw execute-cdb-timeout) (cons 'formatted (number->string execute-cdb-timeout))))
        (cons 'execute-cdb-datain-len (list (cons 'raw execute-cdb-datain-len) (cons 'formatted (number->string execute-cdb-datain-len))))
        (cons 'execute-cdb-sns-len (list (cons 'raw execute-cdb-sns-len) (cons 'formatted (number->string execute-cdb-sns-len))))
        (cons 'execute-cdb-dataout-len (list (cons 'raw execute-cdb-dataout-len) (cons 'formatted (number->string execute-cdb-dataout-len))))
        (cons 'tape-invalid (list (cons 'raw tape-invalid) (cons 'formatted (fmt-hex tape-invalid))))
        (cons 'tape-invalid-partition (list (cons 'raw tape-invalid-partition) (cons 'formatted (if (= tape-invalid-partition 0) "Partition is VALID" "Partition is INVALID"))))
        (cons 'tape-invalid-space-remain (list (cons 'raw tape-invalid-space-remain) (cons 'formatted (if (= tape-invalid-space-remain 0) "Space remaining is VALID" "Space remaining is INVALID"))))
        (cons 'tape-invalid-total-space (list (cons 'raw tape-invalid-total-space) (cons 'formatted (if (= tape-invalid-total-space 0) "Total space is VALID" "Total space is INVALID"))))
        (cons 'tape-invalid-block-no (list (cons 'raw tape-invalid-block-no) (cons 'formatted (if (= tape-invalid-block-no 0) "Block no is VALID" "Block no is INVALID"))))
        (cons 'tape-invalid-block-size (list (cons 'raw tape-invalid-block-size) (cons 'formatted (if (= tape-invalid-block-size 0) "Block size is VALID" "Block size is INVALID"))))
        (cons 'tape-invalid-soft-errors (list (cons 'raw tape-invalid-soft-errors) (cons 'formatted (if (= tape-invalid-soft-errors 0) "Soft errors is VALID" "Soft errors is INVALID"))))
        (cons 'tape-invalid-file-num (list (cons 'raw tape-invalid-file-num) (cons 'formatted (if (= tape-invalid-file-num 0) "File num is VALID" "File num is INVALID"))))
        (cons 'tape-flags (list (cons 'raw tape-flags) (cons 'formatted (fmt-hex tape-flags))))
        (cons 'tape-flags-unload (list (cons 'raw tape-flags-unload) (cons 'formatted (if (= tape-flags-unload 0) "This device does NOT support unload" "This device supports UNLOAD"))))
        (cons 'tape-flags-error (list (cons 'raw tape-flags-error) (cons 'formatted (if (= tape-flags-error 0) "This device shows NO errors" "This device shows ERROR"))))
        (cons 'tape-flags-write-protect (list (cons 'raw tape-flags-write-protect) (cons 'formatted (if (= tape-flags-write-protect 0) "This device is NOT write-protected" "This device is WRITE-PROTECTED"))))
        (cons 'tape-flags-no-rewind (list (cons 'raw tape-flags-no-rewind) (cons 'formatted (if (= tape-flags-no-rewind 0) "This device supports rewind" "This is a NON-REWINDING device"))))
        (cons 'tape-file-num (list (cons 'raw tape-file-num) (cons 'formatted (number->string tape-file-num))))
        (cons 'tape-soft-errors (list (cons 'raw tape-soft-errors) (cons 'formatted (number->string tape-soft-errors))))
        (cons 'tape-block-size (list (cons 'raw tape-block-size) (cons 'formatted (number->string tape-block-size))))
        (cons 'tape-block-no (list (cons 'raw tape-block-no) (cons 'formatted (number->string tape-block-no))))
        (cons 'tape-partition (list (cons 'raw tape-partition) (cons 'formatted (number->string tape-partition))))
        (cons 'resid-count (list (cons 'raw resid-count) (cons 'formatted (number->string resid-count))))
        (cons 'addr-ip (list (cons 'raw addr-ip) (cons 'formatted (fmt-ipv4 addr-ip))))
        (cons 'addr-tcp (list (cons 'raw addr-tcp) (cons 'formatted (number->string addr-tcp))))
        (cons 'addr-fcal-loop-id (list (cons 'raw addr-fcal-loop-id) (cons 'formatted (fmt-hex addr-fcal-loop-id))))
        (cons 'record-num (list (cons 'raw record-num) (cons 'formatted (number->string record-num))))
        (cons 'data-written (list (cons 'raw data-written) (cons 'formatted (number->string data-written))))
        (cons 'bytes-left-to-read (list (cons 'raw bytes-left-to-read) (cons 'formatted (number->string bytes-left-to-read))))
        (cons 'record-size (list (cons 'raw record-size) (cons 'formatted (number->string record-size))))
        (cons 'log-message-id (list (cons 'raw log-message-id) (cons 'formatted (number->string log-message-id))))
        (cons 'version (list (cons 'raw version) (cons 'formatted (number->string version))))
        (cons 'seek-position (list (cons 'raw seek-position) (cons 'formatted (number->string seek-position))))
        (cons 'auth-digest (list (cons 'raw auth-digest) (cons 'formatted (fmt-bytes auth-digest))))
        (cons 'count (list (cons 'raw count) (cons 'formatted (number->string count))))
        (cons 'file-owner (list (cons 'raw file-owner) (cons 'formatted (number->string file-owner))))
        (cons 'file-group (list (cons 'raw file-group) (cons 'formatted (number->string file-group))))
        (cons 'file-fattr (list (cons 'raw file-fattr) (cons 'formatted (fmt-hex file-fattr))))
        (cons 'file-links (list (cons 'raw file-links) (cons 'formatted (number->string file-links))))
        (cons 'file-parent (list (cons 'raw file-parent) (cons 'formatted (number->string file-parent))))
        (cons 'file-node (list (cons 'raw file-node) (cons 'formatted (number->string file-node))))
        (cons 'file-fh-info (list (cons 'raw file-fh-info) (cons 'formatted (number->string file-fh-info))))
        (cons 'window-offset (list (cons 'raw window-offset) (cons 'formatted (number->string window-offset))))
        (cons 'window-length (list (cons 'raw window-length) (cons 'formatted (number->string window-length))))
        (cons 'sequence (list (cons 'raw sequence) (cons 'formatted (number->string sequence))))
        (cons 'reply-sequence (list (cons 'raw reply-sequence) (cons 'formatted (number->string reply-sequence))))
        )))

    (catch (e)
      (err (str "NDMP parse error: " e)))))

;; dissect-ndmp: parse NDMP from bytevector
;; Returns (ok fields-alist) or (err message)