;; packet-netlink-ovs_flow.c
;; Routines for Open vSwitch flow netlink protocol dissection
;; Copyright 2026, Red Hat Inc.
;; By Timothy Redaelli <tredaelli@redhat.com>
;;
;; Wireshark - Network traffic analyzer
;; By Gerald Combs <gerald@wireshark.org>
;; Copyright 1998 Gerald Combs
;;
;; SPDX-License-Identifier: GPL-2.0-or-later
;;

;; jerboa-ethereal/dissectors/netlink-ovs-flow.ss
;; Auto-generated from wireshark/epan/dissectors/packet-netlink_ovs_flow.c

(import (jerboa prelude))

;; ── Protocol Helpers ─────────────────────────────────────────────────
(def (read-u8 buf offset)
  (if (>= offset (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u8-ref buf offset))))

(def (read-u16be buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness big)))))

(def (read-u24be buf offset)
  (if (> (+ offset 3) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (+ (* (bytevector-u8-ref buf offset) 65536)
             (* (bytevector-u8-ref buf (+ offset 1)) 256)
             (bytevector-u8-ref buf (+ offset 2))))))

(def (read-u32be buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness big)))))

(def (read-u16le buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness little)))))

(def (read-u32le buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness little)))))

(def (read-u64be buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness big)))))

(def (read-u64le buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness little)))))

(def (slice buf offset len)
  (if (> (+ offset len) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (let ((result (make-bytevector len)))
            (bytevector-copy! buf offset result 0 len)
            result))))

(def (extract-bits val mask shift)
  (bitwise-arithmetic-shift-right (bitwise-and val mask) shift))

(def (fmt-ipv4 addr)
  (let ((b0 (bitwise-arithmetic-shift-right addr 24))
        (b1 (bitwise-and (bitwise-arithmetic-shift-right addr 16) 255))
        (b2 (bitwise-and (bitwise-arithmetic-shift-right addr 8) 255))
        (b3 (bitwise-and addr 255)))
    (str b0 "." b1 "." b2 "." b3)))

(def (fmt-mac bytes)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bytes))
    ":"))

(def (fmt-hex val)
  (str "0x" (number->string val 16)))

(def (fmt-oct val)
  (str "0" (number->string val 8)))

(def (fmt-port port)
  (number->string port))

(def (fmt-bytes bv)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bv))
    " "))

(def (fmt-ipv6-address bytes)
  (let loop ((i 0) (parts '()))
    (if (>= i 16)
        (string-join (reverse parts) ":")
        (loop (+ i 2)
              (cons (let ((w (+ (* (bytevector-u8-ref bytes i) 256)
                                (bytevector-u8-ref bytes (+ i 1)))))
                      (number->string w 16))
                    parts)))))

;; ── Dissector ──────────────────────────────────────────────────────
(def (dissect-netlink-ovs-flow buffer)
  "Linux ovs_flow (Open vSwitch Flow) protocol"
  (try
    (let* (
           (flow-tunnel-ipv4-src (unwrap (read-u32be buffer 0)))
           (flow-tunnel-ipv4-dst (unwrap (read-u32be buffer 0)))
           (flow-tunnel-tos (unwrap (read-u8 buffer 0)))
           (flow-tunnel-ttl (unwrap (read-u8 buffer 0)))
           (flow-tunnel-geneve-opts (unwrap (slice buffer 0 1)))
           (flow-tunnel-tp-src (unwrap (read-u16be buffer 0)))
           (flow-tunnel-tp-dst (unwrap (read-u16be buffer 0)))
           (flow-tunnel-ipv6-src (unwrap (slice buffer 0 16)))
           (flow-tunnel-ipv6-dst (unwrap (slice buffer 0 16)))
           (flow-tunnel-erspan-opts (unwrap (slice buffer 0 1)))
           (flow-key-priority (unwrap (read-u32be buffer 0)))
           (flow-key-in-port (unwrap (read-u32be buffer 0)))
           (flow-key-eth-src (unwrap (slice buffer 0 6)))
           (flow-key-eth-dst (unwrap (slice buffer 0 6)))
           (flow-key-vlan-tci (unwrap (read-u16be buffer 0)))
           (flow-key-ethertype (unwrap (read-u16be buffer 0)))
           (flow-key-tcp-src (unwrap (read-u16be buffer 0)))
           (flow-key-tcp-dst (unwrap (read-u16be buffer 0)))
           (flow-key-udp-src (unwrap (read-u16be buffer 0)))
           (flow-key-udp-dst (unwrap (read-u16be buffer 0)))
           (flow-key-icmp-type (unwrap (read-u8 buffer 0)))
           (flow-key-icmp-code (unwrap (read-u8 buffer 0)))
           (flow-key-icmpv6-type (unwrap (read-u8 buffer 0)))
           (flow-key-icmpv6-code (unwrap (read-u8 buffer 0)))
           (flow-key-skb-mark (unwrap (read-u32be buffer 0)))
           (flow-key-sctp-src (unwrap (read-u16be buffer 0)))
           (flow-key-sctp-dst (unwrap (read-u16be buffer 0)))
           (flow-key-tcp-flags-value (unwrap (read-u16be buffer 0)))
           (flow-key-dp-hash (unwrap (read-u32be buffer 0)))
           (flow-key-recirc-id (unwrap (read-u32be buffer 0)))
           (flow-key-mpls-lse (unwrap (read-u32be buffer 0)))
           (flow-key-ct-state (unwrap (read-u32be buffer 0)))
           (flow-key-ct-zone (unwrap (read-u16be buffer 0)))
           (flow-key-ct-mark (unwrap (read-u32be buffer 0)))
           (flow-key-ct-labels (unwrap (slice buffer 0 1)))
           (flow-key-packet-type (unwrap (read-u32be buffer 0)))
           (flow-key-ipv6-exthdrs (unwrap (read-u16be buffer 0)))
           (flow-nat-ip-min (unwrap (slice buffer 0 1)))
           (flow-nat-ip-max (unwrap (slice buffer 0 1)))
           (flow-nat-proto-min (unwrap (read-u16be buffer 0)))
           (flow-nat-proto-max (unwrap (read-u16be buffer 0)))
           (flow-ct-zone (unwrap (read-u16be buffer 0)))
           (flow-ct-mark (unwrap (slice buffer 0 1)))
           (flow-ct-labels (unwrap (slice buffer 0 1)))
           (flow-ct-helper (unwrap (slice buffer 0 1)))
           (flow-ct-eventmask (unwrap (read-u32be buffer 0)))
           (flow-ct-timeout (unwrap (slice buffer 0 1)))
           (flow-userspace-pid (unwrap (read-u32be buffer 0)))
           (flow-userspace-userdata (unwrap (slice buffer 0 1)))
           (flow-userspace-egress-tun-port (unwrap (read-u32be buffer 0)))
           (flow-sample-probability (unwrap (read-u32be buffer 0)))
           (flow-action-output (unwrap (read-u32be buffer 0)))
           (flow-action-push-vlan-tpid (unwrap (read-u16be buffer 0)))
           (flow-action-push-vlan-tci (unwrap (read-u16be buffer 0)))
           (flow-action-recirc (unwrap (read-u32be buffer 0)))
           (flow-action-hash-alg (unwrap (read-u32be buffer 0)))
           (flow-action-hash-basis (unwrap (read-u32be buffer 0)))
           (flow-action-push-mpls-lse (unwrap (read-u32be buffer 0)))
           (flow-action-push-mpls-etype (unwrap (read-u16be buffer 0)))
           (flow-action-pop-mpls-etype (unwrap (read-u16be buffer 0)))
           (flow-action-trunc-max-len (unwrap (read-u32be buffer 0)))
           (flow-action-push-eth-src (unwrap (slice buffer 0 6)))
           (flow-action-push-eth-dst (unwrap (slice buffer 0 6)))
           (flow-action-meter (unwrap (read-u32be buffer 0)))
           (flow-action-drop (unwrap (read-u32be buffer 0)))
           (flow-stats-n-packets (unwrap (read-u64be buffer 0)))
           (flow-stats-n-bytes (unwrap (read-u64be buffer 0)))
           (flow-tcp-flags (unwrap (read-u8 buffer 0)))
           (flow-used (unwrap (read-u64be buffer 0)))
           (flow-ufid (unwrap (slice buffer 0 1)))
           (flow-ufid-flags (unwrap (read-u32be buffer 0)))
           (flow-dp-ifindex (unwrap (read-u32be buffer 0)))
           (flow-tunnel-id (unwrap (read-u64be buffer 16)))
           )

      (ok (list
        (cons 'flow-tunnel-ipv4-src (list (cons 'raw flow-tunnel-ipv4-src) (cons 'formatted (fmt-ipv4 flow-tunnel-ipv4-src))))
        (cons 'flow-tunnel-ipv4-dst (list (cons 'raw flow-tunnel-ipv4-dst) (cons 'formatted (fmt-ipv4 flow-tunnel-ipv4-dst))))
        (cons 'flow-tunnel-tos (list (cons 'raw flow-tunnel-tos) (cons 'formatted (fmt-hex flow-tunnel-tos))))
        (cons 'flow-tunnel-ttl (list (cons 'raw flow-tunnel-ttl) (cons 'formatted (number->string flow-tunnel-ttl))))
        (cons 'flow-tunnel-geneve-opts (list (cons 'raw flow-tunnel-geneve-opts) (cons 'formatted (fmt-bytes flow-tunnel-geneve-opts))))
        (cons 'flow-tunnel-tp-src (list (cons 'raw flow-tunnel-tp-src) (cons 'formatted (number->string flow-tunnel-tp-src))))
        (cons 'flow-tunnel-tp-dst (list (cons 'raw flow-tunnel-tp-dst) (cons 'formatted (number->string flow-tunnel-tp-dst))))
        (cons 'flow-tunnel-ipv6-src (list (cons 'raw flow-tunnel-ipv6-src) (cons 'formatted (fmt-ipv6-address flow-tunnel-ipv6-src))))
        (cons 'flow-tunnel-ipv6-dst (list (cons 'raw flow-tunnel-ipv6-dst) (cons 'formatted (fmt-ipv6-address flow-tunnel-ipv6-dst))))
        (cons 'flow-tunnel-erspan-opts (list (cons 'raw flow-tunnel-erspan-opts) (cons 'formatted (fmt-bytes flow-tunnel-erspan-opts))))
        (cons 'flow-key-priority (list (cons 'raw flow-key-priority) (cons 'formatted (number->string flow-key-priority))))
        (cons 'flow-key-in-port (list (cons 'raw flow-key-in-port) (cons 'formatted (number->string flow-key-in-port))))
        (cons 'flow-key-eth-src (list (cons 'raw flow-key-eth-src) (cons 'formatted (fmt-mac flow-key-eth-src))))
        (cons 'flow-key-eth-dst (list (cons 'raw flow-key-eth-dst) (cons 'formatted (fmt-mac flow-key-eth-dst))))
        (cons 'flow-key-vlan-tci (list (cons 'raw flow-key-vlan-tci) (cons 'formatted (fmt-hex flow-key-vlan-tci))))
        (cons 'flow-key-ethertype (list (cons 'raw flow-key-ethertype) (cons 'formatted (fmt-hex flow-key-ethertype))))
        (cons 'flow-key-tcp-src (list (cons 'raw flow-key-tcp-src) (cons 'formatted (number->string flow-key-tcp-src))))
        (cons 'flow-key-tcp-dst (list (cons 'raw flow-key-tcp-dst) (cons 'formatted (number->string flow-key-tcp-dst))))
        (cons 'flow-key-udp-src (list (cons 'raw flow-key-udp-src) (cons 'formatted (number->string flow-key-udp-src))))
        (cons 'flow-key-udp-dst (list (cons 'raw flow-key-udp-dst) (cons 'formatted (number->string flow-key-udp-dst))))
        (cons 'flow-key-icmp-type (list (cons 'raw flow-key-icmp-type) (cons 'formatted (number->string flow-key-icmp-type))))
        (cons 'flow-key-icmp-code (list (cons 'raw flow-key-icmp-code) (cons 'formatted (number->string flow-key-icmp-code))))
        (cons 'flow-key-icmpv6-type (list (cons 'raw flow-key-icmpv6-type) (cons 'formatted (number->string flow-key-icmpv6-type))))
        (cons 'flow-key-icmpv6-code (list (cons 'raw flow-key-icmpv6-code) (cons 'formatted (number->string flow-key-icmpv6-code))))
        (cons 'flow-key-skb-mark (list (cons 'raw flow-key-skb-mark) (cons 'formatted (fmt-hex flow-key-skb-mark))))
        (cons 'flow-key-sctp-src (list (cons 'raw flow-key-sctp-src) (cons 'formatted (number->string flow-key-sctp-src))))
        (cons 'flow-key-sctp-dst (list (cons 'raw flow-key-sctp-dst) (cons 'formatted (number->string flow-key-sctp-dst))))
        (cons 'flow-key-tcp-flags-value (list (cons 'raw flow-key-tcp-flags-value) (cons 'formatted (fmt-hex flow-key-tcp-flags-value))))
        (cons 'flow-key-dp-hash (list (cons 'raw flow-key-dp-hash) (cons 'formatted (fmt-hex flow-key-dp-hash))))
        (cons 'flow-key-recirc-id (list (cons 'raw flow-key-recirc-id) (cons 'formatted (number->string flow-key-recirc-id))))
        (cons 'flow-key-mpls-lse (list (cons 'raw flow-key-mpls-lse) (cons 'formatted (fmt-hex flow-key-mpls-lse))))
        (cons 'flow-key-ct-state (list (cons 'raw flow-key-ct-state) (cons 'formatted (fmt-hex flow-key-ct-state))))
        (cons 'flow-key-ct-zone (list (cons 'raw flow-key-ct-zone) (cons 'formatted (number->string flow-key-ct-zone))))
        (cons 'flow-key-ct-mark (list (cons 'raw flow-key-ct-mark) (cons 'formatted (fmt-hex flow-key-ct-mark))))
        (cons 'flow-key-ct-labels (list (cons 'raw flow-key-ct-labels) (cons 'formatted (fmt-bytes flow-key-ct-labels))))
        (cons 'flow-key-packet-type (list (cons 'raw flow-key-packet-type) (cons 'formatted (fmt-hex flow-key-packet-type))))
        (cons 'flow-key-ipv6-exthdrs (list (cons 'raw flow-key-ipv6-exthdrs) (cons 'formatted (fmt-hex flow-key-ipv6-exthdrs))))
        (cons 'flow-nat-ip-min (list (cons 'raw flow-nat-ip-min) (cons 'formatted (fmt-bytes flow-nat-ip-min))))
        (cons 'flow-nat-ip-max (list (cons 'raw flow-nat-ip-max) (cons 'formatted (fmt-bytes flow-nat-ip-max))))
        (cons 'flow-nat-proto-min (list (cons 'raw flow-nat-proto-min) (cons 'formatted (number->string flow-nat-proto-min))))
        (cons 'flow-nat-proto-max (list (cons 'raw flow-nat-proto-max) (cons 'formatted (number->string flow-nat-proto-max))))
        (cons 'flow-ct-zone (list (cons 'raw flow-ct-zone) (cons 'formatted (number->string flow-ct-zone))))
        (cons 'flow-ct-mark (list (cons 'raw flow-ct-mark) (cons 'formatted (fmt-bytes flow-ct-mark))))
        (cons 'flow-ct-labels (list (cons 'raw flow-ct-labels) (cons 'formatted (fmt-bytes flow-ct-labels))))
        (cons 'flow-ct-helper (list (cons 'raw flow-ct-helper) (cons 'formatted (utf8->string flow-ct-helper))))
        (cons 'flow-ct-eventmask (list (cons 'raw flow-ct-eventmask) (cons 'formatted (fmt-hex flow-ct-eventmask))))
        (cons 'flow-ct-timeout (list (cons 'raw flow-ct-timeout) (cons 'formatted (utf8->string flow-ct-timeout))))
        (cons 'flow-userspace-pid (list (cons 'raw flow-userspace-pid) (cons 'formatted (number->string flow-userspace-pid))))
        (cons 'flow-userspace-userdata (list (cons 'raw flow-userspace-userdata) (cons 'formatted (fmt-bytes flow-userspace-userdata))))
        (cons 'flow-userspace-egress-tun-port (list (cons 'raw flow-userspace-egress-tun-port) (cons 'formatted (number->string flow-userspace-egress-tun-port))))
        (cons 'flow-sample-probability (list (cons 'raw flow-sample-probability) (cons 'formatted (number->string flow-sample-probability))))
        (cons 'flow-action-output (list (cons 'raw flow-action-output) (cons 'formatted (number->string flow-action-output))))
        (cons 'flow-action-push-vlan-tpid (list (cons 'raw flow-action-push-vlan-tpid) (cons 'formatted (fmt-hex flow-action-push-vlan-tpid))))
        (cons 'flow-action-push-vlan-tci (list (cons 'raw flow-action-push-vlan-tci) (cons 'formatted (fmt-hex flow-action-push-vlan-tci))))
        (cons 'flow-action-recirc (list (cons 'raw flow-action-recirc) (cons 'formatted (number->string flow-action-recirc))))
        (cons 'flow-action-hash-alg (list (cons 'raw flow-action-hash-alg) (cons 'formatted (number->string flow-action-hash-alg))))
        (cons 'flow-action-hash-basis (list (cons 'raw flow-action-hash-basis) (cons 'formatted (fmt-hex flow-action-hash-basis))))
        (cons 'flow-action-push-mpls-lse (list (cons 'raw flow-action-push-mpls-lse) (cons 'formatted (fmt-hex flow-action-push-mpls-lse))))
        (cons 'flow-action-push-mpls-etype (list (cons 'raw flow-action-push-mpls-etype) (cons 'formatted (fmt-hex flow-action-push-mpls-etype))))
        (cons 'flow-action-pop-mpls-etype (list (cons 'raw flow-action-pop-mpls-etype) (cons 'formatted (fmt-hex flow-action-pop-mpls-etype))))
        (cons 'flow-action-trunc-max-len (list (cons 'raw flow-action-trunc-max-len) (cons 'formatted (number->string flow-action-trunc-max-len))))
        (cons 'flow-action-push-eth-src (list (cons 'raw flow-action-push-eth-src) (cons 'formatted (fmt-mac flow-action-push-eth-src))))
        (cons 'flow-action-push-eth-dst (list (cons 'raw flow-action-push-eth-dst) (cons 'formatted (fmt-mac flow-action-push-eth-dst))))
        (cons 'flow-action-meter (list (cons 'raw flow-action-meter) (cons 'formatted (number->string flow-action-meter))))
        (cons 'flow-action-drop (list (cons 'raw flow-action-drop) (cons 'formatted (number->string flow-action-drop))))
        (cons 'flow-stats-n-packets (list (cons 'raw flow-stats-n-packets) (cons 'formatted (number->string flow-stats-n-packets))))
        (cons 'flow-stats-n-bytes (list (cons 'raw flow-stats-n-bytes) (cons 'formatted (number->string flow-stats-n-bytes))))
        (cons 'flow-tcp-flags (list (cons 'raw flow-tcp-flags) (cons 'formatted (fmt-hex flow-tcp-flags))))
        (cons 'flow-used (list (cons 'raw flow-used) (cons 'formatted (number->string flow-used))))
        (cons 'flow-ufid (list (cons 'raw flow-ufid) (cons 'formatted (fmt-bytes flow-ufid))))
        (cons 'flow-ufid-flags (list (cons 'raw flow-ufid-flags) (cons 'formatted (fmt-hex flow-ufid-flags))))
        (cons 'flow-dp-ifindex (list (cons 'raw flow-dp-ifindex) (cons 'formatted (number->string flow-dp-ifindex))))
        (cons 'flow-tunnel-id (list (cons 'raw flow-tunnel-id) (cons 'formatted (fmt-hex flow-tunnel-id))))
        )))

    (catch (e)
      (err (str "NETLINK-OVS-FLOW parse error: " e)))))

;; dissect-netlink-ovs-flow: parse NETLINK-OVS-FLOW from bytevector
;; Returns (ok fields-alist) or (err message)