;; packet-netmon.c
;; Routines for Network Monitor capture dissection
;;
;; Wireshark - Network traffic analyzer
;; By Gerald Combs <gerald@wireshark.org>
;; Copyright 1998 Gerald Combs
;;
;; SPDX-License-Identifier: GPL-2.0-or-later
;;
;; Network Event Tracing event taken from:
;;
;; https://docs.microsoft.com/en-us/windows/win32/api/evntcons/ns-evntcons-event_header
;;

;; jerboa-ethereal/dissectors/netmon.ss
;; Auto-generated from wireshark/epan/dissectors/packet-netmon.c

(import (jerboa prelude))

;; ── Protocol Helpers ─────────────────────────────────────────────────
(def (read-u8 buf offset)
  (if (>= offset (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u8-ref buf offset))))

(def (read-u16be buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness big)))))

(def (read-u24be buf offset)
  (if (> (+ offset 3) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (+ (* (bytevector-u8-ref buf offset) 65536)
             (* (bytevector-u8-ref buf (+ offset 1)) 256)
             (bytevector-u8-ref buf (+ offset 2))))))

(def (read-u32be buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness big)))))

(def (read-u16le buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness little)))))

(def (read-u32le buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness little)))))

(def (read-u64be buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness big)))))

(def (read-u64le buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness little)))))

(def (slice buf offset len)
  (if (> (+ offset len) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (let ((result (make-bytevector len)))
            (bytevector-copy! buf offset result 0 len)
            result))))

(def (extract-bits val mask shift)
  (bitwise-arithmetic-shift-right (bitwise-and val mask) shift))

(def (fmt-ipv4 addr)
  (let ((b0 (bitwise-arithmetic-shift-right addr 24))
        (b1 (bitwise-and (bitwise-arithmetic-shift-right addr 16) 255))
        (b2 (bitwise-and (bitwise-arithmetic-shift-right addr 8) 255))
        (b3 (bitwise-and addr 255)))
    (str b0 "." b1 "." b2 "." b3)))

(def (fmt-mac bytes)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bytes))
    ":"))

(def (fmt-hex val)
  (str "0x" (number->string val 16)))

(def (fmt-oct val)
  (str "0" (number->string val 8)))

(def (fmt-port port)
  (number->string port))

(def (fmt-bytes bv)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bv))
    " "))

(def (fmt-ipv6-address bytes)
  (let loop ((i 0) (parts '()))
    (if (>= i 16)
        (string-join (reverse parts) ":")
        (loop (+ i 2)
              (cons (let ((w (+ (* (bytevector-u8-ref bytes i) 256)
                                (bytevector-u8-ref bytes (+ i 1)))))
                      (number->string w 16))
                    parts)))))

;; ── Dissector ──────────────────────────────────────────────────────
(def (dissect-netmon buffer)
  "Network Monitor Header"
  (try
    (let* (
           (header-description-comment (unwrap (slice buffer 0 1)))
           (header-title-comment (unwrap (slice buffer 0 1)))
           (event-size (unwrap (read-u16be buffer 0)))
           (filter-version (unwrap (read-u16be buffer 0)))
           (network-info-version (unwrap (read-u16be buffer 0)))
           (system-trace-buffer-size (unwrap (read-u32be buffer 0)))
           (event-header-type (unwrap (read-u16be buffer 2)))
           (network-info-adapter-count (unwrap (read-u16be buffer 2)))
           (event-flags (unwrap (read-u16le buffer 4)))
           (event-flags-extended-info (extract-bits event-flags 0x0 0))
           (event-flags-private-session (extract-bits event-flags 0x0 0))
           (event-flags-string-only (extract-bits event-flags 0x0 0))
           (event-flags-trace-message (extract-bits event-flags 0x0 0))
           (event-flags-no-cputime (extract-bits event-flags 0x0 0))
           (event-flags-32bit-header (extract-bits event-flags 0x0 0))
           (event-flags-64bit-header (extract-bits event-flags 0x0 0))
           (event-flags-classic-header (extract-bits event-flags 0x0 0))
           (network-info-computer-name (unwrap (slice buffer 4 1)))
           (network-info-friendly-name (unwrap (slice buffer 4 1)))
           (network-info-description (unwrap (slice buffer 4 1)))
           (network-info-miniport-guid (unwrap (slice buffer 4 1)))
           (network-info-media-type (unwrap (read-u32be buffer 4)))
           (system-trace-version (unwrap (read-u32be buffer 4)))
           (event-event-property (unwrap (read-u16le buffer 6)))
           (event-event-property-xml (extract-bits event-event-property 0x0 0))
           (event-event-property-forwarded-xml (extract-bits event-event-property 0x0 0))
           (event-event-property-legacy-eventlog (extract-bits event-event-property 0x0 0))
           (filter-app-major-version (unwrap (read-u32be buffer 6)))
           (event-thread-id (unwrap (read-u32be buffer 8)))
           (network-info-mtu (unwrap (read-u32be buffer 8)))
           (system-trace-provider-version (unwrap (read-u32be buffer 8)))
           (filter-app-minor-version (unwrap (read-u32be buffer 10)))
           (event-process-id (unwrap (read-u32be buffer 12)))
           (network-info-link-speed (unwrap (read-u64be buffer 12)))
           (system-trace-num-processors (unwrap (read-u32be buffer 12)))
           (filter-app-name (unwrap (slice buffer 14 1)))
           (filter-filter (unwrap (slice buffer 14 1)))
           (network-info-mac-address (unwrap (slice buffer 20 6)))
           (event-provider-id (unwrap (slice buffer 24 16)))
           (system-trace-timer-resolution (unwrap (read-u32be buffer 24)))
           (network-info-ipv4-count (unwrap (read-u16be buffer 26)))
           (network-info-ipv6-count (unwrap (read-u16be buffer 28)))
           (system-trace-max-file-size (unwrap (read-u32be buffer 28)))
           (network-info-gateway-count (unwrap (read-u16be buffer 30)))
           (network-info-dhcp-server-count (unwrap (read-u16be buffer 32)))
           (system-trace-log-file-mode (unwrap (read-u32be buffer 32)))
           (network-info-dns-ipv4-count (unwrap (read-u16be buffer 34)))
           (network-info-dns-ipv6-count (unwrap (read-u16be buffer 36)))
           (system-trace-buffers-written (unwrap (read-u32be buffer 36)))
           (network-info-ipv4 (unwrap (read-u32be buffer 38)))
           (event-event-desc-id (unwrap (read-u16be buffer 40)))
           (system-trace-start-buffers (unwrap (read-u32be buffer 40)))
           (event-event-desc-version (unwrap (read-u8 buffer 42)))
           (network-info-subnet (unwrap (read-u32be buffer 42)))
           (event-event-desc-channel (unwrap (read-u8 buffer 43)))
           (system-trace-pointers-size (unwrap (read-u32be buffer 44)))
           (event-event-desc-task (unwrap (read-u16be buffer 46)))
           (network-info-ipv6 (unwrap (slice buffer 46 16)))
           (event-event-desc-keyword (unwrap (read-u64be buffer 48)))
           (system-trace-events-lost (unwrap (read-u32be buffer 48)))
           (system-trace-cpu-speed (unwrap (read-u32be buffer 52)))
           (event-kernel-time (unwrap (read-u32be buffer 56)))
           (system-trace-time-zone-info (unwrap (slice buffer 56 176)))
           (event-user-time (unwrap (read-u32be buffer 60)))
           (network-info-gateway (unwrap (read-u32be buffer 62)))
           (event-processor-time (unwrap (read-u64be buffer 64)))
           (network-info-dhcp-server (unwrap (read-u32be buffer 66)))
           (process-page-fault-count (unwrap (read-u32be buffer 68)))
           (network-info-dns-ipv4 (unwrap (read-u32be buffer 70)))
           (event-activity-id (unwrap (slice buffer 72 16)))
           (process-handle-count (unwrap (read-u32be buffer 72)))
           (network-info-dns-ipv6 (unwrap (slice buffer 74 16)))
           (process-reserved (unwrap (read-u32be buffer 76)))
           (process-peak-virtual-size (unwrap (read-u32be buffer 80)))
           (process-peak-working-set-size (unwrap (read-u32be buffer 84)))
           (event-processor-number (unwrap (read-u8 buffer 88)))
           (process-peak-page-file-usage (unwrap (read-u32be buffer 88)))
           (event-alignment (unwrap (read-u8 buffer 89)))
           (event-logger-id (unwrap (read-u16be buffer 90)))
           (event-extended-data-count (unwrap (read-u16be buffer 92)))
           (process-quota-peak-paged-pool-usage (unwrap (read-u32be buffer 92)))
           (event-user-data-length (unwrap (read-u16be buffer 94)))
           (event-reassembled (unwrap (read-u16be buffer 96)))
           (process-quota-peak-non-paged-pool-usage (unwrap (read-u32be buffer 96)))
           (event-extended-data-reserved (unwrap (read-u16be buffer 97)))
           (event-extended-data-type (unwrap (read-u16be buffer 99)))
           (process-virtual-size (unwrap (read-u32be buffer 100)))
           (event-extended-data-linkage (unwrap (read-u8 buffer 101)))
           (event-extended-data-reserved2 (unwrap (read-u16be buffer 101)))
           (event-extended-data-size (unwrap (read-u16be buffer 103)))
           (process-workingset-size (unwrap (read-u32be buffer 104)))
           (process-pagefile-usage (unwrap (read-u32be buffer 108)))
           (process-quota-paged-pool-usage (unwrap (read-u32be buffer 112)))
           (process-quota-non-paged-pool-usage (unwrap (read-u32be buffer 116)))
           (process-private-page-count (unwrap (read-u32be buffer 120)))
           (process-directory-table-base32 (unwrap (read-u32be buffer 128)))
           (process-process-id (unwrap (read-u32be buffer 132)))
           (process-parent-id (unwrap (read-u32be buffer 136)))
           (process-session-id (unwrap (read-u32be buffer 140)))
           (process-exit-status (unwrap (read-u32be buffer 144)))
           (process-unknown (unwrap (slice buffer 164 8)))
           (process-image-file-name (unwrap (slice buffer 172 1)))
           (process-command-line (unwrap (slice buffer 172 1)))
           (system-trace-perf-freq (unwrap (read-u64be buffer 240)))
           (system-trace-reserved-flags (unwrap (read-u32be buffer 256)))
           (system-trace-buffers-lost (unwrap (read-u32be buffer 260)))
           (system-trace-session-name (unwrap (slice buffer 264 1)))
           (system-trace-log-file-name (unwrap (slice buffer 264 1)))
           (system-trace-group-mask1 (unwrap (read-u32be buffer 264)))
           (system-trace-group-mask2 (unwrap (read-u32be buffer 268)))
           (system-trace-group-mask3 (unwrap (read-u32be buffer 272)))
           (system-trace-group-mask4 (unwrap (read-u32be buffer 276)))
           (system-trace-group-mask5 (unwrap (read-u32be buffer 280)))
           (system-trace-group-mask6 (unwrap (read-u32be buffer 284)))
           (system-trace-group-mask7 (unwrap (read-u32be buffer 288)))
           (system-trace-group-mask8 (unwrap (read-u32be buffer 292)))
           (system-trace-kernel-event-version (unwrap (read-u32be buffer 296)))
           (system-config-nic-name (unwrap (slice buffer 6800 512)))
           (system-config-index (unwrap (read-u32be buffer 7312)))
           (system-config-physical-addr-str (unwrap (slice buffer 7320 16)))
           (system-config-ip-address (unwrap (read-u32be buffer 7340)))
           (system-config-subnet-mask (unwrap (read-u32be buffer 7344)))
           (system-config-dhcp-server (unwrap (read-u32be buffer 7348)))
           (system-config-gateway (unwrap (read-u32be buffer 7352)))
           (system-config-primary-wins-server (unwrap (read-u32be buffer 7356)))
           (system-config-secondary-wins-server (unwrap (read-u32be buffer 7360)))
           (system-config-dns-server1 (unwrap (read-u32be buffer 7364)))
           (system-config-dns-server2 (unwrap (read-u32be buffer 7368)))
           (system-config-dns-server3 (unwrap (read-u32be buffer 7372)))
           (system-config-dns-server4 (unwrap (read-u32be buffer 7376)))
           (system-config-data (unwrap (read-u32be buffer 7380)))
           (system-config-mhz (unwrap (read-u32be buffer 10656)))
           (system-config-num-processors (unwrap (read-u32be buffer 10660)))
           (system-config-mem-size (unwrap (read-u32be buffer 10664)))
           (system-config-page-size (unwrap (read-u32be buffer 10668)))
           (system-config-allocation-granularity (unwrap (read-u32be buffer 10672)))
           (system-config-computer-name (unwrap (slice buffer 10676 512)))
           (system-config-domain-name (unwrap (slice buffer 11188 268)))
           (system-config-sectors-per-track (unwrap (read-u32be buffer 11464)))
           (system-config-tracks-per-cylinder (unwrap (read-u32be buffer 11468)))
           (system-config-cylinders (unwrap (read-u64be buffer 11472)))
           (system-config-scsi-port (unwrap (read-u32be buffer 11480)))
           (system-config-scsi-path (unwrap (read-u32be buffer 11484)))
           (system-config-scsi-target (unwrap (read-u32be buffer 11488)))
           (system-config-scsi-lun (unwrap (read-u32be buffer 11492)))
           (system-config-manufacturer (unwrap (slice buffer 11496 512)))
           (system-config-partition-count (unwrap (read-u32be buffer 12008)))
           (system-config-write-cache-enabled (unwrap (read-u8 buffer 12012)))
           (system-config-boot-drive-letter (unwrap (slice buffer 12014 6)))
           (system-config-spare (unwrap (slice buffer 12020 4)))
           (system-config-start-offset (unwrap (read-u64be buffer 12024)))
           (system-config-partition-size (unwrap (read-u64be buffer 12032)))
           (system-config-disk-number (unwrap (read-u32be buffer 12040)))
           (system-config-size (unwrap (read-u32be buffer 12044)))
           (system-config-drive-type (unwrap (read-u32be buffer 12048)))
           (system-config-drive-letter (unwrap (slice buffer 12052 8)))
           (system-config-partition-number (unwrap (read-u32be buffer 12064)))
           (system-config-sectors-per-cluster (unwrap (read-u32be buffer 12068)))
           (system-config-bytes-per-sector (unwrap (read-u32be buffer 12072)))
           (system-config-num-free-clusters (unwrap (read-u64be buffer 12080)))
           (system-config-total-num-clusters (unwrap (read-u64be buffer 12088)))
           (system-config-file-system (unwrap (slice buffer 12096 32)))
           (system-config-volume-ext (unwrap (read-u32be buffer 12128)))
           (system-config-physical-addr (unwrap (read-u64be buffer 12136)))
           (system-config-physical-addr-len (unwrap (read-u32be buffer 12144)))
           (system-config-ipv4-index (unwrap (read-u32be buffer 12148)))
           (system-config-ipv6-index (unwrap (read-u32be buffer 12152)))
           (system-config-nic-description (unwrap (slice buffer 12156 1)))
           (system-config-ipaddresses (unwrap (slice buffer 12156 1)))
           (system-config-dns-server-addresses (unwrap (slice buffer 12156 1)))
           (system-config-memory-size (unwrap (read-u32be buffer 12156)))
           (system-config-x-resolution (unwrap (read-u32be buffer 12160)))
           (system-config-y-resolution (unwrap (read-u32be buffer 12164)))
           (system-config-bits-per-pixel (unwrap (read-u32be buffer 12168)))
           (system-config-vrefresh (unwrap (read-u32be buffer 12172)))
           (system-config-chip-type (unwrap (slice buffer 12176 512)))
           (system-config-dac-type (unwrap (slice buffer 12688 512)))
           (system-config-adapter-string (unwrap (slice buffer 13200 512)))
           (system-config-bios-string (unwrap (slice buffer 13712 512)))
           (system-config-state-flags (unwrap (read-u32be buffer 14736)))
           (system-config-s1 (unwrap (read-u8 buffer 14752)))
           (system-config-s2 (unwrap (read-u8 buffer 14753)))
           (system-config-s3 (unwrap (read-u8 buffer 14754)))
           (system-config-s4 (unwrap (read-u8 buffer 14755)))
           (system-config-s5 (unwrap (read-u8 buffer 14756)))
           (system-config-tcb-table-partitions (unwrap (read-u32be buffer 14760)))
           (system-config-max-hash-table-size (unwrap (read-u32be buffer 14764)))
           (system-config-max-user-port (unwrap (read-u32be buffer 14768)))
           (system-config-tcp-timed-wait-delay (unwrap (read-u32be buffer 14772)))
           (system-config-target-id (unwrap (read-u32be buffer 14804)))
           (system-config-device-type (unwrap (read-u32be buffer 14808)))
           (system-config-device-timing-mode (unwrap (read-u32be buffer 14812)))
           (system-config-location-information-len (unwrap (read-u32be buffer 14816)))
           (system-config-location-information (unwrap (slice buffer 14820 1)))
           (system-config-system-manufacturer (unwrap (slice buffer 14820 1)))
           (system-config-system-product-name (unwrap (slice buffer 14820 1)))
           (system-config-bios-date (unwrap (slice buffer 14820 1)))
           (system-config-bios-version (unwrap (slice buffer 14820 1)))
           (system-config-process-id (unwrap (read-u32be buffer 14820)))
           (system-config-service-state (unwrap (read-u32be buffer 14824)))
           (system-config-sub-process-tag (unwrap (read-u32be buffer 14828)))
           (system-config-service-name (unwrap (slice buffer 14832 1)))
           (system-config-display-name (unwrap (slice buffer 14832 1)))
           (system-config-process-name (unwrap (slice buffer 14832 1)))
           (system-config-load-order-group (unwrap (slice buffer 14832 1)))
           (system-config-svc-host-group (unwrap (slice buffer 14832 1)))
           (system-config-irq-affinity (unwrap (read-u64be buffer 14832)))
           (system-config-irq-group (unwrap (read-u16be buffer 14840)))
           (system-config-pad (unwrap (slice buffer 14842 2)))
           (system-config-irq-num (unwrap (read-u32be buffer 14844)))
           (system-config-device-id-len (unwrap (read-u32be buffer 14852)))
           (system-config-device-desc-len (unwrap (read-u32be buffer 14856)))
           (system-config-friendly-name-len (unwrap (read-u32be buffer 14860)))
           (system-config-device-id (unwrap (slice buffer 14864 1)))
           (system-config-device-desc (unwrap (slice buffer 14864 1)))
           (system-config-friendly-name (unwrap (slice buffer 14864 1)))
           (system-config-pdo-name (unwrap (slice buffer 14864 1)))
           )

      (ok (list
        (cons 'header-description-comment (list (cons 'raw header-description-comment) (cons 'formatted (utf8->string header-description-comment))))
        (cons 'header-title-comment (list (cons 'raw header-title-comment) (cons 'formatted (utf8->string header-title-comment))))
        (cons 'event-size (list (cons 'raw event-size) (cons 'formatted (number->string event-size))))
        (cons 'filter-version (list (cons 'raw filter-version) (cons 'formatted (number->string filter-version))))
        (cons 'network-info-version (list (cons 'raw network-info-version) (cons 'formatted (number->string network-info-version))))
        (cons 'system-trace-buffer-size (list (cons 'raw system-trace-buffer-size) (cons 'formatted (number->string system-trace-buffer-size))))
        (cons 'event-header-type (list (cons 'raw event-header-type) (cons 'formatted (number->string event-header-type))))
        (cons 'network-info-adapter-count (list (cons 'raw network-info-adapter-count) (cons 'formatted (number->string network-info-adapter-count))))
        (cons 'event-flags (list (cons 'raw event-flags) (cons 'formatted (fmt-hex event-flags))))
        (cons 'event-flags-extended-info (list (cons 'raw event-flags-extended-info) (cons 'formatted (if (= event-flags-extended-info 0) "Not set" "Set"))))
        (cons 'event-flags-private-session (list (cons 'raw event-flags-private-session) (cons 'formatted (if (= event-flags-private-session 0) "Not set" "Set"))))
        (cons 'event-flags-string-only (list (cons 'raw event-flags-string-only) (cons 'formatted (if (= event-flags-string-only 0) "Not set" "Set"))))
        (cons 'event-flags-trace-message (list (cons 'raw event-flags-trace-message) (cons 'formatted (if (= event-flags-trace-message 0) "Not set" "Set"))))
        (cons 'event-flags-no-cputime (list (cons 'raw event-flags-no-cputime) (cons 'formatted (if (= event-flags-no-cputime 0) "Not set" "Set"))))
        (cons 'event-flags-32bit-header (list (cons 'raw event-flags-32bit-header) (cons 'formatted (if (= event-flags-32bit-header 0) "Not set" "Set"))))
        (cons 'event-flags-64bit-header (list (cons 'raw event-flags-64bit-header) (cons 'formatted (if (= event-flags-64bit-header 0) "Not set" "Set"))))
        (cons 'event-flags-classic-header (list (cons 'raw event-flags-classic-header) (cons 'formatted (if (= event-flags-classic-header 0) "Not set" "Set"))))
        (cons 'network-info-computer-name (list (cons 'raw network-info-computer-name) (cons 'formatted (utf8->string network-info-computer-name))))
        (cons 'network-info-friendly-name (list (cons 'raw network-info-friendly-name) (cons 'formatted (utf8->string network-info-friendly-name))))
        (cons 'network-info-description (list (cons 'raw network-info-description) (cons 'formatted (utf8->string network-info-description))))
        (cons 'network-info-miniport-guid (list (cons 'raw network-info-miniport-guid) (cons 'formatted (utf8->string network-info-miniport-guid))))
        (cons 'network-info-media-type (list (cons 'raw network-info-media-type) (cons 'formatted (number->string network-info-media-type))))
        (cons 'system-trace-version (list (cons 'raw system-trace-version) (cons 'formatted (fmt-hex system-trace-version))))
        (cons 'event-event-property (list (cons 'raw event-event-property) (cons 'formatted (fmt-hex event-event-property))))
        (cons 'event-event-property-xml (list (cons 'raw event-event-property-xml) (cons 'formatted (if (= event-event-property-xml 0) "Not set" "Set"))))
        (cons 'event-event-property-forwarded-xml (list (cons 'raw event-event-property-forwarded-xml) (cons 'formatted (if (= event-event-property-forwarded-xml 0) "Not set" "Set"))))
        (cons 'event-event-property-legacy-eventlog (list (cons 'raw event-event-property-legacy-eventlog) (cons 'formatted (if (= event-event-property-legacy-eventlog 0) "Not set" "Set"))))
        (cons 'filter-app-major-version (list (cons 'raw filter-app-major-version) (cons 'formatted (number->string filter-app-major-version))))
        (cons 'event-thread-id (list (cons 'raw event-thread-id) (cons 'formatted (number->string event-thread-id))))
        (cons 'network-info-mtu (list (cons 'raw network-info-mtu) (cons 'formatted (number->string network-info-mtu))))
        (cons 'system-trace-provider-version (list (cons 'raw system-trace-provider-version) (cons 'formatted (number->string system-trace-provider-version))))
        (cons 'filter-app-minor-version (list (cons 'raw filter-app-minor-version) (cons 'formatted (number->string filter-app-minor-version))))
        (cons 'event-process-id (list (cons 'raw event-process-id) (cons 'formatted (number->string event-process-id))))
        (cons 'network-info-link-speed (list (cons 'raw network-info-link-speed) (cons 'formatted (number->string network-info-link-speed))))
        (cons 'system-trace-num-processors (list (cons 'raw system-trace-num-processors) (cons 'formatted (number->string system-trace-num-processors))))
        (cons 'filter-app-name (list (cons 'raw filter-app-name) (cons 'formatted (utf8->string filter-app-name))))
        (cons 'filter-filter (list (cons 'raw filter-filter) (cons 'formatted (utf8->string filter-filter))))
        (cons 'network-info-mac-address (list (cons 'raw network-info-mac-address) (cons 'formatted (fmt-mac network-info-mac-address))))
        (cons 'event-provider-id (list (cons 'raw event-provider-id) (cons 'formatted (fmt-bytes event-provider-id))))
        (cons 'system-trace-timer-resolution (list (cons 'raw system-trace-timer-resolution) (cons 'formatted (number->string system-trace-timer-resolution))))
        (cons 'network-info-ipv4-count (list (cons 'raw network-info-ipv4-count) (cons 'formatted (number->string network-info-ipv4-count))))
        (cons 'network-info-ipv6-count (list (cons 'raw network-info-ipv6-count) (cons 'formatted (number->string network-info-ipv6-count))))
        (cons 'system-trace-max-file-size (list (cons 'raw system-trace-max-file-size) (cons 'formatted (number->string system-trace-max-file-size))))
        (cons 'network-info-gateway-count (list (cons 'raw network-info-gateway-count) (cons 'formatted (number->string network-info-gateway-count))))
        (cons 'network-info-dhcp-server-count (list (cons 'raw network-info-dhcp-server-count) (cons 'formatted (number->string network-info-dhcp-server-count))))
        (cons 'system-trace-log-file-mode (list (cons 'raw system-trace-log-file-mode) (cons 'formatted (number->string system-trace-log-file-mode))))
        (cons 'network-info-dns-ipv4-count (list (cons 'raw network-info-dns-ipv4-count) (cons 'formatted (number->string network-info-dns-ipv4-count))))
        (cons 'network-info-dns-ipv6-count (list (cons 'raw network-info-dns-ipv6-count) (cons 'formatted (number->string network-info-dns-ipv6-count))))
        (cons 'system-trace-buffers-written (list (cons 'raw system-trace-buffers-written) (cons 'formatted (number->string system-trace-buffers-written))))
        (cons 'network-info-ipv4 (list (cons 'raw network-info-ipv4) (cons 'formatted (fmt-ipv4 network-info-ipv4))))
        (cons 'event-event-desc-id (list (cons 'raw event-event-desc-id) (cons 'formatted (number->string event-event-desc-id))))
        (cons 'system-trace-start-buffers (list (cons 'raw system-trace-start-buffers) (cons 'formatted (number->string system-trace-start-buffers))))
        (cons 'event-event-desc-version (list (cons 'raw event-event-desc-version) (cons 'formatted (number->string event-event-desc-version))))
        (cons 'network-info-subnet (list (cons 'raw network-info-subnet) (cons 'formatted (fmt-ipv4 network-info-subnet))))
        (cons 'event-event-desc-channel (list (cons 'raw event-event-desc-channel) (cons 'formatted (number->string event-event-desc-channel))))
        (cons 'system-trace-pointers-size (list (cons 'raw system-trace-pointers-size) (cons 'formatted (number->string system-trace-pointers-size))))
        (cons 'event-event-desc-task (list (cons 'raw event-event-desc-task) (cons 'formatted (number->string event-event-desc-task))))
        (cons 'network-info-ipv6 (list (cons 'raw network-info-ipv6) (cons 'formatted (fmt-ipv6-address network-info-ipv6))))
        (cons 'event-event-desc-keyword (list (cons 'raw event-event-desc-keyword) (cons 'formatted (fmt-hex event-event-desc-keyword))))
        (cons 'system-trace-events-lost (list (cons 'raw system-trace-events-lost) (cons 'formatted (number->string system-trace-events-lost))))
        (cons 'system-trace-cpu-speed (list (cons 'raw system-trace-cpu-speed) (cons 'formatted (number->string system-trace-cpu-speed))))
        (cons 'event-kernel-time (list (cons 'raw event-kernel-time) (cons 'formatted (number->string event-kernel-time))))
        (cons 'system-trace-time-zone-info (list (cons 'raw system-trace-time-zone-info) (cons 'formatted (fmt-bytes system-trace-time-zone-info))))
        (cons 'event-user-time (list (cons 'raw event-user-time) (cons 'formatted (number->string event-user-time))))
        (cons 'network-info-gateway (list (cons 'raw network-info-gateway) (cons 'formatted (fmt-ipv4 network-info-gateway))))
        (cons 'event-processor-time (list (cons 'raw event-processor-time) (cons 'formatted (number->string event-processor-time))))
        (cons 'network-info-dhcp-server (list (cons 'raw network-info-dhcp-server) (cons 'formatted (fmt-ipv4 network-info-dhcp-server))))
        (cons 'process-page-fault-count (list (cons 'raw process-page-fault-count) (cons 'formatted (number->string process-page-fault-count))))
        (cons 'network-info-dns-ipv4 (list (cons 'raw network-info-dns-ipv4) (cons 'formatted (fmt-ipv4 network-info-dns-ipv4))))
        (cons 'event-activity-id (list (cons 'raw event-activity-id) (cons 'formatted (fmt-bytes event-activity-id))))
        (cons 'process-handle-count (list (cons 'raw process-handle-count) (cons 'formatted (number->string process-handle-count))))
        (cons 'network-info-dns-ipv6 (list (cons 'raw network-info-dns-ipv6) (cons 'formatted (fmt-ipv6-address network-info-dns-ipv6))))
        (cons 'process-reserved (list (cons 'raw process-reserved) (cons 'formatted (number->string process-reserved))))
        (cons 'process-peak-virtual-size (list (cons 'raw process-peak-virtual-size) (cons 'formatted (number->string process-peak-virtual-size))))
        (cons 'process-peak-working-set-size (list (cons 'raw process-peak-working-set-size) (cons 'formatted (number->string process-peak-working-set-size))))
        (cons 'event-processor-number (list (cons 'raw event-processor-number) (cons 'formatted (number->string event-processor-number))))
        (cons 'process-peak-page-file-usage (list (cons 'raw process-peak-page-file-usage) (cons 'formatted (number->string process-peak-page-file-usage))))
        (cons 'event-alignment (list (cons 'raw event-alignment) (cons 'formatted (number->string event-alignment))))
        (cons 'event-logger-id (list (cons 'raw event-logger-id) (cons 'formatted (number->string event-logger-id))))
        (cons 'event-extended-data-count (list (cons 'raw event-extended-data-count) (cons 'formatted (number->string event-extended-data-count))))
        (cons 'process-quota-peak-paged-pool-usage (list (cons 'raw process-quota-peak-paged-pool-usage) (cons 'formatted (number->string process-quota-peak-paged-pool-usage))))
        (cons 'event-user-data-length (list (cons 'raw event-user-data-length) (cons 'formatted (number->string event-user-data-length))))
        (cons 'event-reassembled (list (cons 'raw event-reassembled) (cons 'formatted (number->string event-reassembled))))
        (cons 'process-quota-peak-non-paged-pool-usage (list (cons 'raw process-quota-peak-non-paged-pool-usage) (cons 'formatted (number->string process-quota-peak-non-paged-pool-usage))))
        (cons 'event-extended-data-reserved (list (cons 'raw event-extended-data-reserved) (cons 'formatted (fmt-hex event-extended-data-reserved))))
        (cons 'event-extended-data-type (list (cons 'raw event-extended-data-type) (cons 'formatted (number->string event-extended-data-type))))
        (cons 'process-virtual-size (list (cons 'raw process-virtual-size) (cons 'formatted (number->string process-virtual-size))))
        (cons 'event-extended-data-linkage (list (cons 'raw event-extended-data-linkage) (cons 'formatted (if (= event-extended-data-linkage 0) "False" "True"))))
        (cons 'event-extended-data-reserved2 (list (cons 'raw event-extended-data-reserved2) (cons 'formatted (fmt-hex event-extended-data-reserved2))))
        (cons 'event-extended-data-size (list (cons 'raw event-extended-data-size) (cons 'formatted (number->string event-extended-data-size))))
        (cons 'process-workingset-size (list (cons 'raw process-workingset-size) (cons 'formatted (number->string process-workingset-size))))
        (cons 'process-pagefile-usage (list (cons 'raw process-pagefile-usage) (cons 'formatted (number->string process-pagefile-usage))))
        (cons 'process-quota-paged-pool-usage (list (cons 'raw process-quota-paged-pool-usage) (cons 'formatted (number->string process-quota-paged-pool-usage))))
        (cons 'process-quota-non-paged-pool-usage (list (cons 'raw process-quota-non-paged-pool-usage) (cons 'formatted (number->string process-quota-non-paged-pool-usage))))
        (cons 'process-private-page-count (list (cons 'raw process-private-page-count) (cons 'formatted (number->string process-private-page-count))))
        (cons 'process-directory-table-base32 (list (cons 'raw process-directory-table-base32) (cons 'formatted (number->string process-directory-table-base32))))
        (cons 'process-process-id (list (cons 'raw process-process-id) (cons 'formatted (number->string process-process-id))))
        (cons 'process-parent-id (list (cons 'raw process-parent-id) (cons 'formatted (number->string process-parent-id))))
        (cons 'process-session-id (list (cons 'raw process-session-id) (cons 'formatted (number->string process-session-id))))
        (cons 'process-exit-status (list (cons 'raw process-exit-status) (cons 'formatted (number->string process-exit-status))))
        (cons 'process-unknown (list (cons 'raw process-unknown) (cons 'formatted (fmt-bytes process-unknown))))
        (cons 'process-image-file-name (list (cons 'raw process-image-file-name) (cons 'formatted (utf8->string process-image-file-name))))
        (cons 'process-command-line (list (cons 'raw process-command-line) (cons 'formatted (utf8->string process-command-line))))
        (cons 'system-trace-perf-freq (list (cons 'raw system-trace-perf-freq) (cons 'formatted (fmt-hex system-trace-perf-freq))))
        (cons 'system-trace-reserved-flags (list (cons 'raw system-trace-reserved-flags) (cons 'formatted (number->string system-trace-reserved-flags))))
        (cons 'system-trace-buffers-lost (list (cons 'raw system-trace-buffers-lost) (cons 'formatted (number->string system-trace-buffers-lost))))
        (cons 'system-trace-session-name (list (cons 'raw system-trace-session-name) (cons 'formatted (utf8->string system-trace-session-name))))
        (cons 'system-trace-log-file-name (list (cons 'raw system-trace-log-file-name) (cons 'formatted (utf8->string system-trace-log-file-name))))
        (cons 'system-trace-group-mask1 (list (cons 'raw system-trace-group-mask1) (cons 'formatted (fmt-hex system-trace-group-mask1))))
        (cons 'system-trace-group-mask2 (list (cons 'raw system-trace-group-mask2) (cons 'formatted (fmt-hex system-trace-group-mask2))))
        (cons 'system-trace-group-mask3 (list (cons 'raw system-trace-group-mask3) (cons 'formatted (fmt-hex system-trace-group-mask3))))
        (cons 'system-trace-group-mask4 (list (cons 'raw system-trace-group-mask4) (cons 'formatted (fmt-hex system-trace-group-mask4))))
        (cons 'system-trace-group-mask5 (list (cons 'raw system-trace-group-mask5) (cons 'formatted (fmt-hex system-trace-group-mask5))))
        (cons 'system-trace-group-mask6 (list (cons 'raw system-trace-group-mask6) (cons 'formatted (fmt-hex system-trace-group-mask6))))
        (cons 'system-trace-group-mask7 (list (cons 'raw system-trace-group-mask7) (cons 'formatted (fmt-hex system-trace-group-mask7))))
        (cons 'system-trace-group-mask8 (list (cons 'raw system-trace-group-mask8) (cons 'formatted (fmt-hex system-trace-group-mask8))))
        (cons 'system-trace-kernel-event-version (list (cons 'raw system-trace-kernel-event-version) (cons 'formatted (fmt-hex system-trace-kernel-event-version))))
        (cons 'system-config-nic-name (list (cons 'raw system-config-nic-name) (cons 'formatted (utf8->string system-config-nic-name))))
        (cons 'system-config-index (list (cons 'raw system-config-index) (cons 'formatted (number->string system-config-index))))
        (cons 'system-config-physical-addr-str (list (cons 'raw system-config-physical-addr-str) (cons 'formatted (utf8->string system-config-physical-addr-str))))
        (cons 'system-config-ip-address (list (cons 'raw system-config-ip-address) (cons 'formatted (fmt-ipv4 system-config-ip-address))))
        (cons 'system-config-subnet-mask (list (cons 'raw system-config-subnet-mask) (cons 'formatted (fmt-ipv4 system-config-subnet-mask))))
        (cons 'system-config-dhcp-server (list (cons 'raw system-config-dhcp-server) (cons 'formatted (fmt-ipv4 system-config-dhcp-server))))
        (cons 'system-config-gateway (list (cons 'raw system-config-gateway) (cons 'formatted (fmt-ipv4 system-config-gateway))))
        (cons 'system-config-primary-wins-server (list (cons 'raw system-config-primary-wins-server) (cons 'formatted (fmt-ipv4 system-config-primary-wins-server))))
        (cons 'system-config-secondary-wins-server (list (cons 'raw system-config-secondary-wins-server) (cons 'formatted (fmt-ipv4 system-config-secondary-wins-server))))
        (cons 'system-config-dns-server1 (list (cons 'raw system-config-dns-server1) (cons 'formatted (fmt-ipv4 system-config-dns-server1))))
        (cons 'system-config-dns-server2 (list (cons 'raw system-config-dns-server2) (cons 'formatted (fmt-ipv4 system-config-dns-server2))))
        (cons 'system-config-dns-server3 (list (cons 'raw system-config-dns-server3) (cons 'formatted (fmt-ipv4 system-config-dns-server3))))
        (cons 'system-config-dns-server4 (list (cons 'raw system-config-dns-server4) (cons 'formatted (fmt-ipv4 system-config-dns-server4))))
        (cons 'system-config-data (list (cons 'raw system-config-data) (cons 'formatted (fmt-hex system-config-data))))
        (cons 'system-config-mhz (list (cons 'raw system-config-mhz) (cons 'formatted (number->string system-config-mhz))))
        (cons 'system-config-num-processors (list (cons 'raw system-config-num-processors) (cons 'formatted (number->string system-config-num-processors))))
        (cons 'system-config-mem-size (list (cons 'raw system-config-mem-size) (cons 'formatted (number->string system-config-mem-size))))
        (cons 'system-config-page-size (list (cons 'raw system-config-page-size) (cons 'formatted (number->string system-config-page-size))))
        (cons 'system-config-allocation-granularity (list (cons 'raw system-config-allocation-granularity) (cons 'formatted (number->string system-config-allocation-granularity))))
        (cons 'system-config-computer-name (list (cons 'raw system-config-computer-name) (cons 'formatted (utf8->string system-config-computer-name))))
        (cons 'system-config-domain-name (list (cons 'raw system-config-domain-name) (cons 'formatted (utf8->string system-config-domain-name))))
        (cons 'system-config-sectors-per-track (list (cons 'raw system-config-sectors-per-track) (cons 'formatted (number->string system-config-sectors-per-track))))
        (cons 'system-config-tracks-per-cylinder (list (cons 'raw system-config-tracks-per-cylinder) (cons 'formatted (number->string system-config-tracks-per-cylinder))))
        (cons 'system-config-cylinders (list (cons 'raw system-config-cylinders) (cons 'formatted (number->string system-config-cylinders))))
        (cons 'system-config-scsi-port (list (cons 'raw system-config-scsi-port) (cons 'formatted (number->string system-config-scsi-port))))
        (cons 'system-config-scsi-path (list (cons 'raw system-config-scsi-path) (cons 'formatted (number->string system-config-scsi-path))))
        (cons 'system-config-scsi-target (list (cons 'raw system-config-scsi-target) (cons 'formatted (number->string system-config-scsi-target))))
        (cons 'system-config-scsi-lun (list (cons 'raw system-config-scsi-lun) (cons 'formatted (number->string system-config-scsi-lun))))
        (cons 'system-config-manufacturer (list (cons 'raw system-config-manufacturer) (cons 'formatted (utf8->string system-config-manufacturer))))
        (cons 'system-config-partition-count (list (cons 'raw system-config-partition-count) (cons 'formatted (number->string system-config-partition-count))))
        (cons 'system-config-write-cache-enabled (list (cons 'raw system-config-write-cache-enabled) (cons 'formatted (number->string system-config-write-cache-enabled))))
        (cons 'system-config-boot-drive-letter (list (cons 'raw system-config-boot-drive-letter) (cons 'formatted (utf8->string system-config-boot-drive-letter))))
        (cons 'system-config-spare (list (cons 'raw system-config-spare) (cons 'formatted (utf8->string system-config-spare))))
        (cons 'system-config-start-offset (list (cons 'raw system-config-start-offset) (cons 'formatted (number->string system-config-start-offset))))
        (cons 'system-config-partition-size (list (cons 'raw system-config-partition-size) (cons 'formatted (number->string system-config-partition-size))))
        (cons 'system-config-disk-number (list (cons 'raw system-config-disk-number) (cons 'formatted (number->string system-config-disk-number))))
        (cons 'system-config-size (list (cons 'raw system-config-size) (cons 'formatted (number->string system-config-size))))
        (cons 'system-config-drive-type (list (cons 'raw system-config-drive-type) (cons 'formatted (number->string system-config-drive-type))))
        (cons 'system-config-drive-letter (list (cons 'raw system-config-drive-letter) (cons 'formatted (utf8->string system-config-drive-letter))))
        (cons 'system-config-partition-number (list (cons 'raw system-config-partition-number) (cons 'formatted (number->string system-config-partition-number))))
        (cons 'system-config-sectors-per-cluster (list (cons 'raw system-config-sectors-per-cluster) (cons 'formatted (number->string system-config-sectors-per-cluster))))
        (cons 'system-config-bytes-per-sector (list (cons 'raw system-config-bytes-per-sector) (cons 'formatted (number->string system-config-bytes-per-sector))))
        (cons 'system-config-num-free-clusters (list (cons 'raw system-config-num-free-clusters) (cons 'formatted (number->string system-config-num-free-clusters))))
        (cons 'system-config-total-num-clusters (list (cons 'raw system-config-total-num-clusters) (cons 'formatted (number->string system-config-total-num-clusters))))
        (cons 'system-config-file-system (list (cons 'raw system-config-file-system) (cons 'formatted (utf8->string system-config-file-system))))
        (cons 'system-config-volume-ext (list (cons 'raw system-config-volume-ext) (cons 'formatted (number->string system-config-volume-ext))))
        (cons 'system-config-physical-addr (list (cons 'raw system-config-physical-addr) (cons 'formatted (number->string system-config-physical-addr))))
        (cons 'system-config-physical-addr-len (list (cons 'raw system-config-physical-addr-len) (cons 'formatted (number->string system-config-physical-addr-len))))
        (cons 'system-config-ipv4-index (list (cons 'raw system-config-ipv4-index) (cons 'formatted (number->string system-config-ipv4-index))))
        (cons 'system-config-ipv6-index (list (cons 'raw system-config-ipv6-index) (cons 'formatted (number->string system-config-ipv6-index))))
        (cons 'system-config-nic-description (list (cons 'raw system-config-nic-description) (cons 'formatted (utf8->string system-config-nic-description))))
        (cons 'system-config-ipaddresses (list (cons 'raw system-config-ipaddresses) (cons 'formatted (utf8->string system-config-ipaddresses))))
        (cons 'system-config-dns-server-addresses (list (cons 'raw system-config-dns-server-addresses) (cons 'formatted (utf8->string system-config-dns-server-addresses))))
        (cons 'system-config-memory-size (list (cons 'raw system-config-memory-size) (cons 'formatted (number->string system-config-memory-size))))
        (cons 'system-config-x-resolution (list (cons 'raw system-config-x-resolution) (cons 'formatted (number->string system-config-x-resolution))))
        (cons 'system-config-y-resolution (list (cons 'raw system-config-y-resolution) (cons 'formatted (number->string system-config-y-resolution))))
        (cons 'system-config-bits-per-pixel (list (cons 'raw system-config-bits-per-pixel) (cons 'formatted (number->string system-config-bits-per-pixel))))
        (cons 'system-config-vrefresh (list (cons 'raw system-config-vrefresh) (cons 'formatted (number->string system-config-vrefresh))))
        (cons 'system-config-chip-type (list (cons 'raw system-config-chip-type) (cons 'formatted (utf8->string system-config-chip-type))))
        (cons 'system-config-dac-type (list (cons 'raw system-config-dac-type) (cons 'formatted (utf8->string system-config-dac-type))))
        (cons 'system-config-adapter-string (list (cons 'raw system-config-adapter-string) (cons 'formatted (utf8->string system-config-adapter-string))))
        (cons 'system-config-bios-string (list (cons 'raw system-config-bios-string) (cons 'formatted (utf8->string system-config-bios-string))))
        (cons 'system-config-state-flags (list (cons 'raw system-config-state-flags) (cons 'formatted (fmt-hex system-config-state-flags))))
        (cons 'system-config-s1 (list (cons 'raw system-config-s1) (cons 'formatted (number->string system-config-s1))))
        (cons 'system-config-s2 (list (cons 'raw system-config-s2) (cons 'formatted (number->string system-config-s2))))
        (cons 'system-config-s3 (list (cons 'raw system-config-s3) (cons 'formatted (number->string system-config-s3))))
        (cons 'system-config-s4 (list (cons 'raw system-config-s4) (cons 'formatted (number->string system-config-s4))))
        (cons 'system-config-s5 (list (cons 'raw system-config-s5) (cons 'formatted (number->string system-config-s5))))
        (cons 'system-config-tcb-table-partitions (list (cons 'raw system-config-tcb-table-partitions) (cons 'formatted (number->string system-config-tcb-table-partitions))))
        (cons 'system-config-max-hash-table-size (list (cons 'raw system-config-max-hash-table-size) (cons 'formatted (number->string system-config-max-hash-table-size))))
        (cons 'system-config-max-user-port (list (cons 'raw system-config-max-user-port) (cons 'formatted (number->string system-config-max-user-port))))
        (cons 'system-config-tcp-timed-wait-delay (list (cons 'raw system-config-tcp-timed-wait-delay) (cons 'formatted (number->string system-config-tcp-timed-wait-delay))))
        (cons 'system-config-target-id (list (cons 'raw system-config-target-id) (cons 'formatted (number->string system-config-target-id))))
        (cons 'system-config-device-type (list (cons 'raw system-config-device-type) (cons 'formatted (number->string system-config-device-type))))
        (cons 'system-config-device-timing-mode (list (cons 'raw system-config-device-timing-mode) (cons 'formatted (number->string system-config-device-timing-mode))))
        (cons 'system-config-location-information-len (list (cons 'raw system-config-location-information-len) (cons 'formatted (number->string system-config-location-information-len))))
        (cons 'system-config-location-information (list (cons 'raw system-config-location-information) (cons 'formatted (utf8->string system-config-location-information))))
        (cons 'system-config-system-manufacturer (list (cons 'raw system-config-system-manufacturer) (cons 'formatted (utf8->string system-config-system-manufacturer))))
        (cons 'system-config-system-product-name (list (cons 'raw system-config-system-product-name) (cons 'formatted (utf8->string system-config-system-product-name))))
        (cons 'system-config-bios-date (list (cons 'raw system-config-bios-date) (cons 'formatted (utf8->string system-config-bios-date))))
        (cons 'system-config-bios-version (list (cons 'raw system-config-bios-version) (cons 'formatted (utf8->string system-config-bios-version))))
        (cons 'system-config-process-id (list (cons 'raw system-config-process-id) (cons 'formatted (number->string system-config-process-id))))
        (cons 'system-config-service-state (list (cons 'raw system-config-service-state) (cons 'formatted (number->string system-config-service-state))))
        (cons 'system-config-sub-process-tag (list (cons 'raw system-config-sub-process-tag) (cons 'formatted (number->string system-config-sub-process-tag))))
        (cons 'system-config-service-name (list (cons 'raw system-config-service-name) (cons 'formatted (utf8->string system-config-service-name))))
        (cons 'system-config-display-name (list (cons 'raw system-config-display-name) (cons 'formatted (utf8->string system-config-display-name))))
        (cons 'system-config-process-name (list (cons 'raw system-config-process-name) (cons 'formatted (utf8->string system-config-process-name))))
        (cons 'system-config-load-order-group (list (cons 'raw system-config-load-order-group) (cons 'formatted (utf8->string system-config-load-order-group))))
        (cons 'system-config-svc-host-group (list (cons 'raw system-config-svc-host-group) (cons 'formatted (utf8->string system-config-svc-host-group))))
        (cons 'system-config-irq-affinity (list (cons 'raw system-config-irq-affinity) (cons 'formatted (number->string system-config-irq-affinity))))
        (cons 'system-config-irq-group (list (cons 'raw system-config-irq-group) (cons 'formatted (number->string system-config-irq-group))))
        (cons 'system-config-pad (list (cons 'raw system-config-pad) (cons 'formatted (fmt-bytes system-config-pad))))
        (cons 'system-config-irq-num (list (cons 'raw system-config-irq-num) (cons 'formatted (number->string system-config-irq-num))))
        (cons 'system-config-device-id-len (list (cons 'raw system-config-device-id-len) (cons 'formatted (number->string system-config-device-id-len))))
        (cons 'system-config-device-desc-len (list (cons 'raw system-config-device-desc-len) (cons 'formatted (number->string system-config-device-desc-len))))
        (cons 'system-config-friendly-name-len (list (cons 'raw system-config-friendly-name-len) (cons 'formatted (number->string system-config-friendly-name-len))))
        (cons 'system-config-device-id (list (cons 'raw system-config-device-id) (cons 'formatted (utf8->string system-config-device-id))))
        (cons 'system-config-device-desc (list (cons 'raw system-config-device-desc) (cons 'formatted (utf8->string system-config-device-desc))))
        (cons 'system-config-friendly-name (list (cons 'raw system-config-friendly-name) (cons 'formatted (utf8->string system-config-friendly-name))))
        (cons 'system-config-pdo-name (list (cons 'raw system-config-pdo-name) (cons 'formatted (utf8->string system-config-pdo-name))))
        )))

    (catch (e)
      (err (str "NETMON parse error: " e)))))

;; dissect-netmon: parse NETMON from bytevector
;; Returns (ok fields-alist) or (err message)