;; packet-nfs.c
;; Routines for nfs dissection
;; Copyright 1999, Uwe Girlich <Uwe.Girlich@philosys.de>
;; Copyright 2000-2004, Mike Frisch <frisch@hummingbird.com> (NFSv4 decoding)
;;
;; Wireshark - Network traffic analyzer
;; By Gerald Combs <gerald@wireshark.org>
;; Copyright 1998 Gerald Combs
;;
;; Copied from packet-smb.c
;;
;; SPDX-License-Identifier: GPL-2.0-or-later
;;

;; jerboa-ethereal/dissectors/nfs.ss
;; Auto-generated from wireshark/epan/dissectors/packet-nfs.c

(import (jerboa prelude))

;; ── Protocol Helpers ─────────────────────────────────────────────────
(def (read-u8 buf offset)
  (if (>= offset (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u8-ref buf offset))))

(def (read-u16be buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness big)))))

(def (read-u24be buf offset)
  (if (> (+ offset 3) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (+ (* (bytevector-u8-ref buf offset) 65536)
             (* (bytevector-u8-ref buf (+ offset 1)) 256)
             (bytevector-u8-ref buf (+ offset 2))))))

(def (read-u32be buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness big)))))

(def (read-u16le buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness little)))))

(def (read-u32le buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness little)))))

(def (read-u64be buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness big)))))

(def (read-u64le buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness little)))))

(def (slice buf offset len)
  (if (> (+ offset len) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (let ((result (make-bytevector len)))
            (bytevector-copy! buf offset result 0 len)
            result))))

(def (extract-bits val mask shift)
  (bitwise-arithmetic-shift-right (bitwise-and val mask) shift))

(def (fmt-ipv4 addr)
  (let ((b0 (bitwise-arithmetic-shift-right addr 24))
        (b1 (bitwise-and (bitwise-arithmetic-shift-right addr 16) 255))
        (b2 (bitwise-and (bitwise-arithmetic-shift-right addr 8) 255))
        (b3 (bitwise-and addr 255)))
    (str b0 "." b1 "." b2 "." b3)))

(def (fmt-mac bytes)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bytes))
    ":"))

(def (fmt-hex val)
  (str "0x" (number->string val 16)))

(def (fmt-oct val)
  (str "0" (number->string val 8)))

(def (fmt-port port)
  (number->string port))

(def (fmt-bytes bv)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bv))
    " "))

(def (fmt-ipv6-address bytes)
  (let loop ((i 0) (parts '()))
    (if (>= i 16)
        (string-join (reverse parts) ":")
        (loop (+ i 2)
              (cons (let ((w (+ (* (bytevector-u8-ref bytes i) 256)
                                (bytevector-u8-ref bytes (+ i 1)))))
                      (number->string w 16))
                    parts)))))

;; ── Dissector ──────────────────────────────────────────────────────
(def (dissect-nfs buffer)
  "Network File System"
  (try
    (let* (
           (sec-oid (unwrap (slice buffer 0 1)))
           (fh-fhandle-data (unwrap (slice buffer 0 1)))
           (fh-endianness (unwrap (read-u8 buffer 0)))
           (fh-dentry (unwrap (read-u32be buffer 0)))
           (fh-fsid-major16-mask (unwrap (read-u16be buffer 0)))
           (fh-fsid-minor16-mask (unwrap (read-u16be buffer 0)))
           (fh-xfsid-major (unwrap (read-u16be buffer 0)))
           (fh-xfsid-minor (unwrap (read-u16be buffer 0)))
           (fh-xfn-inode (unwrap (read-u32be buffer 0)))
           (fh-pinode (unwrap (read-u32be buffer 0)))
           (fh-hp-len (unwrap (read-u32be buffer 0)))
           (fh-hp-key (unwrap (slice buffer 0 1)))
           (fh-mount-fileid (unwrap (read-u32be buffer 0)))
           (fh-mount-generation (unwrap (read-u32be buffer 0)))
           (fh-flags (unwrap (read-u16le buffer 0)))
           (fh-snapid (unwrap (read-u8 buffer 0)))
           (fh-unused (unwrap (read-u8 buffer 0)))
           (fh-fileid (unwrap (read-u32be buffer 0)))
           (fh-generation (unwrap (read-u32be buffer 0)))
           (fh-export-fileid (unwrap (read-u32be buffer 0)))
           (fh-export-generation (unwrap (read-u32be buffer 0)))
           (fh-export-snapid (unwrap (read-u8 buffer 0)))
           (gxfh-utlfield (unwrap (read-u8 buffer 0)))
           (gxfh-utlfield-tree (extract-bits gxfh-utlfield 0x0 0))
           (gxfh-utlfield-jun (extract-bits gxfh-utlfield 0x0 0))
           (gxfh-utlfield-ver (extract-bits gxfh-utlfield 0x0 0))
           (gxfh-volcnt (unwrap (read-u8 buffer 0)))
           (gxfh-epoch (unwrap (read-u16be buffer 0)))
           (gxfh-ldsid (unwrap (read-u32be buffer 0)))
           (gxfh-cid (unwrap (read-u16be buffer 0)))
           (gxfh-resv (unwrap (read-u16be buffer 0)))
           (gxfh-sfhflags (unwrap (read-u8 buffer 0)))
           (gxfh-sfhflags-resv1 (extract-bits gxfh-sfhflags 0x0 0))
           (gxfh-sfhflags-resv2 (extract-bits gxfh-sfhflags 0x0 0))
           (gxfh-sfhflags-ontap7G (extract-bits gxfh-sfhflags 0x0 0))
           (gxfh-sfhflags-striped (extract-bits gxfh-sfhflags 0x0 0))
           (gxfh-sfhflags-empty (extract-bits gxfh-sfhflags 0x0 0))
           (gxfh-sfhflags-snapdirent (extract-bits gxfh-sfhflags 0x0 0))
           (gxfh-sfhflags-snapdir (extract-bits gxfh-sfhflags 0x0 0))
           (gxfh-sfhflags-streamdir (extract-bits gxfh-sfhflags 0x0 0))
           (gxfh-spinfid (unwrap (read-u32be buffer 0)))
           (gxfh-spinfuid (unwrap (read-u32be buffer 0)))
           (gxfh-exportptid (unwrap (read-u32be buffer 0)))
           (gxfh-exportptuid (unwrap (read-u32be buffer 0)))
           (fh-version (unwrap (read-u8 buffer 0)))
           (fh-dc-exportid (unwrap (read-u32be buffer 0)))
           (fh-dc-opaque (unwrap (slice buffer 0 1)))
           (fh-pd-share (unwrap (read-u32be buffer 0)))
           (fh-pd-flags (unwrap (read-u32le buffer 0)))
           (fh-pd-flags-version (extract-bits fh-pd-flags 0x0 0))
           (fh-pd-flags-reserved (extract-bits fh-pd-flags 0x0 0))
           (fh-pd-inum (unwrap (read-u64be buffer 0)))
           (fh-pd-container (unwrap (read-u64be buffer 0)))
           (fh-pd-spaces (unwrap (read-u64le buffer 0)))
           (fh-pd-spaces-snapid (extract-bits fh-pd-spaces 0x0 0))
           (fh-pd-spaces-container (extract-bits fh-pd-spaces 0x0 0))
           (fh-pd-sites (unwrap (read-u64le buffer 0)))
           (fh-pd-sites-inum (extract-bits fh-pd-sites 0x0 0))
           (fh-pd-sites-siteid (extract-bits fh-pd-sites 0x0 0))
           (fh-obj (unwrap (slice buffer 0 16)))
           (fh-obj-fsid (unwrap (read-u32be buffer 0)))
           (fh-obj-kindid (unwrap (read-u16be buffer 0)))
           (fh-obj-treeid (unwrap (read-u16be buffer 0)))
           (fh-obj-inode (unwrap (read-u32be buffer 0)))
           (fh-obj-gen (unwrap (read-u32be buffer 0)))
           (fh-ex (unwrap (slice buffer 0 16)))
           (fh-ex-fsid (unwrap (read-u32be buffer 0)))
           (fh-ex-kindid (unwrap (read-u16be buffer 0)))
           (fh-ex-treeid (unwrap (read-u16be buffer 0)))
           (fh-ex-inode (unwrap (read-u32be buffer 0)))
           (fh-ex-gen (unwrap (read-u32be buffer 0)))
           (fh-ro-node (unwrap (read-u8 buffer 0)))
           (fh-hash (unwrap (read-u32be buffer 0)))
           (read-offset (unwrap (read-u32be buffer 0)))
           (read-count (unwrap (read-u32be buffer 0)))
           (read-totalcount (unwrap (read-u32be buffer 0)))
           (write-beginoffset (unwrap (read-u32be buffer 0)))
           (write-offset (unwrap (read-u32be buffer 0)))
           (write-totalcount (unwrap (read-u32be buffer 0)))
           (readdir-cookie (unwrap (read-u32be buffer 0)))
           (readdir-count (unwrap (read-u32be buffer 0)))
           (readdir-eof (unwrap (read-u32be buffer 0)))
           (statfs-tsize (unwrap (read-u32be buffer 0)))
           (statfs-bsize (unwrap (read-u32be buffer 0)))
           (statfs-blocks (unwrap (read-u32be buffer 0)))
           (statfs-bfree (unwrap (read-u32be buffer 0)))
           (statfs-bavail (unwrap (read-u32be buffer 0)))
           (access-check (unwrap (read-u32be buffer 0)))
           (access-supported (unwrap (read-u32be buffer 0)))
           (access-rights (unwrap (read-u32be buffer 0)))
           (fsstat-invarsec (unwrap (read-u32be buffer 0)))
           (fsinfo-rtmax (unwrap (read-u32be buffer 0)))
           (pathconf-linkmax (unwrap (read-u32be buffer 0)))
           (fh-fsid-major16 (unwrap (read-u16be buffer 4)))
           (fh-fsid-minor16 (unwrap (read-u16be buffer 4)))
           (fh-fsid-inode (unwrap (read-u32be buffer 4)))
           (fh-exportid (unwrap (slice buffer 4 16)))
           (access-denied (unwrap (read-u8 buffer 4)))
           (fsinfo-rtpref (unwrap (read-u32be buffer 4)))
           (pathconf-name-max (unwrap (read-u32be buffer 4)))
           (huge-bitmap-length (unwrap (read-u32be buffer 4)))
           (num-offload-status (unwrap (read-u32be buffer 4)))
           (readdir-entry-fileid (unwrap (read-u32be buffer 8)))
           (fsinfo-rtmult (unwrap (read-u32be buffer 8)))
           (offload-status-index (unwrap (read-u32be buffer 8)))
           (ops-count (unwrap (read-u32be buffer 8)))
           (readdir-entry-cookie (unwrap (read-u32be buffer 12)))
           (fsinfo-wtmax (unwrap (read-u32be buffer 12)))
           (deviceid (unwrap (slice buffer 12 16)))
           (fattr-uid (unwrap (read-u32be buffer 16)))
           (fsinfo-wtpref (unwrap (read-u32be buffer 16)))
           (stateid (unwrap (slice buffer 16 16)))
           (fh-fn-inode (unwrap (read-u32be buffer 20)))
           (fh-fn-generation (unwrap (read-u32be buffer 20)))
           (fh-dirinode (unwrap (read-u32be buffer 20)))
           (fh-gfid (unwrap (slice buffer 20 16)))
           (fattr-gid (unwrap (read-u32be buffer 20)))
           (verifier (unwrap (slice buffer 20 1)))
           (mode-suid (extract-bits mode 0x800 11))
           (mode-sgid (extract-bits mode 0x400 10))
           (mode-sticky (extract-bits mode 0x200 9))
           (mode-rusr (extract-bits mode 0x100 8))
           (mode-wusr (extract-bits mode 0x80 7))
           (mode-xusr (extract-bits mode 0x40 6))
           (mode-rgrp (extract-bits mode 0x20 5))
           (mode-wgrp (extract-bits mode 0x10 4))
           (mode-xgrp (extract-bits mode 0x8 3))
           (mode-roth (extract-bits mode 0x4 2))
           (mode-woth (extract-bits mode 0x2 1))
           (mode-xoth (extract-bits mode 0x1 0))
           (fsinfo-wtmult (unwrap (read-u32be buffer 20)))
           (fattr-size (unwrap (read-u32be buffer 24)))
           (fsinfo-dtpref (unwrap (read-u32be buffer 24)))
           (fsinfo-properties (unwrap (read-u32be buffer 28)))
           (fsinfo-properties-setattr (extract-bits fsinfo-properties 0x0 0))
           (fsinfo-properties-pathconf (extract-bits fsinfo-properties 0x0 0))
           (fsinfo-properties-symlinks (extract-bits fsinfo-properties 0x0 0))
           (fsinfo-properties-hardlinks (extract-bits fsinfo-properties 0x0 0))
           (sessionid (unwrap (slice buffer 28 16)))
           (specdata1 (unwrap (read-u32be buffer 32)))
           (specdata2 (unwrap (read-u32be buffer 32)))
           (exchid-reply-flags (unwrap (read-u32be buffer 32)))
           (sequence-status-flags (unwrap (read-u32be buffer 36)))
           (sequence-status-flags-cb-path-down (extract-bits sequence-status-flags 0x1 0))
           (sequence-status-flags-cb-gss-contexts-expiring (extract-bits sequence-status-flags 0x2 1))
           (sequence-status-flags-cb-gss-contexts-expired (extract-bits sequence-status-flags 0x4 2))
           (sequence-status-flags-expired-all-state-revoked (extract-bits sequence-status-flags 0x8 3))
           (sequence-status-flags-expired-some-state-revoked (extract-bits sequence-status-flags 0x10 4))
           (sequence-status-flags-admin-state-revoked (extract-bits sequence-status-flags 0x20 5))
           (sequence-status-flags-recallable-state-revoked (extract-bits sequence-status-flags 0x40 6))
           (sequence-status-flags-lease-moved (extract-bits sequence-status-flags 0x80 7))
           (sequence-status-flags-restart-reclaim-needed (extract-bits sequence-status-flags 0x100 8))
           (sequence-status-flags-cb-path-down-session (extract-bits sequence-status-flags 0x200 9))
           (sequence-status-flags-backchannel-fault (extract-bits sequence-status-flags 0x400 10))
           (sequence-status-flags-devid-changed (extract-bits sequence-status-flags 0x800 11))
           (sequence-status-flags-devid-deleted (extract-bits sequence-status-flags 0x1000 12))
           (fh-length (unwrap (read-u32be buffer 40)))
           (pathname-components (unwrap (read-u32be buffer 44)))
           (aceflags (unwrap (read-u32be buffer 52)))
           (aceflag-file-inherit (extract-bits aceflags 0x0 0))
           (aceflag-dir-inherit (extract-bits aceflags 0x0 0))
           (aceflag-no-prop-inherit (extract-bits aceflags 0x0 0))
           (aceflag-inherit-only (extract-bits aceflags 0x0 0))
           (aceflag-successful-access (extract-bits aceflags 0x0 0))
           (aceflag-failed-access (extract-bits aceflags 0x0 0))
           (aceflag-id-group (extract-bits aceflags 0x0 0))
           (aceflag-inherited-ace (extract-bits aceflags 0x0 0))
           (acemask (unwrap (read-u32be buffer 56)))
           (ace-permission (unwrap (read-u32be buffer 56)))
           (aclflags (unwrap (read-u32be buffer 72)))
           (aclflag-auto-inherit (extract-bits aclflags 0x0 0))
           (aclflag-protected (extract-bits aclflags 0x0 0))
           (aclflag-defaulted (extract-bits aclflags 0x0 0))
           (num-aces (unwrap (read-u32be buffer 76)))
           (fattr-aclsupport (unwrap (read-u32be buffer 80)))
           (aclsupport-allow-acl (extract-bits fattr-aclsupport 0x0 0))
           (aclsupport-deny-acl (extract-bits fattr-aclsupport 0x0 0))
           (aclsupport-audit-acl (extract-bits fattr-aclsupport 0x0 0))
           (aclsupport-alarm-acl (extract-bits fattr-aclsupport 0x0 0))
           (fattr-fs-charset-cap (unwrap (read-u32be buffer 84)))
           (mode (unwrap (read-u32be buffer 88)))
           (mode-set-user-id (extract-bits mode 0xFA0 5))
           (mode-set-group-id (extract-bits mode 0x7D0 4))
           (mode-save-swap-text (extract-bits mode 0x3E8 3))
           (mode-read-owner (extract-bits mode 0x190 4))
           (mode-write-owner (extract-bits mode 0xC8 3))
           (mode-exec-owner (extract-bits mode 0x64 2))
           (mode-read-group (extract-bits mode 0x28 3))
           (mode-write-group (extract-bits mode 0x14 2))
           (mode-exec-group (extract-bits mode 0xA 1))
           (mode-read-other (extract-bits mode 0x4 2))
           (mode-write-other (extract-bits mode 0x2 1))
           (mode-exec-other (extract-bits mode 0x1 0))
           (want-notify-flags (unwrap (read-u32be buffer 120)))
           (want-signal-deleg-when-resrc-avail (unwrap (read-u8 buffer 120)))
           (want-push-deleg-when-uncontended (unwrap (read-u8 buffer 120)))
           (listxattr-names-len (unwrap (read-u32be buffer 144)))
           (name (unwrap (slice buffer 148 1)))
           (value-follows (unwrap (read-u8 buffer 148)))
           (open-rflags (unwrap (read-u32be buffer 172)))
           (open-rflags-confirm (extract-bits open-rflags 0x0 0))
           (open-rflags-locktype-posix (extract-bits open-rflags 0x0 0))
           (open-rflags-preserve-unlinked (extract-bits open-rflags 0x0 0))
           (open-rflags-may-notify-lock (extract-bits open-rflags 0x0 0))
           (stateid-hash (unwrap (read-u16be buffer 176)))
           (stateid-other (unwrap (slice buffer 176 12)))
           (stateid-other-hash (unwrap (read-u32be buffer 176)))
           (pattern-hash (unwrap (read-u32be buffer 216)))
           (device-error-count (unwrap (read-u32be buffer 220)))
           (device-errors-index (unwrap (read-u32be buffer 224)))
           (ff-ioerrs-count (unwrap (read-u32be buffer 232)))
           (ff-ioerrs-index (unwrap (read-u32be buffer 236)))
           (ff-iostats-count (unwrap (read-u32be buffer 236)))
           (ff-iostats-index (unwrap (read-u32be buffer 240)))
           (devaddr-scsi-vpd-designator (unwrap (slice buffer 264 1)))
           (devaddr-scsi-private-key (unwrap (slice buffer 264 8)))
           (devaddr-scsi-vol-index (unwrap (read-u32be buffer 284)))
           (devaddr-ssv-start (unwrap (read-u32be buffer 284)))
           (devaddr-ssv-length (unwrap (read-u32be buffer 284)))
           (devaddr-scsi-vol-ref-index (unwrap (read-u32be buffer 284)))
           (devaddr-ssv-stripe-unit (unwrap (read-u32be buffer 284)))
           (callback-stateids (unwrap (read-u32be buffer 284)))
           (callback-stateids-index (unwrap (read-u32be buffer 288)))
           (source-servers (unwrap (read-u32be buffer 288)))
           (source-server-index (unwrap (read-u32be buffer 292)))
           (nfl-util (unwrap (read-u32be buffer 320)))
           (nfl-util-stripe-size (unwrap (read-u32be buffer 320)))
           (nfl-util-commit-thru-mds (unwrap (read-u32be buffer 320)))
           (nfl-util-dense (unwrap (read-u32be buffer 320)))
           (nfl-fhs (unwrap (read-u32be buffer 324)))
           (nfl-mirrors (unwrap (read-u32be buffer 332)))
           (ff-layout-flags (unwrap (read-u32be buffer 344)))
           (ff-layout-flags-no-layoutcommit (extract-bits ff-layout-flags 0x1 0))
           (ff-layout-flags-no-io-thru-mds (extract-bits ff-layout-flags 0x2 1))
           (ff-layout-flags-no-read-io (extract-bits ff-layout-flags 0x4 2))
           (exchid-call-flags (unwrap (read-u32be buffer 376)))
           (exchid-flags-confirmed-r (extract-bits exchid-call-flags 0x80000000 31))
           (exchid-flags-upd-conf-rec-a (extract-bits exchid-call-flags 0x40000000 30))
           (exchid-flags-pnfs-ds (extract-bits exchid-call-flags 0x40000 18))
           (exchid-flags-pnfs-mds (extract-bits exchid-call-flags 0x20000 17))
           (exchid-flags-non-pnfs (extract-bits exchid-call-flags 0x10000 16))
           (exchid-flags-bind-princ (extract-bits exchid-call-flags 0x100 8))
           (exchid-flags-moved-migr (extract-bits exchid-call-flags 0x2 1))
           (exchid-flags-moved-refer (extract-bits exchid-call-flags 0x1 0))
           )

      (ok (list
        (cons 'sec-oid (list (cons 'raw sec-oid) (cons 'formatted (fmt-bytes sec-oid))))
        (cons 'fh-fhandle-data (list (cons 'raw fh-fhandle-data) (cons 'formatted (fmt-bytes fh-fhandle-data))))
        (cons 'fh-endianness (list (cons 'raw fh-endianness) (cons 'formatted (if (= fh-endianness 0) "Big Endian" "Little Endian"))))
        (cons 'fh-dentry (list (cons 'raw fh-dentry) (cons 'formatted (fmt-hex fh-dentry))))
        (cons 'fh-fsid-major16-mask (list (cons 'raw fh-fsid-major16-mask) (cons 'formatted (number->string fh-fsid-major16-mask))))
        (cons 'fh-fsid-minor16-mask (list (cons 'raw fh-fsid-minor16-mask) (cons 'formatted (number->string fh-fsid-minor16-mask))))
        (cons 'fh-xfsid-major (list (cons 'raw fh-xfsid-major) (cons 'formatted (number->string fh-xfsid-major))))
        (cons 'fh-xfsid-minor (list (cons 'raw fh-xfsid-minor) (cons 'formatted (number->string fh-xfsid-minor))))
        (cons 'fh-xfn-inode (list (cons 'raw fh-xfn-inode) (cons 'formatted (number->string fh-xfn-inode))))
        (cons 'fh-pinode (list (cons 'raw fh-pinode) (cons 'formatted (fmt-hex fh-pinode))))
        (cons 'fh-hp-len (list (cons 'raw fh-hp-len) (cons 'formatted (number->string fh-hp-len))))
        (cons 'fh-hp-key (list (cons 'raw fh-hp-key) (cons 'formatted (fmt-bytes fh-hp-key))))
        (cons 'fh-mount-fileid (list (cons 'raw fh-mount-fileid) (cons 'formatted (number->string fh-mount-fileid))))
        (cons 'fh-mount-generation (list (cons 'raw fh-mount-generation) (cons 'formatted (fmt-hex fh-mount-generation))))
        (cons 'fh-flags (list (cons 'raw fh-flags) (cons 'formatted (fmt-hex fh-flags))))
        (cons 'fh-snapid (list (cons 'raw fh-snapid) (cons 'formatted (number->string fh-snapid))))
        (cons 'fh-unused (list (cons 'raw fh-unused) (cons 'formatted (number->string fh-unused))))
        (cons 'fh-fileid (list (cons 'raw fh-fileid) (cons 'formatted (number->string fh-fileid))))
        (cons 'fh-generation (list (cons 'raw fh-generation) (cons 'formatted (fmt-hex fh-generation))))
        (cons 'fh-export-fileid (list (cons 'raw fh-export-fileid) (cons 'formatted (number->string fh-export-fileid))))
        (cons 'fh-export-generation (list (cons 'raw fh-export-generation) (cons 'formatted (fmt-hex fh-export-generation))))
        (cons 'fh-export-snapid (list (cons 'raw fh-export-snapid) (cons 'formatted (number->string fh-export-snapid))))
        (cons 'gxfh-utlfield (list (cons 'raw gxfh-utlfield) (cons 'formatted (fmt-hex gxfh-utlfield))))
        (cons 'gxfh-utlfield-tree (list (cons 'raw gxfh-utlfield-tree) (cons 'formatted (if (= gxfh-utlfield-tree 0) "Write" "Read"))))
        (cons 'gxfh-utlfield-jun (list (cons 'raw gxfh-utlfield-jun) (cons 'formatted (if (= gxfh-utlfield-jun 0) "Not set" "Set"))))
        (cons 'gxfh-utlfield-ver (list (cons 'raw gxfh-utlfield-ver) (cons 'formatted (if (= gxfh-utlfield-ver 0) "Not set" "Set"))))
        (cons 'gxfh-volcnt (list (cons 'raw gxfh-volcnt) (cons 'formatted (fmt-hex gxfh-volcnt))))
        (cons 'gxfh-epoch (list (cons 'raw gxfh-epoch) (cons 'formatted (fmt-hex gxfh-epoch))))
        (cons 'gxfh-ldsid (list (cons 'raw gxfh-ldsid) (cons 'formatted (fmt-hex gxfh-ldsid))))
        (cons 'gxfh-cid (list (cons 'raw gxfh-cid) (cons 'formatted (fmt-hex gxfh-cid))))
        (cons 'gxfh-resv (list (cons 'raw gxfh-resv) (cons 'formatted (fmt-hex gxfh-resv))))
        (cons 'gxfh-sfhflags (list (cons 'raw gxfh-sfhflags) (cons 'formatted (fmt-hex gxfh-sfhflags))))
        (cons 'gxfh-sfhflags-resv1 (list (cons 'raw gxfh-sfhflags-resv1) (cons 'formatted (if (= gxfh-sfhflags-resv1 0) "Not set" "Set"))))
        (cons 'gxfh-sfhflags-resv2 (list (cons 'raw gxfh-sfhflags-resv2) (cons 'formatted (if (= gxfh-sfhflags-resv2 0) "Not set" "Set"))))
        (cons 'gxfh-sfhflags-ontap7G (list (cons 'raw gxfh-sfhflags-ontap7G) (cons 'formatted (if (= gxfh-sfhflags-ontap7G 0) "Not set" "Set"))))
        (cons 'gxfh-sfhflags-striped (list (cons 'raw gxfh-sfhflags-striped) (cons 'formatted (if (= gxfh-sfhflags-striped 0) "Not set" "Set"))))
        (cons 'gxfh-sfhflags-empty (list (cons 'raw gxfh-sfhflags-empty) (cons 'formatted (if (= gxfh-sfhflags-empty 0) "Not set" "Set"))))
        (cons 'gxfh-sfhflags-snapdirent (list (cons 'raw gxfh-sfhflags-snapdirent) (cons 'formatted (if (= gxfh-sfhflags-snapdirent 0) "Not set" "Set"))))
        (cons 'gxfh-sfhflags-snapdir (list (cons 'raw gxfh-sfhflags-snapdir) (cons 'formatted (if (= gxfh-sfhflags-snapdir 0) "Not set" "Set"))))
        (cons 'gxfh-sfhflags-streamdir (list (cons 'raw gxfh-sfhflags-streamdir) (cons 'formatted (if (= gxfh-sfhflags-streamdir 0) "Not set" "Set"))))
        (cons 'gxfh-spinfid (list (cons 'raw gxfh-spinfid) (cons 'formatted (fmt-hex gxfh-spinfid))))
        (cons 'gxfh-spinfuid (list (cons 'raw gxfh-spinfuid) (cons 'formatted (fmt-hex gxfh-spinfuid))))
        (cons 'gxfh-exportptid (list (cons 'raw gxfh-exportptid) (cons 'formatted (fmt-hex gxfh-exportptid))))
        (cons 'gxfh-exportptuid (list (cons 'raw gxfh-exportptuid) (cons 'formatted (fmt-hex gxfh-exportptuid))))
        (cons 'fh-version (list (cons 'raw fh-version) (cons 'formatted (number->string fh-version))))
        (cons 'fh-dc-exportid (list (cons 'raw fh-dc-exportid) (cons 'formatted (fmt-hex fh-dc-exportid))))
        (cons 'fh-dc-opaque (list (cons 'raw fh-dc-opaque) (cons 'formatted (fmt-bytes fh-dc-opaque))))
        (cons 'fh-pd-share (list (cons 'raw fh-pd-share) (cons 'formatted (number->string fh-pd-share))))
        (cons 'fh-pd-flags (list (cons 'raw fh-pd-flags) (cons 'formatted (fmt-hex fh-pd-flags))))
        (cons 'fh-pd-flags-version (list (cons 'raw fh-pd-flags-version) (cons 'formatted (if (= fh-pd-flags-version 0) "Not set" "Set"))))
        (cons 'fh-pd-flags-reserved (list (cons 'raw fh-pd-flags-reserved) (cons 'formatted (if (= fh-pd-flags-reserved 0) "Not set" "Set"))))
        (cons 'fh-pd-inum (list (cons 'raw fh-pd-inum) (cons 'formatted (number->string fh-pd-inum))))
        (cons 'fh-pd-container (list (cons 'raw fh-pd-container) (cons 'formatted (number->string fh-pd-container))))
        (cons 'fh-pd-spaces (list (cons 'raw fh-pd-spaces) (cons 'formatted (fmt-hex fh-pd-spaces))))
        (cons 'fh-pd-spaces-snapid (list (cons 'raw fh-pd-spaces-snapid) (cons 'formatted (if (= fh-pd-spaces-snapid 0) "Not set" "Set"))))
        (cons 'fh-pd-spaces-container (list (cons 'raw fh-pd-spaces-container) (cons 'formatted (if (= fh-pd-spaces-container 0) "Not set" "Set"))))
        (cons 'fh-pd-sites (list (cons 'raw fh-pd-sites) (cons 'formatted (fmt-hex fh-pd-sites))))
        (cons 'fh-pd-sites-inum (list (cons 'raw fh-pd-sites-inum) (cons 'formatted (if (= fh-pd-sites-inum 0) "Not set" "Set"))))
        (cons 'fh-pd-sites-siteid (list (cons 'raw fh-pd-sites-siteid) (cons 'formatted (if (= fh-pd-sites-siteid 0) "Not set" "Set"))))
        (cons 'fh-obj (list (cons 'raw fh-obj) (cons 'formatted (fmt-bytes fh-obj))))
        (cons 'fh-obj-fsid (list (cons 'raw fh-obj-fsid) (cons 'formatted (number->string fh-obj-fsid))))
        (cons 'fh-obj-kindid (list (cons 'raw fh-obj-kindid) (cons 'formatted (number->string fh-obj-kindid))))
        (cons 'fh-obj-treeid (list (cons 'raw fh-obj-treeid) (cons 'formatted (number->string fh-obj-treeid))))
        (cons 'fh-obj-inode (list (cons 'raw fh-obj-inode) (cons 'formatted (number->string fh-obj-inode))))
        (cons 'fh-obj-gen (list (cons 'raw fh-obj-gen) (cons 'formatted (number->string fh-obj-gen))))
        (cons 'fh-ex (list (cons 'raw fh-ex) (cons 'formatted (fmt-bytes fh-ex))))
        (cons 'fh-ex-fsid (list (cons 'raw fh-ex-fsid) (cons 'formatted (number->string fh-ex-fsid))))
        (cons 'fh-ex-kindid (list (cons 'raw fh-ex-kindid) (cons 'formatted (number->string fh-ex-kindid))))
        (cons 'fh-ex-treeid (list (cons 'raw fh-ex-treeid) (cons 'formatted (number->string fh-ex-treeid))))
        (cons 'fh-ex-inode (list (cons 'raw fh-ex-inode) (cons 'formatted (number->string fh-ex-inode))))
        (cons 'fh-ex-gen (list (cons 'raw fh-ex-gen) (cons 'formatted (number->string fh-ex-gen))))
        (cons 'fh-ro-node (list (cons 'raw fh-ro-node) (cons 'formatted (if (= fh-ro-node 0) "object is *not* read-only" "object is read only"))))
        (cons 'fh-hash (list (cons 'raw fh-hash) (cons 'formatted (fmt-hex fh-hash))))
        (cons 'read-offset (list (cons 'raw read-offset) (cons 'formatted (number->string read-offset))))
        (cons 'read-count (list (cons 'raw read-count) (cons 'formatted (number->string read-count))))
        (cons 'read-totalcount (list (cons 'raw read-totalcount) (cons 'formatted (number->string read-totalcount))))
        (cons 'write-beginoffset (list (cons 'raw write-beginoffset) (cons 'formatted (number->string write-beginoffset))))
        (cons 'write-offset (list (cons 'raw write-offset) (cons 'formatted (number->string write-offset))))
        (cons 'write-totalcount (list (cons 'raw write-totalcount) (cons 'formatted (number->string write-totalcount))))
        (cons 'readdir-cookie (list (cons 'raw readdir-cookie) (cons 'formatted (number->string readdir-cookie))))
        (cons 'readdir-count (list (cons 'raw readdir-count) (cons 'formatted (number->string readdir-count))))
        (cons 'readdir-eof (list (cons 'raw readdir-eof) (cons 'formatted (number->string readdir-eof))))
        (cons 'statfs-tsize (list (cons 'raw statfs-tsize) (cons 'formatted (number->string statfs-tsize))))
        (cons 'statfs-bsize (list (cons 'raw statfs-bsize) (cons 'formatted (number->string statfs-bsize))))
        (cons 'statfs-blocks (list (cons 'raw statfs-blocks) (cons 'formatted (number->string statfs-blocks))))
        (cons 'statfs-bfree (list (cons 'raw statfs-bfree) (cons 'formatted (number->string statfs-bfree))))
        (cons 'statfs-bavail (list (cons 'raw statfs-bavail) (cons 'formatted (number->string statfs-bavail))))
        (cons 'access-check (list (cons 'raw access-check) (cons 'formatted (fmt-hex access-check))))
        (cons 'access-supported (list (cons 'raw access-supported) (cons 'formatted (fmt-hex access-supported))))
        (cons 'access-rights (list (cons 'raw access-rights) (cons 'formatted (fmt-hex access-rights))))
        (cons 'fsstat-invarsec (list (cons 'raw fsstat-invarsec) (cons 'formatted (number->string fsstat-invarsec))))
        (cons 'fsinfo-rtmax (list (cons 'raw fsinfo-rtmax) (cons 'formatted (number->string fsinfo-rtmax))))
        (cons 'pathconf-linkmax (list (cons 'raw pathconf-linkmax) (cons 'formatted (number->string pathconf-linkmax))))
        (cons 'fh-fsid-major16 (list (cons 'raw fh-fsid-major16) (cons 'formatted (number->string fh-fsid-major16))))
        (cons 'fh-fsid-minor16 (list (cons 'raw fh-fsid-minor16) (cons 'formatted (number->string fh-fsid-minor16))))
        (cons 'fh-fsid-inode (list (cons 'raw fh-fsid-inode) (cons 'formatted (number->string fh-fsid-inode))))
        (cons 'fh-exportid (list (cons 'raw fh-exportid) (cons 'formatted (fmt-bytes fh-exportid))))
        (cons 'access-denied (list (cons 'raw access-denied) (cons 'formatted (number->string access-denied))))
        (cons 'fsinfo-rtpref (list (cons 'raw fsinfo-rtpref) (cons 'formatted (number->string fsinfo-rtpref))))
        (cons 'pathconf-name-max (list (cons 'raw pathconf-name-max) (cons 'formatted (number->string pathconf-name-max))))
        (cons 'huge-bitmap-length (list (cons 'raw huge-bitmap-length) (cons 'formatted (number->string huge-bitmap-length))))
        (cons 'num-offload-status (list (cons 'raw num-offload-status) (cons 'formatted (number->string num-offload-status))))
        (cons 'readdir-entry-fileid (list (cons 'raw readdir-entry-fileid) (cons 'formatted (number->string readdir-entry-fileid))))
        (cons 'fsinfo-rtmult (list (cons 'raw fsinfo-rtmult) (cons 'formatted (number->string fsinfo-rtmult))))
        (cons 'offload-status-index (list (cons 'raw offload-status-index) (cons 'formatted (number->string offload-status-index))))
        (cons 'ops-count (list (cons 'raw ops-count) (cons 'formatted (number->string ops-count))))
        (cons 'readdir-entry-cookie (list (cons 'raw readdir-entry-cookie) (cons 'formatted (number->string readdir-entry-cookie))))
        (cons 'fsinfo-wtmax (list (cons 'raw fsinfo-wtmax) (cons 'formatted (number->string fsinfo-wtmax))))
        (cons 'deviceid (list (cons 'raw deviceid) (cons 'formatted (fmt-bytes deviceid))))
        (cons 'fattr-uid (list (cons 'raw fattr-uid) (cons 'formatted (number->string fattr-uid))))
        (cons 'fsinfo-wtpref (list (cons 'raw fsinfo-wtpref) (cons 'formatted (number->string fsinfo-wtpref))))
        (cons 'stateid (list (cons 'raw stateid) (cons 'formatted (fmt-bytes stateid))))
        (cons 'fh-fn-inode (list (cons 'raw fh-fn-inode) (cons 'formatted (number->string fh-fn-inode))))
        (cons 'fh-fn-generation (list (cons 'raw fh-fn-generation) (cons 'formatted (number->string fh-fn-generation))))
        (cons 'fh-dirinode (list (cons 'raw fh-dirinode) (cons 'formatted (number->string fh-dirinode))))
        (cons 'fh-gfid (list (cons 'raw fh-gfid) (cons 'formatted (fmt-bytes fh-gfid))))
        (cons 'fattr-gid (list (cons 'raw fattr-gid) (cons 'formatted (number->string fattr-gid))))
        (cons 'verifier (list (cons 'raw verifier) (cons 'formatted (fmt-bytes verifier))))
        (cons 'mode-suid (list (cons 'raw mode-suid) (cons 'formatted (if (= mode-suid 0) "Not set" "Set"))))
        (cons 'mode-sgid (list (cons 'raw mode-sgid) (cons 'formatted (if (= mode-sgid 0) "Not set" "Set"))))
        (cons 'mode-sticky (list (cons 'raw mode-sticky) (cons 'formatted (if (= mode-sticky 0) "Not set" "Set"))))
        (cons 'mode-rusr (list (cons 'raw mode-rusr) (cons 'formatted (if (= mode-rusr 0) "Not set" "Set"))))
        (cons 'mode-wusr (list (cons 'raw mode-wusr) (cons 'formatted (if (= mode-wusr 0) "Not set" "Set"))))
        (cons 'mode-xusr (list (cons 'raw mode-xusr) (cons 'formatted (if (= mode-xusr 0) "Not set" "Set"))))
        (cons 'mode-rgrp (list (cons 'raw mode-rgrp) (cons 'formatted (if (= mode-rgrp 0) "Not set" "Set"))))
        (cons 'mode-wgrp (list (cons 'raw mode-wgrp) (cons 'formatted (if (= mode-wgrp 0) "Not set" "Set"))))
        (cons 'mode-xgrp (list (cons 'raw mode-xgrp) (cons 'formatted (if (= mode-xgrp 0) "Not set" "Set"))))
        (cons 'mode-roth (list (cons 'raw mode-roth) (cons 'formatted (if (= mode-roth 0) "Not set" "Set"))))
        (cons 'mode-woth (list (cons 'raw mode-woth) (cons 'formatted (if (= mode-woth 0) "Not set" "Set"))))
        (cons 'mode-xoth (list (cons 'raw mode-xoth) (cons 'formatted (if (= mode-xoth 0) "Not set" "Set"))))
        (cons 'fsinfo-wtmult (list (cons 'raw fsinfo-wtmult) (cons 'formatted (number->string fsinfo-wtmult))))
        (cons 'fattr-size (list (cons 'raw fattr-size) (cons 'formatted (number->string fattr-size))))
        (cons 'fsinfo-dtpref (list (cons 'raw fsinfo-dtpref) (cons 'formatted (number->string fsinfo-dtpref))))
        (cons 'fsinfo-properties (list (cons 'raw fsinfo-properties) (cons 'formatted (fmt-hex fsinfo-properties))))
        (cons 'fsinfo-properties-setattr (list (cons 'raw fsinfo-properties-setattr) (cons 'formatted (if (= fsinfo-properties-setattr 0) "Not set" "Set"))))
        (cons 'fsinfo-properties-pathconf (list (cons 'raw fsinfo-properties-pathconf) (cons 'formatted (if (= fsinfo-properties-pathconf 0) "should be get for every single file" "is valid for all files"))))
        (cons 'fsinfo-properties-symlinks (list (cons 'raw fsinfo-properties-symlinks) (cons 'formatted (if (= fsinfo-properties-symlinks 0) "Not set" "Set"))))
        (cons 'fsinfo-properties-hardlinks (list (cons 'raw fsinfo-properties-hardlinks) (cons 'formatted (if (= fsinfo-properties-hardlinks 0) "Not set" "Set"))))
        (cons 'sessionid (list (cons 'raw sessionid) (cons 'formatted (fmt-bytes sessionid))))
        (cons 'specdata1 (list (cons 'raw specdata1) (cons 'formatted (number->string specdata1))))
        (cons 'specdata2 (list (cons 'raw specdata2) (cons 'formatted (number->string specdata2))))
        (cons 'exchid-reply-flags (list (cons 'raw exchid-reply-flags) (cons 'formatted (fmt-hex exchid-reply-flags))))
        (cons 'sequence-status-flags (list (cons 'raw sequence-status-flags) (cons 'formatted (fmt-hex sequence-status-flags))))
        (cons 'sequence-status-flags-cb-path-down (list (cons 'raw sequence-status-flags-cb-path-down) (cons 'formatted (if (= sequence-status-flags-cb-path-down 0) "Not set" "Set"))))
        (cons 'sequence-status-flags-cb-gss-contexts-expiring (list (cons 'raw sequence-status-flags-cb-gss-contexts-expiring) (cons 'formatted (if (= sequence-status-flags-cb-gss-contexts-expiring 0) "Not set" "Set"))))
        (cons 'sequence-status-flags-cb-gss-contexts-expired (list (cons 'raw sequence-status-flags-cb-gss-contexts-expired) (cons 'formatted (if (= sequence-status-flags-cb-gss-contexts-expired 0) "Not set" "Set"))))
        (cons 'sequence-status-flags-expired-all-state-revoked (list (cons 'raw sequence-status-flags-expired-all-state-revoked) (cons 'formatted (if (= sequence-status-flags-expired-all-state-revoked 0) "Not set" "Set"))))
        (cons 'sequence-status-flags-expired-some-state-revoked (list (cons 'raw sequence-status-flags-expired-some-state-revoked) (cons 'formatted (if (= sequence-status-flags-expired-some-state-revoked 0) "Not set" "Set"))))
        (cons 'sequence-status-flags-admin-state-revoked (list (cons 'raw sequence-status-flags-admin-state-revoked) (cons 'formatted (if (= sequence-status-flags-admin-state-revoked 0) "Not set" "Set"))))
        (cons 'sequence-status-flags-recallable-state-revoked (list (cons 'raw sequence-status-flags-recallable-state-revoked) (cons 'formatted (if (= sequence-status-flags-recallable-state-revoked 0) "Not set" "Set"))))
        (cons 'sequence-status-flags-lease-moved (list (cons 'raw sequence-status-flags-lease-moved) (cons 'formatted (if (= sequence-status-flags-lease-moved 0) "Not set" "Set"))))
        (cons 'sequence-status-flags-restart-reclaim-needed (list (cons 'raw sequence-status-flags-restart-reclaim-needed) (cons 'formatted (if (= sequence-status-flags-restart-reclaim-needed 0) "Not set" "Set"))))
        (cons 'sequence-status-flags-cb-path-down-session (list (cons 'raw sequence-status-flags-cb-path-down-session) (cons 'formatted (if (= sequence-status-flags-cb-path-down-session 0) "Not set" "Set"))))
        (cons 'sequence-status-flags-backchannel-fault (list (cons 'raw sequence-status-flags-backchannel-fault) (cons 'formatted (if (= sequence-status-flags-backchannel-fault 0) "Not set" "Set"))))
        (cons 'sequence-status-flags-devid-changed (list (cons 'raw sequence-status-flags-devid-changed) (cons 'formatted (if (= sequence-status-flags-devid-changed 0) "Not set" "Set"))))
        (cons 'sequence-status-flags-devid-deleted (list (cons 'raw sequence-status-flags-devid-deleted) (cons 'formatted (if (= sequence-status-flags-devid-deleted 0) "Not set" "Set"))))
        (cons 'fh-length (list (cons 'raw fh-length) (cons 'formatted (number->string fh-length))))
        (cons 'pathname-components (list (cons 'raw pathname-components) (cons 'formatted (number->string pathname-components))))
        (cons 'aceflags (list (cons 'raw aceflags) (cons 'formatted (fmt-hex aceflags))))
        (cons 'aceflag-file-inherit (list (cons 'raw aceflag-file-inherit) (cons 'formatted (if (= aceflag-file-inherit 0) "Not set" "Set"))))
        (cons 'aceflag-dir-inherit (list (cons 'raw aceflag-dir-inherit) (cons 'formatted (if (= aceflag-dir-inherit 0) "Not set" "Set"))))
        (cons 'aceflag-no-prop-inherit (list (cons 'raw aceflag-no-prop-inherit) (cons 'formatted (if (= aceflag-no-prop-inherit 0) "Not set" "Set"))))
        (cons 'aceflag-inherit-only (list (cons 'raw aceflag-inherit-only) (cons 'formatted (if (= aceflag-inherit-only 0) "Not set" "Set"))))
        (cons 'aceflag-successful-access (list (cons 'raw aceflag-successful-access) (cons 'formatted (if (= aceflag-successful-access 0) "Not set" "Set"))))
        (cons 'aceflag-failed-access (list (cons 'raw aceflag-failed-access) (cons 'formatted (if (= aceflag-failed-access 0) "Not set" "Set"))))
        (cons 'aceflag-id-group (list (cons 'raw aceflag-id-group) (cons 'formatted (if (= aceflag-id-group 0) "Not set" "Set"))))
        (cons 'aceflag-inherited-ace (list (cons 'raw aceflag-inherited-ace) (cons 'formatted (if (= aceflag-inherited-ace 0) "Not set" "Set"))))
        (cons 'acemask (list (cons 'raw acemask) (cons 'formatted (fmt-hex acemask))))
        (cons 'ace-permission (list (cons 'raw ace-permission) (cons 'formatted (fmt-hex ace-permission))))
        (cons 'aclflags (list (cons 'raw aclflags) (cons 'formatted (number->string aclflags))))
        (cons 'aclflag-auto-inherit (list (cons 'raw aclflag-auto-inherit) (cons 'formatted (if (= aclflag-auto-inherit 0) "Not set" "Set"))))
        (cons 'aclflag-protected (list (cons 'raw aclflag-protected) (cons 'formatted (if (= aclflag-protected 0) "Not set" "Set"))))
        (cons 'aclflag-defaulted (list (cons 'raw aclflag-defaulted) (cons 'formatted (if (= aclflag-defaulted 0) "Not set" "Set"))))
        (cons 'num-aces (list (cons 'raw num-aces) (cons 'formatted (number->string num-aces))))
        (cons 'fattr-aclsupport (list (cons 'raw fattr-aclsupport) (cons 'formatted (number->string fattr-aclsupport))))
        (cons 'aclsupport-allow-acl (list (cons 'raw aclsupport-allow-acl) (cons 'formatted (if (= aclsupport-allow-acl 0) "Not set" "Set"))))
        (cons 'aclsupport-deny-acl (list (cons 'raw aclsupport-deny-acl) (cons 'formatted (if (= aclsupport-deny-acl 0) "Not set" "Set"))))
        (cons 'aclsupport-audit-acl (list (cons 'raw aclsupport-audit-acl) (cons 'formatted (if (= aclsupport-audit-acl 0) "Not set" "Set"))))
        (cons 'aclsupport-alarm-acl (list (cons 'raw aclsupport-alarm-acl) (cons 'formatted (if (= aclsupport-alarm-acl 0) "Not set" "Set"))))
        (cons 'fattr-fs-charset-cap (list (cons 'raw fattr-fs-charset-cap) (cons 'formatted (fmt-hex fattr-fs-charset-cap))))
        (cons 'mode (list (cons 'raw mode) (cons 'formatted (fmt-oct mode))))
        (cons 'mode-set-user-id (list (cons 'raw mode-set-user-id) (cons 'formatted (if (= mode-set-user-id 0) "Not set" "Set"))))
        (cons 'mode-set-group-id (list (cons 'raw mode-set-group-id) (cons 'formatted (if (= mode-set-group-id 0) "Not set" "Set"))))
        (cons 'mode-save-swap-text (list (cons 'raw mode-save-swap-text) (cons 'formatted (if (= mode-save-swap-text 0) "Not set" "Set"))))
        (cons 'mode-read-owner (list (cons 'raw mode-read-owner) (cons 'formatted (if (= mode-read-owner 0) "Not set" "Set"))))
        (cons 'mode-write-owner (list (cons 'raw mode-write-owner) (cons 'formatted (if (= mode-write-owner 0) "Not set" "Set"))))
        (cons 'mode-exec-owner (list (cons 'raw mode-exec-owner) (cons 'formatted (if (= mode-exec-owner 0) "Not set" "Set"))))
        (cons 'mode-read-group (list (cons 'raw mode-read-group) (cons 'formatted (if (= mode-read-group 0) "Not set" "Set"))))
        (cons 'mode-write-group (list (cons 'raw mode-write-group) (cons 'formatted (if (= mode-write-group 0) "Not set" "Set"))))
        (cons 'mode-exec-group (list (cons 'raw mode-exec-group) (cons 'formatted (if (= mode-exec-group 0) "Not set" "Set"))))
        (cons 'mode-read-other (list (cons 'raw mode-read-other) (cons 'formatted (if (= mode-read-other 0) "Not set" "Set"))))
        (cons 'mode-write-other (list (cons 'raw mode-write-other) (cons 'formatted (if (= mode-write-other 0) "Not set" "Set"))))
        (cons 'mode-exec-other (list (cons 'raw mode-exec-other) (cons 'formatted (if (= mode-exec-other 0) "Not set" "Set"))))
        (cons 'want-notify-flags (list (cons 'raw want-notify-flags) (cons 'formatted (fmt-hex want-notify-flags))))
        (cons 'want-signal-deleg-when-resrc-avail (list (cons 'raw want-signal-deleg-when-resrc-avail) (cons 'formatted (if (= want-signal-deleg-when-resrc-avail 0) "False" "True"))))
        (cons 'want-push-deleg-when-uncontended (list (cons 'raw want-push-deleg-when-uncontended) (cons 'formatted (if (= want-push-deleg-when-uncontended 0) "False" "True"))))
        (cons 'listxattr-names-len (list (cons 'raw listxattr-names-len) (cons 'formatted (number->string listxattr-names-len))))
        (cons 'name (list (cons 'raw name) (cons 'formatted (utf8->string name))))
        (cons 'value-follows (list (cons 'raw value-follows) (cons 'formatted (if (= value-follows 0) "False" "True"))))
        (cons 'open-rflags (list (cons 'raw open-rflags) (cons 'formatted (fmt-hex open-rflags))))
        (cons 'open-rflags-confirm (list (cons 'raw open-rflags-confirm) (cons 'formatted (if (= open-rflags-confirm 0) "Not set" "Set"))))
        (cons 'open-rflags-locktype-posix (list (cons 'raw open-rflags-locktype-posix) (cons 'formatted (if (= open-rflags-locktype-posix 0) "Not set" "Set"))))
        (cons 'open-rflags-preserve-unlinked (list (cons 'raw open-rflags-preserve-unlinked) (cons 'formatted (if (= open-rflags-preserve-unlinked 0) "Not set" "Set"))))
        (cons 'open-rflags-may-notify-lock (list (cons 'raw open-rflags-may-notify-lock) (cons 'formatted (if (= open-rflags-may-notify-lock 0) "Not set" "Set"))))
        (cons 'stateid-hash (list (cons 'raw stateid-hash) (cons 'formatted (fmt-hex stateid-hash))))
        (cons 'stateid-other (list (cons 'raw stateid-other) (cons 'formatted (fmt-bytes stateid-other))))
        (cons 'stateid-other-hash (list (cons 'raw stateid-other-hash) (cons 'formatted (fmt-hex stateid-other-hash))))
        (cons 'pattern-hash (list (cons 'raw pattern-hash) (cons 'formatted (fmt-hex pattern-hash))))
        (cons 'device-error-count (list (cons 'raw device-error-count) (cons 'formatted (number->string device-error-count))))
        (cons 'device-errors-index (list (cons 'raw device-errors-index) (cons 'formatted (number->string device-errors-index))))
        (cons 'ff-ioerrs-count (list (cons 'raw ff-ioerrs-count) (cons 'formatted (number->string ff-ioerrs-count))))
        (cons 'ff-ioerrs-index (list (cons 'raw ff-ioerrs-index) (cons 'formatted (number->string ff-ioerrs-index))))
        (cons 'ff-iostats-count (list (cons 'raw ff-iostats-count) (cons 'formatted (number->string ff-iostats-count))))
        (cons 'ff-iostats-index (list (cons 'raw ff-iostats-index) (cons 'formatted (number->string ff-iostats-index))))
        (cons 'devaddr-scsi-vpd-designator (list (cons 'raw devaddr-scsi-vpd-designator) (cons 'formatted (fmt-bytes devaddr-scsi-vpd-designator))))
        (cons 'devaddr-scsi-private-key (list (cons 'raw devaddr-scsi-private-key) (cons 'formatted (fmt-bytes devaddr-scsi-private-key))))
        (cons 'devaddr-scsi-vol-index (list (cons 'raw devaddr-scsi-vol-index) (cons 'formatted (number->string devaddr-scsi-vol-index))))
        (cons 'devaddr-ssv-start (list (cons 'raw devaddr-ssv-start) (cons 'formatted (number->string devaddr-ssv-start))))
        (cons 'devaddr-ssv-length (list (cons 'raw devaddr-ssv-length) (cons 'formatted (number->string devaddr-ssv-length))))
        (cons 'devaddr-scsi-vol-ref-index (list (cons 'raw devaddr-scsi-vol-ref-index) (cons 'formatted (number->string devaddr-scsi-vol-ref-index))))
        (cons 'devaddr-ssv-stripe-unit (list (cons 'raw devaddr-ssv-stripe-unit) (cons 'formatted (number->string devaddr-ssv-stripe-unit))))
        (cons 'callback-stateids (list (cons 'raw callback-stateids) (cons 'formatted (number->string callback-stateids))))
        (cons 'callback-stateids-index (list (cons 'raw callback-stateids-index) (cons 'formatted (number->string callback-stateids-index))))
        (cons 'source-servers (list (cons 'raw source-servers) (cons 'formatted (number->string source-servers))))
        (cons 'source-server-index (list (cons 'raw source-server-index) (cons 'formatted (number->string source-server-index))))
        (cons 'nfl-util (list (cons 'raw nfl-util) (cons 'formatted (fmt-hex nfl-util))))
        (cons 'nfl-util-stripe-size (list (cons 'raw nfl-util-stripe-size) (cons 'formatted (number->string nfl-util-stripe-size))))
        (cons 'nfl-util-commit-thru-mds (list (cons 'raw nfl-util-commit-thru-mds) (cons 'formatted (number->string nfl-util-commit-thru-mds))))
        (cons 'nfl-util-dense (list (cons 'raw nfl-util-dense) (cons 'formatted (number->string nfl-util-dense))))
        (cons 'nfl-fhs (list (cons 'raw nfl-fhs) (cons 'formatted (fmt-hex nfl-fhs))))
        (cons 'nfl-mirrors (list (cons 'raw nfl-mirrors) (cons 'formatted (number->string nfl-mirrors))))
        (cons 'ff-layout-flags (list (cons 'raw ff-layout-flags) (cons 'formatted (fmt-hex ff-layout-flags))))
        (cons 'ff-layout-flags-no-layoutcommit (list (cons 'raw ff-layout-flags-no-layoutcommit) (cons 'formatted (if (= ff-layout-flags-no-layoutcommit 0) "Not set" "Set"))))
        (cons 'ff-layout-flags-no-io-thru-mds (list (cons 'raw ff-layout-flags-no-io-thru-mds) (cons 'formatted (if (= ff-layout-flags-no-io-thru-mds 0) "Not set" "Set"))))
        (cons 'ff-layout-flags-no-read-io (list (cons 'raw ff-layout-flags-no-read-io) (cons 'formatted (if (= ff-layout-flags-no-read-io 0) "Not set" "Set"))))
        (cons 'exchid-call-flags (list (cons 'raw exchid-call-flags) (cons 'formatted (fmt-hex exchid-call-flags))))
        (cons 'exchid-flags-confirmed-r (list (cons 'raw exchid-flags-confirmed-r) (cons 'formatted (if (= exchid-flags-confirmed-r 0) "Not set" "Set"))))
        (cons 'exchid-flags-upd-conf-rec-a (list (cons 'raw exchid-flags-upd-conf-rec-a) (cons 'formatted (if (= exchid-flags-upd-conf-rec-a 0) "Not set" "Set"))))
        (cons 'exchid-flags-pnfs-ds (list (cons 'raw exchid-flags-pnfs-ds) (cons 'formatted (if (= exchid-flags-pnfs-ds 0) "Not set" "Set"))))
        (cons 'exchid-flags-pnfs-mds (list (cons 'raw exchid-flags-pnfs-mds) (cons 'formatted (if (= exchid-flags-pnfs-mds 0) "Not set" "Set"))))
        (cons 'exchid-flags-non-pnfs (list (cons 'raw exchid-flags-non-pnfs) (cons 'formatted (if (= exchid-flags-non-pnfs 0) "Not set" "Set"))))
        (cons 'exchid-flags-bind-princ (list (cons 'raw exchid-flags-bind-princ) (cons 'formatted (if (= exchid-flags-bind-princ 0) "Not set" "Set"))))
        (cons 'exchid-flags-moved-migr (list (cons 'raw exchid-flags-moved-migr) (cons 'formatted (if (= exchid-flags-moved-migr 0) "Not set" "Set"))))
        (cons 'exchid-flags-moved-refer (list (cons 'raw exchid-flags-moved-refer) (cons 'formatted (if (= exchid-flags-moved-refer 0) "Not set" "Set"))))
        )))

    (catch (e)
      (err (str "NFS parse error: " e)))))

;; dissect-nfs: parse NFS from bytevector
;; Returns (ok fields-alist) or (err message)