;;
;; packet-ocfs2.c
;;
;; Routines for OCFS2's networking protocol disassembly (o2net and o2dlm)
;; The OCFS2 cluster file system is available in the mainline Linux kernel.
;;
;; Copyright (C) 2006, 2011 Oracle. All rights reserved.
;;
;; Authors:
;; Kurt Hackel		<kurt.hackel@oracle.com>
;; Zach Brown		<zach.brown@oracle.com>
;; Sunil Mushran	<sunil.mushran@oracle.com>
;; Jeff Liu		<jeff.liu@oracle.com>
;;
;; SPDX-License-Identifier: GPL-2.0-or-later
;;

;; jerboa-ethereal/dissectors/ocfs2.ss
;; Auto-generated from wireshark/epan/dissectors/packet-ocfs2.c

(import (jerboa prelude))

;; ── Protocol Helpers ─────────────────────────────────────────────────
(def (read-u8 buf offset)
  (if (>= offset (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u8-ref buf offset))))

(def (read-u16be buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness big)))))

(def (read-u24be buf offset)
  (if (> (+ offset 3) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (+ (* (bytevector-u8-ref buf offset) 65536)
             (* (bytevector-u8-ref buf (+ offset 1)) 256)
             (bytevector-u8-ref buf (+ offset 2))))))

(def (read-u32be buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness big)))))

(def (read-u16le buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness little)))))

(def (read-u32le buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness little)))))

(def (read-u64be buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness big)))))

(def (read-u64le buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness little)))))

(def (slice buf offset len)
  (if (> (+ offset len) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (let ((result (make-bytevector len)))
            (bytevector-copy! buf offset result 0 len)
            result))))

(def (extract-bits val mask shift)
  (bitwise-arithmetic-shift-right (bitwise-and val mask) shift))

(def (fmt-ipv4 addr)
  (let ((b0 (bitwise-arithmetic-shift-right addr 24))
        (b1 (bitwise-and (bitwise-arithmetic-shift-right addr 16) 255))
        (b2 (bitwise-and (bitwise-arithmetic-shift-right addr 8) 255))
        (b3 (bitwise-and addr 255)))
    (str b0 "." b1 "." b2 "." b3)))

(def (fmt-mac bytes)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bytes))
    ":"))

(def (fmt-hex val)
  (str "0x" (number->string val 16)))

(def (fmt-oct val)
  (str "0" (number->string val 8)))

(def (fmt-port port)
  (number->string port))

(def (fmt-bytes bv)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bv))
    " "))

(def (fmt-ipv6-address bytes)
  (let loop ((i 0) (parts '()))
    (if (>= i 16)
        (string-join (reverse parts) ":")
        (loop (+ i 2)
              (cons (let ((w (+ (* (bytevector-u8-ref bytes i) 256)
                                (bytevector-u8-ref bytes (+ i 1)))))
                      (number->string w 16))
                    parts)))))

;; ── Dissector ──────────────────────────────────────────────────────
(def (dissect-ocfs2 buffer)
  "OCFS2 Networking"
  (try
    (let* (
           (lock-flags (unwrap (read-u32be buffer 0)))
           (lock-flag-unused1 (extract-bits lock-flags 0xF 0))
           (lock-flag-orphan (extract-bits lock-flags 0x10 4))
           (lock-flag-parentable (extract-bits lock-flags 0x20 5))
           (lock-flag-block (extract-bits lock-flags 0x40 6))
           (lock-flag-local (extract-bits lock-flags 0x80 7))
           (lock-flag-valblk (extract-bits lock-flags 0x100 8))
           (lock-flag-noqueue (extract-bits lock-flags 0x200 9))
           (lock-flag-convert (extract-bits lock-flags 0x400 10))
           (lock-flag-nodlckwt (extract-bits lock-flags 0x800 11))
           (lock-flag-unlock (extract-bits lock-flags 0x1000 12))
           (lock-flag-cancel (extract-bits lock-flags 0x2000 13))
           (lock-flag-deqall (extract-bits lock-flags 0x4000 14))
           (lock-flag-invvalblk (extract-bits lock-flags 0x8000 15))
           (lock-flag-syncsts (extract-bits lock-flags 0x10000 16))
           (lock-flag-timeout (extract-bits lock-flags 0x20000 17))
           (lock-flag-sngldlck (extract-bits lock-flags 0x40000 18))
           (lock-flag-findlocal (extract-bits lock-flags 0x80000 19))
           (lock-flag-proc-owned (extract-bits lock-flags 0x100000 20))
           (lock-flag-xid (extract-bits lock-flags 0x200000 21))
           (lock-flag-xid-conflict (extract-bits lock-flags 0x400000 22))
           (lock-flag-force (extract-bits lock-flags 0x800000 23))
           (lock-flag-revvalblk (extract-bits lock-flags 0x1000000 24))
           (lock-flag-unused2 (extract-bits lock-flags 0xE000000 25))
           (lock-flag-migration (extract-bits lock-flags 0x10000000 28))
           (lock-flag-put-lvb (extract-bits lock-flags 0x20000000 29))
           (lock-flag-get-lvb (extract-bits lock-flags 0x40000000 30))
           (lock-flag-recovery (extract-bits lock-flags 0x80000000 31))
           (data-len (unwrap (read-u16be buffer 2)))
           (mres-num-locks (unwrap (read-u8 buffer 2)))
           (mres-flags (unwrap (read-u8 buffer 3)))
           (mres-flag-recovery (extract-bits mres-flags 0x2 1))
           (mres-flag-migration (extract-bits mres-flags 0x4 2))
           (mres-flag-all-done (extract-bits mres-flags 0xF8 3))
           (pad (unwrap (read-u16be buffer 4)))
           (mres-total-locks (unwrap (read-u32be buffer 4)))
           (sys-status (unwrap (read-u32be buffer 8)))
           (name (unwrap (slice buffer 8 32)))
           (status (unwrap (read-u32be buffer 12)))
           (key (unwrap (read-u32be buffer 16)))
           (msg-num (unwrap (read-u32be buffer 20)))
           (node-idx (unwrap (read-u8 buffer 24)))
           (payload (unwrap (slice buffer 24 1)))
           (mres-ml-flags (unwrap (read-u8 buffer 106)))
           (mres-convert-type (unwrap (read-u8 buffer 108)))
           (mres-highest-blocked (unwrap (read-u8 buffer 109)))
           (mres-node (unwrap (read-u8 buffer 110)))
           (node-map (unwrap (slice buffer 183 1)))
           (qr-node (unwrap (read-u8 buffer 183)))
           (qr-numregions (unwrap (read-u8 buffer 184)))
           (qr-namelen (unwrap (read-u8 buffer 185)))
           (qr-domain (unwrap (slice buffer 187 64)))
           (qr-region (unwrap (slice buffer 251 1)))
           (qn-nodenum (unwrap (read-u8 buffer 251)))
           (qn-numnodes (unwrap (read-u8 buffer 252)))
           (qn-namelen (unwrap (read-u8 buffer 253)))
           (qn-domain (unwrap (slice buffer 254 64)))
           (qn-node (unwrap (read-u8 buffer 318)))
           (qn-port (unwrap (read-u16be buffer 320)))
           (qn-ip (unwrap (read-u32be buffer 322)))
           (flags (unwrap (read-u32be buffer 330)))
           (lvb1 (unwrap (slice buffer 474 24)))
           (lvb2 (unwrap (slice buffer 498 24)))
           (lvb3 (unwrap (slice buffer 522 16)))
           (master (unwrap (read-u8 buffer 546)))
           (new-master (unwrap (read-u8 buffer 547)))
           (domain-name-len (unwrap (read-u8 buffer 557)))
           (domain-name (unwrap (slice buffer 558 64)))
           (namelen (unwrap (read-u8 buffer 625)))
           (pad16 (unwrap (read-u16be buffer 632)))
           (reco-lvb (unwrap (slice buffer 638 64)))
           (dead-node (unwrap (read-u8 buffer 703)))
           (pad8 (unwrap (read-u8 buffer 705)))
           (pad32 (unwrap (read-u32be buffer 706)))
           )

      (ok (list
        (cons 'lock-flags (list (cons 'raw lock-flags) (cons 'formatted (fmt-hex lock-flags))))
        (cons 'lock-flag-unused1 (list (cons 'raw lock-flag-unused1) (cons 'formatted (if (= lock-flag-unused1 0) "Not set" "Set"))))
        (cons 'lock-flag-orphan (list (cons 'raw lock-flag-orphan) (cons 'formatted (if (= lock-flag-orphan 0) "Not set" "Set"))))
        (cons 'lock-flag-parentable (list (cons 'raw lock-flag-parentable) (cons 'formatted (if (= lock-flag-parentable 0) "Not set" "Set"))))
        (cons 'lock-flag-block (list (cons 'raw lock-flag-block) (cons 'formatted (if (= lock-flag-block 0) "Not set" "Set"))))
        (cons 'lock-flag-local (list (cons 'raw lock-flag-local) (cons 'formatted (if (= lock-flag-local 0) "Not set" "Set"))))
        (cons 'lock-flag-valblk (list (cons 'raw lock-flag-valblk) (cons 'formatted (if (= lock-flag-valblk 0) "Not set" "Set"))))
        (cons 'lock-flag-noqueue (list (cons 'raw lock-flag-noqueue) (cons 'formatted (if (= lock-flag-noqueue 0) "Not set" "Set"))))
        (cons 'lock-flag-convert (list (cons 'raw lock-flag-convert) (cons 'formatted (if (= lock-flag-convert 0) "Not set" "Set"))))
        (cons 'lock-flag-nodlckwt (list (cons 'raw lock-flag-nodlckwt) (cons 'formatted (if (= lock-flag-nodlckwt 0) "Not set" "Set"))))
        (cons 'lock-flag-unlock (list (cons 'raw lock-flag-unlock) (cons 'formatted (if (= lock-flag-unlock 0) "Not set" "Set"))))
        (cons 'lock-flag-cancel (list (cons 'raw lock-flag-cancel) (cons 'formatted (if (= lock-flag-cancel 0) "Not set" "Set"))))
        (cons 'lock-flag-deqall (list (cons 'raw lock-flag-deqall) (cons 'formatted (if (= lock-flag-deqall 0) "Not set" "Set"))))
        (cons 'lock-flag-invvalblk (list (cons 'raw lock-flag-invvalblk) (cons 'formatted (if (= lock-flag-invvalblk 0) "Not set" "Set"))))
        (cons 'lock-flag-syncsts (list (cons 'raw lock-flag-syncsts) (cons 'formatted (if (= lock-flag-syncsts 0) "Not set" "Set"))))
        (cons 'lock-flag-timeout (list (cons 'raw lock-flag-timeout) (cons 'formatted (if (= lock-flag-timeout 0) "Not set" "Set"))))
        (cons 'lock-flag-sngldlck (list (cons 'raw lock-flag-sngldlck) (cons 'formatted (if (= lock-flag-sngldlck 0) "Not set" "Set"))))
        (cons 'lock-flag-findlocal (list (cons 'raw lock-flag-findlocal) (cons 'formatted (if (= lock-flag-findlocal 0) "Not set" "Set"))))
        (cons 'lock-flag-proc-owned (list (cons 'raw lock-flag-proc-owned) (cons 'formatted (if (= lock-flag-proc-owned 0) "Not set" "Set"))))
        (cons 'lock-flag-xid (list (cons 'raw lock-flag-xid) (cons 'formatted (if (= lock-flag-xid 0) "Not set" "Set"))))
        (cons 'lock-flag-xid-conflict (list (cons 'raw lock-flag-xid-conflict) (cons 'formatted (if (= lock-flag-xid-conflict 0) "Not set" "Set"))))
        (cons 'lock-flag-force (list (cons 'raw lock-flag-force) (cons 'formatted (if (= lock-flag-force 0) "Not set" "Set"))))
        (cons 'lock-flag-revvalblk (list (cons 'raw lock-flag-revvalblk) (cons 'formatted (if (= lock-flag-revvalblk 0) "Not set" "Set"))))
        (cons 'lock-flag-unused2 (list (cons 'raw lock-flag-unused2) (cons 'formatted (if (= lock-flag-unused2 0) "Not set" "Set"))))
        (cons 'lock-flag-migration (list (cons 'raw lock-flag-migration) (cons 'formatted (if (= lock-flag-migration 0) "Not set" "Set"))))
        (cons 'lock-flag-put-lvb (list (cons 'raw lock-flag-put-lvb) (cons 'formatted (if (= lock-flag-put-lvb 0) "Not set" "Set"))))
        (cons 'lock-flag-get-lvb (list (cons 'raw lock-flag-get-lvb) (cons 'formatted (if (= lock-flag-get-lvb 0) "Not set" "Set"))))
        (cons 'lock-flag-recovery (list (cons 'raw lock-flag-recovery) (cons 'formatted (if (= lock-flag-recovery 0) "Not set" "Set"))))
        (cons 'data-len (list (cons 'raw data-len) (cons 'formatted (number->string data-len))))
        (cons 'mres-num-locks (list (cons 'raw mres-num-locks) (cons 'formatted (number->string mres-num-locks))))
        (cons 'mres-flags (list (cons 'raw mres-flags) (cons 'formatted (fmt-hex mres-flags))))
        (cons 'mres-flag-recovery (list (cons 'raw mres-flag-recovery) (cons 'formatted (if (= mres-flag-recovery 0) "Not set" "Set"))))
        (cons 'mres-flag-migration (list (cons 'raw mres-flag-migration) (cons 'formatted (if (= mres-flag-migration 0) "Not set" "Set"))))
        (cons 'mres-flag-all-done (list (cons 'raw mres-flag-all-done) (cons 'formatted (if (= mres-flag-all-done 0) "Not set" "Set"))))
        (cons 'pad (list (cons 'raw pad) (cons 'formatted (fmt-hex pad))))
        (cons 'mres-total-locks (list (cons 'raw mres-total-locks) (cons 'formatted (number->string mres-total-locks))))
        (cons 'sys-status (list (cons 'raw sys-status) (cons 'formatted (number->string sys-status))))
        (cons 'name (list (cons 'raw name) (cons 'formatted (utf8->string name))))
        (cons 'status (list (cons 'raw status) (cons 'formatted (number->string status))))
        (cons 'key (list (cons 'raw key) (cons 'formatted (fmt-hex key))))
        (cons 'msg-num (list (cons 'raw msg-num) (cons 'formatted (number->string msg-num))))
        (cons 'node-idx (list (cons 'raw node-idx) (cons 'formatted (number->string node-idx))))
        (cons 'payload (list (cons 'raw payload) (cons 'formatted (fmt-bytes payload))))
        (cons 'mres-ml-flags (list (cons 'raw mres-ml-flags) (cons 'formatted (fmt-hex mres-ml-flags))))
        (cons 'mres-convert-type (list (cons 'raw mres-convert-type) (cons 'formatted (number->string mres-convert-type))))
        (cons 'mres-highest-blocked (list (cons 'raw mres-highest-blocked) (cons 'formatted (number->string mres-highest-blocked))))
        (cons 'mres-node (list (cons 'raw mres-node) (cons 'formatted (number->string mres-node))))
        (cons 'node-map (list (cons 'raw node-map) (cons 'formatted (fmt-bytes node-map))))
        (cons 'qr-node (list (cons 'raw qr-node) (cons 'formatted (number->string qr-node))))
        (cons 'qr-numregions (list (cons 'raw qr-numregions) (cons 'formatted (number->string qr-numregions))))
        (cons 'qr-namelen (list (cons 'raw qr-namelen) (cons 'formatted (number->string qr-namelen))))
        (cons 'qr-domain (list (cons 'raw qr-domain) (cons 'formatted (utf8->string qr-domain))))
        (cons 'qr-region (list (cons 'raw qr-region) (cons 'formatted (utf8->string qr-region))))
        (cons 'qn-nodenum (list (cons 'raw qn-nodenum) (cons 'formatted (number->string qn-nodenum))))
        (cons 'qn-numnodes (list (cons 'raw qn-numnodes) (cons 'formatted (number->string qn-numnodes))))
        (cons 'qn-namelen (list (cons 'raw qn-namelen) (cons 'formatted (number->string qn-namelen))))
        (cons 'qn-domain (list (cons 'raw qn-domain) (cons 'formatted (utf8->string qn-domain))))
        (cons 'qn-node (list (cons 'raw qn-node) (cons 'formatted (number->string qn-node))))
        (cons 'qn-port (list (cons 'raw qn-port) (cons 'formatted (number->string qn-port))))
        (cons 'qn-ip (list (cons 'raw qn-ip) (cons 'formatted (fmt-ipv4 qn-ip))))
        (cons 'flags (list (cons 'raw flags) (cons 'formatted (fmt-hex flags))))
        (cons 'lvb1 (list (cons 'raw lvb1) (cons 'formatted (fmt-bytes lvb1))))
        (cons 'lvb2 (list (cons 'raw lvb2) (cons 'formatted (fmt-bytes lvb2))))
        (cons 'lvb3 (list (cons 'raw lvb3) (cons 'formatted (fmt-bytes lvb3))))
        (cons 'master (list (cons 'raw master) (cons 'formatted (number->string master))))
        (cons 'new-master (list (cons 'raw new-master) (cons 'formatted (number->string new-master))))
        (cons 'domain-name-len (list (cons 'raw domain-name-len) (cons 'formatted (number->string domain-name-len))))
        (cons 'domain-name (list (cons 'raw domain-name) (cons 'formatted (utf8->string domain-name))))
        (cons 'namelen (list (cons 'raw namelen) (cons 'formatted (number->string namelen))))
        (cons 'pad16 (list (cons 'raw pad16) (cons 'formatted (fmt-hex pad16))))
        (cons 'reco-lvb (list (cons 'raw reco-lvb) (cons 'formatted (fmt-bytes reco-lvb))))
        (cons 'dead-node (list (cons 'raw dead-node) (cons 'formatted (number->string dead-node))))
        (cons 'pad8 (list (cons 'raw pad8) (cons 'formatted (number->string pad8))))
        (cons 'pad32 (list (cons 'raw pad32) (cons 'formatted (fmt-hex pad32))))
        )))

    (catch (e)
      (err (str "OCFS2 parse error: " e)))))

;; dissect-ocfs2: parse OCFS2 from bytevector
;; Returns (ok fields-alist) or (err message)