;;
;; packet-s5066dts.c
;; Routines for STANAG 5066 DTS layer packet dissection
;;
;; Copyright (c) 2013
;; by Ibrahim Can Yuce <canyuce [at] gmail [dot] com>
;; by M. Baris Demiray <baris.demiray [at] gmail [dot] com>
;;
;; Wireshark - Network traffic analyzer
;; By Gerald Combs <gerald@wireshark.org>
;; Copyright 1998 Gerald Combs
;;
;; SPDX-License-Identifier: GPL-2.0-or-later
;;

;; jerboa-ethereal/dissectors/s5066dts.ss
;; Auto-generated from wireshark/epan/dissectors/packet-s5066dts.c

(import (jerboa prelude))

;; ── Protocol Helpers ─────────────────────────────────────────────────
(def (read-u8 buf offset)
  (if (>= offset (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u8-ref buf offset))))

(def (read-u16be buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness big)))))

(def (read-u24be buf offset)
  (if (> (+ offset 3) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (+ (* (bytevector-u8-ref buf offset) 65536)
             (* (bytevector-u8-ref buf (+ offset 1)) 256)
             (bytevector-u8-ref buf (+ offset 2))))))

(def (read-u32be buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness big)))))

(def (read-u16le buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness little)))))

(def (read-u32le buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness little)))))

(def (read-u64be buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness big)))))

(def (read-u64le buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness little)))))

(def (slice buf offset len)
  (if (> (+ offset len) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (let ((result (make-bytevector len)))
            (bytevector-copy! buf offset result 0 len)
            result))))

(def (extract-bits val mask shift)
  (bitwise-arithmetic-shift-right (bitwise-and val mask) shift))

(def (fmt-ipv4 addr)
  (let ((b0 (bitwise-arithmetic-shift-right addr 24))
        (b1 (bitwise-and (bitwise-arithmetic-shift-right addr 16) 255))
        (b2 (bitwise-and (bitwise-arithmetic-shift-right addr 8) 255))
        (b3 (bitwise-and addr 255)))
    (str b0 "." b1 "." b2 "." b3)))

(def (fmt-mac bytes)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bytes))
    ":"))

(def (fmt-hex val)
  (str "0x" (number->string val 16)))

(def (fmt-oct val)
  (str "0" (number->string val 8)))

(def (fmt-port port)
  (number->string port))

(def (fmt-bytes bv)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bv))
    " "))

(def (fmt-ipv6-address bytes)
  (let loop ((i 0) (parts '()))
    (if (>= i 16)
        (string-join (reverse parts) ":")
        (loop (+ i 2)
              (cons (let ((w (+ (* (bytevector-u8-ref bytes i) 256)
                                (bytevector-u8-ref bytes (+ i 1)))))
                      (number->string w 16))
                    parts)))))

;; ── Dissector ──────────────────────────────────────────────────────
(def (dissect-s5066dts buffer)
  "STANAG 5066(DTS layer)"
  (try
    (let* (
           (eow-unrec-type-response (unwrap (read-u8 buffer 0)))
           (eow-unrec-type-reason (unwrap (read-u8 buffer 0)))
           (eow-capability-adaptive (unwrap (read-u8 buffer 0)))
           (eow-capability-stanag-4529 (unwrap (read-u8 buffer 0)))
           (eow-capability-mil-std-188-110a (unwrap (read-u8 buffer 0)))
           (eow-capability-extended (unwrap (read-u8 buffer 0)))
           (eow-capability-full-duplex (unwrap (read-u8 buffer 0)))
           (eow-capability-split-frequency (unwrap (read-u8 buffer 0)))
           (eow-capability-non-arcs-ale (unwrap (read-u8 buffer 0)))
           (eow-capability-arcs (unwrap (read-u8 buffer 0)))
           (eow-hdr-drc-request-num-channels (unwrap (read-u8 buffer 0)))
           (eow-hftrp-hftrp-token (unwrap (read-u8 buffer 0)))
           (eow-data (unwrap (read-u8 buffer 0)))
           (header-crc (unwrap (read-u16be buffer 0)))
           (sync-word (unwrap (read-u16be buffer 0)))
           (cpdu-crc (unwrap (read-u32be buffer 2)))
           (eot (unwrap (read-u8 buffer 2)))
           (address-size (unwrap (read-u8 buffer 2)))
           (header-size (unwrap (read-u8 buffer 2)))
           (segmented-cpdu (unwrap (slice buffer 2 1)))
           (data-only-cpdu-start (unwrap (read-u8 buffer 6)))
           (data-only-cpdu-end (unwrap (read-u8 buffer 6)))
           (data-only-deliver-in-order (unwrap (read-u8 buffer 6)))
           (data-only-drop-cpdu (unwrap (read-u8 buffer 6)))
           (data-only-tx-win-uwe (unwrap (read-u8 buffer 6)))
           (data-only-tx-win-lwe (unwrap (read-u8 buffer 6)))
           (data-only-segmented-cpdu-size (unwrap (read-u16be buffer 6)))
           (data-only-transmit-sequence-number (unwrap (read-u8 buffer 8)))
           (ack-only-rx-lwe (unwrap (read-u8 buffer 8)))
           (ack-only-acks (unwrap (slice buffer 8 1)))
           (data-ack-cpdu-start (unwrap (read-u8 buffer 8)))
           (data-ack-cpdu-end (unwrap (read-u8 buffer 8)))
           (data-ack-deliver-in-order (unwrap (read-u8 buffer 8)))
           (data-ack-drop-cpdu (unwrap (read-u8 buffer 8)))
           (data-ack-tx-win-uwe (unwrap (read-u8 buffer 8)))
           (data-ack-tx-win-lwe (unwrap (read-u8 buffer 8)))
           (data-ack-segmented-cpdu-size (unwrap (read-u16be buffer 8)))
           (data-ack-transmit-sequence-number (unwrap (read-u8 buffer 10)))
           (data-ack-rx-lwe (unwrap (read-u8 buffer 10)))
           (data-ack-acks (unwrap (slice buffer 10 1)))
           (reset-win-resync-unused (unwrap (read-u8 buffer 10)))
           (reset-win-resync-full-reset-command (unwrap (read-u8 buffer 10)))
           (reset-win-resync-reset-tx-win-rqst (unwrap (read-u8 buffer 10)))
           (reset-win-resync-reset-rx-win-cmnd (unwrap (read-u8 buffer 10)))
           (reset-win-resync-reset-ack (unwrap (read-u8 buffer 10)))
           (reset-win-resync-new-rx-lwe (unwrap (read-u8 buffer 10)))
           (reset-win-resync-reset-frame-id-number (unwrap (read-u8 buffer 10)))
           (exp-data-only-cpdu-start (unwrap (read-u8 buffer 10)))
           (exp-data-only-cpdu-end (unwrap (read-u8 buffer 10)))
           (exp-data-only-cpdu-id (unwrap (read-u8 buffer 10)))
           (exp-data-only-segmented-cpdu-size (unwrap (read-u16be buffer 10)))
           (exp-data-only-transmit-sequence-number (unwrap (read-u8 buffer 12)))
           (exp-ack-only-rx-lwe (unwrap (read-u8 buffer 12)))
           (exp-ack-only-acks (unwrap (slice buffer 12 1)))
           (management-unused (unwrap (read-u8 buffer 12)))
           (management-extended-message-flag (unwrap (read-u8 buffer 12)))
           (management-message (unwrap (read-u8 buffer 12)))
           (management-ack (unwrap (read-u8 buffer 12)))
           (management-management-frame-id (unwrap (read-u8 buffer 12)))
           (eow-hdr-drc-request-data-rate (unwrap (read-u32be buffer 12)))
           (eow-hdr-drc-request-interleaver-length (unwrap (read-u16be buffer 16)))
           (management-extended-message-hftrp-payload-size (unwrap (read-u16be buffer 18)))
           (management-extended-message-hftrp-ra (unwrap (read-u32be buffer 20)))
           (management-extended-message-hftrp-seq-id (unwrap (read-u32be buffer 24)))
           (management-extended-message-hftrp-gen-seq-id (unwrap (read-u32be buffer 28)))
           (management-extended-message-hftrp-new-successor-id (unwrap (read-u32be buffer 32)))
           (management-extended-message-hftrp-number-of-nodes (unwrap (read-u16be buffer 36)))
           (management-extended-message (unwrap (slice buffer 38 1)))
           (non-arq-data-cpdu-id-1 (unwrap (read-u8 buffer 38)))
           (non-arq-data-deliver-in-order (unwrap (read-u8 buffer 38)))
           (non-arq-data-group-address (unwrap (read-u8 buffer 38)))
           (non-arq-data-segmented-cpdu-size (unwrap (read-u16be buffer 38)))
           (non-arq-data-cpdu-id-2 (unwrap (read-u8 buffer 40)))
           (non-arq-data-cpdu-size (unwrap (read-u16be buffer 40)))
           (non-arq-data-cpdu-segment-offset (unwrap (read-u16be buffer 42)))
           (non-arq-data-cpdu-reception-window (unwrap (read-u16be buffer 44)))
           (exp-non-arq-data-cpdu-id-1 (unwrap (read-u8 buffer 46)))
           (exp-non-arq-data-deliver-in-order (unwrap (read-u8 buffer 46)))
           (exp-non-arq-data-group-address (unwrap (read-u8 buffer 46)))
           (exp-non-arq-data-segmented-cpdu-size (unwrap (read-u16be buffer 46)))
           (exp-non-arq-data-cpdu-id-2 (unwrap (read-u8 buffer 48)))
           (exp-non-arq-data-cpdu-size (unwrap (read-u16be buffer 48)))
           (exp-non-arq-data-cpdu-segment-offset (unwrap (read-u16be buffer 50)))
           (exp-non-arq-data-cpdu-reception-window (unwrap (read-u16be buffer 52)))
           (warning-frame-type (unwrap (read-u8 buffer 54)))
           (warning-reason (unwrap (read-u8 buffer 54)))
           )

      (ok (list
        (cons 'eow-unrec-type-response (list (cons 'raw eow-unrec-type-response) (cons 'formatted (number->string eow-unrec-type-response))))
        (cons 'eow-unrec-type-reason (list (cons 'raw eow-unrec-type-reason) (cons 'formatted (number->string eow-unrec-type-reason))))
        (cons 'eow-capability-adaptive (list (cons 'raw eow-capability-adaptive) (cons 'formatted (number->string eow-capability-adaptive))))
        (cons 'eow-capability-stanag-4529 (list (cons 'raw eow-capability-stanag-4529) (cons 'formatted (number->string eow-capability-stanag-4529))))
        (cons 'eow-capability-mil-std-188-110a (list (cons 'raw eow-capability-mil-std-188-110a) (cons 'formatted (number->string eow-capability-mil-std-188-110a))))
        (cons 'eow-capability-extended (list (cons 'raw eow-capability-extended) (cons 'formatted (number->string eow-capability-extended))))
        (cons 'eow-capability-full-duplex (list (cons 'raw eow-capability-full-duplex) (cons 'formatted (number->string eow-capability-full-duplex))))
        (cons 'eow-capability-split-frequency (list (cons 'raw eow-capability-split-frequency) (cons 'formatted (number->string eow-capability-split-frequency))))
        (cons 'eow-capability-non-arcs-ale (list (cons 'raw eow-capability-non-arcs-ale) (cons 'formatted (number->string eow-capability-non-arcs-ale))))
        (cons 'eow-capability-arcs (list (cons 'raw eow-capability-arcs) (cons 'formatted (number->string eow-capability-arcs))))
        (cons 'eow-hdr-drc-request-num-channels (list (cons 'raw eow-hdr-drc-request-num-channels) (cons 'formatted (number->string eow-hdr-drc-request-num-channels))))
        (cons 'eow-hftrp-hftrp-token (list (cons 'raw eow-hftrp-hftrp-token) (cons 'formatted (number->string eow-hftrp-hftrp-token))))
        (cons 'eow-data (list (cons 'raw eow-data) (cons 'formatted (fmt-hex eow-data))))
        (cons 'header-crc (list (cons 'raw header-crc) (cons 'formatted (fmt-hex header-crc))))
        (cons 'sync-word (list (cons 'raw sync-word) (cons 'formatted (fmt-hex sync-word))))
        (cons 'cpdu-crc (list (cons 'raw cpdu-crc) (cons 'formatted (fmt-hex cpdu-crc))))
        (cons 'eot (list (cons 'raw eot) (cons 'formatted (number->string eot))))
        (cons 'address-size (list (cons 'raw address-size) (cons 'formatted (number->string address-size))))
        (cons 'header-size (list (cons 'raw header-size) (cons 'formatted (number->string header-size))))
        (cons 'segmented-cpdu (list (cons 'raw segmented-cpdu) (cons 'formatted (fmt-bytes segmented-cpdu))))
        (cons 'data-only-cpdu-start (list (cons 'raw data-only-cpdu-start) (cons 'formatted (number->string data-only-cpdu-start))))
        (cons 'data-only-cpdu-end (list (cons 'raw data-only-cpdu-end) (cons 'formatted (number->string data-only-cpdu-end))))
        (cons 'data-only-deliver-in-order (list (cons 'raw data-only-deliver-in-order) (cons 'formatted (number->string data-only-deliver-in-order))))
        (cons 'data-only-drop-cpdu (list (cons 'raw data-only-drop-cpdu) (cons 'formatted (number->string data-only-drop-cpdu))))
        (cons 'data-only-tx-win-uwe (list (cons 'raw data-only-tx-win-uwe) (cons 'formatted (number->string data-only-tx-win-uwe))))
        (cons 'data-only-tx-win-lwe (list (cons 'raw data-only-tx-win-lwe) (cons 'formatted (number->string data-only-tx-win-lwe))))
        (cons 'data-only-segmented-cpdu-size (list (cons 'raw data-only-segmented-cpdu-size) (cons 'formatted (number->string data-only-segmented-cpdu-size))))
        (cons 'data-only-transmit-sequence-number (list (cons 'raw data-only-transmit-sequence-number) (cons 'formatted (number->string data-only-transmit-sequence-number))))
        (cons 'ack-only-rx-lwe (list (cons 'raw ack-only-rx-lwe) (cons 'formatted (number->string ack-only-rx-lwe))))
        (cons 'ack-only-acks (list (cons 'raw ack-only-acks) (cons 'formatted (fmt-bytes ack-only-acks))))
        (cons 'data-ack-cpdu-start (list (cons 'raw data-ack-cpdu-start) (cons 'formatted (number->string data-ack-cpdu-start))))
        (cons 'data-ack-cpdu-end (list (cons 'raw data-ack-cpdu-end) (cons 'formatted (number->string data-ack-cpdu-end))))
        (cons 'data-ack-deliver-in-order (list (cons 'raw data-ack-deliver-in-order) (cons 'formatted (number->string data-ack-deliver-in-order))))
        (cons 'data-ack-drop-cpdu (list (cons 'raw data-ack-drop-cpdu) (cons 'formatted (number->string data-ack-drop-cpdu))))
        (cons 'data-ack-tx-win-uwe (list (cons 'raw data-ack-tx-win-uwe) (cons 'formatted (number->string data-ack-tx-win-uwe))))
        (cons 'data-ack-tx-win-lwe (list (cons 'raw data-ack-tx-win-lwe) (cons 'formatted (number->string data-ack-tx-win-lwe))))
        (cons 'data-ack-segmented-cpdu-size (list (cons 'raw data-ack-segmented-cpdu-size) (cons 'formatted (number->string data-ack-segmented-cpdu-size))))
        (cons 'data-ack-transmit-sequence-number (list (cons 'raw data-ack-transmit-sequence-number) (cons 'formatted (number->string data-ack-transmit-sequence-number))))
        (cons 'data-ack-rx-lwe (list (cons 'raw data-ack-rx-lwe) (cons 'formatted (number->string data-ack-rx-lwe))))
        (cons 'data-ack-acks (list (cons 'raw data-ack-acks) (cons 'formatted (fmt-bytes data-ack-acks))))
        (cons 'reset-win-resync-unused (list (cons 'raw reset-win-resync-unused) (cons 'formatted (fmt-hex reset-win-resync-unused))))
        (cons 'reset-win-resync-full-reset-command (list (cons 'raw reset-win-resync-full-reset-command) (cons 'formatted (number->string reset-win-resync-full-reset-command))))
        (cons 'reset-win-resync-reset-tx-win-rqst (list (cons 'raw reset-win-resync-reset-tx-win-rqst) (cons 'formatted (number->string reset-win-resync-reset-tx-win-rqst))))
        (cons 'reset-win-resync-reset-rx-win-cmnd (list (cons 'raw reset-win-resync-reset-rx-win-cmnd) (cons 'formatted (number->string reset-win-resync-reset-rx-win-cmnd))))
        (cons 'reset-win-resync-reset-ack (list (cons 'raw reset-win-resync-reset-ack) (cons 'formatted (number->string reset-win-resync-reset-ack))))
        (cons 'reset-win-resync-new-rx-lwe (list (cons 'raw reset-win-resync-new-rx-lwe) (cons 'formatted (number->string reset-win-resync-new-rx-lwe))))
        (cons 'reset-win-resync-reset-frame-id-number (list (cons 'raw reset-win-resync-reset-frame-id-number) (cons 'formatted (number->string reset-win-resync-reset-frame-id-number))))
        (cons 'exp-data-only-cpdu-start (list (cons 'raw exp-data-only-cpdu-start) (cons 'formatted (number->string exp-data-only-cpdu-start))))
        (cons 'exp-data-only-cpdu-end (list (cons 'raw exp-data-only-cpdu-end) (cons 'formatted (number->string exp-data-only-cpdu-end))))
        (cons 'exp-data-only-cpdu-id (list (cons 'raw exp-data-only-cpdu-id) (cons 'formatted (number->string exp-data-only-cpdu-id))))
        (cons 'exp-data-only-segmented-cpdu-size (list (cons 'raw exp-data-only-segmented-cpdu-size) (cons 'formatted (number->string exp-data-only-segmented-cpdu-size))))
        (cons 'exp-data-only-transmit-sequence-number (list (cons 'raw exp-data-only-transmit-sequence-number) (cons 'formatted (number->string exp-data-only-transmit-sequence-number))))
        (cons 'exp-ack-only-rx-lwe (list (cons 'raw exp-ack-only-rx-lwe) (cons 'formatted (number->string exp-ack-only-rx-lwe))))
        (cons 'exp-ack-only-acks (list (cons 'raw exp-ack-only-acks) (cons 'formatted (fmt-bytes exp-ack-only-acks))))
        (cons 'management-unused (list (cons 'raw management-unused) (cons 'formatted (fmt-hex management-unused))))
        (cons 'management-extended-message-flag (list (cons 'raw management-extended-message-flag) (cons 'formatted (number->string management-extended-message-flag))))
        (cons 'management-message (list (cons 'raw management-message) (cons 'formatted (number->string management-message))))
        (cons 'management-ack (list (cons 'raw management-ack) (cons 'formatted (number->string management-ack))))
        (cons 'management-management-frame-id (list (cons 'raw management-management-frame-id) (cons 'formatted (number->string management-management-frame-id))))
        (cons 'eow-hdr-drc-request-data-rate (list (cons 'raw eow-hdr-drc-request-data-rate) (cons 'formatted (number->string eow-hdr-drc-request-data-rate))))
        (cons 'eow-hdr-drc-request-interleaver-length (list (cons 'raw eow-hdr-drc-request-interleaver-length) (cons 'formatted (number->string eow-hdr-drc-request-interleaver-length))))
        (cons 'management-extended-message-hftrp-payload-size (list (cons 'raw management-extended-message-hftrp-payload-size) (cons 'formatted (fmt-hex management-extended-message-hftrp-payload-size))))
        (cons 'management-extended-message-hftrp-ra (list (cons 'raw management-extended-message-hftrp-ra) (cons 'formatted (fmt-ipv4 management-extended-message-hftrp-ra))))
        (cons 'management-extended-message-hftrp-seq-id (list (cons 'raw management-extended-message-hftrp-seq-id) (cons 'formatted (number->string management-extended-message-hftrp-seq-id))))
        (cons 'management-extended-message-hftrp-gen-seq-id (list (cons 'raw management-extended-message-hftrp-gen-seq-id) (cons 'formatted (number->string management-extended-message-hftrp-gen-seq-id))))
        (cons 'management-extended-message-hftrp-new-successor-id (list (cons 'raw management-extended-message-hftrp-new-successor-id) (cons 'formatted (number->string management-extended-message-hftrp-new-successor-id))))
        (cons 'management-extended-message-hftrp-number-of-nodes (list (cons 'raw management-extended-message-hftrp-number-of-nodes) (cons 'formatted (number->string management-extended-message-hftrp-number-of-nodes))))
        (cons 'management-extended-message (list (cons 'raw management-extended-message) (cons 'formatted (fmt-bytes management-extended-message))))
        (cons 'non-arq-data-cpdu-id-1 (list (cons 'raw non-arq-data-cpdu-id-1) (cons 'formatted (number->string non-arq-data-cpdu-id-1))))
        (cons 'non-arq-data-deliver-in-order (list (cons 'raw non-arq-data-deliver-in-order) (cons 'formatted (number->string non-arq-data-deliver-in-order))))
        (cons 'non-arq-data-group-address (list (cons 'raw non-arq-data-group-address) (cons 'formatted (number->string non-arq-data-group-address))))
        (cons 'non-arq-data-segmented-cpdu-size (list (cons 'raw non-arq-data-segmented-cpdu-size) (cons 'formatted (number->string non-arq-data-segmented-cpdu-size))))
        (cons 'non-arq-data-cpdu-id-2 (list (cons 'raw non-arq-data-cpdu-id-2) (cons 'formatted (number->string non-arq-data-cpdu-id-2))))
        (cons 'non-arq-data-cpdu-size (list (cons 'raw non-arq-data-cpdu-size) (cons 'formatted (number->string non-arq-data-cpdu-size))))
        (cons 'non-arq-data-cpdu-segment-offset (list (cons 'raw non-arq-data-cpdu-segment-offset) (cons 'formatted (number->string non-arq-data-cpdu-segment-offset))))
        (cons 'non-arq-data-cpdu-reception-window (list (cons 'raw non-arq-data-cpdu-reception-window) (cons 'formatted (number->string non-arq-data-cpdu-reception-window))))
        (cons 'exp-non-arq-data-cpdu-id-1 (list (cons 'raw exp-non-arq-data-cpdu-id-1) (cons 'formatted (number->string exp-non-arq-data-cpdu-id-1))))
        (cons 'exp-non-arq-data-deliver-in-order (list (cons 'raw exp-non-arq-data-deliver-in-order) (cons 'formatted (number->string exp-non-arq-data-deliver-in-order))))
        (cons 'exp-non-arq-data-group-address (list (cons 'raw exp-non-arq-data-group-address) (cons 'formatted (number->string exp-non-arq-data-group-address))))
        (cons 'exp-non-arq-data-segmented-cpdu-size (list (cons 'raw exp-non-arq-data-segmented-cpdu-size) (cons 'formatted (number->string exp-non-arq-data-segmented-cpdu-size))))
        (cons 'exp-non-arq-data-cpdu-id-2 (list (cons 'raw exp-non-arq-data-cpdu-id-2) (cons 'formatted (number->string exp-non-arq-data-cpdu-id-2))))
        (cons 'exp-non-arq-data-cpdu-size (list (cons 'raw exp-non-arq-data-cpdu-size) (cons 'formatted (number->string exp-non-arq-data-cpdu-size))))
        (cons 'exp-non-arq-data-cpdu-segment-offset (list (cons 'raw exp-non-arq-data-cpdu-segment-offset) (cons 'formatted (number->string exp-non-arq-data-cpdu-segment-offset))))
        (cons 'exp-non-arq-data-cpdu-reception-window (list (cons 'raw exp-non-arq-data-cpdu-reception-window) (cons 'formatted (number->string exp-non-arq-data-cpdu-reception-window))))
        (cons 'warning-frame-type (list (cons 'raw warning-frame-type) (cons 'formatted (number->string warning-frame-type))))
        (cons 'warning-reason (list (cons 'raw warning-reason) (cons 'formatted (number->string warning-reason))))
        )))

    (catch (e)
      (err (str "S5066DTS parse error: " e)))))

;; dissect-s5066dts: parse S5066DTS from bytevector
;; Returns (ok fields-alist) or (err message)