;; based on SSC3 spec

;; jerboa-ethereal/dissectors/scsi-ssc.ss
;; Auto-generated from wireshark/epan/dissectors/packet-scsi_ssc.c

(import (jerboa prelude))

;; ── Protocol Helpers ─────────────────────────────────────────────────
(def (read-u8 buf offset)
  (if (>= offset (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u8-ref buf offset))))

(def (read-u16be buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness big)))))

(def (read-u24be buf offset)
  (if (> (+ offset 3) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (+ (* (bytevector-u8-ref buf offset) 65536)
             (* (bytevector-u8-ref buf (+ offset 1)) 256)
             (bytevector-u8-ref buf (+ offset 2))))))

(def (read-u32be buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness big)))))

(def (read-u16le buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness little)))))

(def (read-u32le buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness little)))))

(def (read-u64be buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness big)))))

(def (read-u64le buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness little)))))

(def (slice buf offset len)
  (if (> (+ offset len) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (let ((result (make-bytevector len)))
            (bytevector-copy! buf offset result 0 len)
            result))))

(def (extract-bits val mask shift)
  (bitwise-arithmetic-shift-right (bitwise-and val mask) shift))

(def (fmt-ipv4 addr)
  (let ((b0 (bitwise-arithmetic-shift-right addr 24))
        (b1 (bitwise-and (bitwise-arithmetic-shift-right addr 16) 255))
        (b2 (bitwise-and (bitwise-arithmetic-shift-right addr 8) 255))
        (b3 (bitwise-and addr 255)))
    (str b0 "." b1 "." b2 "." b3)))

(def (fmt-mac bytes)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bytes))
    ":"))

(def (fmt-hex val)
  (str "0x" (number->string val 16)))

(def (fmt-oct val)
  (str "0" (number->string val 8)))

(def (fmt-port port)
  (number->string port))

(def (fmt-bytes bv)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bv))
    " "))

(def (fmt-ipv6-address bytes)
  (let loop ((i 0) (parts '()))
    (if (>= i 16)
        (string-join (reverse parts) ":")
        (loop (+ i 2)
              (cons (let ((w (+ (* (bytevector-u8-ref bytes i) 256)
                                (bytevector-u8-ref bytes (+ i 1)))))
                      (number->string w 16))
                    parts)))))

;; ── Dissector ──────────────────────────────────────────────────────
(def (dissect-scsi-ssc buffer)
  "SCSI_SSC"
  (try
    (let* (
           (ssc-read6-flags (unwrap (read-u8 buffer 0)))
           (ssc-sili (extract-bits ssc-read6-flags 0x2 1))
           (ssc-fixed (extract-bits ssc-read6-flags 0x1 0))
           (ssc-rdwr6-xferlen (unwrap (read-u24be buffer 0)))
           (ssc-locate16-loid (unwrap (read-u64be buffer 0)))
           (ssc-ver16-verlen (unwrap (read-u24be buffer 0)))
           (ssc-loadunload-immed-flags (unwrap (read-u8 buffer 0)))
           (ssc-loadunload-flags (unwrap (read-u8 buffer 0)))
           (ssc-hold (extract-bits ssc-loadunload-flags 0x8 3))
           (ssc-eot (extract-bits ssc-loadunload-flags 0x4 2))
           (ssc-reten (extract-bits ssc-loadunload-flags 0x2 1))
           (ssc-load (extract-bits ssc-loadunload-flags 0x1 0))
           (ssc-capacity-prop-value (unwrap (read-u16be buffer 0)))
           (ssc-locate-flags (unwrap (read-u8 buffer 0)))
           (ssc-cp (extract-bits ssc-locate-flags 0x2 1))
           (ssc-locate10-loid (unwrap (read-u32be buffer 0)))
           (ssc-bam-flags (unwrap (read-u8 buffer 0)))
           (ssc-bam (extract-bits ssc-bam-flags 0x1 0))
           (ssc-erase6-immed (unwrap (read-u8 buffer 0)))
           (ssc-erase6-long (unwrap (read-u8 buffer 0)))
           (ssc-erase-flags (unwrap (read-u8 buffer 0)))
           (ssc-fcs (extract-bits ssc-erase-flags 0x8 3))
           (ssc-lcs (extract-bits ssc-erase-flags 0x4 2))
           (ssc-erase-immed (extract-bits ssc-erase-flags 0x2 1))
           (ssc-long (extract-bits ssc-erase-flags 0x1 0))
           (ssc-lbi (unwrap (read-u64be buffer 0)))
           (ssc-space16-count (unwrap (read-u64be buffer 0)))
           (ssc-space16-parameter-len (unwrap (read-u16be buffer 0)))
           (ssc-formatmedium-flags (unwrap (read-u8 buffer 0)))
           (ssc-verify (extract-bits ssc-formatmedium-flags 0x2 1))
           (ssc-immed (extract-bits ssc-formatmedium-flags 0x1 0))
           (ssc-rdwr10-xferlen (unwrap (read-u16be buffer 0)))
           (ssc-readposition-parameter-len (unwrap (read-u16be buffer 0)))
           (ssc-readposition-partition-number (unwrap (read-u32be buffer 32)))
           (ssc-readposition-block-number (unwrap (read-u64be buffer 36)))
           (ssc-readposition-file-number (unwrap (read-u64be buffer 56)))
           (ssc-readposition-set-number (unwrap (read-u64be buffer 64)))
           (ssc-readposition-flags (unwrap (read-u8 buffer 88)))
           (ssc-readposition-bop (extract-bits ssc-readposition-flags 0x80 7))
           (ssc-readposition-eop (extract-bits ssc-readposition-flags 0x40 6))
           (ssc-readposition-bcu (extract-bits ssc-readposition-flags 0x0 0))
           (ssc-readposition-bycu (extract-bits ssc-readposition-flags 0x0 0))
           (ssc-readposition-mpu (extract-bits ssc-readposition-flags 0x0 0))
           (ssc-readposition-bpu (extract-bits ssc-readposition-flags 0x0 0))
           (ssc-readposition-perr (extract-bits ssc-readposition-flags 0x2 1))
           (ssc-partition (unwrap (read-u8 buffer 89)))
           (ssc-readposition-additional-length (unwrap (read-u16be buffer 90)))
           (ssc-readposition-num-blocks-buffer (unwrap (read-u24be buffer 93)))
           (ssc-readposition-first-block-location (unwrap (read-u64be buffer 96)))
           (ssc-readposition-last-block-location (unwrap (read-u64be buffer 104)))
           (ssc-readposition-num-bytes-buffer (unwrap (read-u64be buffer 129)))
           )

      (ok (list
        (cons 'ssc-read6-flags (list (cons 'raw ssc-read6-flags) (cons 'formatted (fmt-hex ssc-read6-flags))))
        (cons 'ssc-sili (list (cons 'raw ssc-sili) (cons 'formatted (if (= ssc-sili 0) "Not set" "Set"))))
        (cons 'ssc-fixed (list (cons 'raw ssc-fixed) (cons 'formatted (if (= ssc-fixed 0) "Not set" "Set"))))
        (cons 'ssc-rdwr6-xferlen (list (cons 'raw ssc-rdwr6-xferlen) (cons 'formatted (number->string ssc-rdwr6-xferlen))))
        (cons 'ssc-locate16-loid (list (cons 'raw ssc-locate16-loid) (cons 'formatted (number->string ssc-locate16-loid))))
        (cons 'ssc-ver16-verlen (list (cons 'raw ssc-ver16-verlen) (cons 'formatted (number->string ssc-ver16-verlen))))
        (cons 'ssc-loadunload-immed-flags (list (cons 'raw ssc-loadunload-immed-flags) (cons 'formatted (fmt-hex ssc-loadunload-immed-flags))))
        (cons 'ssc-loadunload-flags (list (cons 'raw ssc-loadunload-flags) (cons 'formatted (fmt-hex ssc-loadunload-flags))))
        (cons 'ssc-hold (list (cons 'raw ssc-hold) (cons 'formatted (if (= ssc-hold 0) "Not set" "Set"))))
        (cons 'ssc-eot (list (cons 'raw ssc-eot) (cons 'formatted (if (= ssc-eot 0) "Not set" "Set"))))
        (cons 'ssc-reten (list (cons 'raw ssc-reten) (cons 'formatted (if (= ssc-reten 0) "Not set" "Set"))))
        (cons 'ssc-load (list (cons 'raw ssc-load) (cons 'formatted (if (= ssc-load 0) "Not set" "Set"))))
        (cons 'ssc-capacity-prop-value (list (cons 'raw ssc-capacity-prop-value) (cons 'formatted (number->string ssc-capacity-prop-value))))
        (cons 'ssc-locate-flags (list (cons 'raw ssc-locate-flags) (cons 'formatted (fmt-hex ssc-locate-flags))))
        (cons 'ssc-cp (list (cons 'raw ssc-cp) (cons 'formatted (if (= ssc-cp 0) "Not set" "Set"))))
        (cons 'ssc-locate10-loid (list (cons 'raw ssc-locate10-loid) (cons 'formatted (number->string ssc-locate10-loid))))
        (cons 'ssc-bam-flags (list (cons 'raw ssc-bam-flags) (cons 'formatted (fmt-hex ssc-bam-flags))))
        (cons 'ssc-bam (list (cons 'raw ssc-bam) (cons 'formatted (if (= ssc-bam 0) "Not set" "Set"))))
        (cons 'ssc-erase6-immed (list (cons 'raw ssc-erase6-immed) (cons 'formatted (number->string ssc-erase6-immed))))
        (cons 'ssc-erase6-long (list (cons 'raw ssc-erase6-long) (cons 'formatted (number->string ssc-erase6-long))))
        (cons 'ssc-erase-flags (list (cons 'raw ssc-erase-flags) (cons 'formatted (fmt-hex ssc-erase-flags))))
        (cons 'ssc-fcs (list (cons 'raw ssc-fcs) (cons 'formatted (if (= ssc-fcs 0) "Not set" "Set"))))
        (cons 'ssc-lcs (list (cons 'raw ssc-lcs) (cons 'formatted (if (= ssc-lcs 0) "Not set" "Set"))))
        (cons 'ssc-erase-immed (list (cons 'raw ssc-erase-immed) (cons 'formatted (if (= ssc-erase-immed 0) "Not set" "Set"))))
        (cons 'ssc-long (list (cons 'raw ssc-long) (cons 'formatted (if (= ssc-long 0) "Not set" "Set"))))
        (cons 'ssc-lbi (list (cons 'raw ssc-lbi) (cons 'formatted (fmt-hex ssc-lbi))))
        (cons 'ssc-space16-count (list (cons 'raw ssc-space16-count) (cons 'formatted (number->string ssc-space16-count))))
        (cons 'ssc-space16-parameter-len (list (cons 'raw ssc-space16-parameter-len) (cons 'formatted (number->string ssc-space16-parameter-len))))
        (cons 'ssc-formatmedium-flags (list (cons 'raw ssc-formatmedium-flags) (cons 'formatted (fmt-hex ssc-formatmedium-flags))))
        (cons 'ssc-verify (list (cons 'raw ssc-verify) (cons 'formatted (if (= ssc-verify 0) "Not set" "Set"))))
        (cons 'ssc-immed (list (cons 'raw ssc-immed) (cons 'formatted (if (= ssc-immed 0) "Not set" "Set"))))
        (cons 'ssc-rdwr10-xferlen (list (cons 'raw ssc-rdwr10-xferlen) (cons 'formatted (number->string ssc-rdwr10-xferlen))))
        (cons 'ssc-readposition-parameter-len (list (cons 'raw ssc-readposition-parameter-len) (cons 'formatted (number->string ssc-readposition-parameter-len))))
        (cons 'ssc-readposition-partition-number (list (cons 'raw ssc-readposition-partition-number) (cons 'formatted (number->string ssc-readposition-partition-number))))
        (cons 'ssc-readposition-block-number (list (cons 'raw ssc-readposition-block-number) (cons 'formatted (number->string ssc-readposition-block-number))))
        (cons 'ssc-readposition-file-number (list (cons 'raw ssc-readposition-file-number) (cons 'formatted (number->string ssc-readposition-file-number))))
        (cons 'ssc-readposition-set-number (list (cons 'raw ssc-readposition-set-number) (cons 'formatted (number->string ssc-readposition-set-number))))
        (cons 'ssc-readposition-flags (list (cons 'raw ssc-readposition-flags) (cons 'formatted (fmt-hex ssc-readposition-flags))))
        (cons 'ssc-readposition-bop (list (cons 'raw ssc-readposition-bop) (cons 'formatted (if (= ssc-readposition-bop 0) "Not set" "Set"))))
        (cons 'ssc-readposition-eop (list (cons 'raw ssc-readposition-eop) (cons 'formatted (if (= ssc-readposition-eop 0) "Not set" "Set"))))
        (cons 'ssc-readposition-bcu (list (cons 'raw ssc-readposition-bcu) (cons 'formatted (if (= ssc-readposition-bcu 0) "Not set" "Set"))))
        (cons 'ssc-readposition-bycu (list (cons 'raw ssc-readposition-bycu) (cons 'formatted (if (= ssc-readposition-bycu 0) "Not set" "Set"))))
        (cons 'ssc-readposition-mpu (list (cons 'raw ssc-readposition-mpu) (cons 'formatted (if (= ssc-readposition-mpu 0) "Not set" "Set"))))
        (cons 'ssc-readposition-bpu (list (cons 'raw ssc-readposition-bpu) (cons 'formatted (if (= ssc-readposition-bpu 0) "Not set" "Set"))))
        (cons 'ssc-readposition-perr (list (cons 'raw ssc-readposition-perr) (cons 'formatted (if (= ssc-readposition-perr 0) "Not set" "Set"))))
        (cons 'ssc-partition (list (cons 'raw ssc-partition) (cons 'formatted (fmt-hex ssc-partition))))
        (cons 'ssc-readposition-additional-length (list (cons 'raw ssc-readposition-additional-length) (cons 'formatted (number->string ssc-readposition-additional-length))))
        (cons 'ssc-readposition-num-blocks-buffer (list (cons 'raw ssc-readposition-num-blocks-buffer) (cons 'formatted (number->string ssc-readposition-num-blocks-buffer))))
        (cons 'ssc-readposition-first-block-location (list (cons 'raw ssc-readposition-first-block-location) (cons 'formatted (number->string ssc-readposition-first-block-location))))
        (cons 'ssc-readposition-last-block-location (list (cons 'raw ssc-readposition-last-block-location) (cons 'formatted (number->string ssc-readposition-last-block-location))))
        (cons 'ssc-readposition-num-bytes-buffer (list (cons 'raw ssc-readposition-num-bytes-buffer) (cons 'formatted (number->string ssc-readposition-num-bytes-buffer))))
        )))

    (catch (e)
      (err (str "SCSI-SSC parse error: " e)))))

;; dissect-scsi-ssc: parse SCSI-SSC from bytevector
;; Returns (ok fields-alist) or (err message)