;; packet-u3v.c
;; Routines for AIA USB3 Vision (TM) Protocol dissection
;; Copyright 2016, AIA (www.visiononline.org)
;;
;; USB3 Vision (TM): USB3 Vision a standard developed under the sponsorship of
;; the AIA for the benefit of the machine vision industry.
;; U3V stands for USB3 Vision (TM) Protocol.
;;
;; Wireshark - Network traffic analyzer
;; By Gerald Combs <gerald@wireshark.org>
;; Copyright 1998 Gerald Combs
;;
;; SPDX-License-Identifier: GPL-2.0-or-later
;;

;; jerboa-ethereal/dissectors/u3v.ss
;; Auto-generated from wireshark/epan/dissectors/packet-u3v.c

(import (jerboa prelude))

;; ── Protocol Helpers ─────────────────────────────────────────────────
(def (read-u8 buf offset)
  (if (>= offset (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u8-ref buf offset))))

(def (read-u16be buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness big)))))

(def (read-u24be buf offset)
  (if (> (+ offset 3) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (+ (* (bytevector-u8-ref buf offset) 65536)
             (* (bytevector-u8-ref buf (+ offset 1)) 256)
             (bytevector-u8-ref buf (+ offset 2))))))

(def (read-u32be buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness big)))))

(def (read-u16le buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness little)))))

(def (read-u32le buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness little)))))

(def (read-u64be buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness big)))))

(def (read-u64le buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness little)))))

(def (slice buf offset len)
  (if (> (+ offset len) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (let ((result (make-bytevector len)))
            (bytevector-copy! buf offset result 0 len)
            result))))

(def (extract-bits val mask shift)
  (bitwise-arithmetic-shift-right (bitwise-and val mask) shift))

(def (fmt-ipv4 addr)
  (let ((b0 (bitwise-arithmetic-shift-right addr 24))
        (b1 (bitwise-and (bitwise-arithmetic-shift-right addr 16) 255))
        (b2 (bitwise-and (bitwise-arithmetic-shift-right addr 8) 255))
        (b3 (bitwise-and addr 255)))
    (str b0 "." b1 "." b2 "." b3)))

(def (fmt-mac bytes)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bytes))
    ":"))

(def (fmt-hex val)
  (str "0x" (number->string val 16)))

(def (fmt-oct val)
  (str "0" (number->string val 8)))

(def (fmt-port port)
  (number->string port))

(def (fmt-bytes bv)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bv))
    " "))

(def (fmt-ipv6-address bytes)
  (let loop ((i 0) (parts '()))
    (if (>= i 16)
        (string-join (reverse parts) ":")
        (loop (+ i 2)
              (cons (let ((w (+ (* (bytevector-u8-ref bytes i) 256)
                                (bytevector-u8-ref bytes (+ i 1)))))
                      (number->string w 16))
                    parts)))))

;; ── Dissector ──────────────────────────────────────────────────────
(def (dissect-u3v buffer)
  "USB 3 Vision"
  (try
    (let* (
           (stream-data (unwrap (slice buffer 0 1)))
           (address (unwrap (read-u64be buffer 0)))
           (bootstrap-GenCP-Version (unwrap (read-u32be buffer 0)))
           (bootstrap-Manufacturer-Name (unwrap (slice buffer 0 1)))
           (bootstrap-Model-Name (unwrap (slice buffer 0 1)))
           (bootstrap-Family-Name (unwrap (slice buffer 0 1)))
           (bootstrap-Device-Version (unwrap (slice buffer 0 1)))
           (bootstrap-Manufacturer-Info (unwrap (slice buffer 0 1)))
           (bootstrap-Serial-Number (unwrap (slice buffer 0 1)))
           (bootstrap-User-Defined-Name (unwrap (slice buffer 0 1)))
           (bootstrap-Device-Capability (unwrap (read-u64be buffer 0)))
           (bootstrap-Maximum-Device-Response-Time (unwrap (read-u32be buffer 0)))
           (bootstrap-Manifest-Table-Address (unwrap (read-u64be buffer 0)))
           (bootstrap-SBRM-Address (unwrap (read-u64be buffer 0)))
           (bootstrap-Device-Configuration (unwrap (read-u64be buffer 0)))
           (bootstrap-Heartbeat-Timeout (unwrap (read-u32be buffer 0)))
           (bootstrap-Message-Channel-channel-id (unwrap (read-u32be buffer 0)))
           (bootstrap-Timestamp (unwrap (read-u64be buffer 0)))
           (bootstrap-Timestamp-Latch (unwrap (read-u32be buffer 0)))
           (bootstrap-Timestamp-Increment (unwrap (read-u64be buffer 0)))
           (bootstrap-Access-Privilege (unwrap (read-u32be buffer 0)))
           (bootstrap-Protocol-Endianness (unwrap (read-u32be buffer 0)))
           (bootstrap-Implementation-Endianness (unwrap (read-u32be buffer 0)))
           (bootstrap-U3V-Version (unwrap (read-u32be buffer 0)))
           (bootstrap-U3VCP-Capability-Register (unwrap (read-u64be buffer 0)))
           (bootstrap-U3VCP-Configuration-Register (unwrap (read-u64be buffer 0)))
           (bootstrap-Maximum-Command-Transfer-Length (unwrap (read-u32be buffer 0)))
           (bootstrap-Maximum-Acknowledge-Transfer-Length (unwrap (read-u32be buffer 0)))
           (bootstrap-Number-of-Stream-Channels (unwrap (read-u32be buffer 0)))
           (bootstrap-SIRM-Address (unwrap (read-u64be buffer 0)))
           (bootstrap-SIRM-Length (unwrap (read-u32be buffer 0)))
           (bootstrap-EIRM-Address (unwrap (read-u64be buffer 0)))
           (bootstrap-EIRM-Length (unwrap (read-u32be buffer 0)))
           (bootstrap-IIDC2-Address (unwrap (read-u64be buffer 0)))
           (bootstrap-Current-Speed (unwrap (read-u32be buffer 0)))
           (bootstrap-SI-Info (unwrap (read-u32be buffer 0)))
           (bootstrap-SI-Control (unwrap (read-u32be buffer 0)))
           (bootstrap-SI-Required-Payload-Size (unwrap (read-u64be buffer 0)))
           (bootstrap-SI-Required-Leader-Size (unwrap (read-u32be buffer 0)))
           (bootstrap-SI-Required-Trailer-Size (unwrap (read-u32be buffer 0)))
           (bootstrap-SI-Maximum-Leader-Size (unwrap (read-u32be buffer 0)))
           (bootstrap-SI-Payload-Transfer-Size (unwrap (read-u32be buffer 0)))
           (bootstrap-SI-Payload-Transfer-Count (unwrap (read-u32be buffer 0)))
           (bootstrap-SI-Payload-Final-Transfer1-Size (unwrap (read-u32be buffer 0)))
           (bootstrap-SI-Payload-Final-Transfer2-Size (unwrap (read-u32be buffer 0)))
           (bootstrap-SI-Maximum-Trailer-Size (unwrap (read-u32be buffer 0)))
           (bootstrap-EI-Control (unwrap (read-u32be buffer 0)))
           (bootstrap-Maximum-Event-Transfer-Length (unwrap (read-u32be buffer 0)))
           (bootstrap-Event-Test-Control (unwrap (read-u32be buffer 0)))
           (custom-memory-addr (unwrap (read-u64be buffer 0)))
           (stream-prefix (unwrap (read-u32be buffer 0)))
           (device-info-descriptor-bLength (unwrap (read-u8 buffer 0)))
           (device-info-descriptor-bDescriptorType (unwrap (read-u8 buffer 0)))
           (device-info-descriptor-bGenCPVersion-minor (unwrap (read-u32be buffer 0)))
           (device-info-descriptor-bGenCPVersion-major (unwrap (read-u32be buffer 0)))
           (flag (unwrap (read-u16be buffer 4)))
           (acknowledge-required-flag (unwrap (read-u8 buffer 4)))
           (device-info-descriptor-bU3VVersion-minor (unwrap (read-u32be buffer 4)))
           (device-info-descriptor-bU3VVersion-major (unwrap (read-u32be buffer 4)))
           (stream-leader-size (unwrap (read-u16be buffer 6)))
           (stream-trailer-size (unwrap (read-u16be buffer 6)))
           (gencp-prefix (unwrap (read-u32be buffer 6)))
           (stream-block-id (unwrap (read-u64be buffer 8)))
           (device-info-descriptor-iDeviceGUID (unwrap (read-u8 buffer 8)))
           (device-info-descriptor-iVendorName (unwrap (read-u8 buffer 8)))
           (device-info-descriptor-iModelName (unwrap (read-u8 buffer 8)))
           (device-info-descriptor-iFamilyName (unwrap (read-u8 buffer 8)))
           (device-info-descriptor-iDeviceVersion (unwrap (read-u8 buffer 8)))
           (device-info-descriptor-iManufacturerInfo (unwrap (read-u8 buffer 8)))
           (device-info-descriptor-iSerialNumber (unwrap (read-u8 buffer 8)))
           (device-info-descriptor-iUserDefinedName (unwrap (read-u8 buffer 8)))
           (device-info-descriptor-bmSpeedSupport (unwrap (read-u8 buffer 8)))
           (device-info-descriptor-bmSpeedSupport-low-speed (extract-bits device-info-descriptor-bmSpeedSupport 0x1 0))
           (device-info-descriptor-bmSpeedSupport-full-speed (extract-bits device-info-descriptor-bmSpeedSupport 0x2 1))
           (device-info-descriptor-bmSpeedSupport-high-speed (extract-bits device-info-descriptor-bmSpeedSupport 0x4 2))
           (device-info-descriptor-bmSpeedSupport-super-speed (extract-bits device-info-descriptor-bmSpeedSupport 0x8 3))
           (device-info-descriptor-bmSpeedSupport-reserved (extract-bits device-info-descriptor-bmSpeedSupport 0xF0 4))
           (eventcmd-error-id (unwrap (read-u16be buffer 12)))
           (eventcmd-device-specific-id (unwrap (read-u16be buffer 12)))
           (eventcmd-timestamp (unwrap (read-u64be buffer 14)))
           (length (unwrap (read-u16be buffer 14)))
           (request-id (unwrap (read-u16be buffer 16)))
           (stream-reserved (unwrap (slice buffer 18 2)))
           (payloaddata (unwrap (slice buffer 18 1)))
           (stream-timestamp (unwrap (read-u64be buffer 20)))
           (stream-valid-payload-size (unwrap (read-u64be buffer 20)))
           (eventcmd-data (unwrap (slice buffer 22 1)))
           (count (unwrap (read-u16be buffer 24)))
           (reserved (unwrap (slice buffer 24 2)))
           (time-to-completion (unwrap (read-u16be buffer 26)))
           (stream-size-y (unwrap (read-u32be buffer 28)))
           (stream-size-x (unwrap (read-u32be buffer 32)))
           (stream-chunk-layout-id (unwrap (read-u32be buffer 32)))
           (stream-offset-x (unwrap (read-u32be buffer 40)))
           (stream-offset-y (unwrap (read-u32be buffer 44)))
           (stream-padding-x (unwrap (read-u16be buffer 48)))
           )

      (ok (list
        (cons 'stream-data (list (cons 'raw stream-data) (cons 'formatted (fmt-bytes stream-data))))
        (cons 'address (list (cons 'raw address) (cons 'formatted (fmt-hex address))))
        (cons 'bootstrap-GenCP-Version (list (cons 'raw bootstrap-GenCP-Version) (cons 'formatted (number->string bootstrap-GenCP-Version))))
        (cons 'bootstrap-Manufacturer-Name (list (cons 'raw bootstrap-Manufacturer-Name) (cons 'formatted (utf8->string bootstrap-Manufacturer-Name))))
        (cons 'bootstrap-Model-Name (list (cons 'raw bootstrap-Model-Name) (cons 'formatted (utf8->string bootstrap-Model-Name))))
        (cons 'bootstrap-Family-Name (list (cons 'raw bootstrap-Family-Name) (cons 'formatted (utf8->string bootstrap-Family-Name))))
        (cons 'bootstrap-Device-Version (list (cons 'raw bootstrap-Device-Version) (cons 'formatted (utf8->string bootstrap-Device-Version))))
        (cons 'bootstrap-Manufacturer-Info (list (cons 'raw bootstrap-Manufacturer-Info) (cons 'formatted (utf8->string bootstrap-Manufacturer-Info))))
        (cons 'bootstrap-Serial-Number (list (cons 'raw bootstrap-Serial-Number) (cons 'formatted (utf8->string bootstrap-Serial-Number))))
        (cons 'bootstrap-User-Defined-Name (list (cons 'raw bootstrap-User-Defined-Name) (cons 'formatted (utf8->string bootstrap-User-Defined-Name))))
        (cons 'bootstrap-Device-Capability (list (cons 'raw bootstrap-Device-Capability) (cons 'formatted (number->string bootstrap-Device-Capability))))
        (cons 'bootstrap-Maximum-Device-Response-Time (list (cons 'raw bootstrap-Maximum-Device-Response-Time) (cons 'formatted (number->string bootstrap-Maximum-Device-Response-Time))))
        (cons 'bootstrap-Manifest-Table-Address (list (cons 'raw bootstrap-Manifest-Table-Address) (cons 'formatted (fmt-hex bootstrap-Manifest-Table-Address))))
        (cons 'bootstrap-SBRM-Address (list (cons 'raw bootstrap-SBRM-Address) (cons 'formatted (fmt-hex bootstrap-SBRM-Address))))
        (cons 'bootstrap-Device-Configuration (list (cons 'raw bootstrap-Device-Configuration) (cons 'formatted (number->string bootstrap-Device-Configuration))))
        (cons 'bootstrap-Heartbeat-Timeout (list (cons 'raw bootstrap-Heartbeat-Timeout) (cons 'formatted (number->string bootstrap-Heartbeat-Timeout))))
        (cons 'bootstrap-Message-Channel-channel-id (list (cons 'raw bootstrap-Message-Channel-channel-id) (cons 'formatted (number->string bootstrap-Message-Channel-channel-id))))
        (cons 'bootstrap-Timestamp (list (cons 'raw bootstrap-Timestamp) (cons 'formatted (number->string bootstrap-Timestamp))))
        (cons 'bootstrap-Timestamp-Latch (list (cons 'raw bootstrap-Timestamp-Latch) (cons 'formatted (number->string bootstrap-Timestamp-Latch))))
        (cons 'bootstrap-Timestamp-Increment (list (cons 'raw bootstrap-Timestamp-Increment) (cons 'formatted (number->string bootstrap-Timestamp-Increment))))
        (cons 'bootstrap-Access-Privilege (list (cons 'raw bootstrap-Access-Privilege) (cons 'formatted (number->string bootstrap-Access-Privilege))))
        (cons 'bootstrap-Protocol-Endianness (list (cons 'raw bootstrap-Protocol-Endianness) (cons 'formatted (number->string bootstrap-Protocol-Endianness))))
        (cons 'bootstrap-Implementation-Endianness (list (cons 'raw bootstrap-Implementation-Endianness) (cons 'formatted (number->string bootstrap-Implementation-Endianness))))
        (cons 'bootstrap-U3V-Version (list (cons 'raw bootstrap-U3V-Version) (cons 'formatted (number->string bootstrap-U3V-Version))))
        (cons 'bootstrap-U3VCP-Capability-Register (list (cons 'raw bootstrap-U3VCP-Capability-Register) (cons 'formatted (number->string bootstrap-U3VCP-Capability-Register))))
        (cons 'bootstrap-U3VCP-Configuration-Register (list (cons 'raw bootstrap-U3VCP-Configuration-Register) (cons 'formatted (number->string bootstrap-U3VCP-Configuration-Register))))
        (cons 'bootstrap-Maximum-Command-Transfer-Length (list (cons 'raw bootstrap-Maximum-Command-Transfer-Length) (cons 'formatted (number->string bootstrap-Maximum-Command-Transfer-Length))))
        (cons 'bootstrap-Maximum-Acknowledge-Transfer-Length (list (cons 'raw bootstrap-Maximum-Acknowledge-Transfer-Length) (cons 'formatted (number->string bootstrap-Maximum-Acknowledge-Transfer-Length))))
        (cons 'bootstrap-Number-of-Stream-Channels (list (cons 'raw bootstrap-Number-of-Stream-Channels) (cons 'formatted (number->string bootstrap-Number-of-Stream-Channels))))
        (cons 'bootstrap-SIRM-Address (list (cons 'raw bootstrap-SIRM-Address) (cons 'formatted (fmt-hex bootstrap-SIRM-Address))))
        (cons 'bootstrap-SIRM-Length (list (cons 'raw bootstrap-SIRM-Length) (cons 'formatted (fmt-hex bootstrap-SIRM-Length))))
        (cons 'bootstrap-EIRM-Address (list (cons 'raw bootstrap-EIRM-Address) (cons 'formatted (fmt-hex bootstrap-EIRM-Address))))
        (cons 'bootstrap-EIRM-Length (list (cons 'raw bootstrap-EIRM-Length) (cons 'formatted (number->string bootstrap-EIRM-Length))))
        (cons 'bootstrap-IIDC2-Address (list (cons 'raw bootstrap-IIDC2-Address) (cons 'formatted (fmt-hex bootstrap-IIDC2-Address))))
        (cons 'bootstrap-Current-Speed (list (cons 'raw bootstrap-Current-Speed) (cons 'formatted (number->string bootstrap-Current-Speed))))
        (cons 'bootstrap-SI-Info (list (cons 'raw bootstrap-SI-Info) (cons 'formatted (number->string bootstrap-SI-Info))))
        (cons 'bootstrap-SI-Control (list (cons 'raw bootstrap-SI-Control) (cons 'formatted (number->string bootstrap-SI-Control))))
        (cons 'bootstrap-SI-Required-Payload-Size (list (cons 'raw bootstrap-SI-Required-Payload-Size) (cons 'formatted (number->string bootstrap-SI-Required-Payload-Size))))
        (cons 'bootstrap-SI-Required-Leader-Size (list (cons 'raw bootstrap-SI-Required-Leader-Size) (cons 'formatted (number->string bootstrap-SI-Required-Leader-Size))))
        (cons 'bootstrap-SI-Required-Trailer-Size (list (cons 'raw bootstrap-SI-Required-Trailer-Size) (cons 'formatted (number->string bootstrap-SI-Required-Trailer-Size))))
        (cons 'bootstrap-SI-Maximum-Leader-Size (list (cons 'raw bootstrap-SI-Maximum-Leader-Size) (cons 'formatted (number->string bootstrap-SI-Maximum-Leader-Size))))
        (cons 'bootstrap-SI-Payload-Transfer-Size (list (cons 'raw bootstrap-SI-Payload-Transfer-Size) (cons 'formatted (number->string bootstrap-SI-Payload-Transfer-Size))))
        (cons 'bootstrap-SI-Payload-Transfer-Count (list (cons 'raw bootstrap-SI-Payload-Transfer-Count) (cons 'formatted (number->string bootstrap-SI-Payload-Transfer-Count))))
        (cons 'bootstrap-SI-Payload-Final-Transfer1-Size (list (cons 'raw bootstrap-SI-Payload-Final-Transfer1-Size) (cons 'formatted (number->string bootstrap-SI-Payload-Final-Transfer1-Size))))
        (cons 'bootstrap-SI-Payload-Final-Transfer2-Size (list (cons 'raw bootstrap-SI-Payload-Final-Transfer2-Size) (cons 'formatted (number->string bootstrap-SI-Payload-Final-Transfer2-Size))))
        (cons 'bootstrap-SI-Maximum-Trailer-Size (list (cons 'raw bootstrap-SI-Maximum-Trailer-Size) (cons 'formatted (number->string bootstrap-SI-Maximum-Trailer-Size))))
        (cons 'bootstrap-EI-Control (list (cons 'raw bootstrap-EI-Control) (cons 'formatted (number->string bootstrap-EI-Control))))
        (cons 'bootstrap-Maximum-Event-Transfer-Length (list (cons 'raw bootstrap-Maximum-Event-Transfer-Length) (cons 'formatted (number->string bootstrap-Maximum-Event-Transfer-Length))))
        (cons 'bootstrap-Event-Test-Control (list (cons 'raw bootstrap-Event-Test-Control) (cons 'formatted (number->string bootstrap-Event-Test-Control))))
        (cons 'custom-memory-addr (list (cons 'raw custom-memory-addr) (cons 'formatted (fmt-hex custom-memory-addr))))
        (cons 'stream-prefix (list (cons 'raw stream-prefix) (cons 'formatted (fmt-hex stream-prefix))))
        (cons 'device-info-descriptor-bLength (list (cons 'raw device-info-descriptor-bLength) (cons 'formatted (number->string device-info-descriptor-bLength))))
        (cons 'device-info-descriptor-bDescriptorType (list (cons 'raw device-info-descriptor-bDescriptorType) (cons 'formatted (fmt-hex device-info-descriptor-bDescriptorType))))
        (cons 'device-info-descriptor-bGenCPVersion-minor (list (cons 'raw device-info-descriptor-bGenCPVersion-minor) (cons 'formatted (number->string device-info-descriptor-bGenCPVersion-minor))))
        (cons 'device-info-descriptor-bGenCPVersion-major (list (cons 'raw device-info-descriptor-bGenCPVersion-major) (cons 'formatted (number->string device-info-descriptor-bGenCPVersion-major))))
        (cons 'flag (list (cons 'raw flag) (cons 'formatted (fmt-hex flag))))
        (cons 'acknowledge-required-flag (list (cons 'raw acknowledge-required-flag) (cons 'formatted (number->string acknowledge-required-flag))))
        (cons 'device-info-descriptor-bU3VVersion-minor (list (cons 'raw device-info-descriptor-bU3VVersion-minor) (cons 'formatted (number->string device-info-descriptor-bU3VVersion-minor))))
        (cons 'device-info-descriptor-bU3VVersion-major (list (cons 'raw device-info-descriptor-bU3VVersion-major) (cons 'formatted (number->string device-info-descriptor-bU3VVersion-major))))
        (cons 'stream-leader-size (list (cons 'raw stream-leader-size) (cons 'formatted (number->string stream-leader-size))))
        (cons 'stream-trailer-size (list (cons 'raw stream-trailer-size) (cons 'formatted (number->string stream-trailer-size))))
        (cons 'gencp-prefix (list (cons 'raw gencp-prefix) (cons 'formatted (fmt-hex gencp-prefix))))
        (cons 'stream-block-id (list (cons 'raw stream-block-id) (cons 'formatted (number->string stream-block-id))))
        (cons 'device-info-descriptor-iDeviceGUID (list (cons 'raw device-info-descriptor-iDeviceGUID) (cons 'formatted (number->string device-info-descriptor-iDeviceGUID))))
        (cons 'device-info-descriptor-iVendorName (list (cons 'raw device-info-descriptor-iVendorName) (cons 'formatted (number->string device-info-descriptor-iVendorName))))
        (cons 'device-info-descriptor-iModelName (list (cons 'raw device-info-descriptor-iModelName) (cons 'formatted (number->string device-info-descriptor-iModelName))))
        (cons 'device-info-descriptor-iFamilyName (list (cons 'raw device-info-descriptor-iFamilyName) (cons 'formatted (number->string device-info-descriptor-iFamilyName))))
        (cons 'device-info-descriptor-iDeviceVersion (list (cons 'raw device-info-descriptor-iDeviceVersion) (cons 'formatted (number->string device-info-descriptor-iDeviceVersion))))
        (cons 'device-info-descriptor-iManufacturerInfo (list (cons 'raw device-info-descriptor-iManufacturerInfo) (cons 'formatted (number->string device-info-descriptor-iManufacturerInfo))))
        (cons 'device-info-descriptor-iSerialNumber (list (cons 'raw device-info-descriptor-iSerialNumber) (cons 'formatted (number->string device-info-descriptor-iSerialNumber))))
        (cons 'device-info-descriptor-iUserDefinedName (list (cons 'raw device-info-descriptor-iUserDefinedName) (cons 'formatted (number->string device-info-descriptor-iUserDefinedName))))
        (cons 'device-info-descriptor-bmSpeedSupport (list (cons 'raw device-info-descriptor-bmSpeedSupport) (cons 'formatted (fmt-hex device-info-descriptor-bmSpeedSupport))))
        (cons 'device-info-descriptor-bmSpeedSupport-low-speed (list (cons 'raw device-info-descriptor-bmSpeedSupport-low-speed) (cons 'formatted (if (= device-info-descriptor-bmSpeedSupport-low-speed 0) "Not set" "Set"))))
        (cons 'device-info-descriptor-bmSpeedSupport-full-speed (list (cons 'raw device-info-descriptor-bmSpeedSupport-full-speed) (cons 'formatted (if (= device-info-descriptor-bmSpeedSupport-full-speed 0) "Not set" "Set"))))
        (cons 'device-info-descriptor-bmSpeedSupport-high-speed (list (cons 'raw device-info-descriptor-bmSpeedSupport-high-speed) (cons 'formatted (if (= device-info-descriptor-bmSpeedSupport-high-speed 0) "Not set" "Set"))))
        (cons 'device-info-descriptor-bmSpeedSupport-super-speed (list (cons 'raw device-info-descriptor-bmSpeedSupport-super-speed) (cons 'formatted (if (= device-info-descriptor-bmSpeedSupport-super-speed 0) "Not set" "Set"))))
        (cons 'device-info-descriptor-bmSpeedSupport-reserved (list (cons 'raw device-info-descriptor-bmSpeedSupport-reserved) (cons 'formatted (if (= device-info-descriptor-bmSpeedSupport-reserved 0) "Not set" "Set"))))
        (cons 'eventcmd-error-id (list (cons 'raw eventcmd-error-id) (cons 'formatted (fmt-hex eventcmd-error-id))))
        (cons 'eventcmd-device-specific-id (list (cons 'raw eventcmd-device-specific-id) (cons 'formatted (fmt-hex eventcmd-device-specific-id))))
        (cons 'eventcmd-timestamp (list (cons 'raw eventcmd-timestamp) (cons 'formatted (fmt-hex eventcmd-timestamp))))
        (cons 'length (list (cons 'raw length) (cons 'formatted (fmt-hex length))))
        (cons 'request-id (list (cons 'raw request-id) (cons 'formatted (fmt-hex request-id))))
        (cons 'stream-reserved (list (cons 'raw stream-reserved) (cons 'formatted (fmt-bytes stream-reserved))))
        (cons 'payloaddata (list (cons 'raw payloaddata) (cons 'formatted (fmt-bytes payloaddata))))
        (cons 'stream-timestamp (list (cons 'raw stream-timestamp) (cons 'formatted (fmt-hex stream-timestamp))))
        (cons 'stream-valid-payload-size (list (cons 'raw stream-valid-payload-size) (cons 'formatted (fmt-hex stream-valid-payload-size))))
        (cons 'eventcmd-data (list (cons 'raw eventcmd-data) (cons 'formatted (fmt-bytes eventcmd-data))))
        (cons 'count (list (cons 'raw count) (cons 'formatted (fmt-hex count))))
        (cons 'reserved (list (cons 'raw reserved) (cons 'formatted (fmt-bytes reserved))))
        (cons 'time-to-completion (list (cons 'raw time-to-completion) (cons 'formatted (number->string time-to-completion))))
        (cons 'stream-size-y (list (cons 'raw stream-size-y) (cons 'formatted (number->string stream-size-y))))
        (cons 'stream-size-x (list (cons 'raw stream-size-x) (cons 'formatted (number->string stream-size-x))))
        (cons 'stream-chunk-layout-id (list (cons 'raw stream-chunk-layout-id) (cons 'formatted (fmt-hex stream-chunk-layout-id))))
        (cons 'stream-offset-x (list (cons 'raw stream-offset-x) (cons 'formatted (number->string stream-offset-x))))
        (cons 'stream-offset-y (list (cons 'raw stream-offset-y) (cons 'formatted (number->string stream-offset-y))))
        (cons 'stream-padding-x (list (cons 'raw stream-padding-x) (cons 'formatted (number->string stream-padding-x))))
        )))

    (catch (e)
      (err (str "U3V parse error: " e)))))

;; dissect-u3v: parse U3V from bytevector
;; Returns (ok fields-alist) or (err message)