;; packet-ubertooth.c
;; Routines for Ubertooth USB dissection
;;
;; Copyright 2013, Michal Labedzki for Tieto Corporation
;;
;; Wireshark - Network traffic analyzer
;; By Gerald Combs <gerald@wireshark.org>
;; Copyright 1998 Gerald Combs
;;
;; SPDX-License-Identifier: GPL-2.0-or-later
;;

;; jerboa-ethereal/dissectors/ubertooth.ss
;; Auto-generated from wireshark/epan/dissectors/packet-ubertooth.c

(import (jerboa prelude))

;; ── Protocol Helpers ─────────────────────────────────────────────────
(def (read-u8 buf offset)
  (if (>= offset (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u8-ref buf offset))))

(def (read-u16be buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness big)))))

(def (read-u24be buf offset)
  (if (> (+ offset 3) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (+ (* (bytevector-u8-ref buf offset) 65536)
             (* (bytevector-u8-ref buf (+ offset 1)) 256)
             (bytevector-u8-ref buf (+ offset 2))))))

(def (read-u32be buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness big)))))

(def (read-u16le buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness little)))))

(def (read-u32le buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness little)))))

(def (read-u64be buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness big)))))

(def (read-u64le buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness little)))))

(def (slice buf offset len)
  (if (> (+ offset len) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (let ((result (make-bytevector len)))
            (bytevector-copy! buf offset result 0 len)
            result))))

(def (extract-bits val mask shift)
  (bitwise-arithmetic-shift-right (bitwise-and val mask) shift))

(def (fmt-ipv4 addr)
  (let ((b0 (bitwise-arithmetic-shift-right addr 24))
        (b1 (bitwise-and (bitwise-arithmetic-shift-right addr 16) 255))
        (b2 (bitwise-and (bitwise-arithmetic-shift-right addr 8) 255))
        (b3 (bitwise-and addr 255)))
    (str b0 "." b1 "." b2 "." b3)))

(def (fmt-mac bytes)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bytes))
    ":"))

(def (fmt-hex val)
  (str "0x" (number->string val 16)))

(def (fmt-oct val)
  (str "0" (number->string val 8)))

(def (fmt-port port)
  (number->string port))

(def (fmt-bytes bv)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bv))
    " "))

(def (fmt-ipv6-address bytes)
  (let loop ((i 0) (parts '()))
    (if (>= i 16)
        (string-join (reverse parts) ":")
        (loop (+ i 2)
              (cons (let ((w (+ (* (bytevector-u8-ref bytes i) 256)
                                (bytevector-u8-ref bytes (+ i 1)))))
                      (number->string w 16))
                    parts)))))

;; ── Dissector ──────────────────────────────────────────────────────
(def (dissect-ubertooth buffer)
  "Ubertooth"
  (try
    (let* (
           (main-resetn (unwrap (read-u8 buffer 0)))
           (main-reserved-14-10 (unwrap (read-u16be buffer 0)))
           (main-fs-force-en (unwrap (read-u8 buffer 0)))
           (main-rxn-tx (unwrap (read-u8 buffer 0)))
           (main-reserved-7-4 (unwrap (read-u16be buffer 0)))
           (main-reserved-3 (unwrap (read-u8 buffer 0)))
           (main-reserved-2 (unwrap (read-u8 buffer 0)))
           (main-xosc16m-bypass (unwrap (read-u8 buffer 0)))
           (main-xosc16m-en (unwrap (read-u8 buffer 0)))
           (fsctrl-reserved (unwrap (read-u16be buffer 0)))
           (fsctrl-cal-done (unwrap (read-u8 buffer 0)))
           (fsctrl-cal-running (unwrap (read-u8 buffer 0)))
           (fsctrl-lock-status (unwrap (read-u8 buffer 0)))
           (fsdiv-reserved (unwrap (read-u16be buffer 0)))
           (fsdiv-frequency (unwrap (read-u16be buffer 0)))
           (fsdiv-freq-high (unwrap (read-u16be buffer 0)))
           (fsdiv-freq (unwrap (read-u16be buffer 0)))
           (mdmctrl-reserved (unwrap (read-u16be buffer 0)))
           (mdmctrl-mod-offset (unwrap (read-u16be buffer 0)))
           (mdmctrl-mod-dev (unwrap (read-u16be buffer 0)))
           (agcctrl-vga-gain (unwrap (read-u16be buffer 0)))
           (agcctrl-reserved (unwrap (read-u16be buffer 0)))
           (agcctrl-agc-locked (unwrap (read-u8 buffer 0)))
           (agcctrl-agc-lock (unwrap (read-u8 buffer 0)))
           (agcctrl-agc-sync-lock (unwrap (read-u8 buffer 0)))
           (agcctrl-vga-gain-oe (unwrap (read-u8 buffer 0)))
           (frend-reserved-15-4 (unwrap (read-u16be buffer 0)))
           (frend-reserved-3 (unwrap (read-u8 buffer 0)))
           (frend-pa-level (unwrap (read-u16be buffer 0)))
           (rssi-rssi-val (unwrap (read-u16be buffer 0)))
           (rssi-rssi-cs-thres (unwrap (read-u16be buffer 0)))
           (freqest-rx-freq-offset (unwrap (read-u16be buffer 0)))
           (freqest-reserved (unwrap (read-u16be buffer 0)))
           (iocfg-reserved (unwrap (read-u8 buffer 0)))
           (iocfg-gio6-cfg (unwrap (read-u16be buffer 0)))
           (iocfg-gio1-cfg (unwrap (read-u16be buffer 0)))
           (fsmtc-tc-rxon2agcen (unwrap (read-u16be buffer 0)))
           (fsmtc-tc-paon2switch (unwrap (read-u16be buffer 0)))
           (fsmtc-res (unwrap (read-u16be buffer 0)))
           (fsmtc-tc-txend2switch (unwrap (read-u16be buffer 0)))
           (fsmtc-tc-txend2paoff (unwrap (read-u16be buffer 0)))
           (reserved-0x0C-res-15-5 (unwrap (read-u16be buffer 0)))
           (reserved-0x0C-res-4-0 (unwrap (read-u16be buffer 0)))
           (manand-vga-reset-n (unwrap (read-u8 buffer 0)))
           (manand-lock-status (unwrap (read-u8 buffer 0)))
           (manand-balun-ctrl (unwrap (read-u8 buffer 0)))
           (manand-rxtx (unwrap (read-u8 buffer 0)))
           (manand-pre-pd (unwrap (read-u8 buffer 0)))
           (manand-pa-n-pd (unwrap (read-u8 buffer 0)))
           (manand-pa-p-pd (unwrap (read-u8 buffer 0)))
           (manand-dac-lpf-pd (unwrap (read-u8 buffer 0)))
           (manand-bias-pd (unwrap (read-u8 buffer 0)))
           (manand-xosc16m-pd (unwrap (read-u8 buffer 0)))
           (manand-chp-pd (unwrap (read-u8 buffer 0)))
           (manand-fs-pd (unwrap (read-u8 buffer 0)))
           (manand-adc-pd (unwrap (read-u8 buffer 0)))
           (manand-vga-pd (unwrap (read-u8 buffer 0)))
           (manand-rxbpf-pd (unwrap (read-u8 buffer 0)))
           (manand-lnamix-pd (unwrap (read-u8 buffer 0)))
           (fsmstate-reserved-15-13 (unwrap (read-u16be buffer 0)))
           (fsmstate-fsm-state-bkpt (unwrap (read-u16be buffer 0)))
           (fsmstate-reserved-7-5 (unwrap (read-u16be buffer 0)))
           (fsmstate-fsm-cur-state (unwrap (read-u16be buffer 0)))
           (adctst-reserved-15 (unwrap (read-u8 buffer 0)))
           (adctst-adc-i (unwrap (read-u16be buffer 0)))
           (adctst-reserved-7 (unwrap (read-u8 buffer 0)))
           (adctst-adc-q (unwrap (read-u16be buffer 0)))
           (rxbpftst-reserved (unwrap (read-u8 buffer 0)))
           (rxbpftst-rxbpf-cap-oe (unwrap (read-u8 buffer 0)))
           (rxbpftst-rxbpf-cap-o (unwrap (read-u16be buffer 0)))
           (rxbpftst-rxbpf-cap-res (unwrap (read-u16be buffer 0)))
           (pamtst-reserved-15-13 (unwrap (read-u16be buffer 0)))
           (pamtst-vc-in-test-en (unwrap (read-u8 buffer 0)))
           (pamtst-atestmod-pd (unwrap (read-u8 buffer 0)))
           (pamtst-reserved-7 (unwrap (read-u8 buffer 0)))
           (pamtst-txmix-cap-array (unwrap (read-u16be buffer 0)))
           (lmtst-reserved (unwrap (read-u16be buffer 0)))
           (lmtst-rxmix-hgm (unwrap (read-u8 buffer 0)))
           (manor-vga-reset-n (unwrap (read-u8 buffer 0)))
           (manor-lock-status (unwrap (read-u8 buffer 0)))
           (manor-balun-ctrl (unwrap (read-u8 buffer 0)))
           (manor-rxtx (unwrap (read-u8 buffer 0)))
           (manor-pre-pd (unwrap (read-u8 buffer 0)))
           (manor-pa-n-pd (unwrap (read-u8 buffer 0)))
           (manor-pa-p-pd (unwrap (read-u8 buffer 0)))
           (manor-dac-lpf-pd (unwrap (read-u8 buffer 0)))
           (manor-bias-pd (unwrap (read-u8 buffer 0)))
           (manor-xosc16m-pd (unwrap (read-u8 buffer 0)))
           (manor-chp-pd (unwrap (read-u8 buffer 0)))
           (manor-fs-pd (unwrap (read-u8 buffer 0)))
           (manor-adc-pd (unwrap (read-u8 buffer 0)))
           (manor-vga-pd (unwrap (read-u8 buffer 0)))
           (manor-rxbpf-pd (unwrap (read-u8 buffer 0)))
           (manor-lnamix-pd (unwrap (read-u8 buffer 0)))
           (mdmtst0-reserved (unwrap (read-u16be buffer 0)))
           (mdmtst0-tx-prng (unwrap (read-u8 buffer 0)))
           (mdmtst0-tx-1mhz-offset-n (unwrap (read-u8 buffer 0)))
           (mdmtst0-invert-data (unwrap (read-u8 buffer 0)))
           (mdmtst0-afc-adjust-on-packet (unwrap (read-u8 buffer 0)))
           (mdmtst0-afc-delta (unwrap (read-u16be buffer 0)))
           (mdmtst1-reserved (unwrap (read-u16be buffer 0)))
           (mdmtst1-bsync-threshold (unwrap (read-u16be buffer 0)))
           (dactst-reserved (unwrap (read-u8 buffer 0)))
           (dactst-dac-i-o (unwrap (read-u16be buffer 0)))
           (dactst-dac-q-o (unwrap (read-u16be buffer 0)))
           (agctst0-agc-settle-blank-dn (unwrap (read-u16be buffer 0)))
           (agctst0-agc-win-size (unwrap (read-u16be buffer 0)))
           (agctst0-agc-settle-peak (unwrap (read-u16be buffer 0)))
           (agctst0-agc-settle-adc (unwrap (read-u16be buffer 0)))
           (agctst0-agc-attempts (unwrap (read-u16be buffer 0)))
           (agctst1-reserved (unwrap (read-u8 buffer 0)))
           (agctst1-agc-settle-blank-up (unwrap (read-u16be buffer 0)))
           (agctst1-peakdet-cur-boost (unwrap (read-u8 buffer 0)))
           (agctst1-agc-mult-slow (unwrap (read-u16be buffer 0)))
           (agctst1-agc-settle-fixed (unwrap (read-u16be buffer 0)))
           (agctst1-agc-settle-var (unwrap (read-u16be buffer 0)))
           (agctst2-reserved (unwrap (read-u16be buffer 0)))
           (agctst2-agc-backend-blanking (unwrap (read-u16be buffer 0)))
           (agctst2-agc-adjust-m3db (unwrap (read-u16be buffer 0)))
           (agctst2-agc-adjust-m1db (unwrap (read-u16be buffer 0)))
           (agctst2-agc-adjust-p3db (unwrap (read-u16be buffer 0)))
           (agctst2-agc-adjust-p1db (unwrap (read-u16be buffer 0)))
           (fstst0-vco-array-settle-long (unwrap (read-u8 buffer 0)))
           (fstst0-vco-array-oe (unwrap (read-u8 buffer 0)))
           (fstst0-vco-array-o (unwrap (read-u16be buffer 0)))
           (fstst0-vco-array-res (unwrap (read-u16be buffer 0)))
           (fstst1-vco-current-ref (unwrap (read-u16be buffer 0)))
           (fstst1-vco-current-k (unwrap (read-u16be buffer 0)))
           (fstst1-vc-dac-val (unwrap (read-u16be buffer 0)))
           (fstst2-reserved (unwrap (read-u8 buffer 0)))
           (fstst2-vco-current-oe (unwrap (read-u8 buffer 0)))
           (fstst2-vco-current-o (unwrap (read-u16be buffer 0)))
           (fstst2-vco-current-res (unwrap (read-u16be buffer 0)))
           (fstst3-reserved (unwrap (read-u16be buffer 0)))
           (fstst3-chp-test-up (unwrap (read-u8 buffer 0)))
           (fstst3-chp-test-dn (unwrap (read-u8 buffer 0)))
           (fstst3-chp-disable (unwrap (read-u8 buffer 0)))
           (fstst3-stop-chp-current (unwrap (read-u16be buffer 0)))
           (fstst3-start-chp-current (unwrap (read-u16be buffer 0)))
           (manfidl-partnum (unwrap (read-u16be buffer 0)))
           (manfidl-manfid (unwrap (read-u16be buffer 0)))
           (manfidh-version (unwrap (read-u16be buffer 0)))
           (manfidh-partnum (unwrap (read-u16be buffer 0)))
           (grmdm-reserved (unwrap (read-u8 buffer 0)))
           (grmdm-sync-errbits-allowed (unwrap (read-u16be buffer 0)))
           (grmdm-packet-mode (unwrap (read-u8 buffer 0)))
           (grmdm-crc-on (unwrap (read-u8 buffer 0)))
           (grmdm-tx-gaussian-filter (unwrap (read-u8 buffer 0)))
           (grdec-reserved (unwrap (read-u16be buffer 0)))
           (grdec-ind-saturation (unwrap (read-u8 buffer 0)))
           (grdec-dec-val (unwrap (read-u16be buffer 0)))
           (pktstatus-reserved-15-11 (unwrap (read-u16be buffer 0)))
           (pktstatus-sync-word-received (unwrap (read-u8 buffer 0)))
           (pktstatus-crc-ok (unwrap (read-u8 buffer 0)))
           (pktstatus-reserved-8 (unwrap (read-u8 buffer 0)))
           (pktstatus-reserved-7-0 (unwrap (read-u16be buffer 0)))
           (int-reserved-15-8 (unwrap (read-u16be buffer 0)))
           (int-reserved-7 (unwrap (read-u8 buffer 0)))
           (int-pkt-polarity (unwrap (read-u8 buffer 0)))
           (int-fifo-polarity (unwrap (read-u8 buffer 0)))
           (int-fifo-threshold (unwrap (read-u16be buffer 0)))
           (reserved-0x24-res-15-14 (unwrap (read-u16be buffer 0)))
           (reserved-0x24-res-13-10 (unwrap (read-u16be buffer 0)))
           (reserved-0x24-res-9-7 (unwrap (read-u16be buffer 0)))
           (reserved-0x24-res-6-0 (unwrap (read-u16be buffer 0)))
           (reserved-0x25-res-15-12 (unwrap (read-u16be buffer 0)))
           (reserved-0x25-res-11-0 (unwrap (read-u16be buffer 0)))
           (reserved-0x26-res-15-10 (unwrap (read-u16be buffer 0)))
           (reserved-0x26-res-9-0 (unwrap (read-u16be buffer 0)))
           (reserved-0x27-res-15-8 (unwrap (read-u16be buffer 0)))
           (reserved-0x27-res-7-3 (unwrap (read-u16be buffer 0)))
           (reserved-0x27-res-2-0 (unwrap (read-u16be buffer 0)))
           (reserved-0x28-res-15 (unwrap (read-u8 buffer 0)))
           (reserved-0x28-res-14-13 (unwrap (read-u16be buffer 0)))
           (reserved-0x28-res-12-7 (unwrap (read-u16be buffer 0)))
           (reserved-0x28-res-6-0 (unwrap (read-u16be buffer 0)))
           (reserved-0x29-res-15-8 (unwrap (read-u16be buffer 0)))
           (reserved-0x29-res-7-3 (unwrap (read-u16be buffer 0)))
           (reserved-0x29-res-2-0 (unwrap (read-u16be buffer 0)))
           (reserved-0x2A-res-15-11 (unwrap (read-u16be buffer 0)))
           (reserved-0x2A-res-10 (unwrap (read-u8 buffer 0)))
           (reserved-0x2A-res-9-0 (unwrap (read-u16be buffer 0)))
           (reserved-0x2B-res-15-14 (unwrap (read-u16be buffer 0)))
           (reserved-0x2B-res-13 (unwrap (read-u8 buffer 0)))
           (reserved-0x2B-res-12 (unwrap (read-u8 buffer 0)))
           (reserved-0x2B-res-11-0 (unwrap (read-u16be buffer 0)))
           (syncl (unwrap (read-u16be buffer 0)))
           (synch (unwrap (read-u16be buffer 0)))
           (packets (unwrap (read-u16be buffer 1)))
           (init (unwrap (read-u24be buffer 6)))
           (interval (unwrap (read-u16be buffer 9)))
           (increment (unwrap (read-u8 buffer 11)))
           (threshold (unwrap (read-u16be buffer 21)))
           (frequency (unwrap (read-u16be buffer 41)))
           (0 (unwrap (read-u16be buffer 45)))
           (1 (unwrap (read-u16be buffer 47)))
           (length (unwrap (read-u16be buffer 49)))
           (hf-bdaddr (unwrap (slice buffer 51 6)))
           (offset (unwrap (read-u32be buffer 57)))
           (100ns (unwrap (read-u32be buffer 61)))
           (map (unwrap (slice buffer 69 10)))
           (status-reserved (unwrap (read-u8 buffer 76)))
           (status-rssi-trigger (unwrap (read-u8 buffer 76)))
           (status-cs-trigger (unwrap (read-u8 buffer 76)))
           (status-fifo-overflow (unwrap (read-u8 buffer 76)))
           (status-dma-error (unwrap (read-u8 buffer 76)))
           (status-dma-overflow (unwrap (read-u8 buffer 76)))
           (rx-packet-channel (unwrap (read-u8 buffer 77)))
           (max (unwrap (read-u8 buffer 83)))
           (hf-channel (unwrap (read-u16be buffer 83)))
           (min (unwrap (read-u8 buffer 84)))
           (avg (unwrap (read-u8 buffer 85)))
           (count (unwrap (read-u8 buffer 86)))
           (hf-frequency (unwrap (read-u16be buffer 89)))
           (hf-rssi (unwrap (read-u8 buffer 91)))
           (hf-status (unwrap (read-u8 buffer 102)))
           (number (unwrap (read-u32be buffer 103)))
           (amplifier-reserved (unwrap (read-u8 buffer 110)))
           (amplifier-level (unwrap (read-u8 buffer 110)))
           (test-valid (unwrap (read-u8 buffer 111)))
           (test-request-power-amplifier (unwrap (read-u8 buffer 112)))
           (test-request-number (unwrap (read-u8 buffer 113)))
           (test-reply-power-amplifier (unwrap (read-u8 buffer 114)))
           (test-reply-number (unwrap (read-u8 buffer 115)))
           (revision (unwrap (slice buffer 119 1)))
           (hf-squelch (unwrap (read-u16be buffer 120)))
           (ns (unwrap (read-u8 buffer 121)))
           (address (unwrap (read-u32be buffer 122)))
           (hf-reserved (unwrap (slice buffer 129 1)))
           (value (unwrap (read-u16be buffer 130)))
           (hf-length (unwrap (read-u8 buffer 132)))
           (compile-info (unwrap (slice buffer 133 1)))
           )

      (ok (list
        (cons 'main-resetn (list (cons 'raw main-resetn) (cons 'formatted (number->string main-resetn))))
        (cons 'main-reserved-14-10 (list (cons 'raw main-reserved-14-10) (cons 'formatted (number->string main-reserved-14-10))))
        (cons 'main-fs-force-en (list (cons 'raw main-fs-force-en) (cons 'formatted (number->string main-fs-force-en))))
        (cons 'main-rxn-tx (list (cons 'raw main-rxn-tx) (cons 'formatted (number->string main-rxn-tx))))
        (cons 'main-reserved-7-4 (list (cons 'raw main-reserved-7-4) (cons 'formatted (number->string main-reserved-7-4))))
        (cons 'main-reserved-3 (list (cons 'raw main-reserved-3) (cons 'formatted (number->string main-reserved-3))))
        (cons 'main-reserved-2 (list (cons 'raw main-reserved-2) (cons 'formatted (number->string main-reserved-2))))
        (cons 'main-xosc16m-bypass (list (cons 'raw main-xosc16m-bypass) (cons 'formatted (number->string main-xosc16m-bypass))))
        (cons 'main-xosc16m-en (list (cons 'raw main-xosc16m-en) (cons 'formatted (number->string main-xosc16m-en))))
        (cons 'fsctrl-reserved (list (cons 'raw fsctrl-reserved) (cons 'formatted (number->string fsctrl-reserved))))
        (cons 'fsctrl-cal-done (list (cons 'raw fsctrl-cal-done) (cons 'formatted (number->string fsctrl-cal-done))))
        (cons 'fsctrl-cal-running (list (cons 'raw fsctrl-cal-running) (cons 'formatted (number->string fsctrl-cal-running))))
        (cons 'fsctrl-lock-status (list (cons 'raw fsctrl-lock-status) (cons 'formatted (number->string fsctrl-lock-status))))
        (cons 'fsdiv-reserved (list (cons 'raw fsdiv-reserved) (cons 'formatted (number->string fsdiv-reserved))))
        (cons 'fsdiv-frequency (list (cons 'raw fsdiv-frequency) (cons 'formatted (number->string fsdiv-frequency))))
        (cons 'fsdiv-freq-high (list (cons 'raw fsdiv-freq-high) (cons 'formatted (number->string fsdiv-freq-high))))
        (cons 'fsdiv-freq (list (cons 'raw fsdiv-freq) (cons 'formatted (number->string fsdiv-freq))))
        (cons 'mdmctrl-reserved (list (cons 'raw mdmctrl-reserved) (cons 'formatted (number->string mdmctrl-reserved))))
        (cons 'mdmctrl-mod-offset (list (cons 'raw mdmctrl-mod-offset) (cons 'formatted (number->string mdmctrl-mod-offset))))
        (cons 'mdmctrl-mod-dev (list (cons 'raw mdmctrl-mod-dev) (cons 'formatted (number->string mdmctrl-mod-dev))))
        (cons 'agcctrl-vga-gain (list (cons 'raw agcctrl-vga-gain) (cons 'formatted (fmt-hex agcctrl-vga-gain))))
        (cons 'agcctrl-reserved (list (cons 'raw agcctrl-reserved) (cons 'formatted (number->string agcctrl-reserved))))
        (cons 'agcctrl-agc-locked (list (cons 'raw agcctrl-agc-locked) (cons 'formatted (number->string agcctrl-agc-locked))))
        (cons 'agcctrl-agc-lock (list (cons 'raw agcctrl-agc-lock) (cons 'formatted (number->string agcctrl-agc-lock))))
        (cons 'agcctrl-agc-sync-lock (list (cons 'raw agcctrl-agc-sync-lock) (cons 'formatted (number->string agcctrl-agc-sync-lock))))
        (cons 'agcctrl-vga-gain-oe (list (cons 'raw agcctrl-vga-gain-oe) (cons 'formatted (number->string agcctrl-vga-gain-oe))))
        (cons 'frend-reserved-15-4 (list (cons 'raw frend-reserved-15-4) (cons 'formatted (number->string frend-reserved-15-4))))
        (cons 'frend-reserved-3 (list (cons 'raw frend-reserved-3) (cons 'formatted (number->string frend-reserved-3))))
        (cons 'frend-pa-level (list (cons 'raw frend-pa-level) (cons 'formatted (number->string frend-pa-level))))
        (cons 'rssi-rssi-val (list (cons 'raw rssi-rssi-val) (cons 'formatted (number->string rssi-rssi-val))))
        (cons 'rssi-rssi-cs-thres (list (cons 'raw rssi-rssi-cs-thres) (cons 'formatted (number->string rssi-rssi-cs-thres))))
        (cons 'freqest-rx-freq-offset (list (cons 'raw freqest-rx-freq-offset) (cons 'formatted (number->string freqest-rx-freq-offset))))
        (cons 'freqest-reserved (list (cons 'raw freqest-reserved) (cons 'formatted (number->string freqest-reserved))))
        (cons 'iocfg-reserved (list (cons 'raw iocfg-reserved) (cons 'formatted (number->string iocfg-reserved))))
        (cons 'iocfg-gio6-cfg (list (cons 'raw iocfg-gio6-cfg) (cons 'formatted (number->string iocfg-gio6-cfg))))
        (cons 'iocfg-gio1-cfg (list (cons 'raw iocfg-gio1-cfg) (cons 'formatted (number->string iocfg-gio1-cfg))))
        (cons 'fsmtc-tc-rxon2agcen (list (cons 'raw fsmtc-tc-rxon2agcen) (cons 'formatted (number->string fsmtc-tc-rxon2agcen))))
        (cons 'fsmtc-tc-paon2switch (list (cons 'raw fsmtc-tc-paon2switch) (cons 'formatted (number->string fsmtc-tc-paon2switch))))
        (cons 'fsmtc-res (list (cons 'raw fsmtc-res) (cons 'formatted (number->string fsmtc-res))))
        (cons 'fsmtc-tc-txend2switch (list (cons 'raw fsmtc-tc-txend2switch) (cons 'formatted (number->string fsmtc-tc-txend2switch))))
        (cons 'fsmtc-tc-txend2paoff (list (cons 'raw fsmtc-tc-txend2paoff) (cons 'formatted (number->string fsmtc-tc-txend2paoff))))
        (cons 'reserved-0x0C-res-15-5 (list (cons 'raw reserved-0x0C-res-15-5) (cons 'formatted (number->string reserved-0x0C-res-15-5))))
        (cons 'reserved-0x0C-res-4-0 (list (cons 'raw reserved-0x0C-res-4-0) (cons 'formatted (number->string reserved-0x0C-res-4-0))))
        (cons 'manand-vga-reset-n (list (cons 'raw manand-vga-reset-n) (cons 'formatted (number->string manand-vga-reset-n))))
        (cons 'manand-lock-status (list (cons 'raw manand-lock-status) (cons 'formatted (number->string manand-lock-status))))
        (cons 'manand-balun-ctrl (list (cons 'raw manand-balun-ctrl) (cons 'formatted (number->string manand-balun-ctrl))))
        (cons 'manand-rxtx (list (cons 'raw manand-rxtx) (cons 'formatted (number->string manand-rxtx))))
        (cons 'manand-pre-pd (list (cons 'raw manand-pre-pd) (cons 'formatted (number->string manand-pre-pd))))
        (cons 'manand-pa-n-pd (list (cons 'raw manand-pa-n-pd) (cons 'formatted (number->string manand-pa-n-pd))))
        (cons 'manand-pa-p-pd (list (cons 'raw manand-pa-p-pd) (cons 'formatted (number->string manand-pa-p-pd))))
        (cons 'manand-dac-lpf-pd (list (cons 'raw manand-dac-lpf-pd) (cons 'formatted (number->string manand-dac-lpf-pd))))
        (cons 'manand-bias-pd (list (cons 'raw manand-bias-pd) (cons 'formatted (number->string manand-bias-pd))))
        (cons 'manand-xosc16m-pd (list (cons 'raw manand-xosc16m-pd) (cons 'formatted (number->string manand-xosc16m-pd))))
        (cons 'manand-chp-pd (list (cons 'raw manand-chp-pd) (cons 'formatted (number->string manand-chp-pd))))
        (cons 'manand-fs-pd (list (cons 'raw manand-fs-pd) (cons 'formatted (number->string manand-fs-pd))))
        (cons 'manand-adc-pd (list (cons 'raw manand-adc-pd) (cons 'formatted (number->string manand-adc-pd))))
        (cons 'manand-vga-pd (list (cons 'raw manand-vga-pd) (cons 'formatted (number->string manand-vga-pd))))
        (cons 'manand-rxbpf-pd (list (cons 'raw manand-rxbpf-pd) (cons 'formatted (number->string manand-rxbpf-pd))))
        (cons 'manand-lnamix-pd (list (cons 'raw manand-lnamix-pd) (cons 'formatted (number->string manand-lnamix-pd))))
        (cons 'fsmstate-reserved-15-13 (list (cons 'raw fsmstate-reserved-15-13) (cons 'formatted (number->string fsmstate-reserved-15-13))))
        (cons 'fsmstate-fsm-state-bkpt (list (cons 'raw fsmstate-fsm-state-bkpt) (cons 'formatted (number->string fsmstate-fsm-state-bkpt))))
        (cons 'fsmstate-reserved-7-5 (list (cons 'raw fsmstate-reserved-7-5) (cons 'formatted (number->string fsmstate-reserved-7-5))))
        (cons 'fsmstate-fsm-cur-state (list (cons 'raw fsmstate-fsm-cur-state) (cons 'formatted (number->string fsmstate-fsm-cur-state))))
        (cons 'adctst-reserved-15 (list (cons 'raw adctst-reserved-15) (cons 'formatted (number->string adctst-reserved-15))))
        (cons 'adctst-adc-i (list (cons 'raw adctst-adc-i) (cons 'formatted (number->string adctst-adc-i))))
        (cons 'adctst-reserved-7 (list (cons 'raw adctst-reserved-7) (cons 'formatted (number->string adctst-reserved-7))))
        (cons 'adctst-adc-q (list (cons 'raw adctst-adc-q) (cons 'formatted (number->string adctst-adc-q))))
        (cons 'rxbpftst-reserved (list (cons 'raw rxbpftst-reserved) (cons 'formatted (number->string rxbpftst-reserved))))
        (cons 'rxbpftst-rxbpf-cap-oe (list (cons 'raw rxbpftst-rxbpf-cap-oe) (cons 'formatted (number->string rxbpftst-rxbpf-cap-oe))))
        (cons 'rxbpftst-rxbpf-cap-o (list (cons 'raw rxbpftst-rxbpf-cap-o) (cons 'formatted (number->string rxbpftst-rxbpf-cap-o))))
        (cons 'rxbpftst-rxbpf-cap-res (list (cons 'raw rxbpftst-rxbpf-cap-res) (cons 'formatted (number->string rxbpftst-rxbpf-cap-res))))
        (cons 'pamtst-reserved-15-13 (list (cons 'raw pamtst-reserved-15-13) (cons 'formatted (number->string pamtst-reserved-15-13))))
        (cons 'pamtst-vc-in-test-en (list (cons 'raw pamtst-vc-in-test-en) (cons 'formatted (number->string pamtst-vc-in-test-en))))
        (cons 'pamtst-atestmod-pd (list (cons 'raw pamtst-atestmod-pd) (cons 'formatted (number->string pamtst-atestmod-pd))))
        (cons 'pamtst-reserved-7 (list (cons 'raw pamtst-reserved-7) (cons 'formatted (number->string pamtst-reserved-7))))
        (cons 'pamtst-txmix-cap-array (list (cons 'raw pamtst-txmix-cap-array) (cons 'formatted (number->string pamtst-txmix-cap-array))))
        (cons 'lmtst-reserved (list (cons 'raw lmtst-reserved) (cons 'formatted (number->string lmtst-reserved))))
        (cons 'lmtst-rxmix-hgm (list (cons 'raw lmtst-rxmix-hgm) (cons 'formatted (number->string lmtst-rxmix-hgm))))
        (cons 'manor-vga-reset-n (list (cons 'raw manor-vga-reset-n) (cons 'formatted (number->string manor-vga-reset-n))))
        (cons 'manor-lock-status (list (cons 'raw manor-lock-status) (cons 'formatted (number->string manor-lock-status))))
        (cons 'manor-balun-ctrl (list (cons 'raw manor-balun-ctrl) (cons 'formatted (number->string manor-balun-ctrl))))
        (cons 'manor-rxtx (list (cons 'raw manor-rxtx) (cons 'formatted (number->string manor-rxtx))))
        (cons 'manor-pre-pd (list (cons 'raw manor-pre-pd) (cons 'formatted (number->string manor-pre-pd))))
        (cons 'manor-pa-n-pd (list (cons 'raw manor-pa-n-pd) (cons 'formatted (number->string manor-pa-n-pd))))
        (cons 'manor-pa-p-pd (list (cons 'raw manor-pa-p-pd) (cons 'formatted (number->string manor-pa-p-pd))))
        (cons 'manor-dac-lpf-pd (list (cons 'raw manor-dac-lpf-pd) (cons 'formatted (number->string manor-dac-lpf-pd))))
        (cons 'manor-bias-pd (list (cons 'raw manor-bias-pd) (cons 'formatted (number->string manor-bias-pd))))
        (cons 'manor-xosc16m-pd (list (cons 'raw manor-xosc16m-pd) (cons 'formatted (number->string manor-xosc16m-pd))))
        (cons 'manor-chp-pd (list (cons 'raw manor-chp-pd) (cons 'formatted (number->string manor-chp-pd))))
        (cons 'manor-fs-pd (list (cons 'raw manor-fs-pd) (cons 'formatted (number->string manor-fs-pd))))
        (cons 'manor-adc-pd (list (cons 'raw manor-adc-pd) (cons 'formatted (number->string manor-adc-pd))))
        (cons 'manor-vga-pd (list (cons 'raw manor-vga-pd) (cons 'formatted (number->string manor-vga-pd))))
        (cons 'manor-rxbpf-pd (list (cons 'raw manor-rxbpf-pd) (cons 'formatted (number->string manor-rxbpf-pd))))
        (cons 'manor-lnamix-pd (list (cons 'raw manor-lnamix-pd) (cons 'formatted (number->string manor-lnamix-pd))))
        (cons 'mdmtst0-reserved (list (cons 'raw mdmtst0-reserved) (cons 'formatted (number->string mdmtst0-reserved))))
        (cons 'mdmtst0-tx-prng (list (cons 'raw mdmtst0-tx-prng) (cons 'formatted (number->string mdmtst0-tx-prng))))
        (cons 'mdmtst0-tx-1mhz-offset-n (list (cons 'raw mdmtst0-tx-1mhz-offset-n) (cons 'formatted (number->string mdmtst0-tx-1mhz-offset-n))))
        (cons 'mdmtst0-invert-data (list (cons 'raw mdmtst0-invert-data) (cons 'formatted (number->string mdmtst0-invert-data))))
        (cons 'mdmtst0-afc-adjust-on-packet (list (cons 'raw mdmtst0-afc-adjust-on-packet) (cons 'formatted (number->string mdmtst0-afc-adjust-on-packet))))
        (cons 'mdmtst0-afc-delta (list (cons 'raw mdmtst0-afc-delta) (cons 'formatted (number->string mdmtst0-afc-delta))))
        (cons 'mdmtst1-reserved (list (cons 'raw mdmtst1-reserved) (cons 'formatted (number->string mdmtst1-reserved))))
        (cons 'mdmtst1-bsync-threshold (list (cons 'raw mdmtst1-bsync-threshold) (cons 'formatted (number->string mdmtst1-bsync-threshold))))
        (cons 'dactst-reserved (list (cons 'raw dactst-reserved) (cons 'formatted (number->string dactst-reserved))))
        (cons 'dactst-dac-i-o (list (cons 'raw dactst-dac-i-o) (cons 'formatted (number->string dactst-dac-i-o))))
        (cons 'dactst-dac-q-o (list (cons 'raw dactst-dac-q-o) (cons 'formatted (number->string dactst-dac-q-o))))
        (cons 'agctst0-agc-settle-blank-dn (list (cons 'raw agctst0-agc-settle-blank-dn) (cons 'formatted (number->string agctst0-agc-settle-blank-dn))))
        (cons 'agctst0-agc-win-size (list (cons 'raw agctst0-agc-win-size) (cons 'formatted (number->string agctst0-agc-win-size))))
        (cons 'agctst0-agc-settle-peak (list (cons 'raw agctst0-agc-settle-peak) (cons 'formatted (number->string agctst0-agc-settle-peak))))
        (cons 'agctst0-agc-settle-adc (list (cons 'raw agctst0-agc-settle-adc) (cons 'formatted (number->string agctst0-agc-settle-adc))))
        (cons 'agctst0-agc-attempts (list (cons 'raw agctst0-agc-attempts) (cons 'formatted (number->string agctst0-agc-attempts))))
        (cons 'agctst1-reserved (list (cons 'raw agctst1-reserved) (cons 'formatted (number->string agctst1-reserved))))
        (cons 'agctst1-agc-settle-blank-up (list (cons 'raw agctst1-agc-settle-blank-up) (cons 'formatted (number->string agctst1-agc-settle-blank-up))))
        (cons 'agctst1-peakdet-cur-boost (list (cons 'raw agctst1-peakdet-cur-boost) (cons 'formatted (number->string agctst1-peakdet-cur-boost))))
        (cons 'agctst1-agc-mult-slow (list (cons 'raw agctst1-agc-mult-slow) (cons 'formatted (number->string agctst1-agc-mult-slow))))
        (cons 'agctst1-agc-settle-fixed (list (cons 'raw agctst1-agc-settle-fixed) (cons 'formatted (number->string agctst1-agc-settle-fixed))))
        (cons 'agctst1-agc-settle-var (list (cons 'raw agctst1-agc-settle-var) (cons 'formatted (number->string agctst1-agc-settle-var))))
        (cons 'agctst2-reserved (list (cons 'raw agctst2-reserved) (cons 'formatted (number->string agctst2-reserved))))
        (cons 'agctst2-agc-backend-blanking (list (cons 'raw agctst2-agc-backend-blanking) (cons 'formatted (number->string agctst2-agc-backend-blanking))))
        (cons 'agctst2-agc-adjust-m3db (list (cons 'raw agctst2-agc-adjust-m3db) (cons 'formatted (number->string agctst2-agc-adjust-m3db))))
        (cons 'agctst2-agc-adjust-m1db (list (cons 'raw agctst2-agc-adjust-m1db) (cons 'formatted (number->string agctst2-agc-adjust-m1db))))
        (cons 'agctst2-agc-adjust-p3db (list (cons 'raw agctst2-agc-adjust-p3db) (cons 'formatted (number->string agctst2-agc-adjust-p3db))))
        (cons 'agctst2-agc-adjust-p1db (list (cons 'raw agctst2-agc-adjust-p1db) (cons 'formatted (number->string agctst2-agc-adjust-p1db))))
        (cons 'fstst0-vco-array-settle-long (list (cons 'raw fstst0-vco-array-settle-long) (cons 'formatted (number->string fstst0-vco-array-settle-long))))
        (cons 'fstst0-vco-array-oe (list (cons 'raw fstst0-vco-array-oe) (cons 'formatted (number->string fstst0-vco-array-oe))))
        (cons 'fstst0-vco-array-o (list (cons 'raw fstst0-vco-array-o) (cons 'formatted (number->string fstst0-vco-array-o))))
        (cons 'fstst0-vco-array-res (list (cons 'raw fstst0-vco-array-res) (cons 'formatted (number->string fstst0-vco-array-res))))
        (cons 'fstst1-vco-current-ref (list (cons 'raw fstst1-vco-current-ref) (cons 'formatted (number->string fstst1-vco-current-ref))))
        (cons 'fstst1-vco-current-k (list (cons 'raw fstst1-vco-current-k) (cons 'formatted (number->string fstst1-vco-current-k))))
        (cons 'fstst1-vc-dac-val (list (cons 'raw fstst1-vc-dac-val) (cons 'formatted (number->string fstst1-vc-dac-val))))
        (cons 'fstst2-reserved (list (cons 'raw fstst2-reserved) (cons 'formatted (number->string fstst2-reserved))))
        (cons 'fstst2-vco-current-oe (list (cons 'raw fstst2-vco-current-oe) (cons 'formatted (number->string fstst2-vco-current-oe))))
        (cons 'fstst2-vco-current-o (list (cons 'raw fstst2-vco-current-o) (cons 'formatted (number->string fstst2-vco-current-o))))
        (cons 'fstst2-vco-current-res (list (cons 'raw fstst2-vco-current-res) (cons 'formatted (number->string fstst2-vco-current-res))))
        (cons 'fstst3-reserved (list (cons 'raw fstst3-reserved) (cons 'formatted (number->string fstst3-reserved))))
        (cons 'fstst3-chp-test-up (list (cons 'raw fstst3-chp-test-up) (cons 'formatted (number->string fstst3-chp-test-up))))
        (cons 'fstst3-chp-test-dn (list (cons 'raw fstst3-chp-test-dn) (cons 'formatted (number->string fstst3-chp-test-dn))))
        (cons 'fstst3-chp-disable (list (cons 'raw fstst3-chp-disable) (cons 'formatted (number->string fstst3-chp-disable))))
        (cons 'fstst3-stop-chp-current (list (cons 'raw fstst3-stop-chp-current) (cons 'formatted (number->string fstst3-stop-chp-current))))
        (cons 'fstst3-start-chp-current (list (cons 'raw fstst3-start-chp-current) (cons 'formatted (number->string fstst3-start-chp-current))))
        (cons 'manfidl-partnum (list (cons 'raw manfidl-partnum) (cons 'formatted (number->string manfidl-partnum))))
        (cons 'manfidl-manfid (list (cons 'raw manfidl-manfid) (cons 'formatted (fmt-hex manfidl-manfid))))
        (cons 'manfidh-version (list (cons 'raw manfidh-version) (cons 'formatted (number->string manfidh-version))))
        (cons 'manfidh-partnum (list (cons 'raw manfidh-partnum) (cons 'formatted (number->string manfidh-partnum))))
        (cons 'grmdm-reserved (list (cons 'raw grmdm-reserved) (cons 'formatted (number->string grmdm-reserved))))
        (cons 'grmdm-sync-errbits-allowed (list (cons 'raw grmdm-sync-errbits-allowed) (cons 'formatted (number->string grmdm-sync-errbits-allowed))))
        (cons 'grmdm-packet-mode (list (cons 'raw grmdm-packet-mode) (cons 'formatted (number->string grmdm-packet-mode))))
        (cons 'grmdm-crc-on (list (cons 'raw grmdm-crc-on) (cons 'formatted (number->string grmdm-crc-on))))
        (cons 'grmdm-tx-gaussian-filter (list (cons 'raw grmdm-tx-gaussian-filter) (cons 'formatted (number->string grmdm-tx-gaussian-filter))))
        (cons 'grdec-reserved (list (cons 'raw grdec-reserved) (cons 'formatted (number->string grdec-reserved))))
        (cons 'grdec-ind-saturation (list (cons 'raw grdec-ind-saturation) (cons 'formatted (number->string grdec-ind-saturation))))
        (cons 'grdec-dec-val (list (cons 'raw grdec-dec-val) (cons 'formatted (number->string grdec-dec-val))))
        (cons 'pktstatus-reserved-15-11 (list (cons 'raw pktstatus-reserved-15-11) (cons 'formatted (number->string pktstatus-reserved-15-11))))
        (cons 'pktstatus-sync-word-received (list (cons 'raw pktstatus-sync-word-received) (cons 'formatted (number->string pktstatus-sync-word-received))))
        (cons 'pktstatus-crc-ok (list (cons 'raw pktstatus-crc-ok) (cons 'formatted (number->string pktstatus-crc-ok))))
        (cons 'pktstatus-reserved-8 (list (cons 'raw pktstatus-reserved-8) (cons 'formatted (number->string pktstatus-reserved-8))))
        (cons 'pktstatus-reserved-7-0 (list (cons 'raw pktstatus-reserved-7-0) (cons 'formatted (number->string pktstatus-reserved-7-0))))
        (cons 'int-reserved-15-8 (list (cons 'raw int-reserved-15-8) (cons 'formatted (number->string int-reserved-15-8))))
        (cons 'int-reserved-7 (list (cons 'raw int-reserved-7) (cons 'formatted (number->string int-reserved-7))))
        (cons 'int-pkt-polarity (list (cons 'raw int-pkt-polarity) (cons 'formatted (number->string int-pkt-polarity))))
        (cons 'int-fifo-polarity (list (cons 'raw int-fifo-polarity) (cons 'formatted (number->string int-fifo-polarity))))
        (cons 'int-fifo-threshold (list (cons 'raw int-fifo-threshold) (cons 'formatted (number->string int-fifo-threshold))))
        (cons 'reserved-0x24-res-15-14 (list (cons 'raw reserved-0x24-res-15-14) (cons 'formatted (number->string reserved-0x24-res-15-14))))
        (cons 'reserved-0x24-res-13-10 (list (cons 'raw reserved-0x24-res-13-10) (cons 'formatted (number->string reserved-0x24-res-13-10))))
        (cons 'reserved-0x24-res-9-7 (list (cons 'raw reserved-0x24-res-9-7) (cons 'formatted (number->string reserved-0x24-res-9-7))))
        (cons 'reserved-0x24-res-6-0 (list (cons 'raw reserved-0x24-res-6-0) (cons 'formatted (number->string reserved-0x24-res-6-0))))
        (cons 'reserved-0x25-res-15-12 (list (cons 'raw reserved-0x25-res-15-12) (cons 'formatted (number->string reserved-0x25-res-15-12))))
        (cons 'reserved-0x25-res-11-0 (list (cons 'raw reserved-0x25-res-11-0) (cons 'formatted (number->string reserved-0x25-res-11-0))))
        (cons 'reserved-0x26-res-15-10 (list (cons 'raw reserved-0x26-res-15-10) (cons 'formatted (number->string reserved-0x26-res-15-10))))
        (cons 'reserved-0x26-res-9-0 (list (cons 'raw reserved-0x26-res-9-0) (cons 'formatted (number->string reserved-0x26-res-9-0))))
        (cons 'reserved-0x27-res-15-8 (list (cons 'raw reserved-0x27-res-15-8) (cons 'formatted (number->string reserved-0x27-res-15-8))))
        (cons 'reserved-0x27-res-7-3 (list (cons 'raw reserved-0x27-res-7-3) (cons 'formatted (number->string reserved-0x27-res-7-3))))
        (cons 'reserved-0x27-res-2-0 (list (cons 'raw reserved-0x27-res-2-0) (cons 'formatted (number->string reserved-0x27-res-2-0))))
        (cons 'reserved-0x28-res-15 (list (cons 'raw reserved-0x28-res-15) (cons 'formatted (number->string reserved-0x28-res-15))))
        (cons 'reserved-0x28-res-14-13 (list (cons 'raw reserved-0x28-res-14-13) (cons 'formatted (number->string reserved-0x28-res-14-13))))
        (cons 'reserved-0x28-res-12-7 (list (cons 'raw reserved-0x28-res-12-7) (cons 'formatted (number->string reserved-0x28-res-12-7))))
        (cons 'reserved-0x28-res-6-0 (list (cons 'raw reserved-0x28-res-6-0) (cons 'formatted (number->string reserved-0x28-res-6-0))))
        (cons 'reserved-0x29-res-15-8 (list (cons 'raw reserved-0x29-res-15-8) (cons 'formatted (number->string reserved-0x29-res-15-8))))
        (cons 'reserved-0x29-res-7-3 (list (cons 'raw reserved-0x29-res-7-3) (cons 'formatted (number->string reserved-0x29-res-7-3))))
        (cons 'reserved-0x29-res-2-0 (list (cons 'raw reserved-0x29-res-2-0) (cons 'formatted (number->string reserved-0x29-res-2-0))))
        (cons 'reserved-0x2A-res-15-11 (list (cons 'raw reserved-0x2A-res-15-11) (cons 'formatted (number->string reserved-0x2A-res-15-11))))
        (cons 'reserved-0x2A-res-10 (list (cons 'raw reserved-0x2A-res-10) (cons 'formatted (number->string reserved-0x2A-res-10))))
        (cons 'reserved-0x2A-res-9-0 (list (cons 'raw reserved-0x2A-res-9-0) (cons 'formatted (number->string reserved-0x2A-res-9-0))))
        (cons 'reserved-0x2B-res-15-14 (list (cons 'raw reserved-0x2B-res-15-14) (cons 'formatted (number->string reserved-0x2B-res-15-14))))
        (cons 'reserved-0x2B-res-13 (list (cons 'raw reserved-0x2B-res-13) (cons 'formatted (number->string reserved-0x2B-res-13))))
        (cons 'reserved-0x2B-res-12 (list (cons 'raw reserved-0x2B-res-12) (cons 'formatted (number->string reserved-0x2B-res-12))))
        (cons 'reserved-0x2B-res-11-0 (list (cons 'raw reserved-0x2B-res-11-0) (cons 'formatted (number->string reserved-0x2B-res-11-0))))
        (cons 'syncl (list (cons 'raw syncl) (cons 'formatted (fmt-hex syncl))))
        (cons 'synch (list (cons 'raw synch) (cons 'formatted (fmt-hex synch))))
        (cons 'packets (list (cons 'raw packets) (cons 'formatted (number->string packets))))
        (cons 'init (list (cons 'raw init) (cons 'formatted (fmt-hex init))))
        (cons 'interval (list (cons 'raw interval) (cons 'formatted (number->string interval))))
        (cons 'increment (list (cons 'raw increment) (cons 'formatted (number->string increment))))
        (cons 'threshold (list (cons 'raw threshold) (cons 'formatted (number->string threshold))))
        (cons 'frequency (list (cons 'raw frequency) (cons 'formatted (number->string frequency))))
        (cons '0 (list (cons 'raw 0) (cons 'formatted (fmt-hex 0))))
        (cons '1 (list (cons 'raw 1) (cons 'formatted (fmt-hex 1))))
        (cons 'length (list (cons 'raw length) (cons 'formatted (number->string length))))
        (cons 'hf-bdaddr (list (cons 'raw hf-bdaddr) (cons 'formatted (fmt-mac hf-bdaddr))))
        (cons 'offset (list (cons 'raw offset) (cons 'formatted (number->string offset))))
        (cons '100ns (list (cons 'raw 100ns) (cons 'formatted (number->string 100ns))))
        (cons 'map (list (cons 'raw map) (cons 'formatted (fmt-bytes map))))
        (cons 'status-reserved (list (cons 'raw status-reserved) (cons 'formatted (number->string status-reserved))))
        (cons 'status-rssi-trigger (list (cons 'raw status-rssi-trigger) (cons 'formatted (number->string status-rssi-trigger))))
        (cons 'status-cs-trigger (list (cons 'raw status-cs-trigger) (cons 'formatted (number->string status-cs-trigger))))
        (cons 'status-fifo-overflow (list (cons 'raw status-fifo-overflow) (cons 'formatted (number->string status-fifo-overflow))))
        (cons 'status-dma-error (list (cons 'raw status-dma-error) (cons 'formatted (number->string status-dma-error))))
        (cons 'status-dma-overflow (list (cons 'raw status-dma-overflow) (cons 'formatted (number->string status-dma-overflow))))
        (cons 'rx-packet-channel (list (cons 'raw rx-packet-channel) (cons 'formatted (number->string rx-packet-channel))))
        (cons 'max (list (cons 'raw max) (cons 'formatted (number->string max))))
        (cons 'hf-channel (list (cons 'raw hf-channel) (cons 'formatted (number->string hf-channel))))
        (cons 'min (list (cons 'raw min) (cons 'formatted (number->string min))))
        (cons 'avg (list (cons 'raw avg) (cons 'formatted (number->string avg))))
        (cons 'count (list (cons 'raw count) (cons 'formatted (number->string count))))
        (cons 'hf-frequency (list (cons 'raw hf-frequency) (cons 'formatted (number->string hf-frequency))))
        (cons 'hf-rssi (list (cons 'raw hf-rssi) (cons 'formatted (number->string hf-rssi))))
        (cons 'hf-status (list (cons 'raw hf-status) (cons 'formatted (fmt-hex hf-status))))
        (cons 'number (list (cons 'raw number) (cons 'formatted (fmt-hex number))))
        (cons 'amplifier-reserved (list (cons 'raw amplifier-reserved) (cons 'formatted (fmt-hex amplifier-reserved))))
        (cons 'amplifier-level (list (cons 'raw amplifier-level) (cons 'formatted (number->string amplifier-level))))
        (cons 'test-valid (list (cons 'raw test-valid) (cons 'formatted (number->string test-valid))))
        (cons 'test-request-power-amplifier (list (cons 'raw test-request-power-amplifier) (cons 'formatted (number->string test-request-power-amplifier))))
        (cons 'test-request-number (list (cons 'raw test-request-number) (cons 'formatted (number->string test-request-number))))
        (cons 'test-reply-power-amplifier (list (cons 'raw test-reply-power-amplifier) (cons 'formatted (number->string test-reply-power-amplifier))))
        (cons 'test-reply-number (list (cons 'raw test-reply-number) (cons 'formatted (number->string test-reply-number))))
        (cons 'revision (list (cons 'raw revision) (cons 'formatted (utf8->string revision))))
        (cons 'hf-squelch (list (cons 'raw hf-squelch) (cons 'formatted (number->string hf-squelch))))
        (cons 'ns (list (cons 'raw ns) (cons 'formatted (number->string ns))))
        (cons 'address (list (cons 'raw address) (cons 'formatted (fmt-hex address))))
        (cons 'hf-reserved (list (cons 'raw hf-reserved) (cons 'formatted (fmt-bytes hf-reserved))))
        (cons 'value (list (cons 'raw value) (cons 'formatted (fmt-hex value))))
        (cons 'hf-length (list (cons 'raw hf-length) (cons 'formatted (number->string hf-length))))
        (cons 'compile-info (list (cons 'raw compile-info) (cons 'formatted (utf8->string compile-info))))
        )))

    (catch (e)
      (err (str "UBERTOOTH parse error: " e)))))

;; dissect-ubertooth: parse UBERTOOTH from bytevector
;; Returns (ok fields-alist) or (err message)