;; packet-ubx.c
;; u-blox UBX protocol dissection.
;;
;; By Timo Warns <timo.warns@gmail.com>
;; Copyright 2023 Timo Warns
;;
;; Wireshark - Network traffic analyzer
;; By Gerald Combs <gerald@unicom.net>
;; Copyright 1998 Gerald Combs
;;
;; SPDX-License-Identifier: GPL-2.0-or-later
;;

;; jerboa-ethereal/dissectors/ubx.ss
;; Auto-generated from wireshark/epan/dissectors/packet-ubx.c

(import (jerboa prelude))

;; ── Protocol Helpers ─────────────────────────────────────────────────
(def (read-u8 buf offset)
  (if (>= offset (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u8-ref buf offset))))

(def (read-u16be buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness big)))))

(def (read-u24be buf offset)
  (if (> (+ offset 3) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (+ (* (bytevector-u8-ref buf offset) 65536)
             (* (bytevector-u8-ref buf (+ offset 1)) 256)
             (bytevector-u8-ref buf (+ offset 2))))))

(def (read-u32be buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness big)))))

(def (read-u16le buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness little)))))

(def (read-u32le buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness little)))))

(def (read-u64be buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness big)))))

(def (read-u64le buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness little)))))

(def (slice buf offset len)
  (if (> (+ offset len) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (let ((result (make-bytevector len)))
            (bytevector-copy! buf offset result 0 len)
            result))))

(def (extract-bits val mask shift)
  (bitwise-arithmetic-shift-right (bitwise-and val mask) shift))

(def (fmt-ipv4 addr)
  (let ((b0 (bitwise-arithmetic-shift-right addr 24))
        (b1 (bitwise-and (bitwise-arithmetic-shift-right addr 16) 255))
        (b2 (bitwise-and (bitwise-arithmetic-shift-right addr 8) 255))
        (b3 (bitwise-and addr 255)))
    (str b0 "." b1 "." b2 "." b3)))

(def (fmt-mac bytes)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bytes))
    ":"))

(def (fmt-hex val)
  (str "0x" (number->string val 16)))

(def (fmt-oct val)
  (str "0" (number->string val 8)))

(def (fmt-port port)
  (number->string port))

(def (fmt-bytes bv)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bv))
    " "))

(def (fmt-ipv6-address bytes)
  (let loop ((i 0) (parts '()))
    (if (>= i 16)
        (string-join (reverse parts) ":")
        (loop (+ i 2)
              (cons (let ((w (+ (* (bytevector-u8-ref bytes i) 256)
                                (bytevector-u8-ref bytes (+ i 1)))))
                      (number->string w 16))
                    parts)))))

;; ── Dissector ──────────────────────────────────────────────────────
(def (dissect-ubx buffer)
  "UBX Protocol"
  (try
    (let* (
           (cfg-sbas-mode (unwrap (read-u8 buffer 0)))
           (cfg-sbas-mode-enabled (extract-bits cfg-sbas-mode 0x1 0))
           (rxm-measx-version (unwrap (read-u8 buffer 0)))
           (nav-relposned-version (unwrap (read-u8 buffer 0)))
           (nav-odo-version (unwrap (read-u8 buffer 0)))
           (cfg-gnss-version (unwrap (read-u8 buffer 0)))
           (preamble (unwrap (read-u16be buffer 0)))
           (rxm-sfrbx-svid (unwrap (read-u8 buffer 1)))
           (rxm-measx-reserved1 (unwrap (read-u24be buffer 1)))
           (nav-relposned-reserved0 (unwrap (read-u8 buffer 1)))
           (nav-odo-reserved1 (unwrap (read-u24be buffer 1)))
           (cfg-sbas-usage-integrity (unwrap (read-u8 buffer 1)))
           (cfg-sbas-usage-diffcorr (unwrap (read-u8 buffer 1)))
           (cfg-sbas-usage-range (unwrap (read-u8 buffer 1)))
           (cfg-gnss-numtrkchhw (unwrap (read-u8 buffer 1)))
           (rxm-sfrbx-sigid (unwrap (read-u8 buffer 2)))
           (rxm-sfrbx-reserved1 (unwrap (read-u8 buffer 2)))
           (nav-relposned-refstationid (unwrap (read-u16be buffer 2)))
           (cfg-sbas-max-sbas (unwrap (read-u8 buffer 2)))
           (cfg-gnss-numtrkchuse (unwrap (read-u8 buffer 2)))
           (rxm-sfrbx-freqid (unwrap (read-u8 buffer 3)))
           (cfg-sbas-scanmode-prn158 (unwrap (read-u8 buffer 3)))
           (cfg-sbas-scanmode-prn157 (unwrap (read-u8 buffer 3)))
           (cfg-sbas-scanmode-prn156 (unwrap (read-u8 buffer 3)))
           (cfg-sbas-scanmode-prn155 (unwrap (read-u8 buffer 3)))
           (cfg-sbas-scanmode-prn154 (unwrap (read-u8 buffer 3)))
           (cfg-sbas-scanmode-prn153 (unwrap (read-u8 buffer 3)))
           (cfg-sbas-scanmode-prn152 (unwrap (read-u8 buffer 3)))
           (cfg-gnss-numconfigblocks (unwrap (read-u8 buffer 3)))
           (rxm-sfrbx-numwords (unwrap (read-u8 buffer 4)))
           (nav-sbas-geo (unwrap (read-u8 buffer 4)))
           (nav-sat-version (unwrap (read-u8 buffer 4)))
           (nav-pvt-year (unwrap (read-u16be buffer 4)))
           (cfg-sbas-scanmode-prn151 (unwrap (read-u32be buffer 4)))
           (cfg-sbas-scanmode-prn150 (unwrap (read-u32be buffer 4)))
           (cfg-sbas-scanmode-prn149 (unwrap (read-u32be buffer 4)))
           (cfg-sbas-scanmode-prn148 (unwrap (read-u32be buffer 4)))
           (cfg-sbas-scanmode-prn147 (unwrap (read-u32be buffer 4)))
           (cfg-sbas-scanmode-prn146 (unwrap (read-u32be buffer 4)))
           (cfg-sbas-scanmode-prn145 (unwrap (read-u32be buffer 4)))
           (cfg-sbas-scanmode-prn144 (unwrap (read-u32be buffer 4)))
           (cfg-sbas-scanmode-prn143 (unwrap (read-u32be buffer 4)))
           (cfg-sbas-scanmode-prn142 (unwrap (read-u32be buffer 4)))
           (cfg-sbas-scanmode-prn141 (unwrap (read-u32be buffer 4)))
           (cfg-sbas-scanmode-prn140 (unwrap (read-u32be buffer 4)))
           (cfg-sbas-scanmode-prn139 (unwrap (read-u32be buffer 4)))
           (cfg-sbas-scanmode-prn138 (unwrap (read-u32be buffer 4)))
           (cfg-sbas-scanmode-prn137 (unwrap (read-u32be buffer 4)))
           (cfg-sbas-scanmode-prn136 (unwrap (read-u32be buffer 4)))
           (cfg-sbas-scanmode-prn135 (unwrap (read-u32be buffer 4)))
           (cfg-sbas-scanmode-prn134 (unwrap (read-u32be buffer 4)))
           (cfg-sbas-scanmode-prn133 (unwrap (read-u32be buffer 4)))
           (cfg-sbas-scanmode-prn132 (unwrap (read-u32be buffer 4)))
           (cfg-sbas-scanmode-prn131 (unwrap (read-u32be buffer 4)))
           (cfg-sbas-scanmode-prn130 (unwrap (read-u32be buffer 4)))
           (cfg-sbas-scanmode-prn129 (unwrap (read-u32be buffer 4)))
           (cfg-sbas-scanmode-prn128 (unwrap (read-u32be buffer 4)))
           (cfg-sbas-scanmode-prn127 (unwrap (read-u32be buffer 4)))
           (cfg-sbas-scanmode-prn126 (unwrap (read-u32be buffer 4)))
           (cfg-sbas-scanmode-prn125 (unwrap (read-u32be buffer 4)))
           (cfg-sbas-scanmode-prn124 (unwrap (read-u32be buffer 4)))
           (cfg-sbas-scanmode-prn123 (unwrap (read-u32be buffer 4)))
           (cfg-sbas-scanmode-prn122 (unwrap (read-u32be buffer 4)))
           (cfg-sbas-scanmode-prn121 (unwrap (read-u32be buffer 4)))
           (cfg-sbas-scanmode-prn120 (unwrap (read-u32be buffer 4)))
           (payload-len (unwrap (read-u16be buffer 4)))
           (rxm-sfrbx-chn (unwrap (read-u8 buffer 5)))
           (rxm-sfrbx-reserved2 (unwrap (read-u8 buffer 5)))
           (nav-sat-num-svs (unwrap (read-u8 buffer 5)))
           (rxm-sfrbx-version (unwrap (read-u8 buffer 6)))
           (nav-sat-reserved1 (unwrap (read-u16be buffer 6)))
           (nav-pvt-month (unwrap (read-u8 buffer 6)))
           (nav-sbas-service (unwrap (read-u8 buffer 7)))
           (nav-sbas-service-ranging (extract-bits nav-sbas-service 0x1 0))
           (nav-sbas-service-corrections (extract-bits nav-sbas-service 0x2 1))
           (nav-sbas-service-integrity (extract-bits nav-sbas-service 0x4 2))
           (nav-sbas-service-testmode (extract-bits nav-sbas-service 0x8 3))
           (nav-sbas-service-bad (extract-bits nav-sbas-service 0x10 4))
           (rxm-sfrbx-reserved3 (unwrap (read-u8 buffer 7)))
           (nav-pvt-day (unwrap (read-u8 buffer 7)))
           (rxm-rawx-week (unwrap (read-u16be buffer 8)))
           (nav-timegps-week (unwrap (read-u16be buffer 8)))
           (nav-sbas-cnt (unwrap (read-u8 buffer 8)))
           (nav-pvt-hour (unwrap (read-u8 buffer 8)))
           (nav-sbas-reserved1 (unwrap (read-u24be buffer 9)))
           (nav-pvt-min (unwrap (read-u8 buffer 9)))
           (nav-pvt-sec (unwrap (read-u8 buffer 10)))
           (nav-timegps-valid (unwrap (read-u8 buffer 11)))
           (nav-timegps-towvalid (extract-bits nav-timegps-valid 0x1 0))
           (nav-timegps-weekvalid (extract-bits nav-timegps-valid 0x2 1))
           (nav-timegps-leapsvalid (extract-bits nav-timegps-valid 0x4 2))
           (nav-pvt-valid (unwrap (read-u8 buffer 11)))
           (nav-pvt-validdate (extract-bits nav-pvt-valid 0x1 0))
           (nav-pvt-validtime (extract-bits nav-pvt-valid 0x2 1))
           (nav-pvt-fullyresolved (extract-bits nav-pvt-valid 0x4 2))
           (nav-pvt-validmag (extract-bits nav-pvt-valid 0x8 3))
           (rxm-rawx-nummeas (unwrap (read-u8 buffer 11)))
           (rxm-rawx-recstat (unwrap (read-u8 buffer 12)))
           (rxm-rawx-recstat-leapsec (extract-bits rxm-rawx-recstat 0x1 0))
           (rxm-rawx-recstat-clkreset (extract-bits rxm-rawx-recstat 0x2 1))
           (nav-timeutc-year (unwrap (read-u16be buffer 12)))
           (rxm-rawx-version (unwrap (read-u8 buffer 13)))
           (rxm-rawx-reserved1 (unwrap (read-u16be buffer 14)))
           (nav-timeutc-month (unwrap (read-u8 buffer 14)))
           (nav-timeutc-day (unwrap (read-u8 buffer 15)))
           (rxm-measx-reserved2 (unwrap (read-u32be buffer 16)))
           (nav-timeutc-hour (unwrap (read-u8 buffer 16)))
           (nav-timeutc-min (unwrap (read-u8 buffer 17)))
           (nav-timeutc-sec (unwrap (read-u8 buffer 18)))
           (nav-timeutc-valid (unwrap (read-u8 buffer 19)))
           (nav-timeutc-validtow (extract-bits nav-timeutc-valid 0x1 0))
           (nav-timeutc-validwkn (extract-bits nav-timeutc-valid 0x2 1))
           (nav-timeutc-validutc (extract-bits nav-timeutc-valid 0x4 2))
           (nav-pvt-flags (unwrap (read-u8 buffer 21)))
           (nav-pvt-gnssfixok (extract-bits nav-pvt-flags 0x1 0))
           (nav-pvt-diffsoln (extract-bits nav-pvt-flags 0x2 1))
           (nav-pvt-psmstate (extract-bits nav-pvt-flags 0x1C 2))
           (nav-pvt-headvehvalid (extract-bits nav-pvt-flags 0x20 5))
           (nav-pvt-flags2 (unwrap (read-u8 buffer 22)))
           (nav-pvt-confirmedavai (extract-bits nav-pvt-flags2 0x20 5))
           (nav-pvt-confirmeddate (extract-bits nav-pvt-flags2 0x40 6))
           (nav-pvt-confirmedtime (extract-bits nav-pvt-flags2 0x80 7))
           (nav-pvt-numsv (unwrap (read-u8 buffer 23)))
           (nav-relposned-reserved1 (unwrap (read-u32be buffer 28)))
           (rxm-measx-reserved3 (unwrap (read-u16be buffer 30)))
           (rxm-measx-numsv (unwrap (read-u8 buffer 34)))
           (rxm-measx-flags-towset (unwrap (read-u8 buffer 35)))
           (rxm-measx-reserved4 (unwrap (read-u64be buffer 36)))
           (nav-relposned-reserved2 (unwrap (read-u32be buffer 56)))
           (nav-relposned-flags (unwrap (read-u32be buffer 60)))
           (nav-relposned-gnssfixok (extract-bits nav-relposned-flags 0x1 0))
           (nav-relposned-diffsoln (extract-bits nav-relposned-flags 0x2 1))
           (nav-relposned-relposvalid (extract-bits nav-relposned-flags 0x4 2))
           (nav-relposned-ismoving (extract-bits nav-relposned-flags 0x20 5))
           (nav-relposned-refposmiss (extract-bits nav-relposned-flags 0x40 6))
           (nav-relposned-refobsmiss (extract-bits nav-relposned-flags 0x80 7))
           (nav-relposned-relposheadingvalid (extract-bits nav-relposned-flags 0x100 8))
           (nav-relposned-relposnormalized (extract-bits nav-relposned-flags 0x200 9))
           (nav-pvt-invalidllh (unwrap (read-u8 buffer 78)))
           (nav-pvt-reserved1 (unwrap (read-u32be buffer 80)))
           )

      (ok (list
        (cons 'cfg-sbas-mode (list (cons 'raw cfg-sbas-mode) (cons 'formatted (fmt-hex cfg-sbas-mode))))
        (cons 'cfg-sbas-mode-enabled (list (cons 'raw cfg-sbas-mode-enabled) (cons 'formatted (if (= cfg-sbas-mode-enabled 0) "Not set" "Set"))))
        (cons 'rxm-measx-version (list (cons 'raw rxm-measx-version) (cons 'formatted (number->string rxm-measx-version))))
        (cons 'nav-relposned-version (list (cons 'raw nav-relposned-version) (cons 'formatted (number->string nav-relposned-version))))
        (cons 'nav-odo-version (list (cons 'raw nav-odo-version) (cons 'formatted (number->string nav-odo-version))))
        (cons 'cfg-gnss-version (list (cons 'raw cfg-gnss-version) (cons 'formatted (number->string cfg-gnss-version))))
        (cons 'preamble (list (cons 'raw preamble) (cons 'formatted (fmt-hex preamble))))
        (cons 'rxm-sfrbx-svid (list (cons 'raw rxm-sfrbx-svid) (cons 'formatted (number->string rxm-sfrbx-svid))))
        (cons 'rxm-measx-reserved1 (list (cons 'raw rxm-measx-reserved1) (cons 'formatted (fmt-hex rxm-measx-reserved1))))
        (cons 'nav-relposned-reserved0 (list (cons 'raw nav-relposned-reserved0) (cons 'formatted (fmt-hex nav-relposned-reserved0))))
        (cons 'nav-odo-reserved1 (list (cons 'raw nav-odo-reserved1) (cons 'formatted (fmt-hex nav-odo-reserved1))))
        (cons 'cfg-sbas-usage-integrity (list (cons 'raw cfg-sbas-usage-integrity) (cons 'formatted (fmt-hex cfg-sbas-usage-integrity))))
        (cons 'cfg-sbas-usage-diffcorr (list (cons 'raw cfg-sbas-usage-diffcorr) (cons 'formatted (fmt-hex cfg-sbas-usage-diffcorr))))
        (cons 'cfg-sbas-usage-range (list (cons 'raw cfg-sbas-usage-range) (cons 'formatted (fmt-hex cfg-sbas-usage-range))))
        (cons 'cfg-gnss-numtrkchhw (list (cons 'raw cfg-gnss-numtrkchhw) (cons 'formatted (number->string cfg-gnss-numtrkchhw))))
        (cons 'rxm-sfrbx-sigid (list (cons 'raw rxm-sfrbx-sigid) (cons 'formatted (number->string rxm-sfrbx-sigid))))
        (cons 'rxm-sfrbx-reserved1 (list (cons 'raw rxm-sfrbx-reserved1) (cons 'formatted (fmt-hex rxm-sfrbx-reserved1))))
        (cons 'nav-relposned-refstationid (list (cons 'raw nav-relposned-refstationid) (cons 'formatted (number->string nav-relposned-refstationid))))
        (cons 'cfg-sbas-max-sbas (list (cons 'raw cfg-sbas-max-sbas) (cons 'formatted (number->string cfg-sbas-max-sbas))))
        (cons 'cfg-gnss-numtrkchuse (list (cons 'raw cfg-gnss-numtrkchuse) (cons 'formatted (number->string cfg-gnss-numtrkchuse))))
        (cons 'rxm-sfrbx-freqid (list (cons 'raw rxm-sfrbx-freqid) (cons 'formatted (number->string rxm-sfrbx-freqid))))
        (cons 'cfg-sbas-scanmode-prn158 (list (cons 'raw cfg-sbas-scanmode-prn158) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn158))))
        (cons 'cfg-sbas-scanmode-prn157 (list (cons 'raw cfg-sbas-scanmode-prn157) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn157))))
        (cons 'cfg-sbas-scanmode-prn156 (list (cons 'raw cfg-sbas-scanmode-prn156) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn156))))
        (cons 'cfg-sbas-scanmode-prn155 (list (cons 'raw cfg-sbas-scanmode-prn155) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn155))))
        (cons 'cfg-sbas-scanmode-prn154 (list (cons 'raw cfg-sbas-scanmode-prn154) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn154))))
        (cons 'cfg-sbas-scanmode-prn153 (list (cons 'raw cfg-sbas-scanmode-prn153) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn153))))
        (cons 'cfg-sbas-scanmode-prn152 (list (cons 'raw cfg-sbas-scanmode-prn152) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn152))))
        (cons 'cfg-gnss-numconfigblocks (list (cons 'raw cfg-gnss-numconfigblocks) (cons 'formatted (number->string cfg-gnss-numconfigblocks))))
        (cons 'rxm-sfrbx-numwords (list (cons 'raw rxm-sfrbx-numwords) (cons 'formatted (number->string rxm-sfrbx-numwords))))
        (cons 'nav-sbas-geo (list (cons 'raw nav-sbas-geo) (cons 'formatted (number->string nav-sbas-geo))))
        (cons 'nav-sat-version (list (cons 'raw nav-sat-version) (cons 'formatted (number->string nav-sat-version))))
        (cons 'nav-pvt-year (list (cons 'raw nav-pvt-year) (cons 'formatted (number->string nav-pvt-year))))
        (cons 'cfg-sbas-scanmode-prn151 (list (cons 'raw cfg-sbas-scanmode-prn151) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn151))))
        (cons 'cfg-sbas-scanmode-prn150 (list (cons 'raw cfg-sbas-scanmode-prn150) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn150))))
        (cons 'cfg-sbas-scanmode-prn149 (list (cons 'raw cfg-sbas-scanmode-prn149) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn149))))
        (cons 'cfg-sbas-scanmode-prn148 (list (cons 'raw cfg-sbas-scanmode-prn148) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn148))))
        (cons 'cfg-sbas-scanmode-prn147 (list (cons 'raw cfg-sbas-scanmode-prn147) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn147))))
        (cons 'cfg-sbas-scanmode-prn146 (list (cons 'raw cfg-sbas-scanmode-prn146) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn146))))
        (cons 'cfg-sbas-scanmode-prn145 (list (cons 'raw cfg-sbas-scanmode-prn145) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn145))))
        (cons 'cfg-sbas-scanmode-prn144 (list (cons 'raw cfg-sbas-scanmode-prn144) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn144))))
        (cons 'cfg-sbas-scanmode-prn143 (list (cons 'raw cfg-sbas-scanmode-prn143) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn143))))
        (cons 'cfg-sbas-scanmode-prn142 (list (cons 'raw cfg-sbas-scanmode-prn142) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn142))))
        (cons 'cfg-sbas-scanmode-prn141 (list (cons 'raw cfg-sbas-scanmode-prn141) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn141))))
        (cons 'cfg-sbas-scanmode-prn140 (list (cons 'raw cfg-sbas-scanmode-prn140) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn140))))
        (cons 'cfg-sbas-scanmode-prn139 (list (cons 'raw cfg-sbas-scanmode-prn139) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn139))))
        (cons 'cfg-sbas-scanmode-prn138 (list (cons 'raw cfg-sbas-scanmode-prn138) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn138))))
        (cons 'cfg-sbas-scanmode-prn137 (list (cons 'raw cfg-sbas-scanmode-prn137) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn137))))
        (cons 'cfg-sbas-scanmode-prn136 (list (cons 'raw cfg-sbas-scanmode-prn136) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn136))))
        (cons 'cfg-sbas-scanmode-prn135 (list (cons 'raw cfg-sbas-scanmode-prn135) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn135))))
        (cons 'cfg-sbas-scanmode-prn134 (list (cons 'raw cfg-sbas-scanmode-prn134) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn134))))
        (cons 'cfg-sbas-scanmode-prn133 (list (cons 'raw cfg-sbas-scanmode-prn133) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn133))))
        (cons 'cfg-sbas-scanmode-prn132 (list (cons 'raw cfg-sbas-scanmode-prn132) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn132))))
        (cons 'cfg-sbas-scanmode-prn131 (list (cons 'raw cfg-sbas-scanmode-prn131) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn131))))
        (cons 'cfg-sbas-scanmode-prn130 (list (cons 'raw cfg-sbas-scanmode-prn130) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn130))))
        (cons 'cfg-sbas-scanmode-prn129 (list (cons 'raw cfg-sbas-scanmode-prn129) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn129))))
        (cons 'cfg-sbas-scanmode-prn128 (list (cons 'raw cfg-sbas-scanmode-prn128) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn128))))
        (cons 'cfg-sbas-scanmode-prn127 (list (cons 'raw cfg-sbas-scanmode-prn127) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn127))))
        (cons 'cfg-sbas-scanmode-prn126 (list (cons 'raw cfg-sbas-scanmode-prn126) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn126))))
        (cons 'cfg-sbas-scanmode-prn125 (list (cons 'raw cfg-sbas-scanmode-prn125) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn125))))
        (cons 'cfg-sbas-scanmode-prn124 (list (cons 'raw cfg-sbas-scanmode-prn124) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn124))))
        (cons 'cfg-sbas-scanmode-prn123 (list (cons 'raw cfg-sbas-scanmode-prn123) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn123))))
        (cons 'cfg-sbas-scanmode-prn122 (list (cons 'raw cfg-sbas-scanmode-prn122) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn122))))
        (cons 'cfg-sbas-scanmode-prn121 (list (cons 'raw cfg-sbas-scanmode-prn121) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn121))))
        (cons 'cfg-sbas-scanmode-prn120 (list (cons 'raw cfg-sbas-scanmode-prn120) (cons 'formatted (fmt-hex cfg-sbas-scanmode-prn120))))
        (cons 'payload-len (list (cons 'raw payload-len) (cons 'formatted (number->string payload-len))))
        (cons 'rxm-sfrbx-chn (list (cons 'raw rxm-sfrbx-chn) (cons 'formatted (number->string rxm-sfrbx-chn))))
        (cons 'rxm-sfrbx-reserved2 (list (cons 'raw rxm-sfrbx-reserved2) (cons 'formatted (fmt-hex rxm-sfrbx-reserved2))))
        (cons 'nav-sat-num-svs (list (cons 'raw nav-sat-num-svs) (cons 'formatted (number->string nav-sat-num-svs))))
        (cons 'rxm-sfrbx-version (list (cons 'raw rxm-sfrbx-version) (cons 'formatted (fmt-hex rxm-sfrbx-version))))
        (cons 'nav-sat-reserved1 (list (cons 'raw nav-sat-reserved1) (cons 'formatted (fmt-hex nav-sat-reserved1))))
        (cons 'nav-pvt-month (list (cons 'raw nav-pvt-month) (cons 'formatted (number->string nav-pvt-month))))
        (cons 'nav-sbas-service (list (cons 'raw nav-sbas-service) (cons 'formatted (fmt-hex nav-sbas-service))))
        (cons 'nav-sbas-service-ranging (list (cons 'raw nav-sbas-service-ranging) (cons 'formatted (if (= nav-sbas-service-ranging 0) "Not set" "Set"))))
        (cons 'nav-sbas-service-corrections (list (cons 'raw nav-sbas-service-corrections) (cons 'formatted (if (= nav-sbas-service-corrections 0) "Not set" "Set"))))
        (cons 'nav-sbas-service-integrity (list (cons 'raw nav-sbas-service-integrity) (cons 'formatted (if (= nav-sbas-service-integrity 0) "Not set" "Set"))))
        (cons 'nav-sbas-service-testmode (list (cons 'raw nav-sbas-service-testmode) (cons 'formatted (if (= nav-sbas-service-testmode 0) "Not set" "Set"))))
        (cons 'nav-sbas-service-bad (list (cons 'raw nav-sbas-service-bad) (cons 'formatted (if (= nav-sbas-service-bad 0) "Not set" "Set"))))
        (cons 'rxm-sfrbx-reserved3 (list (cons 'raw rxm-sfrbx-reserved3) (cons 'formatted (fmt-hex rxm-sfrbx-reserved3))))
        (cons 'nav-pvt-day (list (cons 'raw nav-pvt-day) (cons 'formatted (number->string nav-pvt-day))))
        (cons 'rxm-rawx-week (list (cons 'raw rxm-rawx-week) (cons 'formatted (number->string rxm-rawx-week))))
        (cons 'nav-timegps-week (list (cons 'raw nav-timegps-week) (cons 'formatted (number->string nav-timegps-week))))
        (cons 'nav-sbas-cnt (list (cons 'raw nav-sbas-cnt) (cons 'formatted (number->string nav-sbas-cnt))))
        (cons 'nav-pvt-hour (list (cons 'raw nav-pvt-hour) (cons 'formatted (number->string nav-pvt-hour))))
        (cons 'nav-sbas-reserved1 (list (cons 'raw nav-sbas-reserved1) (cons 'formatted (fmt-hex nav-sbas-reserved1))))
        (cons 'nav-pvt-min (list (cons 'raw nav-pvt-min) (cons 'formatted (number->string nav-pvt-min))))
        (cons 'nav-pvt-sec (list (cons 'raw nav-pvt-sec) (cons 'formatted (number->string nav-pvt-sec))))
        (cons 'nav-timegps-valid (list (cons 'raw nav-timegps-valid) (cons 'formatted (fmt-hex nav-timegps-valid))))
        (cons 'nav-timegps-towvalid (list (cons 'raw nav-timegps-towvalid) (cons 'formatted (if (= nav-timegps-towvalid 0) "Not set" "Set"))))
        (cons 'nav-timegps-weekvalid (list (cons 'raw nav-timegps-weekvalid) (cons 'formatted (if (= nav-timegps-weekvalid 0) "Not set" "Set"))))
        (cons 'nav-timegps-leapsvalid (list (cons 'raw nav-timegps-leapsvalid) (cons 'formatted (if (= nav-timegps-leapsvalid 0) "Not set" "Set"))))
        (cons 'nav-pvt-valid (list (cons 'raw nav-pvt-valid) (cons 'formatted (fmt-hex nav-pvt-valid))))
        (cons 'nav-pvt-validdate (list (cons 'raw nav-pvt-validdate) (cons 'formatted (if (= nav-pvt-validdate 0) "Not set" "Set"))))
        (cons 'nav-pvt-validtime (list (cons 'raw nav-pvt-validtime) (cons 'formatted (if (= nav-pvt-validtime 0) "Not set" "Set"))))
        (cons 'nav-pvt-fullyresolved (list (cons 'raw nav-pvt-fullyresolved) (cons 'formatted (if (= nav-pvt-fullyresolved 0) "Not set" "Set"))))
        (cons 'nav-pvt-validmag (list (cons 'raw nav-pvt-validmag) (cons 'formatted (if (= nav-pvt-validmag 0) "Not set" "Set"))))
        (cons 'rxm-rawx-nummeas (list (cons 'raw rxm-rawx-nummeas) (cons 'formatted (number->string rxm-rawx-nummeas))))
        (cons 'rxm-rawx-recstat (list (cons 'raw rxm-rawx-recstat) (cons 'formatted (fmt-hex rxm-rawx-recstat))))
        (cons 'rxm-rawx-recstat-leapsec (list (cons 'raw rxm-rawx-recstat-leapsec) (cons 'formatted (if (= rxm-rawx-recstat-leapsec 0) "Not set" "Set"))))
        (cons 'rxm-rawx-recstat-clkreset (list (cons 'raw rxm-rawx-recstat-clkreset) (cons 'formatted (if (= rxm-rawx-recstat-clkreset 0) "Not set" "Set"))))
        (cons 'nav-timeutc-year (list (cons 'raw nav-timeutc-year) (cons 'formatted (number->string nav-timeutc-year))))
        (cons 'rxm-rawx-version (list (cons 'raw rxm-rawx-version) (cons 'formatted (number->string rxm-rawx-version))))
        (cons 'rxm-rawx-reserved1 (list (cons 'raw rxm-rawx-reserved1) (cons 'formatted (fmt-hex rxm-rawx-reserved1))))
        (cons 'nav-timeutc-month (list (cons 'raw nav-timeutc-month) (cons 'formatted (number->string nav-timeutc-month))))
        (cons 'nav-timeutc-day (list (cons 'raw nav-timeutc-day) (cons 'formatted (number->string nav-timeutc-day))))
        (cons 'rxm-measx-reserved2 (list (cons 'raw rxm-measx-reserved2) (cons 'formatted (fmt-hex rxm-measx-reserved2))))
        (cons 'nav-timeutc-hour (list (cons 'raw nav-timeutc-hour) (cons 'formatted (number->string nav-timeutc-hour))))
        (cons 'nav-timeutc-min (list (cons 'raw nav-timeutc-min) (cons 'formatted (number->string nav-timeutc-min))))
        (cons 'nav-timeutc-sec (list (cons 'raw nav-timeutc-sec) (cons 'formatted (number->string nav-timeutc-sec))))
        (cons 'nav-timeutc-valid (list (cons 'raw nav-timeutc-valid) (cons 'formatted (fmt-hex nav-timeutc-valid))))
        (cons 'nav-timeutc-validtow (list (cons 'raw nav-timeutc-validtow) (cons 'formatted (if (= nav-timeutc-validtow 0) "Not set" "Set"))))
        (cons 'nav-timeutc-validwkn (list (cons 'raw nav-timeutc-validwkn) (cons 'formatted (if (= nav-timeutc-validwkn 0) "Not set" "Set"))))
        (cons 'nav-timeutc-validutc (list (cons 'raw nav-timeutc-validutc) (cons 'formatted (if (= nav-timeutc-validutc 0) "Not set" "Set"))))
        (cons 'nav-pvt-flags (list (cons 'raw nav-pvt-flags) (cons 'formatted (fmt-hex nav-pvt-flags))))
        (cons 'nav-pvt-gnssfixok (list (cons 'raw nav-pvt-gnssfixok) (cons 'formatted (if (= nav-pvt-gnssfixok 0) "Not set" "Set"))))
        (cons 'nav-pvt-diffsoln (list (cons 'raw nav-pvt-diffsoln) (cons 'formatted (if (= nav-pvt-diffsoln 0) "Not set" "Set"))))
        (cons 'nav-pvt-psmstate (list (cons 'raw nav-pvt-psmstate) (cons 'formatted (if (= nav-pvt-psmstate 0) "Not set" "Set"))))
        (cons 'nav-pvt-headvehvalid (list (cons 'raw nav-pvt-headvehvalid) (cons 'formatted (if (= nav-pvt-headvehvalid 0) "Not set" "Set"))))
        (cons 'nav-pvt-flags2 (list (cons 'raw nav-pvt-flags2) (cons 'formatted (fmt-hex nav-pvt-flags2))))
        (cons 'nav-pvt-confirmedavai (list (cons 'raw nav-pvt-confirmedavai) (cons 'formatted (if (= nav-pvt-confirmedavai 0) "Not set" "Set"))))
        (cons 'nav-pvt-confirmeddate (list (cons 'raw nav-pvt-confirmeddate) (cons 'formatted (if (= nav-pvt-confirmeddate 0) "Not set" "Set"))))
        (cons 'nav-pvt-confirmedtime (list (cons 'raw nav-pvt-confirmedtime) (cons 'formatted (if (= nav-pvt-confirmedtime 0) "Not set" "Set"))))
        (cons 'nav-pvt-numsv (list (cons 'raw nav-pvt-numsv) (cons 'formatted (number->string nav-pvt-numsv))))
        (cons 'nav-relposned-reserved1 (list (cons 'raw nav-relposned-reserved1) (cons 'formatted (fmt-hex nav-relposned-reserved1))))
        (cons 'rxm-measx-reserved3 (list (cons 'raw rxm-measx-reserved3) (cons 'formatted (fmt-hex rxm-measx-reserved3))))
        (cons 'rxm-measx-numsv (list (cons 'raw rxm-measx-numsv) (cons 'formatted (number->string rxm-measx-numsv))))
        (cons 'rxm-measx-flags-towset (list (cons 'raw rxm-measx-flags-towset) (cons 'formatted (number->string rxm-measx-flags-towset))))
        (cons 'rxm-measx-reserved4 (list (cons 'raw rxm-measx-reserved4) (cons 'formatted (fmt-hex rxm-measx-reserved4))))
        (cons 'nav-relposned-reserved2 (list (cons 'raw nav-relposned-reserved2) (cons 'formatted (fmt-hex nav-relposned-reserved2))))
        (cons 'nav-relposned-flags (list (cons 'raw nav-relposned-flags) (cons 'formatted (fmt-hex nav-relposned-flags))))
        (cons 'nav-relposned-gnssfixok (list (cons 'raw nav-relposned-gnssfixok) (cons 'formatted (if (= nav-relposned-gnssfixok 0) "Not set" "Set"))))
        (cons 'nav-relposned-diffsoln (list (cons 'raw nav-relposned-diffsoln) (cons 'formatted (if (= nav-relposned-diffsoln 0) "Not set" "Set"))))
        (cons 'nav-relposned-relposvalid (list (cons 'raw nav-relposned-relposvalid) (cons 'formatted (if (= nav-relposned-relposvalid 0) "Not set" "Set"))))
        (cons 'nav-relposned-ismoving (list (cons 'raw nav-relposned-ismoving) (cons 'formatted (if (= nav-relposned-ismoving 0) "Not set" "Set"))))
        (cons 'nav-relposned-refposmiss (list (cons 'raw nav-relposned-refposmiss) (cons 'formatted (if (= nav-relposned-refposmiss 0) "Not set" "Set"))))
        (cons 'nav-relposned-refobsmiss (list (cons 'raw nav-relposned-refobsmiss) (cons 'formatted (if (= nav-relposned-refobsmiss 0) "Not set" "Set"))))
        (cons 'nav-relposned-relposheadingvalid (list (cons 'raw nav-relposned-relposheadingvalid) (cons 'formatted (if (= nav-relposned-relposheadingvalid 0) "Not set" "Set"))))
        (cons 'nav-relposned-relposnormalized (list (cons 'raw nav-relposned-relposnormalized) (cons 'formatted (if (= nav-relposned-relposnormalized 0) "Not set" "Set"))))
        (cons 'nav-pvt-invalidllh (list (cons 'raw nav-pvt-invalidllh) (cons 'formatted (number->string nav-pvt-invalidllh))))
        (cons 'nav-pvt-reserved1 (list (cons 'raw nav-pvt-reserved1) (cons 'formatted (fmt-hex nav-pvt-reserved1))))
        )))

    (catch (e)
      (err (str "UBX parse error: " e)))))

;; dissect-ubx: parse UBX from bytevector
;; Returns (ok fields-alist) or (err message)