;; packet-usb-hid.c
;;
;; USB HID dissector
;; By Adam Nielsen <a.nielsen@shikadi.net> 2009
;;
;; SPDX-License-Identifier: GPL-2.0-or-later
;;

;; jerboa-ethereal/dissectors/usb-hid.ss
;; Auto-generated from wireshark/epan/dissectors/packet-usb_hid.c

(import (jerboa prelude))

;; ── Protocol Helpers ─────────────────────────────────────────────────
(def (read-u8 buf offset)
  (if (>= offset (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u8-ref buf offset))))

(def (read-u16be buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness big)))))

(def (read-u24be buf offset)
  (if (> (+ offset 3) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (+ (* (bytevector-u8-ref buf offset) 65536)
             (* (bytevector-u8-ref buf (+ offset 1)) 256)
             (bytevector-u8-ref buf (+ offset 2))))))

(def (read-u32be buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness big)))))

(def (read-u16le buf offset)
  (if (> (+ offset 2) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u16-ref buf offset (endianness little)))))

(def (read-u32le buf offset)
  (if (> (+ offset 4) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u32-ref buf offset (endianness little)))))

(def (read-u64be buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness big)))))

(def (read-u64le buf offset)
  (if (> (+ offset 8) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (bytevector-u64-ref buf offset (endianness little)))))

(def (slice buf offset len)
  (if (> (+ offset len) (bytevector-length buf))
      (err "Buffer overrun")
      (ok (let ((result (make-bytevector len)))
            (bytevector-copy! buf offset result 0 len)
            result))))

(def (extract-bits val mask shift)
  (bitwise-arithmetic-shift-right (bitwise-and val mask) shift))

(def (fmt-ipv4 addr)
  (let ((b0 (bitwise-arithmetic-shift-right addr 24))
        (b1 (bitwise-and (bitwise-arithmetic-shift-right addr 16) 255))
        (b2 (bitwise-and (bitwise-arithmetic-shift-right addr 8) 255))
        (b3 (bitwise-and addr 255)))
    (str b0 "." b1 "." b2 "." b3)))

(def (fmt-mac bytes)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bytes))
    ":"))

(def (fmt-hex val)
  (str "0x" (number->string val 16)))

(def (fmt-oct val)
  (str "0" (number->string val 8)))

(def (fmt-port port)
  (number->string port))

(def (fmt-bytes bv)
  (string-join
    (map (lambda (b) (string-pad (number->string b 16) 2 #\0))
         (bytevector->list bv))
    " "))

(def (fmt-ipv6-address bytes)
  (let loop ((i 0) (parts '()))
    (if (>= i 16)
        (string-join (reverse parts) ":")
        (loop (+ i 2)
              (cons (let ((w (+ (* (bytevector-u8-ref bytes i) 256)
                                (bytevector-u8-ref bytes (+ i 1)))))
                      (number->string w 16))
                    parts)))))

;; ── Dissector ──────────────────────────────────────────────────────
(def (dissect-usb-hid buffer)
  "USB HID"
  (try
    (let* (
           (hid-mainitem-bit0 (unwrap (read-u8 buffer 0)))
           (hid-mainitem-bit1 (unwrap (read-u8 buffer 0)))
           (hid-mainitem-bit2 (unwrap (read-u8 buffer 0)))
           (hid-mainitem-bit3 (unwrap (read-u8 buffer 0)))
           (hid-mainitem-bit4 (unwrap (read-u8 buffer 0)))
           (hid-mainitem-bit5 (unwrap (read-u8 buffer 0)))
           (hid-mainitem-bit6 (unwrap (read-u8 buffer 0)))
           (hid-mainitem-bit7-input (unwrap (read-u8 buffer 0)))
           (hid-mainitem-bit7 (unwrap (read-u8 buffer 0)))
           (hid-mainitem-bit8 (unwrap (read-u8 buffer 0)))
           (hid-item-unk-data (unwrap (slice buffer 0 1)))
           (hid-globalitem-log-min (unwrap (read-u32be buffer 0)))
           (hid-globalitem-log-max (unwrap (read-u32be buffer 0)))
           (hid-globalitem-phy-min (unwrap (read-u32be buffer 0)))
           (hid-globalitem-phy-max (unwrap (read-u32be buffer 0)))
           (hid-globalitem-unit-exp (unwrap (read-u8 buffer 0)))
           (hid-globalitem-report-size (unwrap (read-u8 buffer 0)))
           (hid-globalitem-report-id (unwrap (read-u8 buffer 0)))
           (hid-globalitem-report-count (unwrap (read-u8 buffer 0)))
           (hid-globalitem-push (unwrap (read-u8 buffer 0)))
           (hid-globalitem-pop (unwrap (read-u8 buffer 0)))
           (hid-localitem-usage (unwrap (read-u16be buffer 0)))
           (hid-localitem-usage-min (unwrap (read-u16be buffer 0)))
           (hid-localitem-usage-max (unwrap (read-u16be buffer 0)))
           (hid-localitem-desig-index (unwrap (read-u8 buffer 0)))
           (hid-localitem-desig-min (unwrap (read-u8 buffer 0)))
           (hid-localitem-desig-max (unwrap (read-u8 buffer 0)))
           (hid-localitem-string-index (unwrap (read-u8 buffer 0)))
           (hid-localitem-string-min (unwrap (read-u8 buffer 0)))
           (hid-localitem-string-max (unwrap (read-u8 buffer 0)))
           (hid-localitem-delimiter (unwrap (read-u8 buffer 0)))
           (hid-item-bDataSize (unwrap (read-u8 buffer 0)))
           (hid-item-bLongItemTag (unwrap (read-u8 buffer 0)))
           (boot-report-keyboard-modifier-right-gui (unwrap (read-u8 buffer 0)))
           (boot-report-keyboard-modifier-right-alt (unwrap (read-u8 buffer 0)))
           (boot-report-keyboard-modifier-right-shift (unwrap (read-u8 buffer 0)))
           (boot-report-keyboard-modifier-right-ctrl (unwrap (read-u8 buffer 0)))
           (boot-report-keyboard-modifier-left-gui (unwrap (read-u8 buffer 0)))
           (boot-report-keyboard-modifier-left-alt (unwrap (read-u8 buffer 0)))
           (boot-report-keyboard-modifier-left-shift (unwrap (read-u8 buffer 0)))
           (boot-report-keyboard-modifier-left-ctrl (unwrap (read-u8 buffer 0)))
           (boot-report-keyboard-leds-constants (unwrap (read-u8 buffer 0)))
           (boot-report-keyboard-leds-kana (unwrap (read-u8 buffer 0)))
           (boot-report-keyboard-leds-compose (unwrap (read-u8 buffer 0)))
           (boot-report-keyboard-leds-scroll-lock (unwrap (read-u8 buffer 0)))
           (boot-report-keyboard-leds-caps-lock (unwrap (read-u8 buffer 0)))
           (boot-report-keyboard-leds-num-lock (unwrap (read-u8 buffer 0)))
           (boot-report-mouse-button-8 (unwrap (read-u8 buffer 0)))
           (boot-report-mouse-button-7 (unwrap (read-u8 buffer 0)))
           (boot-report-mouse-button-6 (unwrap (read-u8 buffer 0)))
           (boot-report-mouse-button-5 (unwrap (read-u8 buffer 0)))
           (boot-report-mouse-button-4 (unwrap (read-u8 buffer 0)))
           (boot-report-mouse-button-middle (unwrap (read-u8 buffer 0)))
           (boot-report-mouse-button-right (unwrap (read-u8 buffer 0)))
           (boot-report-mouse-button-left (unwrap (read-u8 buffer 0)))
           (data (unwrap (slice buffer 0 1)))
           (boot-report-keyboard-reserved (unwrap (read-u8 buffer 1)))
           (boot-report-mouse-x-displacement (unwrap (read-u8 buffer 1)))
           (hid-bDescriptorIndex (unwrap (read-u8 buffer 1)))
           (boot-report-mouse-y-displacement (unwrap (read-u8 buffer 2)))
           (hid-bcdHID (unwrap (read-u16be buffer 2)))
           (boot-report-mouse-horizontal-scroll-wheel (unwrap (read-u8 buffer 3)))
           (hid-wInterfaceNumber (unwrap (read-u16be buffer 3)))
           (boot-report-mouse-vertical-scroll-wheel (unwrap (read-u8 buffer 4)))
           (hid-bNumDescriptors (unwrap (read-u8 buffer 4)))
           (hid-wDescriptorLength (unwrap (read-u16be buffer 4)))
           (hid-zero (unwrap (read-u8 buffer 8)))
           (hid-report-id (unwrap (read-u8 buffer 12)))
           (hid-duration (unwrap (read-u8 buffer 12)))
           (hid-value (unwrap (read-u16be buffer 22)))
           (hid-index (unwrap (read-u16be buffer 24)))
           (hid-length (unwrap (read-u16be buffer 26)))
           )

      (ok (list
        (cons 'hid-mainitem-bit0 (list (cons 'raw hid-mainitem-bit0) (cons 'formatted (if (= hid-mainitem-bit0 0) "Data" "Constant"))))
        (cons 'hid-mainitem-bit1 (list (cons 'raw hid-mainitem-bit1) (cons 'formatted (if (= hid-mainitem-bit1 0) "Array" "Variable"))))
        (cons 'hid-mainitem-bit2 (list (cons 'raw hid-mainitem-bit2) (cons 'formatted (if (= hid-mainitem-bit2 0) "Absolute" "Relative"))))
        (cons 'hid-mainitem-bit3 (list (cons 'raw hid-mainitem-bit3) (cons 'formatted (if (= hid-mainitem-bit3 0) "No Wrap" "Wrap"))))
        (cons 'hid-mainitem-bit4 (list (cons 'raw hid-mainitem-bit4) (cons 'formatted (if (= hid-mainitem-bit4 0) "Linear" "Non Linear"))))
        (cons 'hid-mainitem-bit5 (list (cons 'raw hid-mainitem-bit5) (cons 'formatted (if (= hid-mainitem-bit5 0) "Preferred State" "No Preferred"))))
        (cons 'hid-mainitem-bit6 (list (cons 'raw hid-mainitem-bit6) (cons 'formatted (if (= hid-mainitem-bit6 0) "No Null position" "Null state"))))
        (cons 'hid-mainitem-bit7-input (list (cons 'raw hid-mainitem-bit7-input) (cons 'formatted (number->string hid-mainitem-bit7-input))))
        (cons 'hid-mainitem-bit7 (list (cons 'raw hid-mainitem-bit7) (cons 'formatted (if (= hid-mainitem-bit7 0) "Non Volatile" "Volatile"))))
        (cons 'hid-mainitem-bit8 (list (cons 'raw hid-mainitem-bit8) (cons 'formatted (if (= hid-mainitem-bit8 0) "Bit Field" "Buffered Bytes"))))
        (cons 'hid-item-unk-data (list (cons 'raw hid-item-unk-data) (cons 'formatted (fmt-bytes hid-item-unk-data))))
        (cons 'hid-globalitem-log-min (list (cons 'raw hid-globalitem-log-min) (cons 'formatted (number->string hid-globalitem-log-min))))
        (cons 'hid-globalitem-log-max (list (cons 'raw hid-globalitem-log-max) (cons 'formatted (number->string hid-globalitem-log-max))))
        (cons 'hid-globalitem-phy-min (list (cons 'raw hid-globalitem-phy-min) (cons 'formatted (number->string hid-globalitem-phy-min))))
        (cons 'hid-globalitem-phy-max (list (cons 'raw hid-globalitem-phy-max) (cons 'formatted (number->string hid-globalitem-phy-max))))
        (cons 'hid-globalitem-unit-exp (list (cons 'raw hid-globalitem-unit-exp) (cons 'formatted (number->string hid-globalitem-unit-exp))))
        (cons 'hid-globalitem-report-size (list (cons 'raw hid-globalitem-report-size) (cons 'formatted (number->string hid-globalitem-report-size))))
        (cons 'hid-globalitem-report-id (list (cons 'raw hid-globalitem-report-id) (cons 'formatted (fmt-hex hid-globalitem-report-id))))
        (cons 'hid-globalitem-report-count (list (cons 'raw hid-globalitem-report-count) (cons 'formatted (number->string hid-globalitem-report-count))))
        (cons 'hid-globalitem-push (list (cons 'raw hid-globalitem-push) (cons 'formatted (fmt-hex hid-globalitem-push))))
        (cons 'hid-globalitem-pop (list (cons 'raw hid-globalitem-pop) (cons 'formatted (fmt-hex hid-globalitem-pop))))
        (cons 'hid-localitem-usage (list (cons 'raw hid-localitem-usage) (cons 'formatted (fmt-hex hid-localitem-usage))))
        (cons 'hid-localitem-usage-min (list (cons 'raw hid-localitem-usage-min) (cons 'formatted (fmt-hex hid-localitem-usage-min))))
        (cons 'hid-localitem-usage-max (list (cons 'raw hid-localitem-usage-max) (cons 'formatted (fmt-hex hid-localitem-usage-max))))
        (cons 'hid-localitem-desig-index (list (cons 'raw hid-localitem-desig-index) (cons 'formatted (fmt-hex hid-localitem-desig-index))))
        (cons 'hid-localitem-desig-min (list (cons 'raw hid-localitem-desig-min) (cons 'formatted (fmt-hex hid-localitem-desig-min))))
        (cons 'hid-localitem-desig-max (list (cons 'raw hid-localitem-desig-max) (cons 'formatted (fmt-hex hid-localitem-desig-max))))
        (cons 'hid-localitem-string-index (list (cons 'raw hid-localitem-string-index) (cons 'formatted (fmt-hex hid-localitem-string-index))))
        (cons 'hid-localitem-string-min (list (cons 'raw hid-localitem-string-min) (cons 'formatted (fmt-hex hid-localitem-string-min))))
        (cons 'hid-localitem-string-max (list (cons 'raw hid-localitem-string-max) (cons 'formatted (fmt-hex hid-localitem-string-max))))
        (cons 'hid-localitem-delimiter (list (cons 'raw hid-localitem-delimiter) (cons 'formatted (fmt-hex hid-localitem-delimiter))))
        (cons 'hid-item-bDataSize (list (cons 'raw hid-item-bDataSize) (cons 'formatted (number->string hid-item-bDataSize))))
        (cons 'hid-item-bLongItemTag (list (cons 'raw hid-item-bLongItemTag) (cons 'formatted (fmt-hex hid-item-bLongItemTag))))
        (cons 'boot-report-keyboard-modifier-right-gui (list (cons 'raw boot-report-keyboard-modifier-right-gui) (cons 'formatted (number->string boot-report-keyboard-modifier-right-gui))))
        (cons 'boot-report-keyboard-modifier-right-alt (list (cons 'raw boot-report-keyboard-modifier-right-alt) (cons 'formatted (number->string boot-report-keyboard-modifier-right-alt))))
        (cons 'boot-report-keyboard-modifier-right-shift (list (cons 'raw boot-report-keyboard-modifier-right-shift) (cons 'formatted (number->string boot-report-keyboard-modifier-right-shift))))
        (cons 'boot-report-keyboard-modifier-right-ctrl (list (cons 'raw boot-report-keyboard-modifier-right-ctrl) (cons 'formatted (number->string boot-report-keyboard-modifier-right-ctrl))))
        (cons 'boot-report-keyboard-modifier-left-gui (list (cons 'raw boot-report-keyboard-modifier-left-gui) (cons 'formatted (number->string boot-report-keyboard-modifier-left-gui))))
        (cons 'boot-report-keyboard-modifier-left-alt (list (cons 'raw boot-report-keyboard-modifier-left-alt) (cons 'formatted (number->string boot-report-keyboard-modifier-left-alt))))
        (cons 'boot-report-keyboard-modifier-left-shift (list (cons 'raw boot-report-keyboard-modifier-left-shift) (cons 'formatted (number->string boot-report-keyboard-modifier-left-shift))))
        (cons 'boot-report-keyboard-modifier-left-ctrl (list (cons 'raw boot-report-keyboard-modifier-left-ctrl) (cons 'formatted (number->string boot-report-keyboard-modifier-left-ctrl))))
        (cons 'boot-report-keyboard-leds-constants (list (cons 'raw boot-report-keyboard-leds-constants) (cons 'formatted (fmt-hex boot-report-keyboard-leds-constants))))
        (cons 'boot-report-keyboard-leds-kana (list (cons 'raw boot-report-keyboard-leds-kana) (cons 'formatted (number->string boot-report-keyboard-leds-kana))))
        (cons 'boot-report-keyboard-leds-compose (list (cons 'raw boot-report-keyboard-leds-compose) (cons 'formatted (number->string boot-report-keyboard-leds-compose))))
        (cons 'boot-report-keyboard-leds-scroll-lock (list (cons 'raw boot-report-keyboard-leds-scroll-lock) (cons 'formatted (number->string boot-report-keyboard-leds-scroll-lock))))
        (cons 'boot-report-keyboard-leds-caps-lock (list (cons 'raw boot-report-keyboard-leds-caps-lock) (cons 'formatted (number->string boot-report-keyboard-leds-caps-lock))))
        (cons 'boot-report-keyboard-leds-num-lock (list (cons 'raw boot-report-keyboard-leds-num-lock) (cons 'formatted (number->string boot-report-keyboard-leds-num-lock))))
        (cons 'boot-report-mouse-button-8 (list (cons 'raw boot-report-mouse-button-8) (cons 'formatted (number->string boot-report-mouse-button-8))))
        (cons 'boot-report-mouse-button-7 (list (cons 'raw boot-report-mouse-button-7) (cons 'formatted (number->string boot-report-mouse-button-7))))
        (cons 'boot-report-mouse-button-6 (list (cons 'raw boot-report-mouse-button-6) (cons 'formatted (number->string boot-report-mouse-button-6))))
        (cons 'boot-report-mouse-button-5 (list (cons 'raw boot-report-mouse-button-5) (cons 'formatted (number->string boot-report-mouse-button-5))))
        (cons 'boot-report-mouse-button-4 (list (cons 'raw boot-report-mouse-button-4) (cons 'formatted (number->string boot-report-mouse-button-4))))
        (cons 'boot-report-mouse-button-middle (list (cons 'raw boot-report-mouse-button-middle) (cons 'formatted (number->string boot-report-mouse-button-middle))))
        (cons 'boot-report-mouse-button-right (list (cons 'raw boot-report-mouse-button-right) (cons 'formatted (number->string boot-report-mouse-button-right))))
        (cons 'boot-report-mouse-button-left (list (cons 'raw boot-report-mouse-button-left) (cons 'formatted (number->string boot-report-mouse-button-left))))
        (cons 'data (list (cons 'raw data) (cons 'formatted (fmt-bytes data))))
        (cons 'boot-report-keyboard-reserved (list (cons 'raw boot-report-keyboard-reserved) (cons 'formatted (fmt-hex boot-report-keyboard-reserved))))
        (cons 'boot-report-mouse-x-displacement (list (cons 'raw boot-report-mouse-x-displacement) (cons 'formatted (number->string boot-report-mouse-x-displacement))))
        (cons 'hid-bDescriptorIndex (list (cons 'raw hid-bDescriptorIndex) (cons 'formatted (fmt-hex hid-bDescriptorIndex))))
        (cons 'boot-report-mouse-y-displacement (list (cons 'raw boot-report-mouse-y-displacement) (cons 'formatted (number->string boot-report-mouse-y-displacement))))
        (cons 'hid-bcdHID (list (cons 'raw hid-bcdHID) (cons 'formatted (fmt-hex hid-bcdHID))))
        (cons 'boot-report-mouse-horizontal-scroll-wheel (list (cons 'raw boot-report-mouse-horizontal-scroll-wheel) (cons 'formatted (number->string boot-report-mouse-horizontal-scroll-wheel))))
        (cons 'hid-wInterfaceNumber (list (cons 'raw hid-wInterfaceNumber) (cons 'formatted (number->string hid-wInterfaceNumber))))
        (cons 'boot-report-mouse-vertical-scroll-wheel (list (cons 'raw boot-report-mouse-vertical-scroll-wheel) (cons 'formatted (number->string boot-report-mouse-vertical-scroll-wheel))))
        (cons 'hid-bNumDescriptors (list (cons 'raw hid-bNumDescriptors) (cons 'formatted (number->string hid-bNumDescriptors))))
        (cons 'hid-wDescriptorLength (list (cons 'raw hid-wDescriptorLength) (cons 'formatted (number->string hid-wDescriptorLength))))
        (cons 'hid-zero (list (cons 'raw hid-zero) (cons 'formatted (number->string hid-zero))))
        (cons 'hid-report-id (list (cons 'raw hid-report-id) (cons 'formatted (number->string hid-report-id))))
        (cons 'hid-duration (list (cons 'raw hid-duration) (cons 'formatted (number->string hid-duration))))
        (cons 'hid-value (list (cons 'raw hid-value) (cons 'formatted (fmt-hex hid-value))))
        (cons 'hid-index (list (cons 'raw hid-index) (cons 'formatted (number->string hid-index))))
        (cons 'hid-length (list (cons 'raw hid-length) (cons 'formatted (number->string hid-length))))
        )))

    (catch (e)
      (err (str "USB-HID parse error: " e)))))

;; dissect-usb-hid: parse USB-HID from bytevector
;; Returns (ok fields-alist) or (err message)